import type { RegionLandingDef } from "./types";

/**
 * 2차 지역·생활권 63개 — 광역(metro-defs) 하위 SEO 랜딩
 * RegionLandingDef 필드만 사용 (types.ts 기준)
 */

function city(
  partial: Omit<
    RegionLandingDef,
    "kind" | "priority" | "published" | "noticeType"
  > &
    Partial<Pick<RegionLandingDef, "regionType" | "parentRegion">>,
): RegionLandingDef {
  return {
    ...partial,
    kind: "region",
    priority: 2,
    published: true,
    noticeType: "jurisdiction-exception",
    regionType: partial.regionType ?? "시",
  };
}

export const cityRegionDefs: RegionLandingDef[] = [
  city({
    slug: "강남구상속등기법무사",
    regionName: "강남구",
    parentRegion: "서울",
    regionType: "구",
    primaryKeyword: "강남구 상속등기 법무사",
    secondaryKeywords: ["강남구 법무사 상속등기","강남구 비대면 상속등기","강남구 아파트 상속등기"],
    seoTitle: "강남구 상속등기 법무사｜아파트·상가 상속 비용과 절차",
    metaDescription: "강남구 상속등기 법무사. 고가 아파트·상가·오피스가 많고 상속인이 해외·지방에 거주하는 사례가 잦습니다. 강남구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "강남구 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 강남구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 강남구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "강남구 상속등기를 검색하셔도 반드시 강남구에 사무소가 있어야 하는 것은 아닙니다. 고가 아파트·상가·오피스가 많고 상속인이 해외·지방에 거주하는 사례가 잦습니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["heir-scattered","sell-first","farm-forest"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["gangnam-apt","branch-myth","deadline-3m"],
    relatedRegionSlugs: ["서울상속등기법무사","서초구상속등기법무사","송파구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "강남구 상속등기 가능 여부 확인",
    ctaDescription: "강남구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "서초구상속등기법무사",
    regionName: "서초구",
    parentRegion: "서울",
    regionType: "구",
    primaryKeyword: "서초구 상속등기 법무사",
    secondaryKeywords: ["서초구 상속등기 비용","서초구 상속등기 서류","서울 상속등기"],
    seoTitle: "서초구 상속등기 법무사｜상속인이 다른 지역에 사는 경우",
    metaDescription: "서초구 상속등기 법무사. 법조·교육 인근 아파트와 상가 상속, 협의분할 논의가 길어지는 경우가 있습니다. 서초구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "서초구 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 서초구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 서초구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "서초구에서 법조·교육 인근 아파트와 상가 상속, 협의분할 논의가 길어지는 경우가 있습니다. 다옴법무사사무소는 부산 해운대에 있으므로 서초구 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["multi-gu","overseas-heir","office-retail"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["jurisdiction-special","seoul-search"],
    relatedRegionSlugs: ["서울상속등기법무사","강남구상속등기법무사","송파구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "서초구 상속등기 가능 여부 확인",
    ctaDescription: "서초구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "송파구상속등기법무사",
    regionName: "송파구",
    parentRegion: "서울",
    regionType: "구",
    primaryKeyword: "송파구 상속등기 법무사",
    secondaryKeywords: ["송파구 상속부동산","송파구 상속등기 절차","타지역 상속등기"],
    seoTitle: "송파구 아파트 상속등기｜비대면 서류 준비와 취득세",
    metaDescription: "송파구 상속등기 법무사. 잠실·문정 일대 대단지 아파트와 상가가 함께 상속되는 경우가 많습니다. 송파구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "송파구 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 송파구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 송파구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "송파구 부동산 상속등기 문의는 잠실·문정 일대 대단지 아파트와 상가가 함께 상속되는 경우가 많습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 송파구에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["apt-land-mix","busan-remote","heir-scattered"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["visit-need","gyeonggi-cities"],
    relatedRegionSlugs: ["서울상속등기법무사","강남구상속등기법무사","서초구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "송파구 상속등기 가능 여부 확인",
    ctaDescription: "송파구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "마포구상속등기법무사",
    regionName: "마포구",
    parentRegion: "서울",
    regionType: "구",
    primaryKeyword: "마포구 상속등기 법무사",
    secondaryKeywords: ["마포구 법무사 상속등기","마포구 비대면 상속등기","마포구 아파트 상속등기"],
    seoTitle: "마포구 상속등기 법무사｜주택·상가 상속 절차 총정리",
    metaDescription: "마포구 상속등기 법무사. 한강변 아파트·오피스텔·상가가 섞인 상속에서 임대차·근저당 확인이 중요합니다. 마포구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "마포구에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 마포구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 마포구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "마포구 상속등기를 검색하셔도 반드시 마포구에 사무소가 있어야 하는 것은 아닙니다. 한강변 아파트·오피스텔·상가가 섞인 상속에서 임대차·근저당 확인이 중요합니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["sell-first","newtown-outer","heir-scattered"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["cost-split","incheon-songdo"],
    relatedRegionSlugs: ["서울상속등기법무사","용산구상속등기법무사","영등포구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "마포구 상속등기 가능 여부 확인",
    ctaDescription: "마포구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "용산구상속등기법무사",
    regionName: "용산구",
    parentRegion: "서울",
    regionType: "구",
    primaryKeyword: "용산구 상속등기 법무사",
    secondaryKeywords: ["용산구 상속등기 비용","용산구 상속등기 서류","서울 상속등기"],
    seoTitle: "용산구 상속부동산 등기｜여러 상속인의 협의분할 방법",
    metaDescription: "용산구 상속등기 법무사. 재개발·고급 주거와 상가가 겹치며 권리관계가 복잡한 사례가 있습니다. 용산구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "용산구 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 용산구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 용산구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "용산구에서 재개발·고급 주거와 상가가 겹치며 권리관계가 복잡한 사례가 있습니다. 다옴법무사사무소는 부산 해운대에 있으므로 용산구 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["overseas-heir","farm-forest","multi-gu"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["multi-prop","jeju-visit"],
    relatedRegionSlugs: ["서울상속등기법무사","마포구상속등기법무사","성동구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "용산구 상속등기 가능 여부 확인",
    ctaDescription: "용산구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "영등포구상속등기법무사",
    regionName: "영등포구",
    parentRegion: "서울",
    regionType: "구",
    primaryKeyword: "영등포구 상속등기 법무사",
    secondaryKeywords: ["영등포구 법무사 상속등기","영등포구 비대면 상속등기","영등포구 아파트 상속등기"],
    seoTitle: "영등포구 상속등기｜아파트·오피스텔 비대면 진행",
    metaDescription: "영등포구 상속등기 법무사. 여의도·당산 일대 오피스·상가와 주거용 부동산이 함께 넘어오는 상속이 많습니다. 영등포구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "영등포구 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 영등포구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 영등포구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "영등포구 부동산 상속등기 문의는 여의도·당산 일대 오피스·상가와 주거용 부동산이 함께 넘어오는 상속이 많습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 영등포구에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["office-retail","apt-land-mix","heir-scattered"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["deadline-3m","choose-lawyer"],
    relatedRegionSlugs: ["서울상속등기법무사","마포구상속등기법무사","강서구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "영등포구 상속등기 가능 여부 확인",
    ctaDescription: "영등포구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "성동구상속등기법무사",
    regionName: "성동구",
    parentRegion: "서울",
    regionType: "구",
    primaryKeyword: "성동구 상속등기 법무사",
    secondaryKeywords: ["성동구 상속등기 비용","성동구 상속등기 서류","서울 상속등기"],
    seoTitle: "성동구 상속등기 법무사｜부동산이 여러 곳인 경우",
    metaDescription: "성동구 상속등기 법무사. 성수·왕십리 재건축·리모델링 단지와 상가 상속 문의가 꾸준합니다. 성동구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "성동구 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 성동구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 성동구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "성동구 상속등기를 검색하셔도 반드시 성동구에 사무소가 있어야 하는 것은 아닙니다. 성수·왕십리 재건축·리모델링 단지와 상가 상속 문의가 꾸준합니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["newtown-outer","busan-remote","sell-first"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["seoul-search","gangnam-apt"],
    relatedRegionSlugs: ["서울상속등기법무사","용산구상속등기법무사","송파구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "성동구 상속등기 가능 여부 확인",
    ctaDescription: "성동구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "강서구상속등기법무사",
    regionName: "강서구",
    parentRegion: "서울",
    regionType: "구",
    primaryKeyword: "강서구 상속등기 법무사",
    secondaryKeywords: ["강서구 상속부동산","강서구 상속등기 절차","타지역 상속등기"],
    seoTitle: "서울 강서구 상속등기｜필요서류와 법무사 비용 안내",
    metaDescription: "강서구 상속등기 법무사. 김포공항 인근 아파트와 상가, 상속인이 경기·지방에 거주하는 경우가 많습니다. 강서구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "강서구 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 강서구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 강서구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "강서구에서 김포공항 인근 아파트와 상가, 상속인이 경기·지방에 거주하는 경우가 많습니다. 다옴법무사사무소는 부산 해운대에 있으므로 강서구 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["farm-forest","heir-scattered","overseas-heir"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["gyeonggi-cities","bundang-heirs"],
    relatedRegionSlugs: ["서울상속등기법무사","영등포구상속등기법무사","마포구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "강서구 상속등기 가능 여부 확인",
    ctaDescription: "강서구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "노원구상속등기법무사",
    regionName: "노원구",
    parentRegion: "서울",
    regionType: "구",
    primaryKeyword: "노원구 상속등기 법무사",
    secondaryKeywords: ["노원구 법무사 상속등기","노원구 비대면 상속등기","노원구 아파트 상속등기"],
    seoTitle: "노원구 아파트 상속등기｜상속재산분할협의부터 신청까지",
    metaDescription: "노원구 상속등기 법무사. 대단지 아파트 위주 상속에서 상속인 간 협의·위임 정리가 핵심입니다. 노원구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "노원구에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 노원구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 노원구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "노원구 부동산 상속등기 문의는 대단지 아파트 위주 상속에서 상속인 간 협의·위임 정리가 핵심입니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 노원구에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["office-retail","multi-gu","busan-remote"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["incheon-songdo","remote-table"],
    relatedRegionSlugs: ["서울상속등기법무사","은평구상속등기법무사","강서구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "노원구 상속등기 가능 여부 확인",
    ctaDescription: "노원구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "은평구상속등기법무사",
    regionName: "은평구",
    parentRegion: "서울",
    regionType: "구",
    primaryKeyword: "은평구 상속등기 법무사",
    secondaryKeywords: ["은평구 상속등기 비용","은평구 상속등기 서류","서울 상속등기"],
    seoTitle: "은평구 상속등기 법무사｜방문 없이 진행 가능한 범위",
    metaDescription: "은평구 상속등기 법무사. 북한산 인근 주택·아파트와 외곽 토지가 함께 상속되는 사례가 있습니다. 은평구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "은평구 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 은평구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 은평구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "은평구 상속등기를 검색하셔도 반드시 은평구에 사무소가 있어야 하는 것은 아닙니다. 북한산 인근 주택·아파트와 외곽 토지가 함께 상속되는 사례가 있습니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["busan-remote","apt-land-mix","newtown-outer"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["jeju-visit","branch-myth"],
    relatedRegionSlugs: ["서울상속등기법무사","노원구상속등기법무사","마포구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "은평구 상속등기 가능 여부 확인",
    ctaDescription: "은평구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "수원상속등기법무사",
    regionName: "수원",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "수원 상속등기 법무사",
    secondaryKeywords: ["수원 법무사 상속등기","수원 비대면 상속등기","수원 아파트 상속등기"],
    seoTitle: "수원 상속등기 법무사｜아파트·토지 상속 절차와 비용",
    metaDescription: "수원 상속등기 법무사. 장안·권선·팔달·영통 등 행정구역이 나뉜 아파트·상가 상속이 많습니다. 수원 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "수원 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 수원에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 수원 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "수원에서 장안·권선·팔달·영통 등 행정구역이 나뉜 아파트·상가 상속이 많습니다. 다옴법무사사무소는 부산 해운대에 있으므로 수원 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["heir-scattered","sell-first","farm-forest"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["choose-lawyer","jurisdiction-special"],
    relatedRegionSlugs: ["경기상속등기법무사","성남상속등기법무사","용인상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "수원 상속등기 가능 여부 확인",
    ctaDescription: "수원 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "성남상속등기법무사",
    regionName: "성남",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "성남 상속등기 법무사",
    secondaryKeywords: ["성남 상속등기 비용","성남 상속등기 서류","경기 상속등기"],
    seoTitle: "성남 상속등기 법무사｜분당 아파트 비대면 상속등기",
    metaDescription: "성남 상속등기 법무사. 수정·중원·분당 행정구와 인접 시 부동산이 분산되는 경우가 있습니다. 성남 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "성남 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 성남에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 성남 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "성남 부동산 상속등기 문의는 수정·중원·분당 행정구와 인접 시 부동산이 분산되는 경우가 있습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 성남에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["multi-gu","overseas-heir","office-retail"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["gangnam-apt","visit-need"],
    relatedRegionSlugs: ["경기상속등기법무사","분당상속등기법무사","수원상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "성남 상속등기 가능 여부 확인",
    ctaDescription: "성남 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "분당상속등기법무사",
    regionName: "분당",
    parentRegion: "경기",
    regionType: "생활권",
    primaryKeyword: "분당 상속등기 법무사",
    secondaryKeywords: ["분당 상속부동산","분당 상속등기 절차","타지역 상속등기"],
    seoTitle: "분당 상속등기 법무사｜아파트 상속인이 여러 명인 경우",
    metaDescription: "분당 상속등기 법무사. 대단지 아파트 상속에서 상속인이 여러 명이거나 타지역·해외 거주인 경우가 많습니다. 분당 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "분당 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 분당에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 분당 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "분당 상속등기를 검색하셔도 반드시 분당에 사무소가 있어야 하는 것은 아닙니다. 대단지 아파트 상속에서 상속인이 여러 명이거나 타지역·해외 거주인 경우가 많습니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["apt-land-mix","busan-remote","heir-scattered"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["bundang-heirs","cost-split"],
    relatedRegionSlugs: ["경기상속등기법무사","성남상속등기법무사","용인상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "분당 상속등기 가능 여부 확인",
    ctaDescription: "분당 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "용인상속등기법무사",
    regionName: "용인",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "용인 상속등기 법무사",
    secondaryKeywords: ["용인 법무사 상속등기","용인 비대면 상속등기","용인 아파트 상속등기"],
    seoTitle: "용인 상속부동산 등기｜아파트와 토지를 함께 상속받은 경우",
    metaDescription: "용인 상속등기 법무사. 신도시 아파트와 외곽 토지·농지가 함께 상속되는 패턴이 흔합니다. 용인 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "용인에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 용인에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 용인 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "용인에서 신도시 아파트와 외곽 토지·농지가 함께 상속되는 패턴이 흔합니다. 다옴법무사사무소는 부산 해운대에 있으므로 용인 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["sell-first","newtown-outer","heir-scattered"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["remote-table","multi-prop"],
    relatedRegionSlugs: ["경기상속등기법무사","수원상속등기법무사","화성상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "용인 상속등기 가능 여부 확인",
    ctaDescription: "용인 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "고양상속등기법무사",
    regionName: "고양",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "고양 상속등기 법무사",
    secondaryKeywords: ["고양 상속등기 비용","고양 상속등기 서류","경기 상속등기"],
    seoTitle: "고양 상속등기 법무사｜일산 부동산 방문 없이 진행",
    metaDescription: "고양 상속등기 법무사. 일산·덕양 생활권과 토지·주택이 섞인 상속 목록 정리가 중요합니다. 고양 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "고양 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 고양에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 고양 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "고양 부동산 상속등기 문의는 일산·덕양 생활권과 토지·주택이 섞인 상속 목록 정리가 중요합니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 고양에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["overseas-heir","farm-forest","multi-gu"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["branch-myth","deadline-3m"],
    relatedRegionSlugs: ["경기상속등기법무사","일산상속등기법무사","파주상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "고양 상속등기 가능 여부 확인",
    ctaDescription: "고양 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "일산상속등기법무사",
    regionName: "일산",
    parentRegion: "경기",
    regionType: "생활권",
    primaryKeyword: "일산 상속등기 법무사",
    secondaryKeywords: ["일산 법무사 상속등기","일산 비대면 상속등기","일산 아파트 상속등기"],
    seoTitle: "일산 상속등기｜아파트·상가 필요서류와 비용",
    metaDescription: "일산 상속등기 법무사. 일산 신·구 아파트와 상가 상속에서 협의분할·매도 순서를 맞추는 상담이 많습니다. 일산 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "일산 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 일산에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 일산 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "일산 상속등기를 검색하셔도 반드시 일산에 사무소가 있어야 하는 것은 아닙니다. 일산 신·구 아파트와 상가 상속에서 협의분할·매도 순서를 맞추는 상담이 많습니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["office-retail","apt-land-mix","heir-scattered"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["jurisdiction-special","seoul-search"],
    relatedRegionSlugs: ["경기상속등기법무사","고양상속등기법무사","파주상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "일산 상속등기 가능 여부 확인",
    ctaDescription: "일산 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "화성상속등기법무사",
    regionName: "화성",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "화성 상속등기 법무사",
    secondaryKeywords: ["화성 상속등기 비용","화성 상속등기 서류","경기 상속등기"],
    seoTitle: "화성 상속등기 법무사｜동탄 아파트와 토지 상속 절차",
    metaDescription: "화성 상속등기 법무사. 동탄 신도시와 농지·토지가 함께 있는 상속에서 필지 누락을 줄이는 것이 우선입니다. 화성 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "화성 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 화성에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 화성 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "화성에서 동탄 신도시와 농지·토지가 함께 있는 상속에서 필지 누락을 줄이는 것이 우선입니다. 다옴법무사사무소는 부산 해운대에 있으므로 화성 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["newtown-outer","busan-remote","sell-first"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["visit-need","gyeonggi-cities"],
    relatedRegionSlugs: ["경기상속등기법무사","동탄상속등기법무사","용인상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "화성 상속등기 가능 여부 확인",
    ctaDescription: "화성 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "동탄상속등기법무사",
    regionName: "동탄",
    parentRegion: "경기",
    regionType: "생활권",
    primaryKeyword: "동탄 상속등기 법무사",
    secondaryKeywords: ["동탄 상속부동산","동탄 상속등기 절차","타지역 상속등기"],
    seoTitle: "동탄 아파트 상속등기｜상속인이 타지역에 살아도 가능",
    metaDescription: "동탄 상속등기 법무사. 신도시 아파트 상속인이 수도권·영남으로 흩어진 경우 비대면 협의가 필요합니다. 동탄 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "동탄 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 동탄에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 동탄 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "동탄 부동산 상속등기 문의는 신도시 아파트 상속인이 수도권·영남으로 흩어진 경우 비대면 협의가 필요합니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 동탄에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["farm-forest","heir-scattered","overseas-heir"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["cost-split","incheon-songdo"],
    relatedRegionSlugs: ["경기상속등기법무사","화성상속등기법무사","용인상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "동탄 상속등기 가능 여부 확인",
    ctaDescription: "동탄 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "부천상속등기법무사",
    regionName: "부천",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "부천 상속등기 법무사",
    secondaryKeywords: ["부천 법무사 상속등기","부천 비대면 상속등기","부천 아파트 상속등기"],
    seoTitle: "부천 상속등기 법무사｜상속재산분할과 취득세 안내",
    metaDescription: "부천 상속등기 법무사. 구·신 아파트와 상가·오피스텔이 함께 넘어오는 상속이 많습니다. 부천 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "부천에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 부천에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 부천 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "부천 상속등기를 검색하셔도 반드시 부천에 사무소가 있어야 하는 것은 아닙니다. 구·신 아파트와 상가·오피스텔이 함께 넘어오는 상속이 많습니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["office-retail","multi-gu","busan-remote"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["multi-prop","jeju-visit"],
    relatedRegionSlugs: ["경기상속등기법무사","안양상속등기법무사","광명상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "부천 상속등기 가능 여부 확인",
    ctaDescription: "부천 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "안양상속등기법무사",
    regionName: "안양",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "안양 상속등기 법무사",
    secondaryKeywords: ["안양 상속등기 비용","안양 상속등기 서류","경기 상속등기"],
    seoTitle: "안양 상속등기｜비대면 진행 절차와 법무사 비용",
    metaDescription: "안양 상속등기 법무사. 평촌·범계 일대 아파트·상가 상속에서 등기부·임대차를 함께 확인합니다. 안양 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "안양 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 안양에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 안양 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "안양에서 평촌·범계 일대 아파트·상가 상속에서 등기부·임대차를 함께 확인합니다. 다옴법무사사무소는 부산 해운대에 있으므로 안양 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["busan-remote","apt-land-mix","newtown-outer"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["deadline-3m","choose-lawyer"],
    relatedRegionSlugs: ["경기상속등기법무사","부천상속등기법무사","수원상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "안양 상속등기 가능 여부 확인",
    ctaDescription: "안양 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "안산상속등기법무사",
    regionName: "안산",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "안산 상속등기 법무사",
    secondaryKeywords: ["안산 법무사 상속등기","안산 비대면 상속등기","안산 아파트 상속등기"],
    seoTitle: "안산 상속부동산 등기｜아파트·토지 한 번에 정리",
    metaDescription: "안산 상속등기 법무사. 단원·상록 구역 아파트와 산업단지 인근 토지 상속 문의가 있습니다. 안산 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "안산 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 안산에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 안산 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "안산 부동산 상속등기 문의는 단원·상록 구역 아파트와 산업단지 인근 토지 상속 문의가 있습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 안산에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["heir-scattered","sell-first","farm-forest"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["seoul-search","gangnam-apt"],
    relatedRegionSlugs: ["경기상속등기법무사","평택상속등기법무사","광명상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "안산 상속등기 가능 여부 확인",
    ctaDescription: "안산 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "평택상속등기법무사",
    regionName: "평택",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "평택 상속등기 법무사",
    secondaryKeywords: ["평택 상속등기 비용","평택 상속등기 서류","경기 상속등기"],
    seoTitle: "평택 상속등기 법무사｜토지와 주택 상속 필요서류",
    metaDescription: "평택 상속등기 법무사. 항만·산업 인근 토지·주택과 아파트가 함께 상속되는 경우가 있습니다. 평택 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "평택 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 평택에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 평택 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "평택 상속등기를 검색하셔도 반드시 평택에 사무소가 있어야 하는 것은 아닙니다. 항만·산업 인근 토지·주택과 아파트가 함께 상속되는 경우가 있습니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["multi-gu","overseas-heir","office-retail"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["gyeonggi-cities","bundang-heirs"],
    relatedRegionSlugs: ["경기상속등기법무사","안산상속등기법무사","화성상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "평택 상속등기 가능 여부 확인",
    ctaDescription: "평택 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "김포상속등기법무사",
    regionName: "김포",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "김포 상속등기 법무사",
    secondaryKeywords: ["김포 상속부동산","김포 상속등기 절차","타지역 상속등기"],
    seoTitle: "김포 상속등기｜서울 거주 상속인의 비대면 진행 방법",
    metaDescription: "김포 상속등기 법무사. 한강 신도시 아파트와 농지·토지가 섞인 상속에서 목록을 먼저 작성합니다. 김포 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "김포 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 김포에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 김포 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "김포에서 한강 신도시 아파트와 농지·토지가 섞인 상속에서 목록을 먼저 작성합니다. 다옴법무사사무소는 부산 해운대에 있으므로 김포 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["apt-land-mix","busan-remote","heir-scattered"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["incheon-songdo","remote-table"],
    relatedRegionSlugs: ["경기상속등기법무사","고양상속등기법무사","파주상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "김포 상속등기 가능 여부 확인",
    ctaDescription: "김포 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "남양주상속등기법무사",
    regionName: "남양주",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "남양주 상속등기 법무사",
    secondaryKeywords: ["남양주 법무사 상속등기","남양주 비대면 상속등기","남양주 아파트 상속등기"],
    seoTitle: "남양주 상속등기 법무사｜여러 필지 토지 상속 절차",
    metaDescription: "남양주 상속등기 법무사. 별내·다산 신도시와 외곽 주택·토지가 함께 있는 상속이 많습니다. 남양주 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "남양주에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 남양주에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 남양주 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "남양주 부동산 상속등기 문의는 별내·다산 신도시와 외곽 주택·토지가 함께 있는 상속이 많습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 남양주에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["sell-first","newtown-outer","heir-scattered"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["jeju-visit","branch-myth"],
    relatedRegionSlugs: ["경기상속등기법무사","하남상속등기법무사","의정부상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "남양주 상속등기 가능 여부 확인",
    ctaDescription: "남양주 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "하남상속등기법무사",
    regionName: "하남",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "하남 상속등기 법무사",
    secondaryKeywords: ["하남 상속등기 비용","하남 상속등기 서류","경기 상속등기"],
    seoTitle: "하남 아파트 상속등기｜비용·서류·처리기간 안내",
    metaDescription: "하남 상속등기 법무사. 미사·감일 신도시 아파트 상속에서 상속인 거주지가 갈라진 경우가 흔합니다. 하남 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "하남 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 하남에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 하남 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "하남 상속등기를 검색하셔도 반드시 하남에 사무소가 있어야 하는 것은 아닙니다. 미사·감일 신도시 아파트 상속에서 상속인 거주지가 갈라진 경우가 흔합니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["overseas-heir","farm-forest","multi-gu"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["choose-lawyer","jurisdiction-special"],
    relatedRegionSlugs: ["경기상속등기법무사","남양주상속등기법무사","성남상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "하남 상속등기 가능 여부 확인",
    ctaDescription: "하남 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "파주상속등기법무사",
    regionName: "파주",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "파주 상속등기 법무사",
    secondaryKeywords: ["파주 법무사 상속등기","파주 비대면 상속등기","파주 아파트 상속등기"],
    seoTitle: "파주 상속부동산 등기｜토지와 주택이 함께 있는 경우",
    metaDescription: "파주 상속등기 법무사. 운정·금촌 아파트와 외곽 농지·토지 상속에서 지번 확인이 중요합니다. 파주 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "파주 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 파주에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 파주 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "파주에서 운정·금촌 아파트와 외곽 농지·토지 상속에서 지번 확인이 중요합니다. 다옴법무사사무소는 부산 해운대에 있으므로 파주 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["office-retail","apt-land-mix","heir-scattered"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["gangnam-apt","visit-need"],
    relatedRegionSlugs: ["경기상속등기법무사","고양상속등기법무사","김포상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "파주 상속등기 가능 여부 확인",
    ctaDescription: "파주 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "의정부상속등기법무사",
    regionName: "의정부",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "의정부 상속등기 법무사",
    secondaryKeywords: ["의정부 상속등기 비용","의정부 상속등기 서류","경기 상속등기"],
    seoTitle: "의정부 상속등기 법무사｜상속인이 전국에 흩어진 경우",
    metaDescription: "의정부 상속등기 법무사. 도심 아파트·상가와 외곽 토지가 함께 상속되는 사례가 있습니다. 의정부 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "의정부 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 의정부에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 의정부 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "의정부 부동산 상속등기 문의는 도심 아파트·상가와 외곽 토지가 함께 상속되는 사례가 있습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 의정부에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["newtown-outer","busan-remote","sell-first"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["bundang-heirs","cost-split"],
    relatedRegionSlugs: ["경기상속등기법무사","남양주상속등기법무사","파주상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "의정부 상속등기 가능 여부 확인",
    ctaDescription: "의정부 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "광명상속등기법무사",
    regionName: "광명",
    parentRegion: "경기",
    regionType: "시",
    primaryKeyword: "광명 상속등기 법무사",
    secondaryKeywords: ["광명 상속부동산","광명 상속등기 절차","타지역 상속등기"],
    seoTitle: "광명 상속등기｜아파트 상속과 협의분할 진행 방법",
    metaDescription: "광명 상속등기 법무사. 철산·하안 일대 아파트·상가 상속에서 협의·위임 일정 조율이 핵심입니다. 광명 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "광명 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 광명에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 광명 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "광명 상속등기를 검색하셔도 반드시 광명에 사무소가 있어야 하는 것은 아닙니다. 철산·하안 일대 아파트·상가 상속에서 협의·위임 일정 조율이 핵심입니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["farm-forest","heir-scattered","overseas-heir"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["remote-table","multi-prop"],
    relatedRegionSlugs: ["경기상속등기법무사","부천상속등기법무사","안양상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "광명 상속등기 가능 여부 확인",
    ctaDescription: "광명 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "송도상속등기법무사",
    regionName: "송도",
    parentRegion: "인천",
    regionType: "생활권",
    primaryKeyword: "송도 상속등기 법무사",
    secondaryKeywords: ["송도 법무사 상속등기","송도 비대면 상속등기","송도 아파트 상속등기"],
    seoTitle: "송도 상속등기 법무사｜아파트·오피스텔 비대면 진행",
    metaDescription: "송도 상속등기 법무사. 송도 국제도시 아파트·오피스텔 상속에서 상속인이 육지·해외에 있는 경우가 많습니다. 송도 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "송도에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 송도에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 송도 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "송도에서 송도 국제도시 아파트·오피스텔 상속에서 상속인이 육지·해외에 있는 경우가 많습니다. 다옴법무사사무소는 부산 해운대에 있으므로 송도 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["office-retail","multi-gu","busan-remote"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["incheon-songdo","branch-myth","deadline-3m"],
    relatedRegionSlugs: ["인천상속등기법무사","청라상속등기법무사","부평구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "송도 상속등기 가능 여부 확인",
    ctaDescription: "송도 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "청라상속등기법무사",
    regionName: "청라",
    parentRegion: "인천",
    regionType: "생활권",
    primaryKeyword: "청라 상속등기 법무사",
    secondaryKeywords: ["청라 상속등기 비용","청라 상속등기 서류","인천 상속등기"],
    seoTitle: "청라 상속등기｜아파트 상속 필요서류와 비용",
    metaDescription: "청라 상속등기 법무사. 청라 신도시 아파트와 인근 상가 상속에서 비대면 서류 검토가 먼저 이뤄집니다. 청라 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "청라 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 청라에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 청라 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "청라 부동산 상속등기 문의는 청라 신도시 아파트와 인근 상가 상속에서 비대면 서류 검토가 먼저 이뤄집니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 청라에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["busan-remote","apt-land-mix","newtown-outer"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["incheon-songdo","jurisdiction-special","seoul-search"],
    relatedRegionSlugs: ["인천상속등기법무사","송도상속등기법무사","영종도상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "청라 상속등기 가능 여부 확인",
    ctaDescription: "청라 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "부평구상속등기법무사",
    regionName: "부평구",
    parentRegion: "인천",
    regionType: "구",
    primaryKeyword: "부평구 상속등기 법무사",
    secondaryKeywords: ["부평구 법무사 상속등기","부평구 비대면 상속등기","부평구 아파트 상속등기"],
    seoTitle: "부평구 상속등기 법무사｜상속인이 타지역에 사는 경우",
    metaDescription: "부평구 상속등기 법무사. 부평·산곡 일대 구축·신축 아파트와 상가 상속 문의가 꾸준합니다. 부평구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "부평구 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 부평구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 부평구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "부평구 상속등기를 검색하셔도 반드시 부평구에 사무소가 있어야 하는 것은 아닙니다. 부평·산곡 일대 구축·신축 아파트와 상가 상속 문의가 꾸준합니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["heir-scattered","sell-first","farm-forest"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["visit-need","gyeonggi-cities"],
    relatedRegionSlugs: ["인천상속등기법무사","남동구상속등기법무사","송도상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "부평구 상속등기 가능 여부 확인",
    ctaDescription: "부평구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "남동구상속등기법무사",
    regionName: "남동구",
    parentRegion: "인천",
    regionType: "구",
    primaryKeyword: "남동구 상속등기 법무사",
    secondaryKeywords: ["남동구 상속등기 비용","남동구 상속등기 서류","인천 상속등기"],
    seoTitle: "인천 남동구 상속등기｜아파트·상가 상속 절차",
    metaDescription: "남동구 상속등기 법무사. 구월·간석 아파트·상가 상속에서 등기부와 협의분할을 함께 맞춥니다. 남동구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "남동구 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 남동구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 남동구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "남동구에서 구월·간석 아파트·상가 상속에서 등기부와 협의분할을 함께 맞춥니다. 다옴법무사사무소는 부산 해운대에 있으므로 남동구 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["multi-gu","overseas-heir","office-retail"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["cost-split","incheon-songdo"],
    relatedRegionSlugs: ["인천상속등기법무사","부평구상속등기법무사","송도상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "남동구 상속등기 가능 여부 확인",
    ctaDescription: "남동구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "영종도상속등기법무사",
    regionName: "영종도",
    parentRegion: "인천",
    regionType: "생활권",
    primaryKeyword: "영종도 상속등기 법무사",
    secondaryKeywords: ["영종도 상속부동산","영종도 상속등기 절차","타지역 상속등기"],
    seoTitle: "영종도 상속부동산 등기｜육지 거주 상속인의 진행 방법",
    metaDescription: "영종도 상속등기 법무사. 공항 인근 아파트 상속인이 수도권에 거주하는 경우 방문 횟수를 줄이는 절차를 안내합니다. 영종도 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "영종도 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 영종도에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 영종도 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "영종도 부동산 상속등기 문의는 공항 인근 아파트 상속인이 수도권에 거주하는 경우 방문 횟수를 줄이는 절차를 안내합니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 영종도에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["apt-land-mix","busan-remote","heir-scattered"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["multi-prop","jeju-visit"],
    relatedRegionSlugs: ["인천상속등기법무사","송도상속등기법무사","강화도상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "영종도 상속등기 가능 여부 확인",
    ctaDescription: "영종도 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "강화도상속등기법무사",
    regionName: "강화도",
    parentRegion: "인천",
    regionType: "군",
    primaryKeyword: "강화도 상속등기 법무사",
    secondaryKeywords: ["강화도 법무사 상속등기","강화도 비대면 상속등기","강화도 아파트 상속등기"],
    seoTitle: "강화도 토지 상속등기｜여러 필지와 공동상속 정리",
    metaDescription: "강화도 상속등기 법무사. 강화·옹진 토지·주택·농지 상속에서 필지 목록과 지목 확인이 중요합니다. 강화도 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "강화도에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 강화도에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 강화도 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "강화도 상속등기를 검색하셔도 반드시 강화도에 사무소가 있어야 하는 것은 아닙니다. 강화·옹진 토지·주택·농지 상속에서 필지 목록과 지목 확인이 중요합니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["sell-first","newtown-outer","heir-scattered"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["deadline-3m","choose-lawyer"],
    relatedRegionSlugs: ["인천상속등기법무사","영종도상속등기법무사","부평구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "강화도 상속등기 가능 여부 확인",
    ctaDescription: "강화도 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "창원상속등기법무사",
    regionName: "창원",
    parentRegion: "경남",
    regionType: "시",
    primaryKeyword: "창원 상속등기 법무사",
    secondaryKeywords: ["창원 상속등기 비용", "마산 상속등기", "진해 상속등기"],
    seoTitle: "창원 상속등기 법무사｜의창·성산·마산·진해 부동산 정리",
    metaDescription:
      "창원 상속등기 법무사. 의창·성산·마산·진해 5개 구 부동산 일괄 정리. 창원 지점 없이 부산 해운대에서 관할 특례·방문·비대면 가능 여부를 검토합니다.",
    h1: "창원 5개 구의 상속부동산을 한 번에 정리하려면",
    disclosure:
      "다옴법무사사무소는 부산 해운대구에 있으며 창원에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 창원 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro:
      "창원에서는 의창·성산·마산합포·마산회원·진해에 아파트·토지·상가가 나뉜 경우가 많습니다. 부모·조부모 명의 부동산과 상속 후 매도·담보 일정이 겹치면 목록부터 한 표로 맞춥니다. 부산 해운대 사무소에서 방문·비대면 중 편한 방식을 안내하며 창원 지점은 없습니다.",
    scenarioIds: ["multi-gu", "apt-land-mix", "sell-first", "busan-remote"],
    propertyTypeIds: ["apt", "land", "retail"],
    uniqueFaqIds: ["multi-prop", "cost-split", "visit-need", "jurisdiction-special"],
    relatedRegionSlugs: [
      "경남상속등기법무사",
      "김해상속등기법무사",
      "양산상속등기법무사",
      "창원의창구상속등기법무사",
      "진해구상속등기법무사",
      "창원상속등기비용",
    ],
    relatedServiceSlugs: ["전국상속부동산일괄등기", "경남법무사업무"],
    ctaTitle: "창원 상속등기 가능 여부 확인",
    ctaDescription: "어느 구의 부동산인지, 상속인 거주지만 알려주셔도 됩니다.",
  }),
  city({
    slug: "김해상속등기법무사",
    regionName: "김해",
    parentRegion: "경남",
    regionType: "시",
    primaryKeyword: "김해 상속등기 법무사",
    secondaryKeywords: [
      "장유 상속등기",
      "율하 아파트 상속등기",
      "김해 상속등기 비용",
    ],
    seoTitle: "김해 상속등기 법무사｜장유·율하·진영 부동산 비대면 진행",
    metaDescription:
      "김해 상속등기 법무사. 장유·율하 아파트와 진영·주촌 토지·공장 분산 상속. 김해 지점 없이 부산 해운대에서 방문·비대면 가능 여부를 검토합니다.",
    h1: "김해 상속부동산을 부산 법무사에게 맡기는 방법",
    disclosure:
      "다옴법무사사무소는 부산 해운대구에 있으며 김해에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 김해 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro:
      "김해는 부산과 가까워 방문 상담을 원하는 경우와, 장유·율하·진영에 부동산이 흩어진 경우를 자주 문의합니다. 아파트와 토지·공장이 함께 있으면 목록과 매도 일정을 먼저 맞춥니다. 상속인이 부산·타지역에 있어도 한 사무소에서 검토할 수 있는지 안내하며, 김해 지점은 없습니다.",
    scenarioIds: ["apt-land-mix", "heir-scattered", "sell-first", "busan-remote"],
    propertyTypeIds: ["apt", "land", "retail", "farm"],
    uniqueFaqIds: ["visit-need", "cost-split", "branch-myth", "multi-prop"],
    relatedRegionSlugs: [
      "경남상속등기법무사",
      "장유상속등기법무사",
      "율하상속등기법무사",
      "양산상속등기법무사",
      "김해상속등기비용",
      "부산거주김해부동산상속",
    ],
    relatedServiceSlugs: ["전국상속등기법무사", "경남법무사업무"],
    ctaTitle: "김해 상속등기 가능 여부 확인",
    ctaDescription: "장유·율하·진영 등 생활권과 상속인 거주지를 알려주세요.",
  }),
  city({
    slug: "양산상속등기법무사",
    regionName: "양산",
    parentRegion: "경남",
    regionType: "시",
    primaryKeyword: "양산 상속등기 법무사",
    secondaryKeywords: [
      "물금 상속등기",
      "증산 아파트 상속등기",
      "사송 상속등기",
    ],
    seoTitle: "양산 상속등기 법무사｜물금·증산·사송·웅상 부동산 상담",
    metaDescription:
      "양산 상속등기 법무사. 물금·증산·사송 아파트와 원동·상북 토지. 양산 지점 없이 부산 해운대에서 방문·비대면 가능 여부를 검토합니다.",
    h1: "양산 상속등기를 부산에서 방문 또는 비대면으로 진행하려면",
    disclosure:
      "다옴법무사사무소는 부산 해운대구에 있으며 양산에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 양산 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro:
      "양산은 물금·증산·사송 신축 아파트와 원동·상북·하북 토지·농지, 웅상권 주택·상가가 함께 상속되는 문의가 많습니다. 부산 거주 상속인도 방문·비대면 중 편한 방식을 선택할 수 있습니다. 양산 지점은 없으며 해운대 사무소에서 관할·서류를 검토합니다.",
    scenarioIds: ["newtown-outer", "apt-land-mix", "busan-remote", "farm-forest"],
    propertyTypeIds: ["apt", "land", "house", "farm"],
    uniqueFaqIds: ["visit-need", "multi-prop", "cost-split", "jurisdiction-special"],
    relatedRegionSlugs: [
      "경남상속등기법무사",
      "물금상속등기법무사",
      "증산상속등기법무사",
      "사송상속등기법무사",
      "김해상속등기법무사",
      "양산상속등기비용",
    ],
    relatedServiceSlugs: ["전국상속등기법무사", "경남법무사업무"],
    ctaTitle: "양산 상속등기 가능 여부 확인",
    ctaDescription: "물금·증산·사송·웅상 등 권역과 상속인 거주지를 알려주세요.",
  }),
  city({
    slug: "진주상속등기법무사",
    regionName: "진주",
    parentRegion: "경남",
    regionType: "시",
    primaryKeyword: "진주 상속등기 법무사",
    secondaryKeywords: ["진주 상속부동산","진주 상속등기 절차","타지역 상속등기"],
    seoTitle: "진주 상속등기｜상속인이 다른 지역에 살아도 가능한 방법",
    metaDescription: "진주 상속등기 법무사. 내륙 주택·토지·농지와 아파트가 섞인 상속 목록 정리가 필요합니다. 진주 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "진주 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 진주에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 진주 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "진주에서 내륙 주택·토지·농지와 아파트가 섞인 상속 목록 정리가 필요합니다. 다옴법무사사무소는 부산 해운대에 있으므로 진주 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["farm-forest","heir-scattered","overseas-heir"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["jeju-visit","branch-myth"],
    relatedRegionSlugs: ["경남상속등기법무사","창원상속등기법무사","거제상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "진주 상속등기 가능 여부 확인",
    ctaDescription: "진주 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "거제상속등기법무사",
    regionName: "거제",
    parentRegion: "경남",
    regionType: "시",
    primaryKeyword: "거제 상속등기 법무사",
    secondaryKeywords: ["거제 법무사 상속등기","거제 비대면 상속등기","거제 아파트 상속등기"],
    seoTitle: "거제 상속부동산 등기｜아파트·토지 필요서류와 비용",
    metaDescription: "거제 상속등기 법무사. 섬 지역 토지·주택 상속에서 상속인이 육지·부산에 거주하는 경우가 많습니다. 거제 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "거제에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 거제에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 거제 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "거제 부동산 상속등기 문의는 섬 지역 토지·주택 상속에서 상속인이 육지·부산에 거주하는 경우가 많습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 거제에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["office-retail","multi-gu","busan-remote"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["choose-lawyer","jurisdiction-special"],
    relatedRegionSlugs: ["경남상속등기법무사","진주상속등기법무사","김해상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "거제 상속등기 가능 여부 확인",
    ctaDescription: "거제 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "울산남구상속등기법무사",
    regionName: "울산남구",
    parentRegion: "울산",
    regionType: "구",
    primaryKeyword: "울산남구 상속등기 법무사",
    secondaryKeywords: ["울산남구 상속등기 비용","울산남구 상속등기 서류","울산 상속등기"],
    seoTitle: "울산 남구 상속등기｜아파트·상가 비대면 진행",
    metaDescription: "울산남구 상속등기 법무사. 삼산·달동 아파트·상가 상속에서 협의·위임 일정을 맞추는 상담이 많습니다. 울산남구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "울산남구 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 울산남구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 울산남구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "울산남구 상속등기를 검색하셔도 반드시 울산남구에 사무소가 있어야 하는 것은 아닙니다. 삼산·달동 아파트·상가 상속에서 협의·위임 일정을 맞추는 상담이 많습니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["busan-remote","apt-land-mix","newtown-outer"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["gangnam-apt","visit-need"],
    relatedRegionSlugs: ["울산상속등기법무사","울주군상속등기법무사","양산상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "울산남구 상속등기 가능 여부 확인",
    ctaDescription: "울산남구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "울주군상속등기법무사",
    regionName: "울주군",
    parentRegion: "울산",
    regionType: "군",
    primaryKeyword: "울주군 상속등기 법무사",
    secondaryKeywords: ["울주군 법무사 상속등기","울주군 비대면 상속등기","울주군 아파트 상속등기"],
    seoTitle: "울주군 토지 상속등기｜농지·임야·주택 상속 절차",
    metaDescription: "울주군 상속등기 법무사. 온산·언양 일대 토지·주택·농지 상속에서 지번·지목 확인이 중요합니다. 울주군 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "울주군 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 울주군에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 울주군 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "울주군에서 온산·언양 일대 토지·주택·농지 상속에서 지번·지목 확인이 중요합니다. 다옴법무사사무소는 부산 해운대에 있으므로 울주군 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["heir-scattered","sell-first","farm-forest"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["bundang-heirs","cost-split"],
    relatedRegionSlugs: ["울산상속등기법무사","울산남구상속등기법무사","양산상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "울주군 상속등기 가능 여부 확인",
    ctaDescription: "울주군 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "대구수성구상속등기법무사",
    regionName: "대구수성구",
    parentRegion: "대구",
    regionType: "구",
    primaryKeyword: "대구수성구 상속등기 법무사",
    secondaryKeywords: ["대구수성구 상속등기 비용","대구수성구 상속등기 서류","대구 상속등기"],
    seoTitle: "대구 수성구 상속등기 법무사｜아파트 상속 비용과 서류",
    metaDescription: "대구수성구 상속등기 법무사. 범어·수성못 인근 고급 아파트·상가 상속에서 협의분할 논의가 길어질 수 있습니다. 대구수성구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "대구수성구 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 대구수성구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 대구수성구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "대구수성구 부동산 상속등기 문의는 범어·수성못 인근 고급 아파트·상가 상속에서 협의분할 논의가 길어질 수 있습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 대구수성구에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["multi-gu","overseas-heir","office-retail"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["remote-table","multi-prop"],
    relatedRegionSlugs: ["대구상속등기법무사","대구달서구상속등기법무사","경산상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "대구수성구 상속등기 가능 여부 확인",
    ctaDescription: "대구수성구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "대구달서구상속등기법무사",
    regionName: "대구달서구",
    parentRegion: "대구",
    regionType: "구",
    primaryKeyword: "대구달서구 상속등기 법무사",
    secondaryKeywords: ["대구달서구 상속부동산","대구달서구 상속등기 절차","타지역 상속등기"],
    seoTitle: "대구 달서구 상속등기｜상속재산분할과 취득세 안내",
    metaDescription: "대구달서구 상속등기 법무사. 성서·월성 일대 아파트·상가 상속에서 등기부·임대차를 함께 확인합니다. 대구달서구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "대구달서구 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 대구달서구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 대구달서구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "대구달서구 상속등기를 검색하셔도 반드시 대구달서구에 사무소가 있어야 하는 것은 아닙니다. 성서·월성 일대 아파트·상가 상속에서 등기부·임대차를 함께 확인합니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["apt-land-mix","busan-remote","heir-scattered"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["branch-myth","deadline-3m"],
    relatedRegionSlugs: ["대구상속등기법무사","대구수성구상속등기법무사","경산상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "대구달서구 상속등기 가능 여부 확인",
    ctaDescription: "대구달서구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "포항상속등기법무사",
    regionName: "포항",
    parentRegion: "경북",
    regionType: "시",
    primaryKeyword: "포항 상속등기 법무사",
    secondaryKeywords: ["포항 법무사 상속등기","포항 비대면 상속등기","포항 아파트 상속등기"],
    seoTitle: "포항 상속등기 법무사｜아파트·토지 한 번에 정리",
    metaDescription: "포항 상속등기 법무사. 북·남구 아파트와 토지·주택이 함께 상속되는 사례가 많습니다. 포항 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "포항에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 포항에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 포항 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "포항에서 북·남구 아파트와 토지·주택이 함께 상속되는 사례가 많습니다. 다옴법무사사무소는 부산 해운대에 있으므로 포항 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["sell-first","newtown-outer","heir-scattered"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["jurisdiction-special","seoul-search"],
    relatedRegionSlugs: ["경북상속등기법무사","경주상속등기법무사","구미상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "포항 상속등기 가능 여부 확인",
    ctaDescription: "포항 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "구미상속등기법무사",
    regionName: "구미",
    parentRegion: "경북",
    regionType: "시",
    primaryKeyword: "구미 상속등기 법무사",
    secondaryKeywords: ["구미 상속등기 비용","구미 상속등기 서류","경북 상속등기"],
    seoTitle: "구미 상속등기｜상속인이 타지역에 살아도 비대면 진행",
    metaDescription: "구미 상속등기 법무사. 산업도시 아파트·토지 상속에서 상속인 간 거주지가 갈라진 경우가 흔합니다. 구미 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "구미 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 구미에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 구미 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "구미 부동산 상속등기 문의는 산업도시 아파트·토지 상속에서 상속인 간 거주지가 갈라진 경우가 흔합니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 구미에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["overseas-heir","farm-forest","multi-gu"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["visit-need","gyeonggi-cities"],
    relatedRegionSlugs: ["경북상속등기법무사","경산상속등기법무사","포항상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "구미 상속등기 가능 여부 확인",
    ctaDescription: "구미 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "경산상속등기법무사",
    regionName: "경산",
    parentRegion: "경북",
    regionType: "시",
    primaryKeyword: "경산 상속등기 법무사",
    secondaryKeywords: ["경산 법무사 상속등기","경산 비대면 상속등기","경산 아파트 상속등기"],
    seoTitle: "경산 상속부동산 등기｜대구 거주 상속인의 진행 방법",
    metaDescription: "경산 상속등기 법무사. 대구 인접 아파트 상속에서 관할·비대면 절차를 먼저 검토합니다. 경산 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "경산 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 경산에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 경산 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "경산 상속등기를 검색하셔도 반드시 경산에 사무소가 있어야 하는 것은 아닙니다. 대구 인접 아파트 상속에서 관할·비대면 절차를 먼저 검토합니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["office-retail","apt-land-mix","heir-scattered"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["cost-split","incheon-songdo"],
    relatedRegionSlugs: ["경북상속등기법무사","대구수성구상속등기법무사","구미상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "경산 상속등기 가능 여부 확인",
    ctaDescription: "경산 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "경주상속등기법무사",
    regionName: "경주",
    parentRegion: "경북",
    regionType: "시",
    primaryKeyword: "경주 상속등기 법무사",
    secondaryKeywords: ["경주 상속등기 비용","경주 상속등기 서류","경북 상속등기"],
    seoTitle: "경주 토지·주택 상속등기｜필요서류와 비용 안내",
    metaDescription: "경주 상속등기 법무사. 역사도시 주택·토지·농지와 아파트가 섞인 상속에서 필지 누락을 줄입니다. 경주 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "경주 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 경주에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 경주 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "경주에서 역사도시 주택·토지·농지와 아파트가 섞인 상속에서 필지 누락을 줄입니다. 다옴법무사사무소는 부산 해운대에 있으므로 경주 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["newtown-outer","busan-remote","sell-first"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["multi-prop","jeju-visit"],
    relatedRegionSlugs: ["경북상속등기법무사","포항상속등기법무사","구미상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "경주 상속등기 가능 여부 확인",
    ctaDescription: "경주 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "대전유성구상속등기법무사",
    regionName: "대전유성구",
    parentRegion: "대전",
    regionType: "구",
    primaryKeyword: "대전유성구 상속등기 법무사",
    secondaryKeywords: ["대전유성구 상속부동산","대전유성구 상속등기 절차","타지역 상속등기"],
    seoTitle: "대전 유성구 상속등기｜아파트·상가 비대면 진행",
    metaDescription: "대전유성구 상속등기 법무사. 대덕·유성 연구단지 인근 아파트·상가 상속에서 상속인 타지역 거주가 많습니다. 대전유성구 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "대전유성구 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 대전유성구에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 대전유성구 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "대전유성구 부동산 상속등기 문의는 대덕·유성 연구단지 인근 아파트·상가 상속에서 상속인 타지역 거주가 많습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 대전유성구에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["farm-forest","heir-scattered","overseas-heir"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["deadline-3m","choose-lawyer"],
    relatedRegionSlugs: ["대전상속등기법무사","천안상속등기법무사","청주상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "대전유성구 상속등기 가능 여부 확인",
    ctaDescription: "대전유성구 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "천안상속등기법무사",
    regionName: "천안",
    parentRegion: "충남",
    regionType: "시",
    primaryKeyword: "천안 상속등기 법무사",
    secondaryKeywords: ["천안 법무사 상속등기","천안 비대면 상속등기","천안 아파트 상속등기"],
    seoTitle: "천안 상속등기 법무사｜아파트와 토지 상속 절차",
    metaDescription: "천안 상속등기 법무사. 두정·불당·배방 일대 아파트와 외곽 토지·농지가 함께 상속됩니다. 천안 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "천안에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 천안에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 천안 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "천안 상속등기를 검색하셔도 반드시 천안에 사무소가 있어야 하는 것은 아닙니다. 두정·불당·배방 일대 아파트와 외곽 토지·농지가 함께 상속됩니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["office-retail","multi-gu","busan-remote"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["seoul-search","gangnam-apt"],
    relatedRegionSlugs: ["충남상속등기법무사","아산상속등기법무사","대전유성구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "천안 상속등기 가능 여부 확인",
    ctaDescription: "천안 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "아산상속등기법무사",
    regionName: "아산",
    parentRegion: "충남",
    regionType: "시",
    primaryKeyword: "아산 상속등기 법무사",
    secondaryKeywords: ["아산 상속등기 비용","아산 상속등기 서류","충남 상속등기"],
    seoTitle: "아산 상속등기｜상속인이 다른 지역에 사는 경우",
    metaDescription: "아산 상속등기 법무사. 탕정·배방 신도시와 농지·토지 상속에서 목록을 먼저 작성합니다. 아산 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "아산 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 아산에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 아산 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "아산에서 탕정·배방 신도시와 농지·토지 상속에서 목록을 먼저 작성합니다. 다옴법무사사무소는 부산 해운대에 있으므로 아산 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["busan-remote","apt-land-mix","newtown-outer"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["gyeonggi-cities","bundang-heirs"],
    relatedRegionSlugs: ["충남상속등기법무사","천안상속등기법무사","평택상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "아산 상속등기 가능 여부 확인",
    ctaDescription: "아산 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "청주상속등기법무사",
    regionName: "청주",
    parentRegion: "충북",
    regionType: "시",
    primaryKeyword: "청주 상속등기 법무사",
    secondaryKeywords: ["청주 법무사 상속등기","청주 비대면 상속등기","청주 아파트 상속등기"],
    seoTitle: "청주 상속등기 법무사｜부동산 상속 비용·서류 총정리",
    metaDescription: "청주 상속등기 법무사. 흥덕·상당·서원·청원 행정구역에 걸친 아파트·토지 상속이 많습니다. 청주 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "청주 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 청주에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 청주 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "청주 부동산 상속등기 문의는 흥덕·상당·서원·청원 행정구역에 걸친 아파트·토지 상속이 많습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 청주에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["heir-scattered","sell-first","farm-forest"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["incheon-songdo","remote-table"],
    relatedRegionSlugs: ["충북상속등기법무사","충주상속등기법무사","대전유성구상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "청주 상속등기 가능 여부 확인",
    ctaDescription: "청주 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "충주상속등기법무사",
    regionName: "충주",
    parentRegion: "충북",
    regionType: "시",
    primaryKeyword: "충주 상속등기 법무사",
    secondaryKeywords: ["충주 상속등기 비용","충주 상속등기 서류","충북 상속등기"],
    seoTitle: "충주 상속부동산 등기｜토지와 주택 일괄 검토",
    metaDescription: "충주 상속등기 법무사. 내륙 주택·농지·임야와 아파트가 함께 상속되는 사례가 있습니다. 충주 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "충주 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 충주에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 충주 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "충주 상속등기를 검색하셔도 반드시 충주에 사무소가 있어야 하는 것은 아닙니다. 내륙 주택·농지·임야와 아파트가 함께 상속되는 사례가 있습니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["multi-gu","overseas-heir","office-retail"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["jeju-visit","branch-myth"],
    relatedRegionSlugs: ["충북상속등기법무사","청주상속등기법무사","원주상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "충주 상속등기 가능 여부 확인",
    ctaDescription: "충주 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "전주상속등기법무사",
    regionName: "전주",
    parentRegion: "전북",
    regionType: "시",
    primaryKeyword: "전주 상속등기 법무사",
    secondaryKeywords: ["전주 상속부동산","전주 상속등기 절차","타지역 상속등기"],
    seoTitle: "전주 상속등기 법무사｜아파트·토지 비대면 진행",
    metaDescription: "전주 상속등기 법무사. 한옥·상가와 아파트가 섞인 상속에서 권리관계 확인이 중요합니다. 전주 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "전주 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 전주에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 전주 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "전주에서 한옥·상가와 아파트가 섞인 상속에서 권리관계 확인이 중요합니다. 다옴법무사사무소는 부산 해운대에 있으므로 전주 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["apt-land-mix","busan-remote","heir-scattered"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["choose-lawyer","jurisdiction-special"],
    relatedRegionSlugs: ["전북상속등기법무사","익산상속등기법무사","군산상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "전주 상속등기 가능 여부 확인",
    ctaDescription: "전주 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "익산상속등기법무사",
    regionName: "익산",
    parentRegion: "전북",
    regionType: "시",
    primaryKeyword: "익산 상속등기 법무사",
    secondaryKeywords: ["익산 법무사 상속등기","익산 비대면 상속등기","익산 아파트 상속등기"],
    seoTitle: "익산 상속등기｜상속인이 전국에 흩어진 경우",
    metaDescription: "익산 상속등기 법무사. 산업·주거 지역 아파트·토지 상속에서 협의·위임을 정리합니다. 익산 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "익산에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 익산에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 익산 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "익산 부동산 상속등기 문의는 산업·주거 지역 아파트·토지 상속에서 협의·위임을 정리합니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 익산에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["sell-first","newtown-outer","heir-scattered"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["gangnam-apt","visit-need"],
    relatedRegionSlugs: ["전북상속등기법무사","전주상속등기법무사","군산상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "익산 상속등기 가능 여부 확인",
    ctaDescription: "익산 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "군산상속등기법무사",
    regionName: "군산",
    parentRegion: "전북",
    regionType: "시",
    primaryKeyword: "군산 상속등기 법무사",
    secondaryKeywords: ["군산 상속등기 비용","군산 상속등기 서류","전북 상속등기"],
    seoTitle: "군산 상속부동산 등기｜주택·상가·토지 상속 절차",
    metaDescription: "군산 상속등기 법무사. 항만·구도심 상가와 아파트·토지가 함께 상속되는 경우가 많습니다. 군산 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "군산 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 군산에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 군산 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "군산 상속등기를 검색하셔도 반드시 군산에 사무소가 있어야 하는 것은 아닙니다. 항만·구도심 상가와 아파트·토지가 함께 상속되는 경우가 많습니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["overseas-heir","farm-forest","multi-gu"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["bundang-heirs","cost-split"],
    relatedRegionSlugs: ["전북상속등기법무사","익산상속등기법무사","전주상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "군산 상속등기 가능 여부 확인",
    ctaDescription: "군산 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "순천상속등기법무사",
    regionName: "순천",
    parentRegion: "전남",
    regionType: "시",
    primaryKeyword: "순천 상속등기 법무사",
    secondaryKeywords: ["순천 법무사 상속등기","순천 비대면 상속등기","순천 아파트 상속등기"],
    seoTitle: "순천 상속등기 법무사｜아파트와 토지 일괄 진행",
    metaDescription: "순천 상속등기 법무사. 순천만 인근 토지·농지와 아파트 상속에서 필지 목록이 중요합니다. 순천 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "순천 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 순천에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 순천 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "순천에서 순천만 인근 토지·농지와 아파트 상속에서 필지 목록이 중요합니다. 다옴법무사사무소는 부산 해운대에 있으므로 순천 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["office-retail","apt-land-mix","heir-scattered"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["remote-table","multi-prop"],
    relatedRegionSlugs: ["전남상속등기법무사","여수상속등기법무사","목포상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "순천 상속등기 가능 여부 확인",
    ctaDescription: "순천 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "여수상속등기법무사",
    regionName: "여수",
    parentRegion: "전남",
    regionType: "시",
    primaryKeyword: "여수 상속등기 법무사",
    secondaryKeywords: ["여수 상속등기 비용","여수 상속등기 서류","전남 상속등기"],
    seoTitle: "여수 상속등기｜상속인이 타지역에 살아도 가능한 방법",
    metaDescription: "여수 상속등기 법무사. 연안 주택·토지·상가와 아파트 상속에서 상속인 수도권 거주가 흔합니다. 여수 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "여수 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 여수에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 여수 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "여수 부동산 상속등기 문의는 연안 주택·토지·상가와 아파트 상속에서 상속인 수도권 거주가 흔합니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 여수에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["newtown-outer","busan-remote","sell-first"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["branch-myth","deadline-3m"],
    relatedRegionSlugs: ["전남상속등기법무사","순천상속등기법무사","목포상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "여수 상속등기 가능 여부 확인",
    ctaDescription: "여수 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "목포상속등기법무사",
    regionName: "목포",
    parentRegion: "전남",
    regionType: "시",
    primaryKeyword: "목포 상속등기 법무사",
    secondaryKeywords: ["목포 상속부동산","목포 상속등기 절차","타지역 상속등기"],
    seoTitle: "목포 상속부동산 등기｜필요서류와 법무사 비용",
    metaDescription: "목포 상속등기 법무사. 항구·구도심 상가·주택과 아파트 상속에서 등기부를 함께 확인합니다. 목포 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "목포 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 목포에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 목포 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "목포 상속등기를 검색하셔도 반드시 목포에 사무소가 있어야 하는 것은 아닙니다. 항구·구도심 상가·주택과 아파트 상속에서 등기부를 함께 확인합니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["farm-forest","heir-scattered","overseas-heir"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["jurisdiction-special","seoul-search"],
    relatedRegionSlugs: ["전남상속등기법무사","여수상속등기법무사","순천상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "목포 상속등기 가능 여부 확인",
    ctaDescription: "목포 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "원주상속등기법무사",
    regionName: "원주",
    parentRegion: "강원",
    regionType: "시",
    primaryKeyword: "원주 상속등기 법무사",
    secondaryKeywords: ["원주 법무사 상속등기","원주 비대면 상속등기","원주 아파트 상속등기"],
    seoTitle: "원주 상속등기 법무사｜아파트·토지 비대면 진행",
    metaDescription: "원주 상속등기 법무사. 단구·명륜 아파트와 외곽 토지·농지 상속에서 지번 확인이 중요합니다. 원주 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "원주에 있는 아파트·토지, 어디서 상속등기를 받을까",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 원주에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 원주 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "원주에서 단구·명륜 아파트와 외곽 토지·농지 상속에서 지번 확인이 중요합니다. 다옴법무사사무소는 부산 해운대에 있으므로 원주 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["office-retail","multi-gu","busan-remote"],
    propertyTypeIds: ["land","farm","house"],
    uniqueFaqIds: ["visit-need","gyeonggi-cities"],
    relatedRegionSlugs: ["강원상속등기법무사","춘천상속등기법무사","강릉상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "원주 상속등기 가능 여부 확인",
    ctaDescription: "원주 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "춘천상속등기법무사",
    regionName: "춘천",
    parentRegion: "강원",
    regionType: "시",
    primaryKeyword: "춘천 상속등기 법무사",
    secondaryKeywords: ["춘천 상속등기 비용","춘천 상속등기 서류","강원 상속등기"],
    seoTitle: "춘천 상속등기｜상속인이 수도권에 거주하는 경우",
    metaDescription: "춘천 상속등기 법무사. 호수·도심 아파트와 주택·토지가 함께 상속되는 사례가 많습니다. 춘천 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "춘천 상속인이 여러 지역에 살아도 진행 가능한가",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 춘천에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 춘천 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "춘천 부동산 상속등기 문의는 호수·도심 아파트와 주택·토지가 함께 상속되는 사례가 많습니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 춘천에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["busan-remote","apt-land-mix","newtown-outer"],
    propertyTypeIds: ["apt","land","farm"],
    uniqueFaqIds: ["cost-split","incheon-songdo"],
    relatedRegionSlugs: ["강원상속등기법무사","원주상속등기법무사","강릉상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사"],
    ctaTitle: "춘천 상속등기 가능 여부 확인",
    ctaDescription: "춘천 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "강릉상속등기법무사",
    regionName: "강릉",
    parentRegion: "강원",
    regionType: "시",
    primaryKeyword: "강릉 상속등기 법무사",
    secondaryKeywords: ["강릉 법무사 상속등기","강릉 비대면 상속등기","강릉 아파트 상속등기"],
    seoTitle: "강릉 상속부동산 등기｜주택·토지 상속 절차와 비용",
    metaDescription: "강릉 상속등기 법무사. 연안·내륙 토지·주택·농지와 아파트 상속에서 상속인 타지역 거주가 흔합니다. 강릉 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "강릉 상속부동산을 부산 방문 없이 맡기는 방법",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 강릉에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 강릉 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "강릉 상속등기를 검색하셔도 반드시 강릉에 사무소가 있어야 하는 것은 아닙니다. 연안·내륙 토지·주택·농지와 아파트 상속에서 상속인 타지역 거주가 흔합니다. 상속인이 서울·부산·해외 등 다른 지역에 있어도, 협의분할·위임·등기부 확인을 한 사무소에서 정리할 수 있는지 먼저 검토합니다. 공과금과 법무사 보수를 구분해 안내하며, 가짜 실적이나 지점 존재를 표현하지 않습니다.",
    scenarioIds: ["heir-scattered","sell-first","farm-forest"],
    propertyTypeIds: ["apt","retail","house"],
    uniqueFaqIds: ["multi-prop","jeju-visit"],
    relatedRegionSlugs: ["강원상속등기법무사","원주상속등기법무사","춘천상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국상속부동산일괄등기"],
    ctaTitle: "강릉 상속등기 가능 여부 확인",
    ctaDescription: "강릉 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "제주시상속등기법무사",
    regionName: "제주시",
    parentRegion: "제주",
    regionType: "시",
    primaryKeyword: "제주시 상속등기 법무사",
    secondaryKeywords: ["제주시 상속등기 비용","제주시 상속등기 서류","제주 상속등기"],
    seoTitle: "제주시 상속등기 법무사｜육지 거주 상속인의 비대면 진행",
    metaDescription: "제주시 상속등기 법무사. 제주시 아파트·토지·농지 상속에서 상속인이 육지에 거주하는 경우가 많습니다. 제주시 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "제주시 상속등기 비용과 필요서류부터 확인하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 제주시에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 제주시 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "제주시에서 제주시 아파트·토지·농지 상속에서 상속인이 육지에 거주하는 경우가 많습니다. 다옴법무사사무소는 부산 해운대에 있으므로 제주시 지점이 있다는 뜻이 아닙니다. 초기 상담에서는 등기부·협의 개요·상속인 거주지만으로 진행 가능 범위를 설명하고, 원본이 필요한 단계는 수임 전에 구분합니다. 아파트·상가·토지가 섞여 있으면 목록표부터 작성하는 것이 누락을 줄입니다.",
    scenarioIds: ["multi-gu","overseas-heir","office-retail","mainland-jeju"],
    propertyTypeIds: ["apt","land","house"],
    uniqueFaqIds: ["jeju-visit","deadline-3m","choose-lawyer"],
    relatedRegionSlugs: ["제주상속등기법무사","서귀포상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속등기법무사","전국비대면법무사"],
    ctaTitle: "제주시 상속등기 가능 여부 확인",
    ctaDescription: "제주시 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  }),
  city({
    slug: "서귀포상속등기법무사",
    regionName: "서귀포",
    parentRegion: "제주",
    regionType: "시",
    primaryKeyword: "서귀포 상속등기 법무사",
    secondaryKeywords: ["서귀포 상속부동산","서귀포 상속등기 절차","타지역 상속등기"],
    seoTitle: "서귀포 상속부동산 등기｜토지·주택 상속 필요서류",
    metaDescription: "서귀포 상속등기 법무사. 서귀포·중문 토지·주택·농지 상속에서 방문 없이 가능한 단계를 구분해 안내합니다. 서귀포 지점 없이 부산 해운대 사무소에서 관할 특례·비대면 진행 가능 여부를 검토합니다.",
    h1: "서귀포 부동산 상속등기, 관할 특례부터 검토하기",
    disclosure: "다옴법무사사무소는 부산 해운대구에 있으며 서귀포에 별도 지점이 있는 것은 아닙니다. 상속등기 관할 특례와 비대면 서류 전달 방식을 검토하여 서귀포 소재 부동산도 진행 가능 여부를 안내합니다.",
    localIntro: "서귀포 부동산 상속등기 문의는 서귀포·중문 토지·주택·농지 상속에서 방문 없이 가능한 단계를 구분해 안내합니다. 거리보다 관할 특례 적용 여부와 서류 수집 순서가 중요합니다. 부산 해운대 사무소에서 전화·카카오·우편으로 상담하며, 서귀포에 별도 출장 사무소는 운영하지 않습니다. 매도를 앞둔 물건이 있으면 협의분할과 신청 순서를 함께 맞춥니다.",
    scenarioIds: ["apt-land-mix","mainland-jeju","busan-remote"],
    propertyTypeIds: ["apt","retail","land"],
    uniqueFaqIds: ["jeju-visit","seoul-search","gangnam-apt"],
    relatedRegionSlugs: ["제주상속등기법무사","제주시상속등기법무사","지역별상속등기법무사"],
    relatedServiceSlugs: ["전국상속부동산일괄등기","전국비대면법무사"],
    ctaTitle: "서귀포 상속등기 가능 여부 확인",
    ctaDescription: "서귀포 부동산 종류와 상속인 거주지만 알려주셔도 서류 목록을 안내합니다.",
  })
];
