import type { RegionLandingDef } from "./types";

/** 전국 업무·허브 페이지 (1차 공개) */
export const nationwideServiceDefs: RegionLandingDef[] = [
  {
    slug: "전국업무사례",
    regionName: "전국",
    regionType: "전국허브",
    priority: 1,
    kind: "hub",
    noticeType: "remote-accept",
    primaryKeyword: "전국 법무사 업무사례",
    secondaryKeywords: [
      "전국 상속등기",
      "비대면 법무사",
      "타지역 법무사 의뢰",
    ],
    seoTitle: "전국 법무사 업무사례｜상속등기·유증등기·법인등기 비대면 진행",
    metaDescription:
      "부산 다옴법무사사무소 전국 법무사 업무사례. 상속·유증 관할 특례, 본점이전, 공동근저당, 비대면 수임을 구분해 안내합니다. 지점 오인 없이 진행 가능 여부를 먼저 확인합니다.",
    h1: "부산에 방문하지 않아도 맡길 수 있는 전국 법무사 업무",
    disclosure:
      "다옴법무사사무소는 부산 해운대구에 있으며, 해당 지역에 별도 지점이 있다는 의미는 아닙니다. 상속·유증등기의 관할 특례와 비대면 상담·서류 전달 방식을 활용하여 타지역 사건도 진행 가능 여부를 검토합니다.",
    localIntro:
      "다옴법무사사무소는 부산 해운대구에 있지만 모든 업무가 부산 사건으로 한정되는 것은 아닙니다. 상속·유증등기처럼 관할 특례가 적용될 수 있는 업무와 법정 관할을 지키면서 비대면으로 상담·서류 준비·신청을 진행할 수 있는 업무를 구분하여 전국 의뢰를 검토합니다.",
    scenarioIds: ["heir-scattered", "multi-gu", "busan-remote"],
    propertyTypeIds: ["apt", "land", "retail"],
    uniqueFaqIds: ["branch-myth", "jurisdiction-special", "cost-split", "choose-lawyer"],
    relatedRegionSlugs: ["지역별상속등기법무사", "서울상속등기법무사", "경기상속등기법무사"],
    relatedServiceSlugs: [
      "전국상속등기법무사",
      "전국유증등기법무사",
      "전국상속부동산일괄등기",
      "전국법인본점이전등기",
      "전국공동근저당권등기",
      "전국비대면법무사",
    ],
    ctaTitle: "내 지역도 진행 가능한지 확인하기",
    ctaDescription:
      "거주 지역과 부동산·법인 소재지만 알려주셔도 전국 진행 가능 여부와 준비 서류부터 안내합니다.",
    published: true,
  },
  {
    slug: "전국상속등기법무사",
    regionName: "전국",
    regionType: "전국허브",
    priority: 1,
    kind: "service",
    noticeType: "jurisdiction-exception",
    primaryKeyword: "전국 상속등기 법무사",
    secondaryKeywords: [
      "비대면 상속등기",
      "타지역 상속등기",
      "상속등기 관할 특례",
    ],
    seoTitle: "전국 상속등기 법무사｜타지역 부동산도 비대면 진행",
    metaDescription:
      "전국 상속등기 법무사 안내. 타지역·비대면 상속등기, 관할 특례, 해외 상속인, 취득세·공과금 구분. 부산 해운대 사무소에서 진행 가능 여부를 검토합니다.",
    h1: "전국 어디서나 맡길 수 있는 상속등기",
    disclosure:
      "다옴법무사사무소는 부산 해운대구에 있으며 타지역 지점이 없습니다. 상속등기 관할 특례와 비대면 서류 전달을 검토하여 진행 가능 여부를 안내합니다.",
    localIntro:
      "부동산이 부산에 있지 않아도 상속등기를 상담할 수 있습니다. 상속인이 서로 다른 지역에 살아도, 전국에 부동산이 흩어져 있어도 서류 수집부터 신청 방식까지 한 사무소에서 검토합니다.",
    scenarioIds: ["heir-scattered", "apt-land-mix", "overseas-heir", "busan-remote"],
    propertyTypeIds: ["apt", "land", "house"],
    uniqueFaqIds: ["jurisdiction-special", "deadline-3m", "visit-need", "multi-prop"],
    relatedRegionSlugs: ["지역별상속등기법무사", "전국상속부동산일괄등기"],
    relatedServiceSlugs: ["전국유증등기법무사", "전국비대면법무사", "타지역법무사의뢰"],
    ctaTitle: "전국 상속등기 가능 여부 확인하기",
    ctaDescription: "부동산 소재지와 상속인 거주 지역만 알려주셔도 다음 확인 항목을 정리합니다.",
    published: true,
  },
  {
    slug: "전국유증등기법무사",
    regionName: "전국",
    regionType: "전국허브",
    priority: 1,
    kind: "service",
    noticeType: "jurisdiction-exception",
    primaryKeyword: "전국 유증등기",
    secondaryKeywords: ["유증등기 법무사", "유언 부동산 이전", "유증등기 관할 특례"],
    seoTitle: "전국 유증등기 법무사｜유언에 따른 부동산 이전 절차",
    metaDescription:
      "전국 유증등기 법무사. 특정·포괄유증, 유언공정증서, 유언집행자, 해외 수증자, 관할 특례와 필요서류·비용을 상속등기와 구분해 안내합니다.",
    h1: "부동산 소재지가 달라도 상담할 수 있는 유증등기",
    disclosure:
      "부산 해운대 사무소이며 타지역 지점이 없습니다. 유증등기 관할 특례 적용 여부는 사건별로 확인합니다.",
    localIntro:
      "유언에 따른 부동산 이전은 상속등기와 서류·쟁점이 다릅니다. 포괄·특정유증, 유언집행자, 이미 상속등기가 끝난 경우 등을 구분해 안내합니다.",
    scenarioIds: ["overseas-heir", "office-retail", "busan-remote"],
    propertyTypeIds: ["apt", "retail", "land"],
    uniqueFaqIds: ["jurisdiction-special", "branch-myth", "cost-split"],
    relatedRegionSlugs: ["전국상속등기법무사"],
    relatedServiceSlugs: ["전국업무사례", "전국비대면법무사"],
    ctaTitle: "유증등기 필요서류 확인하기",
    ctaDescription: "유언 형식과 부동산 소재지만 알려주셔도 다음 단계를 안내합니다.",
    published: true,
  },
  {
    slug: "전국상속부동산일괄등기",
    regionName: "전국",
    regionType: "전국허브",
    priority: 1,
    kind: "service",
    noticeType: "jurisdiction-exception",
    primaryKeyword: "여러 지역에 흩어진 상속부동산 등기",
    secondaryKeywords: ["전국 상속부동산 일괄등기", "여러 지역 상속등기"],
    seoTitle: "전국 상속부동산 일괄등기｜여러 지역 부동산 한 번에 정리",
    metaDescription:
      "전국에 흩어진 상속부동산 일괄 검토. 서울 아파트와 지방 토지, 부동산별 상속인, 취득세·누락 방지, 일부 매도 일정을 한 사무소에서 정리합니다.",
    h1: "전국에 흩어진 상속부동산을 한 번에 정리하려면",
    disclosure:
      "부산 사무소이며 각 지역 지점이 없습니다. 복수 부동산의 관할 특례·신청 묶음 가능 여부는 사건별 확인이 필요합니다.",
    localIntro:
      "서울 아파트와 지방 토지를 함께 상속받거나, 부동산마다 받는 사람이 다른 경우 누락·취득세·협의 불일치가 생기기 쉽습니다. 전국 상속등기 일반론과 달리 복수 자산 정리에 집중합니다.",
    scenarioIds: ["multi-gu", "apt-land-mix", "sell-first", "farm-forest"],
    propertyTypeIds: ["apt", "land", "farm", "retail"],
    uniqueFaqIds: ["multi-prop", "cost-split", "deadline-3m"],
    relatedRegionSlugs: ["전국상속등기법무사", "지역별상속등기법무사"],
    relatedServiceSlugs: ["전국업무사례"],
    ctaTitle: "여러 지역 부동산 한 번에 문의하기",
    ctaDescription: "알고 있는 주소 목록만 남겨주셔도 누락 점검부터 안내합니다.",
    published: true,
  },
  {
    slug: "전국법인본점이전등기",
    regionName: "전국",
    regionType: "전국허브",
    priority: 1,
    kind: "service",
    noticeType: "expandable-jurisdiction",
    primaryKeyword: "전국 법인 본점이전등기",
    secondaryKeywords: ["타관할 본점이전", "서울 부산 본점이전"],
    seoTitle: "전국 법인 본점이전등기｜서울·경기·부산 타지역 이전",
    metaDescription:
      "전국 법인 본점이전등기. 동일·타관할 차이, 서울↔부산·경남 이전, 정관·등록면허세·임원변경 동시 신청을 비대면으로 상담합니다. 법정 관할은 유지됩니다.",
    h1: "지역이 달라지는 법인 본점이전등기",
    disclosure:
      "부산 해운대 사무소이며 타지역 법인등기 지점이 없습니다. 본점이전은 종전·신규 관할을 확인한 뒤 진행합니다.",
    localIntro:
      "관할 외 본점이전등기는 종전 본점과 새 본점 소재지 관할을 확인합니다. 부산으로 오는 이전과 부산에서 나가는 이전 모두 비대면 상담이 가능합니다.",
    scenarioIds: ["busan-remote", "office-retail"],
    propertyTypeIds: ["retail"],
    uniqueFaqIds: ["hq-transfer", "visit-need", "cost-split"],
    relatedRegionSlugs: ["전국업무사례"],
    relatedServiceSlugs: ["전국공동근저당권등기", "전국비대면법무사"],
    ctaTitle: "방문 없이 본점이전 가능 여부 확인하기",
    ctaDescription: "종전·신규 본점 주소와 희망일만 알려주셔도 관할·서류를 정리합니다.",
    published: true,
  },
  {
    slug: "전국공동근저당권등기",
    regionName: "전국",
    regionType: "전국허브",
    priority: 1,
    kind: "service",
    noticeType: "bundled-jurisdiction",
    primaryKeyword: "전국 공동근저당권등기",
    secondaryKeywords: ["여러 지역 부동산 공동담보", "공동담보목록"],
    seoTitle: "전국 공동근저당권등기｜여러 지역 부동산 공동담보 설정",
    metaDescription:
      "전국 공동근저당권등기. 공동담보목록, 담보 추가·해지, 채권최고액·채무자 변경. 일괄 신청은 사건별 요건 확인 후 안내합니다.",
    h1: "서로 다른 지역의 부동산을 공동담보로 제공하는 경우",
    disclosure:
      "부산 사무소이며 타지역 지점이 없습니다. 복수 관할 공동담보의 묶음 신청 가능 여부는 단정하지 않고 요건을 확인합니다.",
    localIntro:
      "서로 다른 지역 부동산을 하나의 채권을 위해 공동담보로 제공하는 경우, 당사자·등기목적·등기원인 구조에 따라 하나의 관할에서 함께 신청할 수 있는지 검토할 수 있습니다.",
    scenarioIds: ["multi-gu", "apt-land-mix", "busan-remote"],
    propertyTypeIds: ["apt", "land", "retail"],
    uniqueFaqIds: ["joint-mortgage", "cost-split", "branch-myth"],
    relatedRegionSlugs: ["전국업무사례"],
    relatedServiceSlugs: ["전국법인본점이전등기", "전국비대면법무사"],
    ctaTitle: "여러 지역 공동담보 가능 여부 확인하기",
    ctaDescription: "담보 부동산 지역과 채권최고액 규모만 알려주셔도 검토 포인트를 안내합니다.",
    published: true,
  },
  {
    slug: "전국비대면법무사",
    regionName: "전국",
    regionType: "전국허브",
    priority: 1,
    kind: "service",
    noticeType: "remote-accept",
    primaryKeyword: "전국 비대면 법무사",
    secondaryKeywords: ["방문 없이 법무사", "비대면 등기", "비대면 상속"],
    seoTitle: "전국 비대면 법무사｜방문 없이 가능한 등기·상속 업무",
    metaDescription:
      "전국 비대면 법무사 안내. 업무별 비대면 상담·원본·법정 관할·방문 가능성·전자·우편 신청을 표로 정리합니다. 부산 해운대 사무소 기준.",
    h1: "부산까지 방문하지 않고 진행할 수 있는 법무사 업무",
    disclosure:
      "다옴법무사사무소는 부산 해운대구에 있습니다. 비대면 수임과 「전국 어느 관할에나 신청」은 다릅니다.",
    localIntro:
      "업무마다 비대면으로 가능한 단계와 원본·방문이 필요한 단계가 다릅니다. 수임 전에 표 기준으로 범위를 안내합니다.",
    scenarioIds: ["busan-remote", "heir-scattered"],
    propertyTypeIds: ["apt", "land"],
    uniqueFaqIds: ["remote-table", "visit-need", "branch-myth", "choose-lawyer"],
    relatedRegionSlugs: ["타지역법무사의뢰", "전국상속등기법무사"],
    relatedServiceSlugs: ["전국업무사례"],
    ctaTitle: "방문 없이 진행 가능한지 확인하기",
    ctaDescription: "문의 업무와 소재 지역만 알려주셔도 비대면 가능 범위를 안내합니다.",
    published: true,
  },
  {
    slug: "타지역법무사의뢰",
    regionName: "전국",
    regionType: "전국허브",
    priority: 1,
    kind: "service",
    noticeType: "remote-accept",
    primaryKeyword: "타지역 법무사 의뢰",
    secondaryKeywords: ["거리가 있는 법무사", "타지역 법무사 선택"],
    seoTitle: "타지역 법무사 의뢰｜거리가 있어도 맡길 수 있는 업무와 절차",
    metaDescription:
      "타지역 법무사 의뢰 전 확인사항. 관할 지역 법무사만 선임해야 하는지, 원본·본인확인·추가 비용·직접 상담 여부를 정리합니다.",
    h1: "거리가 있는 법무사에게 업무를 맡기기 전 확인할 사항",
    disclosure:
      "부산 해운대 사무소이며 의뢰인 거주지에 지점이 있다는 뜻이 아닙니다. 업무 유형에 따라 관할·비대면 범위를 구분해 안내합니다.",
    localIntro:
      "관할 지역 법무사만 선임해야 하는지, 서울 사건을 부산 법무사에게 맡길 수 있는지부터 확인합니다. 원본 전달·본인확인·진행 공유·추가 비용 여부를 수임 전에 설명합니다.",
    scenarioIds: ["heir-scattered", "busan-remote", "overseas-heir"],
    propertyTypeIds: ["apt", "land"],
    uniqueFaqIds: ["choose-lawyer", "branch-myth", "cost-split", "visit-need"],
    relatedRegionSlugs: ["전국비대면법무사", "전국상속등기법무사"],
    relatedServiceSlugs: ["전국업무사례"],
    ctaTitle: "타지역 의뢰 가능 여부 확인하기",
    ctaDescription: "업무 종류와 소재 지역만 남겨주셔도 확인 포인트를 안내합니다.",
    published: true,
  },
  {
    slug: "지역별상속등기법무사",
    regionName: "전국",
    regionType: "권역허브",
    priority: 1,
    kind: "region-hub",
    noticeType: "jurisdiction-exception",
    primaryKeyword: "지역별 상속등기 법무사",
    secondaryKeywords: [
      "서울 상속등기 법무사",
      "경기 상속등기 법무사",
      "제주 상속등기 법무사",
    ],
    seoTitle: "지역별 상속등기 법무사｜서울·경기·인천·제주 전국 안내",
    metaDescription:
      "지역별 상속등기 법무사 허브. 서울·경기·인천·충청·영호남·강원·제주 권역 카드를 검색·필터로 찾습니다. 부산은 기존 부산 상속등기 페이지로 연결합니다.",
    h1: "지역이 달라도 맡길 수 있는 전국 상속등기",
    disclosure:
      "다옴법무사사무소는 부산 해운대구에 있으며 각 지역 지점이 없습니다. 지역 키워드는 검색·안내용이며 해당 지역 사무소를 의미하지 않습니다.",
    localIntro:
      "권역별 카드에서 서울·경기·인천 등 광역 안내로 이동할 수 있습니다. 부산 지역은 신규 페이지 대신 기존 부산 상속등기 안내로 연결합니다.",
    scenarioIds: ["heir-scattered", "multi-gu", "busan-remote"],
    propertyTypeIds: ["apt", "land"],
    uniqueFaqIds: ["branch-myth", "seoul-search", "jurisdiction-special"],
    relatedRegionSlugs: [
      "서울상속등기법무사",
      "경기상속등기법무사",
      "인천상속등기법무사",
      "제주상속등기법무사",
    ],
    relatedServiceSlugs: ["전국상속등기법무사", "전국상속부동산일괄등기"],
    ctaTitle: "지역별 상속등기 가능 여부 확인하기",
    ctaDescription: "부동산 소재 시·도를 알려주시면 맞는 안내 페이지와 서류를 연결합니다.",
    published: true,
  },
];
