import type { DistrictMeta } from "./types";

/** 부산 16개 구·군 + 법정동·주요 행정동 */
export const DISTRICT_METAS: DistrictMeta[] = [
  {
    key: "jung",
    name: "중구",
    slug: "중구법무사",
    traits: ["oldtown", "commercial", "market", "station"],
    context:
      "남포·광복·국제시장 등 원도심 상권이 모여 있고, 상가·주택 권리관계와 상속·매매 등기 문의가 함께 이어지는 지역입니다.",
    dongs: [
      "영주동",
      "대청동",
      "동광동",
      "보수동",
      "신창동",
      "창선동",
      "대창동",
      "남포동",
      "광복동",
      "부평동",
      "중앙동",
    ],
  },
  {
    key: "seo",
    name: "서구",
    slug: "서구법무사",
    traits: ["residential", "oldtown", "tourism", "university"],
    context:
      "대신·암남·송도 일대는 주거와 병원·해수욕장 생활권이 겹쳐, 상속·부동산 이전과 병원 인근 거주자 상담이 많은 편입니다.",
    dongs: [
      "남부민동",
      "부민동",
      "부용동",
      "아미동",
      "초장동",
      "충무동",
      "토성동",
      "서대신동",
      "동대신동",
      "암남동",
    ],
  },
  {
    key: "dong",
    name: "동구",
    slug: "동구법무사",
    traits: ["port", "station", "commercial", "oldtown"],
    context:
      "부산역·초량·범일 일대는 역세권과 항만 배후 상가가 이어져, 상가 매매·임대차·법인 본점 이전 문의가 자주 있습니다.",
    dongs: ["초량동", "수정동", "좌천동", "범일동"],
  },
  {
    key: "yeongdo",
    name: "영도구",
    slug: "영도구법무사",
    traits: ["port", "tourism", "residential", "industrial"],
    context:
      "영도대교·태종대·흰여울 등 관광·주거가 공존하고, 항만·혁신지구 관련 부동산·법인등기 상담이 이뤄지는 지역입니다.",
    dongs: [
      "남항동",
      "대교동",
      "대평동",
      "동삼동",
      "봉래동",
      "신선동",
      "영선동",
      "청학동",
    ],
  },
  {
    key: "busanjin",
    name: "부산진구",
    slug: "부산진구법무사",
    traits: ["commercial", "station", "residential", "market"],
    context:
      "서면·전포·부전 상권과 주거 단지가 맞닿아 잔금일 등기, 상가 이전, 법인 임원변경 문의가 꾸준한 생활권입니다.",
    dongs: [
      "가야동",
      "개금동",
      "당감동",
      "범전동",
      "범천동",
      "부암동",
      "부전동",
      "양정동",
      "연지동",
      "전포동",
      "초읍동",
    ],
  },
  {
    key: "dongnae",
    name: "동래구",
    slug: "동래구법무사",
    traits: ["residential", "station", "market", "oldtown"],
    context:
      "온천장·사직·안락 등 전통 주거·상권이 이어져 상속등기, 공동주택 이전, 가족 간 권리 정리 상담이 많은 지역입니다.",
    dongs: [
      "낙민동",
      "명장동",
      "명륜동",
      "복천동",
      "수안동",
      "사직동",
      "안락동",
      "온천동",
      "칠산동",
    ],
  },
  {
    key: "nam",
    name: "남구",
    slug: "남구법무사",
    traits: ["finance", "university", "residential", "coastal"],
    context:
      "문현금융단지·대학가·용호 주거지가 함께 있어 법인등기, 오피스·주택 매매등기, 상속 관련 문의가 고루 들어오는 편입니다.",
    dongs: ["감만동", "대연동", "용호동", "용당동", "문현동", "우암동"],
  },
  {
    key: "buk",
    name: "북구",
    slug: "북구법무사",
    traits: ["residential", "newtown", "station", "university"],
    context:
      "화명·덕천·만덕 등 주거 밀집 지역으로, 아파트 소유권이전·상속·근저당 설정·말소 등기 상담이 잦은 생활권입니다.",
    dongs: ["구포동", "금곡동", "덕천동", "만덕동", "화명동"],
  },
  {
    key: "haeundae",
    name: "해운대구",
    slug: "해운대구법무사",
    traits: ["coastal", "commercial", "finance", "tourism", "residential"],
    context:
      "해운대·센텀·재송·반여 일대는 주거·업무·관광이 겹쳐 부동산등기, 법인등기, 상속·잔금일 협업 문의가 많은 대표 생활권입니다.",
    dongs: [
      "우동",
      "중동",
      "좌동",
      "송정동",
      "반여동",
      "반송동",
      "재송동",
      "석대동",
    ],
    adminDongs: [
      "반여1동",
      "반여2동",
      "반여3동",
      "반여4동",
      "재송1동",
      "재송2동",
      "반송1동",
      "반송2동",
      "좌1동",
      "좌2동",
      "좌3동",
      "좌4동",
      "우1동",
      "우2동",
      "우3동",
      "중1동",
      "중2동",
    ],
  },
  {
    key: "saha",
    name: "사하구",
    slug: "사하구법무사",
    traits: ["coastal", "residential", "industrial", "tourism"],
    context:
      "하단·다대·장림·감천 일대는 주거와 산업·관광지가 인접해 주택 이전, 공장·상가 등기, 상속 상담이 함께 이뤄집니다.",
    dongs: [
      "감천동",
      "구평동",
      "괴정동",
      "하단동",
      "당리동",
      "다대동",
      "장림동",
      "신평동",
    ],
  },
  {
    key: "geumjeong",
    name: "금정구",
    slug: "금정구법무사",
    traits: ["university", "residential", "station", "industrial"],
    context:
      "부산대·장전·구서·노포 생활권으로 대학가 임대·주거 매매, 상속등기, 인근 공업지역 관련 법인·부동산 문의가 있습니다.",
    dongs: [
      "금사동",
      "금성동",
      "구서동",
      "남산동",
      "노포동",
      "두구동",
      "부곡동",
      "서동",
      "선동",
      "오륜동",
      "장전동",
      "청룡동",
      "회동동",
    ],
  },
  {
    key: "gangseo",
    name: "강서구",
    slug: "강서구법무사",
    traits: ["newtown", "industrial", "port", "residential"],
    context:
      "명지·에코델타·녹산·신항 일대는 신도시와 산업·물류가 맞물려 신축 보존등기, 공장·창고 이전, 법인 설립·변경 문의가 많습니다.",
    dongs: [
      "강동동",
      "구랑동",
      "눌차동",
      "대저동",
      "대항동",
      "동선동",
      "명지동",
      "미음동",
      "범방동",
      "봉림동",
      "생곡동",
      "성북동",
      "식만동",
      "신호동",
      "죽동동",
      "죽림동",
      "지사동",
      "천성동",
      "화전동",
      "녹산동",
      "가락동",
    ],
  },
  {
    key: "yeonje",
    name: "연제구",
    slug: "연제구법무사",
    traits: ["court", "registry", "station", "residential", "commercial"],
    context:
      "거제·연산 일대는 시청·법원·등기 관련 기관과 가까워 소송·회생·등기 일정과 맞춘 법무사 업무 문의가 많은 지역입니다.",
    dongs: ["거제동", "연산동"],
    adminDongs: [
      "거제1동",
      "거제2동",
      "거제3동",
      "거제4동",
      "연산1동",
      "연산2동",
      "연산3동",
      "연산4동",
      "연산5동",
      "연산6동",
      "연산8동",
      "연산9동",
    ],
  },
  {
    key: "suyeong",
    name: "수영구",
    slug: "수영구법무사",
    traits: ["coastal", "residential", "commercial", "tourism", "station"],
    context:
      "광안리·남천·망미 일대는 해안 주거와 상권이 밀집해 아파트·오피스텔 이전등기, 상가 권리, 상속 상담이 이어집니다.",
    dongs: ["광안동", "남천동", "망미동", "민락동", "수영동"],
    adminDongs: [
      "광안1동",
      "광안2동",
      "광안3동",
      "광안4동",
      "남천1동",
      "남천2동",
      "망미1동",
      "망미2동",
    ],
  },
  {
    key: "sasang",
    name: "사상구",
    slug: "사상구법무사",
    traits: ["industrial", "station", "residential", "commercial"],
    context:
      "사상터미널·주례·학장 일대는 교통 거점과 공업·주거가 공존해 공장·상가 등기, 법인 변경, 주택 이전 문의가 함께 있습니다.",
    dongs: [
      "감전동",
      "괘법동",
      "덕포동",
      "모라동",
      "삼락동",
      "엄궁동",
      "주례동",
      "학장동",
    ],
  },
  {
    key: "gijang",
    name: "기장군",
    slug: "기장군법무사",
    traits: ["newtown", "tourism", "industrial", "coastal", "residential"],
    context:
      "정관·일광·오시리아 등 신도시·관광·산업단지가 있어 신축·분양 관련 등기, 상속, 입주 기업 법인등기 상담이 이뤄집니다.",
    dongs: ["기장읍", "정관읍", "장안읍", "일광읍", "철마면"],
  },
];
