/**
 * 지금 독립 색인 페이지로 만들지 않는 B2B 후보.
 * 문의·검색 데이터가 쌓이면 독립 페이지 기준(§3)을 재검토한다.
 */
export type B2BBacklogItem = {
  candidateSlug: string;
  label: string;
  intent: string;
  overlapRisk: string;
  independentWhen: string;
  collectWhenInquiries: string;
};

export const b2bPageBacklog: B2BBacklogItem[] = [
  {
    candidateSlug: "부산긴급등기접수",
    label: "부산 긴급 등기 접수",
    intent: "마감 임박 접수·보정·잔금일 긴급 조율",
    overlapRisk: "/부산등기접수협업·/협업문의?type=urgent와 중복",
    independentWhen: "긴급 전용 체크리스트·연락 프로토콜이 접수 페이지와 실질적으로 달라질 때",
    collectWhenInquiries: "기한, 서류 준비도, 관할, 당일 여부",
  },
  {
    candidateSlug: "부산등기서류전달업무",
    label: "부산 등기 서류 전달 업무",
    intent: "원본 수령·전달·반환만 필요한 현지 지원",
    overlapRisk: "/부산원거리등기협업·/부산등기소현지업무와 중복",
    independentWhen: "전달만의 보안·추적·수령 절차가 2,000자 이상 고유해질 때",
    collectWhenInquiries: "전달 방식, 원본 종류, 반환지, 일정",
  },
  {
    candidateSlug: "부산법무법인등기협업",
    label: "부산 법무법인 등기 협업",
    intent: "법무법인 전용 복대리·현지 협업",
    overlapRisk: "/부산법무사복대리와 검색의도 중복",
    independentWhen: "법무법인 전용 역할·컴플라이언스 안내가 복대리와 차별화될 때",
    collectWhenInquiries: "법인 규모, 반복 여부, 업무 유형",
  },
  {
    candidateSlug: "부산분양대행사등기협업",
    label: "부산 분양대행사 등기 협업",
    intent: "분양대행 창구 중심 수분양자 이전 조율",
    overlapRisk: "/부산분양등기·/부산시행사등기와 중복",
    independentWhen: "대행 전용 고객 안내·목록 운영이 분양등기와 분리될 때",
    collectWhenInquiries: "호실 수, 잔금 캘린더, 시행·대행 창구",
  },
  {
    candidateSlug: "부산창고보존등기",
    label: "부산 창고 보존등기",
    intent: "창고·물류시설 신축 보존",
    overlapRisk: "/부산신축건물보존등기 유형별 안내와 중복",
    independentWhen: "창고 전용 대장·표시·용도 체크가 허브보다 나은 답을 줄 때",
    collectWhenInquiries: "용도, 승인 상태, 필지·동 수",
  },
  {
    candidateSlug: "부산다가구주택보존등기",
    label: "부산 다가구주택 보존등기",
    intent: "다가구·다세대 신축 보존",
    overlapRisk: "보존등기 허브·집합/일반 구분 안내와 중복",
    independentWhen: "다가구 전용 표시·호실 구조 안내가 충분할 때",
    collectWhenInquiries: "호실 수, 대장 상태, 건축주 관계",
  },
  {
    candidateSlug: "부산공동주택보존등기",
    label: "부산 공동주택 보존등기",
    intent: "아파트 등 공동주택 보존",
    overlapRisk: "/부산신축건물보존등기·집단등기와 중복",
    independentWhen: "공동주택 전용 목록·입주 연동 안내가 독립할 때",
    collectWhenInquiries: "동·호 수, 입주 일정, 분양 연결",
  },
  {
    candidateSlug: "부산집합건물보존등기",
    label: "부산 집합건물 보존등기",
    intent: "집합건물 전용 보존·구분소유",
    overlapRisk: "보존등기 허브·분양등기와 중복",
    independentWhen: "전유·공용 표시 안내가 허브와 명확히 달라질 때",
    collectWhenInquiries: "전유 수, 규약, 표시 확정 여부",
  },
  {
    candidateSlug: "부산프랜차이즈법인등기",
    label: "부산 프랜차이즈 법인등기",
    intent: "가맹·본사 다수 법인 변경등기",
    overlapRisk: "/부산법인등기아웃소싱과 중복",
    independentWhen: "프랜차이즈 전용 다법인 운영 안내가 아웃소싱과 분리될 때",
    collectWhenInquiries: "법인 수, 변경 유형, 주기",
  },
  {
    candidateSlug: "부산스타트업법인등기",
    label: "부산 스타트업 법인등기",
    intent: "설립·투자 후 임원·주식 관련 등기",
    overlapRisk: "/부산법인설립등기·아웃소싱과 중복",
    independentWhen: "투자·스톡옵션 연계 안내가 고유해질 때",
    collectWhenInquiries: "단계(설립·증자·임원), 일정, 투자 여부",
  },
  {
    candidateSlug: "부산세무사법무사협업",
    label: "부산 세무사·법무사 협업",
    intent: "세무·등기 역할 분담 협업",
    overlapRisk: "/협업문의?partner=tax-accounting과 중복",
    independentWhen: "세무 연계 전용 체크리스트가 문의 폼만으로 부족할 때",
    collectWhenInquiries: "세무 유형, 등기 유형, 일정",
  },
  {
    candidateSlug: "부산회계법인등기협업",
    label: "부산 회계법인 등기 협업",
    intent: "회계법인 고객사 등기 연계",
    overlapRisk: "세무·기업 아웃소싱 안내와 중복",
    independentWhen: "회계법인 전용 창구·컴플라이언스 안내가 필요할 때",
    collectWhenInquiries: "고객사 수, 업무 유형, 주기",
  },
  {
    candidateSlug: "부산협동조합등기",
    label: "부산 협동조합 등기",
    intent: "협동조합 설립·변경·부동산",
    overlapRisk: "비영리·법인 허브와 중복",
    independentWhen: "협동조합 전용 의결·정관 안내가 충분할 때",
    collectWhenInquiries: "조합 형태, 변경 유형, 의결 자료",
  },
  {
    candidateSlug: "부산금융기관담보등기",
    label: "부산 금융기관 담보등기",
    intent: "금융 담보·설정·말소 협업",
    overlapRisk: "근저당·잔금 협업·금융 파트너 카드와 중복",
    independentWhen: "금융기관 전용 일정·서류 프로토콜이 독립할 때",
    collectWhenInquiries: "설정·말소 건수, 실행일, 기관 수",
  },
  {
    candidateSlug: "부산경매낙찰등기",
    label: "부산 경매 낙찰등기",
    intent: "경매·공매 낙찰 후 이전",
    overlapRisk: "기존 /부산경매낙찰등기 등 검색의도 페이지와 중복 가능",
    independentWhen: "B2B(자산관리·NPL) 전용 협업 안내가 개인용과 달라질 때",
    collectWhenInquiries: "낙찰일, 잔금, 말소·인수 권리",
  },
  {
    candidateSlug: "부산정비사업등기",
    label: "부산 정비사업 등기",
    intent: "재개발·재건축·도시정비 프로젝트",
    overlapRisk: "/부산재개발등기·/부산재건축등기와 중복",
    independentWhen: "프로젝트 담당자용 일정·역할이 기존과 차별화될 때",
    collectWhenInquiries: "사업단계, 세대·필지 수, 조합·시행 구조",
  },
  {
    candidateSlug: "부산조합등기업무",
    label: "부산 조합 등기업무",
    intent: "조합 법인·부동산 등기",
    overlapRisk: "정비사업·비영리 안내와 중복",
    independentWhen: "조합 전용 의결·등기 안내가 충분할 때",
    collectWhenInquiries: "조합 유형, 의결 상태, 부동산 병행",
  },
  {
    candidateSlug: "부산특수부동산등기",
    label: "부산 특수 부동산등기",
    intent: "정형화하기 어려운 특수 권리·표시",
    overlapRisk: "/특수등기의뢰와 중복",
    independentWhen: "특수 유형별 고유 실무가 허브보다 깊어질 때",
    collectWhenInquiries: "특수 유형, 권리구조, 자료 상태",
  },
  {
    candidateSlug: "부산공인중개사등기협업",
    label: "부산 공인중개사 등기 협업",
    intent: "중개사무소 전용 등기 협업",
    overlapRisk: "/부산부동산협력법무사와 검색의도 중복(주력 유지)",
    independentWhen: "중개사-only 톤·체크가 협력 법무사 페이지와 실질 분리될 때",
    collectWhenInquiries: "잔금일, 거래 유형, 반복 협업 여부",
  },
  {
    candidateSlug: "부산대량등기",
    label: "부산 대량등기",
    intent: "대량·다건 일괄 등기",
    overlapRisk: "/부산집단등기와 중복(주력 유지)",
    independentWhen: "대량만의 운영·견적 안내가 집단등기와 달라질 때",
    collectWhenInquiries: "건수 구간, 목록 상태, 일정",
  },
  {
    candidateSlug: "부산공기업등기업무",
    label: "부산 공기업 등기업무",
    intent: "공기업·공공 자회사 등기",
    overlapRisk: "/공공기관등기업무와 중복",
    independentWhen: "공기업 전용 공문·입찰·의결 안내가 충분할 때",
    collectWhenInquiries: "기관 유형, 공문·입찰 여부, 업무 유형",
  },
  {
    candidateSlug: "부산학교법인등기",
    label: "부산 학교법인 등기",
    intent: "학교법인·교육기관 등기",
    overlapRisk: "/공공기관등기업무와 중복",
    independentWhen: "학교법인 전용 의결·정관·부동산 안내가 충분할 때",
    collectWhenInquiries: "법인 유형, 의결 상태, 부동산·법인 병행",
  },
  {
    candidateSlug: "부산비영리법인등기",
    label: "부산 비영리법인 등기",
    intent: "비영리·사단·재단 등기",
    overlapRisk: "공공·법인 허브와 중복",
    independentWhen: "비영리 전용 서류·절차가 허브보다 나은 답을 줄 때",
    collectWhenInquiries: "법인 형태, 변경 유형, 내부 의결 자료",
  },
  {
    candidateSlug: "부산신탁등기",
    label: "부산 신탁등기",
    intent: "신탁·담보·이전 관련",
    overlapRisk:
      "확인되지 않은 전문성 단정 위험 + 기존 /부산신탁등기 라이브 페이지 유지(독립 강화 시 재검토)",
    independentWhen: "실제 수행 범위가 확인되고 B2B 협업 안내가 개인용과 분리될 때",
    collectWhenInquiries: "신탁 유형, 권리구조, 담당 기관",
  },
  {
    candidateSlug: "부산건물멸실등기",
    label: "부산 건물 멸실등기",
    intent: "멸실등기",
    overlapRisk: "특수등기·보존등기 허브와 중복",
    independentWhen: "멸실 준비서류·위험이 허브와 명확히 다를 때",
    collectWhenInquiries: "멸실 사유, 대장 정리 상태, 후속 신축 여부",
  },
  {
    candidateSlug: "부산건물표시변경등기",
    label: "부산 건물 표시변경등기",
    intent: "표시변경·구조 변경 등기",
    overlapRisk: "멸실·특수등기 안내와 중복",
    independentWhen: "표시변경만의 체크리스트가 독립할 때",
    collectWhenInquiries: "변경 내용, 대장 상태, 후속 등기",
  },
  {
    candidateSlug: "부산촉탁등기",
    label: "부산 촉탁등기",
    intent: "법원·기관 촉탁 관련",
    overlapRisk: "/공공기관등기업무·특수등기와 중복",
    independentWhen: "촉탁 전용 절차·서류 안내가 충분할 때",
    collectWhenInquiries: "촉탁 유형, 기관, 일정",
  },
  {
    candidateSlug: "부산대량말소등기",
    label: "부산 대량 말소등기",
    intent: "다수 근저당·가등기 말소 일괄",
    overlapRisk: "/부산집단등기·근저당 말소 페이지와 중복",
    independentWhen: "말소만의 권리구조·금융 일정 안내가 2,000자 이상 고유해질 때",
    collectWhenInquiries: "말소 건수, 금융기관 수, 잔금·완제 일정",
  },
  {
    candidateSlug: "부산근저당설정말소협업",
    label: "부산 근저당 설정·말소 협업",
    intent: "B2B 담보 설정·말소 협업",
    overlapRisk: "기존 근저당 설정/말소·잔금 협업과 중복",
    independentWhen: "금융·중개·시행 협업 전용 안내가 개인용과 분리될 때",
    collectWhenInquiries: "설정·말소, 실행일, 동시 이전 여부",
  },
  {
    candidateSlug: "부산법인부동산거래등기",
    label: "부산 법인 부동산 거래등기",
    intent: "법인 매수·매도 부동산등기",
    overlapRisk: "/부산부동산등기·잔금 협업·기업 안내와 중복",
    independentWhen: "법인 거래 전용 결의·첨부 안내가 독립할 때",
    collectWhenInquiries: "매수·매도, 결의 상태, 담보 연동",
  },
  {
    candidateSlug: "부산재개발재건축프로젝트등기",
    label: "부산 재개발·재건축 프로젝트 등기",
    intent: "정비사업·조합 관련 대량 등기",
    overlapRisk: "기존 재개발·재건축 등기 페이지와 중복",
    independentWhen: "프로젝트 담당자용 일정·역할 안내가 기존과 차별화될 때",
    collectWhenInquiries: "사업단계, 세대·필지 수, 조합·시행 구조",
  },
  {
    candidateSlug: "부산산업단지등기업무",
    label: "부산 산업단지 등기업무",
    intent: "산업단지 기업 반복 등기",
    overlapRisk: "/부산기업법률자문·산업단지 관련 기존 페이지",
    independentWhen: "단지별 반복 업무 프로세스가 독립 페이지를 정당화할 때",
    collectWhenInquiries: "단지명(공개 가능 범위), 업무 유형, 주기",
  },
];
