import type { CoreHub, HubSpoke } from "./types";

function s(href: string, label: string): HubSpoke {
  return { href, label };
}

/** 핵심 허브 15개 — slug는 기존 URL 유지 */
export const CORE_HUBS: CoreHub[] = [
  {
    id: "busan-lawyer",
    slug: "부산법무사",
    title: "부산 법무사",
    theme: "region-lawyer",
    spokes: [
      s("/해운대법무사", "해운대·센텀 법무사 상담"),
      s("/센텀법무사", "센텀 법인·부동산 등기"),
      s("/부산여성법무사", "부산 여성 법무사 상담"),
      s("/부산상속등기", "부산 상속등기 절차"),
      s("/부산법인등기", "부산 법인등기 안내"),
      s("/부산부동산등기", "부산 부동산등기"),
      s("/부산등기법무사", "부산 등기 법무사"),
      s("/부산부동산등기법무사", "부산 부동산등기 법무사"),
      s("/부산상속법무사", "부산 상속 법무사"),
      s("/부산법인법무사", "부산 법인 법무사"),
      s("/부산소유권이전등기", "부산 소유권이전등기"),
      s("/부산근저당설정등기", "부산 근저당설정등기"),
      s("/부산근저당말소등기", "부산 근저당말소등기"),
      s("/부산전세권설정등기", "부산 전세권설정등기"),
      s("/부산전세권말소등기", "부산 전세권말소등기"),
      s("/부산임원변경등기", "부산 임원변경등기"),
      s("/부산신축건물보존등기", "신축건물 보존등기"),
      s("/공공기관등기업무", "공공기관 등기업무"),
      s("/부산역법무사", "부산역 법무사"),
      s("/서면법무사", "서면 법무사"),
      s("/광안리법무사", "광안리 법무사"),
      s("/동래역법무사", "동래역 법무사"),
      s("/연산동법무사", "연산동 법무사"),
      s("/남천동법무사", "남천동 법무사"),
      s("/대연동법무사", "대연동 법무사"),
      s("/덕천동법무사", "덕천동 법무사"),
      s("/명지법무사", "명지 법무사"),
      s("/정관법무사", "정관 법무사"),
      s("/사상법무사", "사상 법무사"),
      s("/하단법무사", "하단 법무사"),
      s("/부산개인회생", "부산 개인회생 신청"),
      s("/부산법무사비용", "부산 법무사 비용·수임료"),
      s("/부산법무사추천", "부산 법무사 추천 선택 기준"),
      s("/부산등기법무사추천", "부산 등기 법무사 선택 기준"),
      s("/부산법무사상담", "부산 법무사 상담 준비"),
      s("/부산법무사비교", "부산 법무사 비교 기준"),
      s("/부산상속등기전문", "부산 상속등기 상담 확인"),
      s("/부산부동산등기전문", "부산 부동산등기 상담 확인"),
      s("/부산법인등기전문", "부산 법인등기 상담 확인"),
      s("/상속등기비용", "상속등기 비용 견적"),
      s("/상속등기필요서류", "상속등기 필요서류"),
      s("/부산지방법원등기국", "부산지방법원 등기국 안내"),
      s("/부산재개발등기", "부산 재개발·재건축 등기"),
      s("/부산선박등기", "부산 선박등기"),
      s("/명례산업단지법인등기", "명례 산업단지 법인등기"),
      s("/services", "업무안내 전체"),
      s("/services/cases/haeundae-inheritance-registration-case", "해운대 상속등기 상담 사례"),
      s("/services/cases/busan-personal-rehabilitation-consultation", "부산 개인회생 상담 사례"),
      s("/faq/how-to-book-consultation-faq", "법무사 상담 예약 방법"),
      s("/faq/lawyer-fee-and-remote-faq", "법무사 수임료·비대면 상담"),
      s("/blog/busan-lawyer-consultation-documents", "부산 법무사 상담 준비 서류"),
      s("/contact", "부산 법무사 상담 문의"),
    ],
  },
  {
    id: "haeundae-lawyer",
    slug: "해운대법무사",
    title: "해운대 법무사",
    theme: "region-lawyer",
    spokes: [
      s("/센텀법무사", "센텀시티·재송 법무사"),
      s("/재송동법무사", "재송동 상속·매매 등기"),
      s("/반여동법무사", "반여동 아파트 상속등기"),
      s("/해운대구상속등기", "해운대구 상속등기"),
      s("/해운대구법인등기", "해운대구 법인등기"),
      s("/해운대구부동산등기", "해운대구 부동산등기"),
      s("/센텀법인등기", "센텀 법인 본점·임원 등기"),
      s("/해운대재개발상속등기", "해운대 재개발 지역 상속등기"),
      s("/부산상속등기", "부산 전역 상속등기"),
      s("/부산법무사", "부산 법무사 종합 안내"),
      s("/services/cases/haeundae-inheritance-registration-case", "해운대 아파트 상속등기 사례"),
      s("/faq/inheritance-registration-cost", "상속등기 비용 FAQ"),
      s("/location", "센텀 법무사 오시는 길"),
      s("/contact", "해운대 법무사 상담 신청"),
    ],
  },
  {
    id: "centum-lawyer",
    slug: "센텀법무사",
    title: "센텀 법무사",
    theme: "region-lawyer",
    spokes: [
      s("/재송동법무사", "재송동 법무사"),
      s("/센텀법인등기", "센텀 법인등기"),
      s("/센텀법인설립등기", "센텀 법인설립등기"),
      s("/센텀임원변경등기", "센텀 임원변경등기"),
      s("/부산국제금융센터법인등기", "BIFC 법인등기"),
      s("/해운대구상속등기", "센텀·재송 상속등기"),
      s("/부산법인등기", "부산 법인등기"),
      s("/부산법무사", "부산 법무사"),
      s("/services/cases/suyeong-company-establishment-case", "센텀 법인 설립 사례"),
      s("/services/cases/centum-ownership-transfer-case", "센텀 부동산 매매 등기 사례"),
      s("/법인설립등기비용", "법인설립등기 비용"),
      s("/임원변경등기과태료", "임원변경등기 과태료"),
      s("/location", "센텀시티역 인근 법무사"),
      s("/contact", "센텀 법무사 상담"),
    ],
  },
  {
    id: "female-lawyer",
    slug: "부산여성법무사",
    title: "부산 여성 법무사",
    theme: "female-lawyer",
    spokes: [
      s("/해운대여성법무사", "해운대 여성 법무사"),
      s("/센텀여성법무사", "센텀 여성 법무사"),
      s("/상속여성법무사", "상속·가사 여성 법무사"),
      s("/개인회생여성법무사", "개인회생 여성 법무사"),
      s("/부산상속등기", "부산 상속등기 편안한 상담"),
      s("/부산상속포기", "부산 상속포기 가정법원 신고"),
      s("/부산개인회생", "부산 개인회생 상담"),
      s("/부산법무사", "부산 법무사"),
      s("/faq/inheritance-renunciation-family-effect", "상속포기 가족 영향 FAQ"),
      s("/faq/personal-rehabilitation-eligibility-faq", "개인회생 자격 FAQ"),
      s("/services/cases/jaesong-inheritance-renunciation-consultation", "상속포기 상담 사례"),
      s("/about", "안윤정 법무사 소개"),
      s("/contact", "여성 법무사 상담 문의"),
    ],
  },
  {
    id: "inheritance-reg",
    slug: "부산상속등기",
    title: "부산 상속등기",
    theme: "inheritance",
    spokes: [
      s("/상속등기비용", "부산 상속등기 비용 안내"),
      s("/상속등기필요서류", "부산 상속등기 필요서류"),
      s("/상속등기기간", "부산 상속등기 기간·기한"),
      s("/부산상속포기", "부산 상속포기 절차"),
      s("/부산한정승인", "부산 한정승인 안내"),
      s("/부산가정법원상속", "부산가정법원 상속·가사"),
      s("/해운대구상속등기", "해운대구 상속등기"),
      s("/수영구상속등기", "수영구 상속등기"),
      s("/기장토지상속등기", "기장 토지 상속등기"),
      s("/연제구상속등기", "연제구 상속등기"),
      s("/상속", "상속 종합 허브"),
      s("/services/inheritance-registration", "상속등기 업무 상세"),
      s("/services/cases/haeundae-inheritance-registration-case", "해운대 상속등기 상담 사례"),
      s("/services/cases/gijang-land-inheritance-case", "기장 토지 상속 사례"),
      s("/faq/inheritance-registration-cost", "상속등기 비용 FAQ"),
      s("/faq/when-to-file-inheritance-registration", "상속등기 신청 시기 FAQ"),
      s("/faq/multiple-heirs-inheritance-registration", "공동상속인 등기 FAQ"),
      s("/blog/busan-inheritance-registration-procedure-documents", "부산 상속등기 절차·서류"),
      s("/contact", "부산 상속등기 상담"),
    ],
  },
  {
    id: "inheritance-renunciation",
    slug: "부산상속포기",
    title: "부산 상속포기",
    theme: "inheritance",
    spokes: [
      s("/상속포기비용", "상속포기 비용"),
      s("/상속포기필요서류", "상속포기 필요서류"),
      s("/부산한정승인", "부산 한정승인 비교"),
      s("/부산가정법원상속포기", "부산가정법원 상속포기"),
      s("/부산상속등기", "부산 상속등기"),
      s("/부산개인회생", "채무 과다 시 개인회생"),
      s("/services/inheritance-renunciation", "상속포기 업무 상세"),
      s("/services/cases/jaesong-inheritance-renunciation-consultation", "상속포기 상담 사례"),
      s("/faq/inheritance-renunciation-deadline", "상속포기 기한 FAQ"),
      s("/faq/what-is-inheritance-renunciation", "상속포기란 FAQ"),
      s("/blog/inheritance-renunciation-vs-qualified-acceptance", "상속포기 vs 한정승인"),
      s("/contact", "부산 상속포기 상담"),
    ],
  },
  {
    id: "qualified-acceptance",
    slug: "부산한정승인",
    title: "부산 한정승인",
    theme: "inheritance",
    spokes: [
      s("/한정승인비용", "한정승인 비용"),
      s("/한정승인기간", "한정승인 기한"),
      s("/부산상속포기", "부산 상속포기"),
      s("/부산상속등기", "부산 상속등기"),
      s("/부산가정법원상속", "부산가정법원 한정승인"),
      s("/services/qualified-acceptance", "한정승인 업무 상세"),
      s("/services/cases/dongnae-qualified-acceptance-consultation", "한정승인 상담 사례"),
      s("/faq/qualified-acceptance-procedure", "한정승인 절차 FAQ"),
      s("/faq/when-to-choose-qualified-acceptance", "한정승인 선택 시기 FAQ"),
      s("/blog/inheritance-renunciation-vs-qualified-acceptance", "상속포기·한정승인 비교"),
      s("/contact", "부산 한정승인 상담"),
    ],
  },
  {
    id: "corporate-reg",
    slug: "부산법인등기",
    title: "부산 법인등기",
    theme: "corporate",
    spokes: [
      s("/센텀법인등기", "센텀 법인등기"),
      s("/부산법인설립등기", "부산 법인설립등기"),
      s("/부산임원변경등기", "부산 임원변경등기"),
      s("/법인등기비용", "법인등기 비용"),
      s("/법인설립등기비용", "법인설립등기 비용"),
      s("/임원변경등기과태료", "임원변경등기 과태료"),
      s("/명례산업단지법인등기", "명례 산업단지 법인등기"),
      s("/문현금융단지법인등기", "문현금융단지 법인등기"),
      s("/법인등기", "법인등기 종합 허브"),
      s("/services/corporate-registration", "법인등기 업무 상세"),
      s("/services/cases/suyeong-company-establishment-case", "법인 설립 사례"),
      s("/faq/director-change-deadline-faq", "임원변경 기한 FAQ"),
      s("/blog/company-establishment-registration-checklist", "법인설립 등기 체크리스트"),
      s("/contact", "부산 법인등기 상담"),
    ],
  },
  {
    id: "real-estate-reg",
    slug: "부산부동산등기",
    title: "부산 부동산등기",
    theme: "real-estate",
    spokes: [
      s("/부산소유권이전등기", "부산 소유권이전등기"),
      s("/부산신축건물보존등기", "신축건물 보존등기"),
      s("/공공기관등기업무", "공공기관 등기업무"),
      s("/소유권이전등기서류", "소유권이전등기 필요서류"),
      s("/소유권이전등기비용", "소유권이전등기 비용"),
      s("/해운대구부동산등기", "해운대구 부동산등기"),
      s("/수영구부동산등기", "수영구 부동산등기"),
      s("/부산재개발등기", "부산 재개발 등기"),
      s("/부산재건축등기", "부산 재건축 등기"),
      s("/부동산등기", "부동산등기 종합 허브"),
      s("/services/real-estate-registration", "부동산등기 업무 상세"),
      s("/services/cases/centum-ownership-transfer-case", "센텀 매매 등기 사례"),
      s("/faq/ownership-transfer-documents", "소유권이전 서류 FAQ"),
      s("/blog/real-estate-ownership-transfer-procedure", "부동산 소유권이전 절차"),
      s("/contact", "부산 부동산등기 상담"),
    ],
  },
  {
    id: "rehab",
    slug: "부산개인회생",
    title: "부산 개인회생",
    theme: "rehab",
    spokes: [
      s("/개인회생비용", "개인회생 비용"),
      s("/개인회생필요서류", "개인회생 필요서류"),
      s("/개인회생기간", "개인회생 기간"),
      s("/부산파산", "부산 개인파산"),
      s("/부산회생법원법무사", "부산회생법원 법무사"),
      s("/부산회생법원개인회생", "부산회생법원 개인회생"),
      s("/개인회생파산", "개인회생·파산 허브"),
      s("/services/personal-rehabilitation", "개인회생 업무 상세"),
      s("/services/cases/busan-personal-rehabilitation-consultation", "개인회생 상담 사례"),
      s("/faq/personal-rehabilitation-eligibility-faq", "개인회생 자격 FAQ"),
      s("/faq/personal-rehabilitation-duration-faq", "개인회생 기간 FAQ"),
      s("/blog/personal-rehabilitation-before-application", "개인회생 신청 전 준비"),
      s("/contact", "부산 개인회생 상담"),
    ],
  },
  {
    id: "lawyer-fee",
    slug: "부산법무사비용",
    title: "부산 법무사 비용",
    theme: "cost",
    spokes: [
      s("/부산법무사보수표", "부산 법무사 보수표"),
      s("/상속등기비용", "상속등기 비용"),
      s("/법인설립등기비용", "법인설립등기 비용"),
      s("/개인회생비용", "개인회생 비용"),
      s("/상속포기비용", "상속포기 비용"),
      s("/한정승인비용", "한정승인 비용"),
      s("/부산상속등기", "부산 상속등기"),
      s("/부산법인등기", "부산 법인등기"),
      s("/부산개인회생", "부산 개인회생"),
      s("/faq/lawyer-fee-and-remote-faq", "법무사 수임료 FAQ"),
      s("/faq/inheritance-registration-cost", "상속등기 비용 FAQ"),
      s("/contact", "비용 상담·견적 문의"),
    ],
  },
  {
    id: "court-registry",
    slug: "부산지방법원등기국",
    title: "부산 법원·등기소 법무사",
    theme: "court",
    spokes: [
      s("/부산지방법원법무사", "부산지방법원 법무사"),
      s("/부산지방법원동부지원법무사", "동부지원 법무사"),
      s("/부산지방법원동부지원등기과", "동부지원 등기과"),
      s("/남부산등기소법무사", "남부산등기소 법무사"),
      s("/북부산등기소법무사", "북부산등기소 법무사"),
      s("/중부산등기소법무사", "중부산등기소 법무사"),
      s("/부산진등기소법무사", "부산진등기소 법무사"),
      s("/부산회생법원법무사", "부산회생법원 법무사"),
      s("/부산가정법원상속", "부산가정법원 상속"),
      s("/등기소근처법무사", "등기소 근처 법무사"),
      s("/부산법원근처법무사", "부산 법원 근처 법무사"),
      s("/부산상속등기", "부산 상속등기"),
      s("/부산부동산등기", "부산 부동산등기"),
      s("/contact", "법원·등기소 업무 상담"),
    ],
  },
  {
    id: "industrial",
    slug: "명례산업단지법인등기",
    title: "부산 산업단지 법인등기",
    theme: "industrial",
    spokes: [
      s("/녹산산업단지법인등기", "녹산 산업단지 법인등기"),
      s("/문현금융단지법인등기", "문현금융단지 법인등기"),
      s("/정관법인등기", "정관 법인등기"),
      s("/명지국제신도시법인등기", "명지국제신도시 법인등기"),
      s("/에코델타시티법인등기", "에코델타시티 법인등기"),
      s("/센텀법인등기", "센텀 법인등기"),
      s("/법인설립등기비용", "법인설립등기 비용"),
      s("/임원변경등기과태료", "임원변경등기 과태료"),
      s("/산업단지법인등기", "산업단지 법인등기"),
      s("/물류회사법인등기", "물류회사 법인등기"),
      s("/부산법인등기", "부산 법인등기"),
      s("/services/corporate-registration", "법인등기 업무 상세"),
      s("/contact", "산업단지 법인등기 상담"),
    ],
  },
  {
    id: "redevelopment",
    slug: "부산재개발등기",
    title: "부산 재개발·재건축 등기",
    theme: "real-estate",
    spokes: [
      s("/부산재건축등기", "부산 재건축등기"),
      s("/해운대재개발상속등기", "해운대 재개발 상속등기"),
      s("/부산신축아파트소유권이전등기", "신축 아파트 소유권이전등기"),
      s("/부산토지상속등기", "부산 토지 상속등기"),
      s("/부산상속등기", "부산 상속등기"),
      s("/부산부동산등기", "부산 부동산등기"),
      s("/services/real-estate-registration", "부동산등기 업무"),
      s("/services/cases/gijang-land-inheritance-case", "토지 상속 사례"),
      s("/blog/delaying-inheritance-registration-risks", "상속등기 지연 위험"),
      s("/contact", "재개발·재건축 등기 상담"),
    ],
  },
  {
    id: "ship",
    slug: "부산선박등기",
    title: "부산 선박등기",
    theme: "maritime",
    spokes: [
      s("/해운회사법인등기", "해운회사 법인등기"),
      s("/물류회사법인등기", "물류회사 법인등기"),
      s("/영도구선박등기", "영도구 선박등기"),
      s("/부산법인등기", "부산 법인등기"),
      s("/명례산업단지법인등기", "항만·물류 산업단지 법인등기"),
      s("/services/corporate-registration", "법인등기 업무"),
      s("/contact", "선박·해운 등기 상담"),
    ],
  },
];

export const CORE_HUB_SLUGS = new Set(CORE_HUBS.map((h) => h.slug));

export function getCoreHubBySlug(slug: string): CoreHub | undefined {
  return CORE_HUBS.find((h) => h.slug === slug);
}
