import type { LocalLandingConfig } from "@/types/local-landing";

/** SEO 핵심 키워드 전용 랜딩 (기존 URL과 별도 slug) */
export const keywordLandingConfigs: LocalLandingConfig[] = [
  {
    slug: "부산등기법무사",
    pageType: "keyword-hub",
    keywordKey: "부산등기법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "센텀", "수영구", "연제구"],
    relatedCaseSlug: "centum-ownership-transfer-case",
  },
  {
    slug: "부산부동산등기법무사",
    pageType: "keyword-hub",
    keywordKey: "부산부동산등기법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "수영구", "광안동"],
    relatedCaseSlug: "centum-ownership-transfer-case",
  },
  {
    slug: "부산상속법무사",
    pageType: "keyword-hub",
    keywordKey: "부산상속법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "연제구", "동래구"],
    relatedCaseSlug: "haeundae-inheritance-registration-case",
  },
  {
    slug: "부산법인법무사",
    pageType: "keyword-hub",
    keywordKey: "부산법인법무사",
    serviceSlug: "corporate-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["센텀", "해운대구", "연제구"],
    relatedCaseSlug: "suyeong-company-establishment-case",
  },
  {
    slug: "부산근저당설정등기",
    pageType: "keyword-hub",
    keywordKey: "부산근저당설정등기",
    serviceSlug: "real-estate-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "수영구", "북구"],
  },
  {
    slug: "부산근저당말소등기",
    pageType: "keyword-hub",
    keywordKey: "부산근저당말소등기",
    serviceSlug: "real-estate-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "연제구", "사상구"],
    relatedCaseSlug: "centum-ownership-transfer-case",
  },
  {
    slug: "부산전세권설정등기",
    pageType: "keyword-hub",
    keywordKey: "부산전세권설정등기",
    serviceSlug: "real-estate-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["수영구", "광안동", "해운대구"],
  },
  {
    slug: "부산전세권말소등기",
    pageType: "keyword-hub",
    keywordKey: "부산전세권말소등기",
    serviceSlug: "real-estate-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["수영구", "연제구", "동래구"],
  },
];
