import type { LocalLandingConfig } from "@/types/local-landing";

/** 동네·역세권 법무사 SEO 페이지 (기존 SEO 자동생성 페이지 대체) */
export const neighborhoodHubConfigs: LocalLandingConfig[] = [
  {
    slug: "부산역법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "부산역법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "donggu",
    regionLabel: "부산역",
    neighborhoods: ["부산역", "초량동", "범일동"],
    caseAngle: "부산역 인근 상가 매매 등기",
  },
  {
    slug: "서면법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "서면법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "busanjin",
    regionLabel: "서면",
    neighborhoods: ["서면", "부전동", "전포동"],
    caseAngle: "서면 상가·오피스 매매 등기",
    relatedCaseSlug: "centum-ownership-transfer-case",
  },
  {
    slug: "광안리법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "광안리법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "gwanganri",
    regionLabel: "광안리",
    neighborhoods: ["광안동", "광안리", "민락동"],
    caseAngle: "광안리 아파트 전세권·매매 등기",
  },
  {
    slug: "동래역법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "동래역법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "dongnae",
    regionLabel: "동래역",
    neighborhoods: ["낙민동", "온천동", "명륜동"],
    caseAngle: "동래역 인근 재건축 아파트 상속등기",
  },
  {
    slug: "연산동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "연산동법무사",
    serviceSlug: "corporate-registration",
    regionKey: "yeonje",
    regionLabel: "연산동",
    neighborhoods: ["연산동", "거제동"],
    caseAngle: "연산동 법인 본점·임원변경 등기",
  },
  {
    slug: "남천동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "남천동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "suyeong",
    regionLabel: "남천동",
    neighborhoods: ["남천동", "광안동", "민락동"],
    caseAngle: "남천동 아파트 전세·매매 등기",
  },
  {
    slug: "대연동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "대연동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "namgu",
    regionLabel: "대연동",
    neighborhoods: ["대연동", "용호동"],
    caseAngle: "대연동 아파트 상속·매매 등기",
  },
  {
    slug: "덕천동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "덕천동법무사",
    serviceSlug: "personal-rehabilitation",
    regionKey: "buk",
    regionLabel: "덕천동",
    neighborhoods: ["덕천동", "구포동"],
    caseAngle: "덕천동 거주 직장인 개인회생",
    relatedCaseSlug: "busan-personal-rehabilitation-consultation",
  },
  {
    slug: "명지법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "명지법무사",
    serviceSlug: "company-establishment",
    regionKey: "myeongji",
    regionLabel: "명지",
    neighborhoods: ["명지", "명지국제신도시", "가락동"],
    caseAngle: "명지 신도시 법인 설립·신축 등기",
    relatedCaseSlug: "suyeong-company-establishment-case",
  },
  {
    slug: "정관법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "정관법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "jeonggwan",
    regionLabel: "정관",
    neighborhoods: ["정관읍", "정관신도시"],
    caseAngle: "정관 토지·주택 상속등기",
    relatedCaseSlug: "gijang-land-inheritance-case",
  },
  {
    slug: "사상법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "사상법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "sasang",
    regionLabel: "사상",
    neighborhoods: ["괘법동", "엄궁동", "감전동"],
    caseAngle: "사상구 공장·상가 근저당·등기",
  },
  {
    slug: "하단법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "하단법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "saha",
    regionLabel: "하단",
    neighborhoods: ["하단동", "괴정동", "당리동"],
    caseAngle: "하단동 아파트 상속등기",
  },
];
