import type { LocalLandingConfig } from "@/types/local-landing";

/** 동네·역세권 법무사 SEO 페이지 (기존 SEO 자동생성 페이지 대체) */
export const neighborhoodHubConfigs: LocalLandingConfig[] = [
  {
    slug: "부산역법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "부산역법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "donggu",
    regionLabel: "부산역",
    neighborhoods: ["부산역", "초량동", "범일동"],
    caseAngle: "부산역 인근 상가 매매 등기",
  },
  {
    slug: "서면법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "서면법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "busanjin",
    regionLabel: "서면",
    neighborhoods: ["서면", "부전동", "전포동"],
    caseAngle: "서면 상가·오피스 매매 등기",
    relatedCaseSlug: "centum-ownership-transfer-case",
  },
  {
    slug: "광안리법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "광안리법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "gwanganri",
    regionLabel: "광안리",
    neighborhoods: ["광안동", "광안리", "민락동"],
    caseAngle: "광안리 아파트 전세권·매매 등기",
  },
  {
    slug: "동래역법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "동래역법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "dongnae",
    regionLabel: "동래역",
    neighborhoods: ["낙민동", "온천동", "명륜동"],
    caseAngle: "동래역 인근 재건축 아파트 상속등기",
  },
  {
    slug: "연산동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "연산동법무사",
    serviceSlug: "corporate-registration",
    regionKey: "yeonje",
    regionLabel: "연산동",
    neighborhoods: ["연산동", "거제동"],
    caseAngle: "연산동 법인 본점·임원변경 등기",
  },
  {
    slug: "남천동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "남천동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "suyeong",
    regionLabel: "남천동",
    neighborhoods: ["남천동", "광안동", "민락동"],
    caseAngle: "남천동 아파트 전세·매매 등기",
  },
  {
    slug: "대연동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "대연동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "namgu",
    regionLabel: "대연동",
    neighborhoods: ["대연동", "용호동"],
    caseAngle: "대연동 아파트 상속·매매 등기",
  },
  {
    slug: "덕천동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "덕천동법무사",
    serviceSlug: "personal-rehabilitation",
    regionKey: "buk",
    regionLabel: "덕천동",
    neighborhoods: ["덕천동", "구포동"],
    caseAngle: "덕천동 거주 직장인 개인회생",
    relatedCaseSlug: "busan-personal-rehabilitation-consultation",
  },
  {
    slug: "명지법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "명지법무사",
    serviceSlug: "company-establishment",
    regionKey: "myeongji",
    regionLabel: "명지",
    neighborhoods: ["명지", "명지국제신도시", "가락동"],
    caseAngle: "명지 신도시 법인 설립·신축 등기",
    relatedCaseSlug: "suyeong-company-establishment-case",
  },
  {
    slug: "정관법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "정관법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "jeonggwan",
    regionLabel: "정관",
    neighborhoods: ["정관읍", "정관신도시"],
    caseAngle: "정관 토지·주택 상속등기",
    relatedCaseSlug: "gijang-land-inheritance-case",
  },
  {
    slug: "사상법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "사상법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "sasang",
    regionLabel: "사상",
    neighborhoods: ["괘법동", "엄궁동", "감전동"],
    caseAngle: "사상구 공장·상가 근저당·등기",
  },
  {
    slug: "하단법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "하단법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "saha",
    regionLabel: "하단",
    neighborhoods: ["하단동", "괴정동", "당리동"],
    caseAngle: "하단동 아파트 상속등기",
  },
  {
    slug: "우동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "우동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "haeundae",
    regionLabel: "우동",
    neighborhoods: ["우동", "마린시티", "해운대해수욕장"],
    caseAngle: "마린시티·우동 아파트·상가 등기",
  },
  {
    slug: "좌동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "좌동법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "haeundae",
    regionLabel: "좌동",
    neighborhoods: ["좌동", "장산역", "해운대 신시가지"],
    caseAngle: "좌동 대단지 아파트 상속등기",
  },
  {
    slug: "사직동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "사직동법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "dongnae",
    regionLabel: "사직동",
    neighborhoods: ["사직동", "사직야구장", "사직역"],
    caseAngle: "사직동 재건축·아파트 상속등기",
  },
  {
    slug: "화명동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "화명동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "buk",
    regionLabel: "화명동",
    neighborhoods: ["화명동", "화명신도시", "금곡동"],
    caseAngle: "화명신도시 아파트 매매·상속 등기",
  },
  {
    slug: "부곡동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "부곡동법무사",
    serviceSlug: "qualified-acceptance",
    regionKey: "geumjeong",
    regionLabel: "부곡동",
    neighborhoods: ["부곡동", "부산대", "장전동"],
    caseAngle: "부곡동 다가구·임대 상속·한정승인",
  },
  {
    slug: "거제동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "거제동법무사",
    serviceSlug: "personal-rehabilitation",
    regionKey: "yeonje",
    regionLabel: "거제동",
    neighborhoods: ["거제동", "거제역", "법조타운"],
    caseAngle: "거제동 법원 인근 회생·민사·등기",
    relatedCaseSlug: "busan-personal-rehabilitation-consultation",
  },
  {
    slug: "전포동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "전포동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "busanjin",
    regionLabel: "전포동",
    neighborhoods: ["전포동", "전포카페거리", "서면"],
    caseAngle: "전포카페거리 상가·권리금 등기",
  },
  {
    slug: "문현동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "문현동법무사",
    serviceSlug: "corporate-registration",
    regionKey: "munhyeon",
    regionLabel: "문현동",
    neighborhoods: ["문현동", "문현금융단지", "BIFC"],
    caseAngle: "문현금융단지 법인·주거 등기",
  },
  {
    slug: "용호동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "용호동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "namgu",
    regionLabel: "용호동",
    neighborhoods: ["용호동", "이기대", "오륙도"],
    caseAngle: "용호·이기대 아파트 매매·상속 등기",
  },
  {
    slug: "망미동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "망미동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "suyeong",
    regionLabel: "망미동",
    neighborhoods: ["망미동", "망미역", "수영강"],
    caseAngle: "망미동 아파트 전세·매매 등기",
  },
  {
    slug: "일광읍법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "일광읍법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "gijang",
    regionLabel: "일광읍",
    neighborhoods: ["일광읍", "일광해수욕장", "기장읍"],
    caseAngle: "일광읍 토지·신축 주택 상속등기",
    relatedCaseSlug: "gijang-land-inheritance-case",
  },
  {
    slug: "남포동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "남포동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "junggu",
    regionLabel: "남포동",
    neighborhoods: ["남포동", "자갈치", "중앙동"],
    caseAngle: "남포·원도심 상가 상속·매매 등기",
  },
  // phase3 — 미개설 상위 검색 동네(기존 URL 유지, 신규 슬러그만 추가)
  {
    slug: "초량동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "초량동법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "donggu",
    regionLabel: "초량동",
    neighborhoods: ["초량동", "좌천동", "수정동"],
    caseAngle: "초량 다가구 공동상속과 다수 임차인 보증금 정리",
  },
  {
    slug: "범일동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "범일동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "donggu",
    regionLabel: "범일동",
    neighborhoods: ["범일동", "범천동"],
    caseAngle: "범일 공구상가 매매의 권리금·소유권 분리",
  },
  {
    slug: "구포동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "구포동법무사",
    serviceSlug: "personal-rehabilitation",
    regionKey: "buk",
    regionLabel: "구포동",
    neighborhoods: ["구포동", "만덕동"],
    caseAngle: "구포·만덕 담보 주거와 개인회생 재산목록",
    relatedCaseSlug: "busan-personal-rehabilitation-consultation",
  },
  {
    slug: "다대동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "다대동법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "saha",
    regionLabel: "다대동",
    neighborhoods: ["다대동", "장림동", "감천동"],
    caseAngle: "다대·장림 다가구 상속 후 임차인 유지 매도",
  },
  {
    slug: "괴정동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "괴정동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "saha",
    regionLabel: "괴정동",
    neighborhoods: ["괴정동", "당리동", "신평동"],
    caseAngle: "괴정 역세권 전세 승계 매매 잔금일 등기",
  },
  {
    slug: "개금동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "개금동법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "busanjin",
    regionLabel: "개금동",
    neighborhoods: ["개금동", "가야동", "당감동"],
    caseAngle: "개금·당감 공동상속 아파트 정산",
  },
  {
    slug: "안락동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "안락동법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "dongnae",
    regionLabel: "안락동",
    neighborhoods: ["안락동", "명장동", "수안동"],
    caseAngle: "안락·명장 상속 명의 후 정비·매도 일정",
  },
  {
    slug: "구서동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "구서동법무사",
    serviceSlug: "qualified-acceptance",
    regionKey: "geumjeong",
    regionLabel: "구서동",
    neighborhoods: ["구서동", "서동", "청룡동"],
    caseAngle: "구서 임대 다가구 상속·한정승인 검토",
  },
  {
    slug: "반송동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "반송동법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "haeundae",
    regionLabel: "반송동",
    neighborhoods: ["반송동", "석대동", "회동동"],
    caseAngle: "반송·회동 토지·주택 공동상속 지분 정리",
  },
  {
    slug: "주례동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "주례동법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "sasang",
    regionLabel: "주례동",
    neighborhoods: ["주례동", "학장동", "모라동"],
    caseAngle: "주례·모라 아파트 상속 후 전세 유지 매도",
  },
  {
    slug: "동삼동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "동삼동법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "yeongdo",
    regionLabel: "동삼동",
    neighborhoods: ["동삼동", "영선동", "청학동"],
    caseAngle: "영도 동삼 주택 원격 협의분할",
  },
  {
    slug: "우암동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "우암동법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "namgu",
    regionLabel: "우암동",
    neighborhoods: ["우암동", "감만동", "용당동"],
    caseAngle: "우암·감만 다가구 상속과 임차인 보증금 목록",
  },
  {
    slug: "기장읍법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "기장읍법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "gijang",
    regionLabel: "기장읍",
    neighborhoods: ["기장읍", "장안읍", "철마면"],
    caseAngle: "기장읍·철마 토지 원격 협의분할",
    relatedCaseSlug: "gijang-land-inheritance-case",
  },
  {
    slug: "연지동법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "연지동법무사",
    serviceSlug: "inheritance-registration",
    regionKey: "busanjin",
    regionLabel: "연지동",
    neighborhoods: ["연지동", "초읍동"],
    caseAngle: "연지·초읍 아파트 상속과 전세 만기 매도",
  },
  {
    slug: "오시리아법무사",
    pageType: "neighborhood-hub",
    neighborhoodKey: "오시리아법무사",
    serviceSlug: "real-estate-registration",
    regionKey: "gijang",
    regionLabel: "오시리아",
    neighborhoods: ["오시리아", "동부산"],
    caseAngle: "오시리아·동부산 분양 잔금과 상속 명의 일정",
  },
];
