import type { LocalLandingConfig } from "@/types/local-landing";

/** 추천·선택기준·비교·상담 SEO 허브 (기존 URL과 별도 slug) */
export const selectionLandingConfigs: LocalLandingConfig[] = [
  {
    slug: "부산법무사추천",
    pageType: "selection-hub",
    keywordKey: "부산법무사추천",
    serviceSlug: "inheritance-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "센텀", "서면", "연제구"],
  },
  {
    slug: "부산등기법무사추천",
    pageType: "selection-hub",
    keywordKey: "부산등기법무사추천",
    serviceSlug: "real-estate-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "수영구", "연제구"],
  },
  {
    slug: "부산상속등기전문",
    pageType: "selection-hub",
    keywordKey: "부산상속등기전문",
    serviceSlug: "inheritance-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "연제구", "동래구"],
    relatedCaseSlug: "haeundae-inheritance-registration-case",
  },
  {
    slug: "부산부동산등기전문",
    pageType: "selection-hub",
    keywordKey: "부산부동산등기전문",
    serviceSlug: "real-estate-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "수영구", "광안동"],
    relatedCaseSlug: "centum-ownership-transfer-case",
  },
  {
    slug: "부산법인등기전문",
    pageType: "selection-hub",
    keywordKey: "부산법인등기전문",
    serviceSlug: "corporate-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["센텀", "해운대구"],
    relatedCaseSlug: "suyeong-company-establishment-case",
  },
  {
    slug: "부산법무사상담",
    pageType: "selection-hub",
    keywordKey: "부산법무사상담",
    serviceSlug: "inheritance-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "센텀", "재송동"],
  },
  {
    slug: "부산법무사후기",
    pageType: "selection-hub",
    keywordKey: "부산법무사후기",
    serviceSlug: "inheritance-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "센텀"],
  },
  {
    slug: "부산법무사비교",
    pageType: "selection-hub",
    keywordKey: "부산법무사비교",
    serviceSlug: "inheritance-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "연제구", "부산진구"],
  },
  {
    slug: "부산법무사무소",
    pageType: "selection-hub",
    keywordKey: "부산법무사무소",
    serviceSlug: "inheritance-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "센텀", "재송동"],
  },
  {
    slug: "부산법무사서류준비",
    pageType: "selection-hub",
    keywordKey: "부산법무사서류준비",
    serviceSlug: "inheritance-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "센텀"],
  },
  {
    slug: "부산법무사방문상담",
    pageType: "selection-hub",
    keywordKey: "부산법무사방문상담",
    serviceSlug: "inheritance-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "센텀", "재송동"],
  },
  {
    slug: "부산법무사비대면상담",
    pageType: "selection-hub",
    keywordKey: "부산법무사비대면상담",
    serviceSlug: "inheritance-registration",
    regionKey: "busan",
    regionLabel: "부산",
    neighborhoods: ["해운대구", "센텀"],
  },
];
