import type { SearchPopularLink } from "./types";

export const SEARCH_POPULAR_LINKS: SearchPopularLink[] = [
  { href: "/", label: "다옴법무사사무소", group: "region" },
  { href: "/부산법무사", label: "업무·선택 안내", group: "region" },
  { href: "/부산법무사추천", label: "법무사 선택 기준", group: "region" },
  { href: "/부산상속등기", label: "상속등기", group: "service" },
  { href: "/부산개인회생", label: "개인회생", group: "service" },
  { href: "/부산개인파산", label: "개인파산", group: "service" },
  { href: "/부산법인설립등기", label: "법인설립", group: "service" },
  { href: "/부산소유권이전등기", label: "소유권이전등기", group: "service" },
  { href: "/부산매매등기법무사", label: "매매등기", group: "service" },
  { href: "/부산증여등기", label: "증여등기", group: "service" },
  { href: "/부산임차권등기명령", label: "임차권등기명령", group: "service" },
  { href: "/부산가등기", label: "가등기", group: "service" },
  { href: "/부산경매권리분석", label: "경매 권리분석", group: "service" },
  { href: "/부산가압류말소등기", label: "가압류 말소", group: "service" },
  { href: "/부산신탁등기", label: "신탁등기", group: "service" },
  { href: "/부산법률상담", label: "부산 법률상담", group: "service" },
  { href: "/부산법률전문가", label: "강의·공공활동", group: "lecture" },
  { href: "/법률강의", label: "법률 강의", group: "lecture" },
  { href: "/강의이력", label: "강의 이력", group: "lecture" },
  { href: "/contact", label: "상담 문의", group: "menu" },
  { href: "/해운대법무사", label: "해운대 법무사", group: "region" },
  { href: "/센텀법무사", label: "센텀 법무사", group: "region" },
  { href: "/전세사기예방교육", label: "전세사기 예방교육", group: "lecture" },
  { href: "/부산도서관법률특강", label: "도서관 법률특강", group: "lecture" },
  { href: "/부산등기복대리", label: "등기 복대리", group: "service" },
  { href: "/부산집단등기", label: "집단등기", group: "service" },
  { href: "/자가진단", label: "자가진단", group: "menu" },
  { href: "/services", label: "전체 업무", group: "menu" },
];

export const FEATURED_PATHS = new Set([
  "/",
  "/services",
  "/부산법무사",
  "/부산법무사추천",
  "/법률강의",
  "/기업법률교육",
  "/부산기업법률자문",
  "/부산법률상담",
  "/강의이력",
  "/자가진단",
  "/situations",
  "/tools",
  "/glossary",
  "/faq",
  "/contact",
  "/location",
  "/부산법무사",
  "/부산등기법무사",
  "/부산상속등기",
  "/부산개인회생",
  "/부산개인파산",
  "/부산법인설립등기",
  "/부산소유권이전등기",
  "/부산매매등기법무사",
  "/부산증여등기",
  "/부산명의변경등기",
  "/부산임차권등기명령",
  "/부산가압류말소등기",
  "/부산외국인부동산등기",
  "/부산신탁등기",
  "/부산등기복대리",
  "/부산집단등기",
  "/부산입주등기",
  "/부산법무사비용",
  "/강사소개",
  "/강의문의",
  "/부산법무사강의",
  "/부산기관법률특강",
  "/부산도서관법률특강",
  "/부산법률강사",
]);
