import type { SearchPopularLink } from "./types";

export const SEARCH_POPULAR_LINKS: SearchPopularLink[] = [
  { href: "/부산법무사", label: "부산 법무사", group: "region" },
  { href: "/부산상속등기", label: "상속등기", group: "service" },
  { href: "/부산개인회생", label: "개인회생", group: "service" },
  { href: "/부산개인파산", label: "개인파산", group: "service" },
  { href: "/부산법인설립등기", label: "법인설립", group: "service" },
  { href: "/부산소유권이전등기", label: "소유권이전등기", group: "service" },
  { href: "/법률강의", label: "법률 강의", group: "lecture" },
  { href: "/부산법무사강의", label: "부산 법무사 강의", group: "lecture" },
  { href: "/부산기관법률특강", label: "기관 법률특강", group: "lecture" },
  { href: "/부산기업법률자문", label: "기업 법률실무", group: "service" },
  { href: "/강의이력", label: "강의 이력", group: "lecture" },
  { href: "/contact", label: "상담 문의", group: "menu" },
  { href: "/해운대법무사", label: "해운대 법무사", group: "region" },
  { href: "/센텀법무사", label: "센텀 법무사", group: "region" },
  { href: "/전세사기예방교육", label: "전세사기 예방교육", group: "lecture" },
  { href: "/부산도서관법률특강", label: "도서관 법률특강", group: "lecture" },
  { href: "/부산등기복대리", label: "등기 복대리", group: "service" },
  { href: "/부산집단등기", label: "집단등기", group: "service" },
  { href: "/자가진단", label: "자가진단", group: "menu" },
  { href: "/services", label: "전체 업무", group: "menu" },
];

export const FEATURED_PATHS = new Set([
  "/",
  "/services",
  "/법률강의",
  "/부산기업법률자문",
  "/강의이력",
  "/자가진단",
  "/situations",
  "/tools",
  "/glossary",
  "/faq",
  "/contact",
  "/location",
  "/부산법무사",
  "/부산상속등기",
  "/부산개인회생",
  "/부산개인파산",
  "/부산법인설립등기",
  "/부산등기복대리",
  "/부산집단등기",
  "/부산법무사비용",
  "/강사소개",
  "/강의문의",
  "/부산법무사강의",
  "/부산기관법률특강",
  "/부산도서관법률특강",
  "/부산법률강사",
]);
