import type { SpecialEntityPageContent } from "../types";
import {
  SPECIAL_ENTITY_HUB_LINKS,
  SPECIAL_ENTITY_OFFICE_LINE,
  SPECIAL_ENTITY_SCOPE_NOTICE,
  baseSpecialRelated,
} from "./shared";

/**
 * 김해·양산 복제 대신 부산 구·권역별 고유 관할·산업 특성이 있는 페이지만 생성.
 */
export const phase3BusanRegionalPages: SpecialEntityPageContent[] = [
  {
    slug: "해운대비영리법인설립",
    kind: "intent",
    title: "해운대 비영리법인 설립",
    metaTitle: "해운대 비영리법인 설립｜센텀·해운대 사단·재단 허가와 등기",
    metaDescription:
      "해운대·센텀 소재 사단·재단법인 설립. 해운대구·부산시 주무관청, 부산지방법원 등기국 — 다옴법무사.",
    h1: "해운대 비영리법인 — 센텀·해운대 단체의 허가와 등기",
    eyebrow: "해운대 · 비영리법인",
    heroIntro:
      "해운대구·센텀시티에 주사무소를 두는 협회·학회·문화·복지 단체는 부산 비영리법인 설립 절차를 따릅니다.",
    heroParagraphs: [
      "해운대구청·부산광역시·교육청 중 목적에 맞는 주무관청에 허가 신청 후, 부산지방법원 등기국 등 관할 등기소에 설립등기합니다. 다옴법무사사무소는 해운대·센텀에 소재해 상담·수임이 용이합니다.",
      "관광·국제·문화·스타트업 연계 단체가 많은 권역 특성을 반영해 목적·정관을 정리하는 것이 좋습니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "해운대 소재 비영리법인은 사단·재단 중 형태를 정한 뒤 주무관청 허가 후 3주 이내 설립등기합니다.",
    primaryKeyword: "해운대 비영리법인 설립",
    secondaryKeywords: [
      "센텀 사단법인",
      "해운대 재단법인",
      "해운대 협회 법인",
    ],
    questionKeywords: ["해운대 법인 설립", "센텀 비영리법인"],
    searchIntent: "해운대·센텀에서 비영리법인을 설립하려는 검색",
    whoNeedsThis: [
      "해운대·센텀 사무실 예정 협회·단체",
      "관광·문화·국제교류 목적 단체",
    ],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["창립총회", "해운대구·부산시·교육청 등"],
    documents: ["허가서", "정관", "의사록", "주사무소 증빙"],
    procedures: ["유형 선택", "허가", "부산 등기소 접수"],
    costFactors: ["사단 vs 재단", "기본재산"],
    penaltyRisks: ["구·시 관할 혼동"],
    commonConfusions: ["구청 등록만으로 법인 완성으로 오인"],
    diyErrors: ["허가 없이 등기"],
    faqs: [],
    relatedLinks: [
      { href: "/부산비영리법인설립등기", label: "부산 비영리법인" },
      { href: "/부산사단법인설립", label: "부산 사단법인" },
      { href: "/센텀법인설립등기", label: "센텀 주식회사 설립(비교)" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "해운대 비영리법인 설립 상담",
    ctaText: "해운대·센텀 주사무소 예정과 단체 목적을 알려주세요.",
    legalProfile: {
      entityName: "비영리법인(해운대·센텀)",
      legalBasis: ["민법 제32조"],
      establishmentMethod: "주무관청 허가 후 설립등기",
      competentAuthority: [
        "해운대구·부산광역시·교육청(목적별)",
        "부산지방법원 등기국 등",
      ],
      preRegistrationSteps: ["유형·관할", "허가", "창립총회"],
      registrationDeadline: "허가 후 3주 이내",
      registrableMatters: ["설립 등기사항"],
      lawyerScope: ["허가 후 등기"],
      excludedScope: ["허가 대리"],
      lastLegalReview: "2026-07-29",
      regionalNotes: [
        "해운대·센텀 문화·관광·국제·스타트업 연계 단체",
        "사무소: 해운대 다옴법무사",
      ],
    },
  },
  {
    slug: "수영구비영리법인설립",
    kind: "intent",
    title: "수영구 비영리법인 설립",
    metaTitle: "수영구 비영리법인 설립｜광안·민락 사단·재단 허가와 등기",
    metaDescription:
      "수영구 소재 사단·재단법인 설립. 수영구·부산시 주무관청, 부산 등기소 — 다옴법무사.",
    h1: "수영구 비영리법인 — 광안·민락 단체의 허가와 등기",
    eyebrow: "수영구 · 비영리법인",
    heroIntro:
      "수영구에 주사무소를 두는 체육·문화·지역단체는 목적별 주무관청 허가 후 설립등기합니다.",
    heroParagraphs: [
      "수영구청·부산시·교육청 관할을 목적에 맞게 확인하고, 부산 관할 등기소에 접수합니다. 생활체육·문화 단체가 많은 권역입니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "수영구 비영리법인은 허가 후 3주 이내 설립등기합니다. `/체육단체사단법인설립`, `/문화예술단체사단법인설립`도 참고하세요.",
    primaryKeyword: "수영구 비영리법인 설립",
    secondaryKeywords: ["수영구 사단법인", "광안 협회 법인"],
    questionKeywords: ["수영구 법인 설립"],
    searchIntent: "수영구에서 비영리법인을 설립하려는 검색",
    whoNeedsThis: ["수영구 소재 체육·문화·지역 단체"],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["창립총회", "수영구·부산시 등"],
    documents: ["허가서", "정관"],
    procedures: ["허가", "등기"],
    costFactors: ["법인 유형"],
    penaltyRisks: ["관할 혼동"],
    commonConfusions: ["구청 등록=법인"],
    diyErrors: ["허가 전 등기"],
    faqs: [],
    relatedLinks: [
      { href: "/체육단체사단법인설립", label: "체육단체 사단법인" },
      { href: "/부산사단법인설립", label: "부산 사단법인" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "수영구 비영리법인 설립 상담",
    ctaText: "수영구 주사무소와 단체 목적을 알려주세요.",
    legalProfile: {
      entityName: "비영리법인(수영구)",
      legalBasis: ["민법 제32조"],
      establishmentMethod: "허가 후 설립등기",
      competentAuthority: ["수영구·부산시 등", "부산 관할 등기소"],
      preRegistrationSteps: ["허가"],
      registrationDeadline: "허가 후 3주 이내",
      registrableMatters: ["설립 등기사항"],
      lawyerScope: ["등기"],
      excludedScope: ["허가"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["광안·민락 체육·문화 단체"],
    },
  },
  {
    slug: "부산진구비영리법인설립",
    kind: "intent",
    title: "부산진구 비영리법인 설립",
    metaTitle: "부산진구 비영리법인 설립｜서면·전포 협회·단체 법인화",
    metaDescription:
      "부산진구(서면·전포) 사단·재단법인 설립. 부산진구·부산시 허가, 부산 등기소 — 다옴법무사.",
    h1: "부산진구 비영리법인 — 서면·전포 협회·단체의 법인화",
    eyebrow: "부산진구 · 비영리법인",
    heroIntro:
      "서면·전포 등 부산진구에 사무실을 두는 업종 협회·학회·복지 단체는 사단법인 설립을 검토하는 경우가 많습니다.",
    heroParagraphs: [
      "상업·서비스·교육 밀집 지역 특성상 협회·직능단체 법인화 수요가 있습니다. 주무관청은 목적에 따라 부산진구·부산시·교육청 등으로 달라집니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "부산진구 비영리법인은 허가 후 설립등기합니다. 협회형은 `/협회사단법인설립`을 함께 참고하세요.",
    primaryKeyword: "부산진구 비영리법인 설립",
    secondaryKeywords: [
      "서면 사단법인",
      "전포 협회 법인",
      "부산진구 재단",
    ],
    questionKeywords: ["부산진구 법인 설립", "서면 협회 법인"],
    searchIntent: "부산진구에서 비영리법인을 설립하려는 검색",
    whoNeedsThis: ["서면·전포 업종 협회·학회·복지 단체"],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["창립총회", "부산진구·부산시 등"],
    documents: ["허가서", "정관", "회원 명부"],
    procedures: ["허가", "등기"],
    costFactors: ["회원·임원"],
    penaltyRisks: ["관할 오류"],
    commonConfusions: ["주식회사와 협회 혼동"],
    diyErrors: ["허가 전 등기"],
    faqs: [],
    relatedLinks: [
      { href: "/협회사단법인설립", label: "협회 사단법인" },
      { href: "/부산협회단체법인설립", label: "부산 협회·단체" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "부산진구 비영리법인 설립 상담",
    ctaText: "서면·전포 주사무소와 협회 목적을 알려주세요.",
    legalProfile: {
      entityName: "비영리법인(부산진구)",
      legalBasis: ["민법 제32조"],
      establishmentMethod: "허가 후 설립등기",
      competentAuthority: ["부산진구·부산시 등", "부산 관할 등기소"],
      preRegistrationSteps: ["허가"],
      registrationDeadline: "허가 후 3주 이내",
      registrableMatters: ["설립 등기사항"],
      lawyerScope: ["등기"],
      excludedScope: ["허가"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["서면·전포 업종 협회·직능단체"],
    },
  },
  {
    slug: "부산문화예술단체법인설립",
    kind: "intent",
    title: "부산 문화예술단체 법인설립",
    metaTitle: "부산 문화예술단체 법인설립｜공연·미술·영상 사단법인",
    metaDescription:
      "부산 문화예술단체 사단법인 설립. 문체·시·구 주무관청, 허가 후 등기 — 다옴법무사.",
    h1: "부산 문화예술단체 법인설립 — 공연·창작 단체의 법인화",
    eyebrow: "부산 · 문화예술",
    heroIntro:
      "부산의 공연·음악·미술·영상·문학 단체는 사단법인으로 법인화하는 경우가 많습니다.",
    heroParagraphs: [
      "영화의전당·벡스코·해운대·원도심 등 문화 인프라와 연계된 협회·단체가 있습니다. 목적에 따라 문화체육관광·부산시·구 주무관청이 달라집니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "부산 문화예술단체는 사단법인 허가 후 설립등기합니다. `/문화예술단체사단법인설립`과 절차가 같되, 부산 관할을 구체적으로 안내합니다.",
    primaryKeyword: "부산 문화예술단체 법인설립",
    secondaryKeywords: [
      "부산 예술인 협회",
      "부산 공연단체 법인",
      "부산 문화재단",
    ],
    questionKeywords: ["부산 문화단체 법인"],
    searchIntent: "부산 문화예술 단체의 법인화를 확인하려는 검색",
    whoNeedsThis: ["부산 공연·창작·전시 단체"],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["창립총회", "문체·시·구"],
    documents: ["허가서", "정관", "회원 명부"],
    procedures: ["허가", "등기"],
    costFactors: ["회원·임원"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["지원사업 등록=법인"],
    diyErrors: ["수익 배분 조항 오류"],
    faqs: [],
    relatedLinks: [
      { href: "/문화예술단체사단법인설립", label: "문화예술단체 사단법인" },
      { href: "/부산사단법인설립", label: "부산 사단법인" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "부산 문화예술단체 법인 상담",
    ctaText: "단체 장르와 회원 구성을 알려주세요.",
    legalProfile: {
      entityName: "문화예술 사단법인(부산)",
      legalBasis: ["민법 제32조"],
      establishmentMethod: "허가 후 설립등기",
      competentAuthority: ["문화·시·구 주무관청", "부산 등기소"],
      preRegistrationSteps: ["허가"],
      registrationDeadline: "허가 후 3주 이내",
      registrableMatters: ["설립 등기사항"],
      lawyerScope: ["등기"],
      excludedScope: ["지원금·세무"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["부산 문화·영상·공연 인프라 연계"],
    },
  },
  {
    slug: "부산체육단체법인설립",
    kind: "intent",
    title: "부산 체육단체 법인설립",
    metaTitle: "부산 체육단체 법인설립｜종목·생활체육 사단법인",
    metaDescription:
      "부산 체육단체·종목협회 사단법인 설립. 허가·창립총회·등기 — 다옴법무사.",
    h1: "부산 체육단체 법인설립 — 종목·생활체육 협회 법인화",
    eyebrow: "부산 · 체육",
    heroIntro:
      "부산 종목별 협회·생활체육·해양·구기 종목 단체는 사단법인 설립을 검토할 수 있습니다.",
    heroParagraphs: [
      "문화체육관광·부산시·구·체육회 체계와의 관계를 정관에 명확히 하고, 주무관청 허가 후 설립등기합니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "부산 체육단체 사단법인은 허가 후 설립등기합니다. 대한체육회·종목단체 산하 관계는 별도 확인이 필요합니다.",
    primaryKeyword: "부산 체육단체 법인설립",
    secondaryKeywords: [
      "부산 종목협회",
      "부산 생활체육 법인",
      "부산 스포츠클럽",
    ],
    questionKeywords: ["부산 체육협회 법인"],
    searchIntent: "부산 체육 단체의 법인화를 확인하려는 검색",
    whoNeedsThis: ["부산 종목·생활체육 단체"],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["창립총회"],
    documents: ["허가서", "정관"],
    procedures: ["허가", "등기"],
    costFactors: ["회원 규모"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["체육회 산하=자동 법인"],
    diyErrors: ["목적 불명확"],
    faqs: [],
    relatedLinks: [
      { href: "/체육단체사단법인설립", label: "체육단체 사단법인" },
      { href: "/수영구비영리법인설립", label: "수영구 비영리법인" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "부산 체육단체 법인 상담",
    ctaText: "종목과 회원 구조를 알려주세요.",
    legalProfile: {
      entityName: "체육 사단법인(부산)",
      legalBasis: ["민법 제32조"],
      establishmentMethod: "허가 후 설립등기",
      competentAuthority: ["체육·시·구 주무관청", "부산 등기소"],
      preRegistrationSteps: ["허가"],
      registrationDeadline: "허가 후 3주 이내",
      registrableMatters: ["설립 등기사항"],
      lawyerScope: ["등기"],
      excludedScope: ["체육회 행정"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["부산 해양·생활체육·종목 단체"],
    },
  },
];
