import type { SpecialEntityPageContent } from "../types";
import {
  SPECIAL_ENTITY_OFFICE_LINE,
  SPECIAL_ENTITY_SCOPE_NOTICE,
  baseSpecialRelated,
} from "./shared";

export const phase3RegionalPages: SpecialEntityPageContent[] = [
  {
    slug: "경남사단법인설립",
    kind: "intent",
    title: "경남 사단법인 설립",
    metaTitle: "경남 사단법인 설립｜창원·김해·양산 주무관청과 등기소",
    metaDescription:
      "경남(창원·김해·양산 등) 사단법인 설립허가·등기. 시·군·교육청 관할, 창원지방법원 등기국 — 다옴법무사.",
    h1: "경남 사단법인 설립 — 시·군별 주무관청을 먼저 확인하세요",
    eyebrow: "경남 · 사단법인",
    heroIntro:
      "경상남도에 주사무소를 두는 사단법인은 목적에 따라 경남도·시·군·교육청이 주무관청이 될 수 있습니다.",
    heroParagraphs: [
      "창원·김해·양산·거제·진주 등 시·군별로 허가 창구가 다릅니다. 설립등기는 주사무소 관할 등기소(통상 창원지방법원 등기국 등)에 접수합니다.",
      "부산 다옴법무사사무소에서도 경남 소재 법인 등기 수임·상담이 가능하나, 관할 등기소·주무관청은 주사무소 소재지 기준입니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "경남 사단법인은 해당 시·군·도 주무관청 허가 후 3주 이내 관할 등기소에 설립등기합니다.",
    primaryKeyword: "경남 사단법인 설립",
    secondaryKeywords: [
      "창원 사단법인",
      "김해 협회 법인",
      "양산 사단법인",
      "경남 협회 설립",
    ],
    questionKeywords: ["경남 사단법인 절차", "창원 법인 설립"],
    searchIntent: "경남에서 사단법인을 설립하려는 검색",
    whoNeedsThis: [
      "경남 소재 협회·단체·학회",
      "창원·김해·양산에 사무실을 두는 발기인",
    ],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["창립총회", "경남·시·군 주무관청"],
    documents: ["허가서", "정관", "의사록", "임원 서류"],
    procedures: ["관할 주무관청 확인", "허가", "창원 등기국 등 접수"],
    costFactors: ["관할", "임원 수"],
    penaltyRisks: ["시·군 관할 오류"],
    commonConfusions: ["부산 허가 vs 경남 허가"],
    diyErrors: ["잘못된 주무관청 신청"],
    faqs: [
      {
        question: "부산 사무소에서 경남 법인 등기를 하나요?",
        answer:
          "상담·서류 작성은 가능하나 접수는 주사무소 관할 등기소입니다. `/부산사단법인설립`과 관할이 다릅니다.",
      },
    ],
    relatedLinks: [
      { href: "/창원비영리법인설립", label: "창원 비영리법인" },
      { href: "/부산사단법인설립", label: "부산 사단법인" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "경남 사단법인 설립 상담",
    ctaText: "주사무소 예정지와 단체 목적을 알려주세요.",
    legalProfile: {
      entityName: "사단법인(경남)",
      legalBasis: ["민법 제32·37조", "민법 시행령"],
      establishmentMethod: "주무관청 허가 후 설립등기",
      competentAuthority: [
        "경상남도·시·군·교육청(목적별)",
        "창원지방법원 등기국 등",
      ],
      preRegistrationSteps: ["관할 확인", "허가", "창립총회"],
      registrationDeadline: "허가 후 3주 이내",
      registrableMatters: ["목적·임원·주사무소"],
      lawyerScope: ["허가 후 등기"],
      excludedScope: ["허가 대행"],
      lastLegalReview: "2026-07-29",
      regionalNotes: [
        "창원·김해·양산 등 시·군별 주무관청 상이",
        "등기: 주사무소 관할(통상 창원 등기국)",
      ],
    },
  },
  {
    slug: "경남재단법인설립",
    kind: "intent",
    title: "경남 재단법인 설립",
    metaTitle: "경남 재단법인 설립｜출연재산·기본재산과 창원 등기",
    metaDescription:
      "경남 재단법인 설립허가·기본재산·설립등기. 경남·시·군 주무관청 — 다옴법무사.",
    h1: "경남 재단법인 — 출연과 관할부터 정리하세요",
    eyebrow: "경남 · 재단법인",
    heroIntro: "경남에 기본재산·주사무소를 두는 재단법인은 목적별 주무관청 허가 후 설립등기합니다.",
    heroParagraphs: [
      "장학·복지·문화·지역발전 목적 재단이 많습니다. 기본재산 귀속 증빙이 허가·등기의 핵심입니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion: "경남 재단법인은 허가 후 3주 이내 관할 등기소에 설립등기합니다.",
    primaryKeyword: "경남 재단법인 설립",
    secondaryKeywords: ["양산 재단법인", "경남 장학재단", "창원 재단"],
    questionKeywords: ["경남 재단 설립"],
    searchIntent: "경남에서 재단법인을 설립하려는 검색",
    whoNeedsThis: ["경남 소재 재단 설립"],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["설립위원회", "주무관청"],
    documents: ["허가서", "기본재산 목록", "정관"],
    procedures: ["허가", "등기"],
    costFactors: ["기본재산 가액"],
    penaltyRisks: ["재산 미귀속"],
    commonConfusions: ["부산·경난 관할"],
    diyErrors: ["기본재산 증빙 누락"],
    faqs: [],
    relatedLinks: [
      { href: "/경남사단법인설립", label: "경남 사단법인" },
      { href: "/부산재단법인설립", label: "부산 재단법인" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "경남 재단법인 설립 상담",
    ctaText: "출연·기본재산 구조를 알려주세요.",
    legalProfile: {
      entityName: "재단법인(경남)",
      legalBasis: ["민법 제32·42조"],
      establishmentMethod: "주무관청 허가 후 설립등기",
      competentAuthority: ["경남·시·군", "창원 등기국 등"],
      preRegistrationSteps: ["출연·허가"],
      registrationDeadline: "허가 후 3주 이내",
      registrableMatters: ["기본재산·임원"],
      lawyerScope: ["등기"],
      excludedScope: ["세무·기부금"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["양산·창원 등 지역 재단 수요"],
    },
  },
  {
    slug: "창원비영리법인설립",
    kind: "intent",
    title: "창원 비영리법인 설립",
    metaTitle: "창원 비영리법인 설립｜창원시 주무관청·창원 등기국",
    metaDescription:
      "창원 소재 사단·재단법인 설립. 창원시·교육청 관할, 창원지방법원 등기국 — 다옴법무사.",
    h1: "창원 비영리법인 — 행정도시·교육·산업 단체의 관할",
    eyebrow: "창원 · 비영리법인",
    heroIntro:
      "창원시는 경남 행정 중심으로 협회·학회·복지·산업 단체의 비영리법인 설립 수요가 있습니다.",
    heroParagraphs: [
      "주사무소가 창원이면 창원시·경남도·교육청 중 목적에 맞는 주무관청에 허가를 신청하고, 창원지방법원 등기국 등에 설립등기합니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "창원 비영리법인은 사단·재단 중 목적에 맞는 형태를 선택한 뒤 허가·등기합니다.",
    primaryKeyword: "창원 비영리법인 설립",
    secondaryKeywords: [
      "창원 사단법인",
      "창원 재단법인",
      "창원 협회 법인",
    ],
    questionKeywords: ["창원 법인 설립"],
    searchIntent: "창원에서 비영리법인을 설립하려는 검색",
    whoNeedsThis: ["창원 소재 단체·협회"],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["창립총회", "창원시·경남도 등"],
    documents: ["허가서", "정관"],
    procedures: ["유형 선택", "허가", "등기"],
    costFactors: ["사단 vs 재단"],
    penaltyRisks: ["관할 혼동"],
    commonConfusions: ["경남 페이지와 중복? → 창원시 관할 구체화"],
    diyErrors: ["구·동만 바꿔 신청"],
    faqs: [],
    relatedLinks: [
      { href: "/경남사단법인설립", label: "경남 사단법인" },
      { href: "/협회사단법인설립", label: "협회 사단법인" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "창원 비영리법인 설립 상담",
    ctaText: "창원 주사무소 예정과 목적을 알려주세요.",
    legalProfile: {
      entityName: "비영리법인(창원)",
      legalBasis: ["민법 제32조"],
      establishmentMethod: "허가 후 설립등기",
      competentAuthority: ["창원시·경남도·교육청", "창원지방법원 등기국"],
      preRegistrationSteps: ["관할·유형", "허가"],
      registrationDeadline: "허가 후 3주 이내",
      registrableMatters: ["설립 등기사항"],
      lawyerScope: ["등기"],
      excludedScope: ["허가"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["창원 행정·교육·산업 단체"],
    },
  },
];
