import type { SpecialEntityPageContent } from "../types";
import {
  SPECIAL_ENTITY_HUB_LINKS,
  SPECIAL_ENTITY_OFFICE_LINE,
  SPECIAL_ENTITY_SCOPE_NOTICE,
  baseSpecialRelated,
} from "./shared";

export const phase2ComparisonPages: SpecialEntityPageContent[] = [
  {
    slug: "농업회사법인과영농조합법인차이",
    kind: "comparison",
    title: "농업회사법인과 영농조합법인 차이",
    metaTitle: "농업회사법인과 영농조합법인｜사업 구조에 따라 달라지는 설립 방식",
    metaDescription:
      "농업회사법인 vs 영농조합법인. 인증·조합원·출자·세무·등기 차이. 부산·경남 농업법인 선택 — 다옴법무사.",
    h1: "농업회사법인 vs 영농조합법인 — 사업 구조로 선택하세요",
    eyebrow: "농업법인 · 비교",
    heroIntro:
      "둘 다 농업 사업 법인이지만 근거 법률·조합원 구조·인증 절차가 다릅니다.",
    heroParagraphs: [
      "농업회사법인은 농업회사법인육성법, 영농조합법인은 농업협동조합법 체계입니다. 세제·농지 관련 사항은 등기와 별도입니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "조합 기반·조합원 중심이면 영농조합법인, 출자자·회사형 구조면 농업회사법인을 검토합니다.",
    primaryKeyword: "농업회사법인과 영농조합법인 차이",
    secondaryKeywords: ["농업법인 종류", "영농조합 vs 농업회사"],
    questionKeywords: ["농업법인 뭐가 다름"],
    searchIntent: "농업 관련 법인 유형을 비교하려는 검색",
    whoNeedsThis: ["농업 사업 법인화를 검토하는 농업인"],
    whenAndDeadline: ["유형별 인증·인가 후 등기"],
    decisionBodies: ["발기인·조합원총회"],
    documents: ["유형별 인증·정관"],
    procedures: ["유형 선택", "인증·인가", "등기"],
    costFactors: ["출자·조합원 구조"],
    penaltyRisks: ["유형 오선택"],
    commonConfusions: ["이름만 보고 선택"],
    diyErrors: ["조합원 없이 영농조합법인 시도"],
    faqs: [],
    relatedLinks: [
      { href: "/부산농업회사법인설립", label: "농업회사법인" },
      { href: "/영농조합법인설립", label: "영농조합법인" },
      { href: "/농어업법인설립등기", label: "농·어업 허브" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "농업법인 유형 상담",
    ctaText: "사업 구조와 참여자 구성을 알려주세요.",
    comparisonSummary: [
      "농업회사법인: 농림부 인증, 회사형 출자",
      "영농조합법인: 농협법 체계, 조합원 기반",
    ],
    comparisonPoints: [
      { aspect: "근거 법률", optionA: "농업회사법인육성법", optionB: "농업협동조합법" },
      { aspect: "설립 방식", optionA: "농림부 장관 인증 후 등기", optionB: "조합원총회·인가 후 등기" },
      { aspect: "구성", optionA: "출자자·주주형", optionB: "조합원·조합형" },
      { aspect: "적합 사업", optionA: "가공·유통·스마트팜·체험", optionB: "조합 기반 영농·공동사업" },
      { aspect: "세제·농지", optionA: "별도 법령 확인", optionB: "별도 법령 확인" },
    ],
  },
  {
    slug: "사회적협동조합과사단법인차이",
    kind: "comparison",
    title: "사회적협동조합과 사단법인 차이",
    metaTitle: "사회적협동조합과 사단법인 차이｜조합원 사업 vs 회원 단체",
    metaDescription:
      "사회적협동조합 vs 사단법인. 인가·회원·수익·의사결정·등기 비교 — 다옴법무사.",
    h1: "사회적협동조합 vs 사단법인 — 무엇이 다른가요",
    eyebrow: "법인 유형 · 비교",
    heroIntro:
      "사회적협동조합은 조합원 공동 사업, 사단법인은 회원 단체 운영에 가깝습니다.",
    heroParagraphs: [
      "사회적협동조합은 행안부 인가, 사단법인은 주무관청 허가 후 등기합니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "공동 사업·조합원 배당 구조면 사회적협동조합, 협회·단체·회원 모임이면 사단법인을 검토합니다.",
    primaryKeyword: "사회적협동조합과 사단법인 차이",
    secondaryKeywords: ["사회적협동조합 사단법인", "협동조합 단체 비교"],
    questionKeywords: ["사회적협동조합 단체 차이"],
    searchIntent: "사회적협동조합과 사단법인 중 선택하려는 검색",
    whoNeedsThis: ["마을기업·돌봄·문화 단체 설립자"],
    whenAndDeadline: ["유형별 인가·허가 후 등기"],
    decisionBodies: ["조합원·회원 총회"],
    documents: ["유형별 정관"],
    procedures: ["유형 선택", "인가·허가", "등기"],
    costFactors: ["조합원·회원 수"],
    penaltyRisks: ["유형 오선택"],
    commonConfusions: ["사회적기업=사회적협동조합"],
    diyErrors: ["인가 없이 운영"],
    faqs: [],
    relatedLinks: [
      { href: "/부산사회적협동조합설립", label: "사회적협동조합" },
      { href: "/부산사단법인설립", label: "사단법인" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "법인 유형 선택 상담",
    ctaText: "단체 목적·참여 방식을 알려주세요.",
    comparisonPoints: [
      { aspect: "근거 법률", optionA: "사회적협동조합법", optionB: "민법(사단법인)" },
      { aspect: "설립", optionA: "행안부 장관 인가", optionB: "주무관청 허가" },
      { aspect: "구성", optionA: "조합원·공동사업", optionB: "회원·단체" },
      { aspect: "수익", optionA: "조합원 배당·공동이익", optionB: "비영리·잉여금 제한" },
      { aspect: "적합", optionA: "공동 사업·마을기업", optionB: "협회·학회·단체" },
    ],
  },
  {
    slug: "협동조합과주식회사차이",
    kind: "comparison",
    title: "협동조합과 주식회사 차이",
    metaTitle: "협동조합과 주식회사 차이｜조합원 vs 주주 구조",
    metaDescription:
      "협동조합 vs 주식회사(유한회사). 출자·의결권·배당·설립 절차 비교 — 다옴법무사.",
    h1: "협동조합 vs 주식회사 — 출자와 의사결정 구조",
    eyebrow: "법인 유형 · 비교",
    heroIntro:
      "협동조합은 조합원 1인 1표, 주식회사는 주식 비율에 따른 의결권이 원칙입니다.",
    heroParagraphs: [
      "소상공인·프리랜서·지역사업은 협동조합, 투자·지분 거래는 주식회사가 일반적입니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "공동 사업·민주적 운영이면 협동조합, 투자·지분 거래·스케일업이면 주식회사를 검토합니다.",
    primaryKeyword: "협동조합과 주식회사 차이",
    secondaryKeywords: ["협동조합 주식회사", "조합 법인 비교"],
    questionKeywords: ["협동조합 회사 차이"],
    searchIntent: "협동조합과 주식회사 중 선택하려는 검색",
    whoNeedsThis: ["창업·사업자 법인 형태 선택"],
    whenAndDeadline: ["협동조합: 창립총회 후 2주", "주식회사: 설립등기"],
    decisionBodies: ["조합원총회 vs 주주총회"],
    documents: ["정관"],
    procedures: ["유형 선택", "설립"],
    costFactors: ["출자 구조"],
    penaltyRisks: ["형태 오선택"],
    commonConfusions: ["협동조합도 주식 발행"],
    diyErrors: ["목적에 맞지 않는 형태"],
    faqs: [],
    relatedLinks: [
      { href: "/부산협동조합설립등기", label: "협동조합" },
      { href: "/부산법인설립등기", label: "주식회사 설립" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "법인 형태 선택 상담",
    ctaText: "사업 목적과 참여자 구조를 알려주세요.",
    comparisonPoints: [
      { aspect: "근거 법률", optionA: "협동조합기본법", optionB: "상법" },
      { aspect: "의결권", optionA: "1인 1표(원칙)", optionB: "주식 비율" },
      { aspect: "설립", optionA: "창립총회 후 2주 이내", optionB: "발기·설립등기" },
      { aspect: "수익 배분", optionA: "조합원 거래·배당 규칙", optionB: "주주 배당" },
      { aspect: "적합", optionA: "공동 사업·상생", optionB: "투자·성장·M&A" },
    ],
  },
  {
    slug: "사회적기업과사회적협동조합차이",
    kind: "comparison",
    title: "사회적기업과 사회적협동조합 차이",
    metaTitle: "사회적기업과 사회적협동조합 차이｜인증 vs 법인 설립",
    metaDescription:
      "사회적기업 인증 vs 사회적협동조합 설립. 법인 설립과 인증·지정 구분 — 다옴법무사.",
    h1: "사회적기업 vs 사회적협동조합 — 인증과 법인을 구분하세요",
    eyebrow: "사회적경제 · 비교",
    heroIntro:
      "사회적기업은 인증·지정 제도이고, 사회적협동조합은 별도 법인 유형입니다.",
    heroParagraphs: [
      "주식회사·협동조합 등으로 먼저 법인을 설립한 뒤 사회적기업 인증을 받는 경우가 많습니다. 사회적협동조합은 법인 설립 자체가 목적에 맞는 형태일 수 있습니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "법인 형태를 먼저 정하고, 사회적기업 인증 필요 여부는 별도로 검토하세요. 인증은 등기와 별개입니다.",
    primaryKeyword: "사회적기업과 사회적협동조합 차이",
    secondaryKeywords: ["사회적기업 인증", "사회적협동조합 비교"],
    questionKeywords: ["사회적기업 협동조합 차이"],
    searchIntent: "사회적기업과 사회적협동조합을 구분하려는 검색",
    whoNeedsThis: ["사회적 목적 사업 창업자"],
    whenAndDeadline: ["법인 설립 후 인증 신청(사회적기업)"],
    decisionBodies: ["해당 없음(비교 페이지)"],
    documents: ["법인 설립 서류 vs 인증 신청 서류"],
    procedures: ["법인 선택", "설립·인가", "인증(선택)"],
    costFactors: ["법인 유형", "인증 유지"],
    penaltyRisks: ["인증=설립 완료 오인"],
    commonConfusions: ["사회적기업=법인 종류"],
    diyErrors: ["인증만 받고 법인 미설립"],
    faqs: [],
    relatedLinks: [
      { href: "/부산사회적협동조합설립", label: "사회적협동조합" },
      { href: "/부산협동조합설립등기", label: "협동조합" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "사회적경제 법인 상담",
    ctaText: "사업 목적과 참여 구조를 알려주세요.",
    comparisonPoints: [
      { aspect: "성격", optionA: "사회적기업: 인증·지정", optionB: "사회적협동조합: 법인 유형" },
      { aspect: "근거", optionA: "사회적기업 육성법 등", optionB: "사회적협동조합법" },
      { aspect: "절차", optionA: "법인 설립 후 인증 신청", optionB: "인가 후 법인 설립등기" },
      { aspect: "법무사", optionA: "등기(설립 법인 기준)", optionB: "인가 후 설립등기" },
      { aspect: "적합", optionA: "기존·신규 법인의 인증", optionB: "조합원 공동 사업" },
    ],
  },
  {
    slug: "사단법인과협동조합차이",
    kind: "comparison",
    title: "사단법인과 협동조합 차이",
    metaTitle: "사단법인과 협동조합 차이｜회원 단체 vs 조합원 사업",
    metaDescription:
      "사단법인 vs 협동조합. 회원·조합원·수익·설립 절차 비교 — 다옴법무사.",
    h1: "사단법인 vs 협동조합 — 단체와 사업의 구분",
    eyebrow: "법인 유형 · 비교",
    heroIntro:
      "사단법인은 회원 단체, 협동조합은 조합원이 공동으로 사업을 하는 법인입니다.",
    heroParagraphs: [
      "협회·학회는 사단법인, 공동 사업·소상공인 연대는 협동조합이 검토 대상입니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "회원 모임·협회 목적이면 사단법인, 조합원 공동 사업이면 협동조합을 검토합니다.",
    primaryKeyword: "사단법인과 협동조합 차이",
    secondaryKeywords: ["사단법인 협동조합", "단체 법인 비교"],
    questionKeywords: ["사단법인 협동조합 뭐가 다름"],
    searchIntent: "사단법인과 협동조합을 비교하려는 검색",
    whoNeedsThis: ["단체·사업자 법인 형태 선택"],
    whenAndDeadline: ["사단: 허가 후 3주", "협동: 창립총회 후 2주"],
    decisionBodies: ["총회·창립총회"],
    documents: ["정관"],
    procedures: ["유형 선택", "설립"],
    costFactors: ["회원·조합원 수"],
    penaltyRisks: ["유형 오선택"],
    commonConfusions: ["협회=협동조합"],
    diyErrors: ["협회를 협동조합으로 설립"],
    faqs: [],
    relatedLinks: [
      SPECIAL_ENTITY_HUB_LINKS.association,
      { href: "/부산협동조합설립등기", label: "협동조합" },
      SPECIAL_ENTITY_HUB_LINKS.compareAssociationFoundation,
      ...baseSpecialRelated,
    ],
    ctaTitle: "법인 유형 선택 상담",
    ctaText: "단체 목적과 사업 여부를 알려주세요.",
    comparisonPoints: [
      { aspect: "근거", optionA: "민법(사단법인)", optionB: "협동조합기본법" },
      { aspect: "설립", optionA: "주무관청 허가", optionB: "창립총회(인가 없음)" },
      { aspect: "구성", optionA: "회원", optionB: "조합원·출자" },
      { aspect: "목적", optionA: "단체·협회 운영", optionB: "공동 사업" },
      { aspect: "등기 기한", optionA: "허가 후 3주", optionB: "창립총회 후 2주" },
    ],
  },
];
