import type { SpecialEntityPageContent } from "../types";
import {
  SPECIAL_ENTITY_HUB_LINKS,
  SPECIAL_ENTITY_OFFICE_LINE,
  SPECIAL_ENTITY_SCOPE_NOTICE,
  baseSpecialRelated,
} from "./shared";

export const phase2SectorPages: SpecialEntityPageContent[] = [
  {
    slug: "문화예술단체사단법인설립",
    kind: "intent",
    title: "문화예술단체 사단법인 설립",
    metaTitle: "문화예술단체 사단법인 설립｜예술인 협회·단체 법인화",
    metaDescription:
      "문화예술단체·예술인 협회 사단법인 설립. 주무관청 허가·창립총회·설립등기 — 다옴법무사.",
    h1: "문화예술단체 사단법인 — 공연·창작·전시 단체의 법인화",
    eyebrow: "문화예술 · 사단법인",
    heroIntro:
      "공연·음악·미술·문학·영상 등 문화예술 분야 단체는 사단법인으로 법인화하는 경우가 많습니다.",
    heroParagraphs: [
      "문화체육관광부·지자체·교육청 등 목적에 따른 주무관청 허가 후 설립등기합니다. 부산은 문화예술 인프라가 풍부해 협회·단체 설립 문의가 있습니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "문화예술단체 사단법인은 민법상 비영리 사단법인으로, 주무관청 허가 후 3주 이내 설립등기가 필요합니다.",
    primaryKeyword: "문화예술단체 사단법인 설립",
    secondaryKeywords: [
      "예술인 협회 법인",
      "공연예술단체 법인화",
      "문화단체 사단법인",
      "부산 문화예술단체",
    ],
    questionKeywords: ["문화단체 법인 설립", "예술협회 사단법인"],
    searchIntent: "문화예술 단체의 사단법인 설립을 확인하려는 검색",
    whoNeedsThis: ["예술인 협회·창작단체·공연단체"],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["창립총회", "주무관청"],
    documents: ["허가서", "정관", "회원 명부", "의사록"],
    procedures: ["허가", "창립총회", "등기"],
    costFactors: ["회원·임원 규모"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["예술단체 등록과 법인 혼동"],
    diyErrors: ["수익 배분 조항 오류"],
    faqs: [],
    relatedLinks: [
      { href: "/부산사단법인설립", label: "부산 사단법인 설립" },
      SPECIAL_ENTITY_HUB_LINKS.association,
      ...baseSpecialRelated,
    ],
    ctaTitle: "문화예술단체 법인 설립 상담",
    ctaText: "단체 목적과 회원 구성을 알려주세요.",
  },
  {
    slug: "체육단체사단법인설립",
    kind: "intent",
    title: "체육단체 사단법인 설립",
    metaTitle: "체육단체 사단법인 설립｜종목·생활체육 협회 법인화",
    metaDescription:
      "체육단체·종목협회·생활체육단체 사단법인 설립. 허가·정관·등기 — 다옴법무사.",
    h1: "체육단체 사단법인 — 종목·지역 체육 협회 설립",
    eyebrow: "체육 · 사단법인",
    heroIntro:
      "종목별 협회·생활체육단체·스포츠클럽 연합 등은 사단법인 형태로 설립할 수 있습니다.",
    heroParagraphs: [
      "문화체육관광부·시·도·구 체육 관련 주무관청 허가가 필요할 수 있습니다. 부산은 해양·생활체육·종목 단체 수요가 있습니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "체육단체 사단법인은 주무관청 허가 후 설립등기합니다. 대한체육회·종목단체 체계와의 관계는 별도 확인이 필요합니다.",
    primaryKeyword: "체육단체 사단법인 설립",
    secondaryKeywords: ["종목협회 법인", "생활체육단체 법인화", "스포츠클럽 법인"],
    questionKeywords: ["체육협회 법인 설립"],
    searchIntent: "체육 단체 사단법인 설립을 확인하려는 검색",
    whoNeedsThis: ["종목·지역 체육 협회", "생활체육 단체"],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["창립총회"],
    documents: ["허가서", "정관", "회원 명부"],
    procedures: ["허가", "등기"],
    costFactors: ["회원 규모"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["체육회 산하 단체와 독립 법인"],
    diyErrors: ["정관 목적 불명확"],
    faqs: [],
    relatedLinks: [
      { href: "/부산사단법인설립", label: "부산 사단법인" },
      { href: "/협회사단법인설립", label: "협회 사단법인" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "체육단체 법인 설립 상담",
    ctaText: "종목·회원 구조를 알려주시면 허가·등기 단계를 확인할 수 있습니다.",
  },
  {
    slug: "환경단체사단법인설립",
    kind: "intent",
    title: "환경단체 사단법인 설립",
    metaTitle: "환경보호단체 사단법인 설립｜환경·생태 단체 법인화",
    metaDescription:
      "환경보호·생태·기후 단체 사단법인 설립. 비영리 목적·허가·등기 — 다옴법무사.",
    h1: "환경단체 사단법인 — 환경·생태 목적 단체의 법인화",
    eyebrow: "환경 · 사단법인",
    heroIntro: "환경보호·생태계 보전·기후·재활용 등 목적의 단체는 사단법인으로 설립할 수 있습니다.",
    heroParagraphs: ["주무관청은 사업 목적에 따라 환경·지자체·교육 관련 부서로 달라집니다."],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion: "환경단체 사단법인은 민법상 비영리 사단법인 설립 절차를 따릅니다.",
    primaryKeyword: "환경단체 사단법인 설립",
    secondaryKeywords: ["환경보호단체 법인", "생태단체 법인화", "환경 NGO 법인"],
    questionKeywords: ["환경단체 법인 만들기"],
    searchIntent: "환경 단체 사단법인 설립을 확인하려는 검색",
    whoNeedsThis: ["환경·생태·동물보호 연계 단체"],
    whenAndDeadline: ["허가 후 3주 이내"],
    decisionBodies: ["창립총회"],
    documents: ["허가서", "정관"],
    procedures: ["허가", "등기"],
    costFactors: ["회원·임원"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["비영리민간단체와 혼동"],
    diyErrors: ["정관 목적 과도"],
    faqs: [],
    relatedLinks: [
      { href: "/부산사단법인설립", label: "사단법인 설립" },
      SPECIAL_ENTITY_HUB_LINKS.compareNgoAssociation,
      ...baseSpecialRelated,
    ],
    ctaTitle: "환경단체 법인 설립 상담",
    ctaText: "단체 목적을 알려주시면 적합한 설립 절차를 확인할 수 있습니다.",
  },
  {
    slug: "복지단체사단법인설립",
    kind: "intent",
    title: "복지단체 사단법인 설립",
    metaTitle: "복지단체 사단법인 설립｜사회복지법인과 구분",
    metaDescription:
      "복지·자선·지역복지 단체 사단법인 vs 사회복지법인. 목적별 법인 선택 — 다옴법무사.",
    h1: "복지단체 사단법인 — 사회복지법인과 언제 다른가요",
    eyebrow: "복지 · 사단법인",
    heroIntro:
      "일반 복지·자선·지역봉사 단체는 사단법인이 해당될 수 있고, 사회복지사업 시설 운영은 사회복지법인이 해당될 수 있습니다.",
    heroParagraphs: [
      "목적·사업 범위에 따라 법인 유형이 달라집니다. 잘못된 유형 선택은 이후 인가·세무에서 문제가 될 수 있습니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "복지 목적이지만 사회복지사업법상 사업이 아니면 사단법인을, 시설·사회복지사업이면 사회복지법인을 검토합니다.",
    primaryKeyword: "복지단체 사단법인 설립",
    secondaryKeywords: ["복지단체 법인화", "자선단체 사단법인", "지역복지 단체"],
    questionKeywords: ["복지단체 법인 설립", "사회복지법인 차이"],
    searchIntent: "복지 단체의 법인 유형을 선택하려는 검색",
    whoNeedsThis: ["복지·자선·지역돌봄 단체"],
    whenAndDeadline: ["유형별 허가·인가 후 등기"],
    decisionBodies: ["창립총회·설립위원회"],
    documents: ["허가·인가서", "정관"],
    procedures: ["유형 선택", "허가·인가", "등기"],
    costFactors: ["법인 유형", "시설 여부"],
    penaltyRisks: ["유형 오선택"],
    commonConfusions: ["사회복지법인=사단법인"],
    diyErrors: ["시설 운영인데 사단법인만 설립"],
    faqs: [
      {
        question: "사회복지법인이 필요한 경우는?",
        answer:
          "사회복지사업법상 사회복지사업·시설 운영이 주된 목적이면 사회복지법인을 검토합니다. `/사회복지법인설립등기`를 참고하세요.",
      },
    ],
    relatedLinks: [
      { href: "/사회복지법인설립등기", label: "사회복지법인" },
      { href: "/부산사단법인설립", label: "사단법인 설립" },
      ...baseSpecialRelated,
    ],
    ctaTitle: "복지단체 법인 유형 상담",
    ctaText: "단체가 하는 사업 내용을 알려주시면 사단·사회복지 중 적합한 형태를 함께 검토할 수 있습니다.",
  },
];
