import type { SpecialEntityPageContent } from "../types";
import {
  SPECIAL_ENTITY_HUB_LINKS,
  SPECIAL_ENTITY_OFFICE_LINE,
  SPECIAL_ENTITY_SCOPE_NOTICE,
  baseSpecialRelated,
} from "./shared";

const specialLawRelated = [
  { href: "/특별법법인설립등기", label: "특별법 법인 설립 허브" },
  ...baseSpecialRelated,
];

export const phase2SpecialLawPages: SpecialEntityPageContent[] = [
  {
    slug: "사회복지법인설립등기",
    kind: "intent",
    title: "사회복지법인 설립등기",
    metaTitle: "사회복지법인 설립등기｜시·도지사 인가 후 1월 이내 등기",
    metaDescription:
      "사회복지법인 설립인가·기본재산·시설·정관, 인가 후 1월 이내 설립등기. 행정과 등기 구분 — 다옴법무사.",
    h1: "사회복지법인 설립등기 — 인가와 등기는 별도 단계입니다",
    eyebrow: "사회복지법인 · 설립",
    heroIntro:
      "사회복지법인은 사회복지사업을 수행하기 위해 사회복지법에 따라 설립되는 법인입니다.",
    heroParagraphs: [
      "시·도지사의 설립인가를 받은 후 1월 이내에 설립등기를 해야 합니다(사회복지법 제12조). 사회복지사업의 종류·시설·기본재산·임원 요건은 인가 단계에서 먼저 검토됩니다.",
      "법무사는 인가 이후 설립등기·변경등기 서류 작성·접수를 지원합니다. 시설 인허가·사업 계획 심사는 행정 절차입니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "사회복지법인 설립은 관할 시·도지사 설립인가 후 1월 이내 설립등기가 필요합니다. 부산 소재 법인은 부산광역시장 인가·부산 관할 등기소 접수가 원칙입니다.",
    primaryKeyword: "사회복지법인 설립등기",
    secondaryKeywords: [
      "사회복지법인 설립인가",
      "사회복지법인 정관",
      "사회복지법인 기본재산",
      "복지법인 설립",
    ],
    questionKeywords: [
      "사회복지법인 설립 절차",
      "사회복지법인 등기 기한",
      "사회복지법인 주무관청",
    ],
    searchIntent: "사회복지법인 설립 인가 후 등기 절차를 확인하려는 검색",
    whoNeedsThis: [
      "사회복지시설·복지단체 법인 설립",
      "인가를 받고 등기만 남은 발기인",
      "기본재산·시설 요건을 점검 중인 단체",
    ],
    whenAndDeadline: ["설립인가일부터 1월 이내 설립등기(사회복지법 제12조)"],
    decisionBodies: ["설립발기인·이사회·총회(정관)"],
    documents: [
      "설립인가서",
      "정관",
      "기본재산 목록·증빙",
      "시설 관련 증빙(해당 시)",
      "임원 취임승낙서·인감증명서",
      "주사무소·시설 사용권 증빙",
    ],
    procedures: [
      "사업계획·시설·기본재산 검토",
      "설립인가 신청",
      "인가 후 설립등기",
      "시설 개설·운영 신고(별도 행정)",
    ],
    costFactors: ["기본재산 가액", "시설 수", "임원 수"],
    penaltyRisks: ["인가 후 등기 기한 경과", "기본재산 미이전"],
    commonConfusions: [
      "사단법인과 동일 절차로 가정",
      "시설 인허가=설립 완료로 오인",
    ],
    anonymousCase:
      "부산 소재 노인복지시설 설립 단체가 인가 후 정관·기본재산 증빙 정리가 지연되어 등기 기한이 임박했습니다. 인가서·정관 대조 후 설립등기를 완료했습니다.",
    diyErrors: ["인가 전 등기", "기본재산 목록 누락", "시설 주소 불일치"],
    faqs: [
      {
        question: "사회복지법인과 사단법인 중 무엇을 선택하나요?",
        answer:
          "사회복지사업을 주된 목적으로 하면 사회복지법인이 해당될 수 있습니다. 일반 협회·단체 목적이면 사단법인을 검토합니다.",
      },
    ],
    relatedLinks: [
      { href: "/부산사회복지법인등기", label: "부산 사회복지법인 등기" },
      { href: "/사회복지법인임원변경등기", label: "사회복지법인 임원변경" },
      ...specialLawRelated,
    ],
    ctaTitle: "사회복지법인 설립등기 상담",
    ctaText: "설립인가서가 준비되어 있다면 등기 서류부터 검토할 수 있습니다.",
    legalProfile: {
      entityName: "사회복지법인",
      legalBasis: ["사회복지법"],
      establishmentMethod: "시·도지사 설립인가 후 설립등기",
      competentAuthority: [
        "설립인가: 관할 시·도지사(부산: 부산광역시장)",
        "등기: 주사무소 관할 등기소",
      ],
      preRegistrationSteps: [
        "사업계획·시설·기본재산 준비",
        "설립인가 신청",
        "임원 구성",
      ],
      registrationDeadline: "설립인가일부터 1월 이내(제12조)",
      registrableMatters: ["목적·명칭·주사무소·기본재산·임원"],
      lawyerScope: ["인가 후 설립·변경·해산 등기"],
      excludedScope: ["설립인가 대리 보장", "시설 인허가", "세무"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["부산 소재 → 부산광역시장 인가, 부산지방법원 등기국 등"],
    },
  },
  {
    slug: "부산사회복지법인등기",
    kind: "intent",
    title: "부산 사회복지법인 등기",
    metaTitle: "부산 사회복지법인 등기｜설립·임원변경·주사무소 이전",
    metaDescription:
      "부산 소재 사회복지법인 설립등기·임원변경·주사무소 이전·해산. 부산광역시장 인가와 등기 순서 — 다옴법무사.",
    h1: "부산 사회복지법인 등기 — 시장 인가와 등기소 관할을 확인하세요",
    eyebrow: "부산 · 사회복지법인",
    heroIntro:
      "부산에 주사무소·시설을 두는 사회복지법인은 부산광역시장의 설립인가·변경인가 후 관할 등기소에 등기합니다.",
    heroParagraphs: [
      "부산에서는 노인·장애인·아동·지역복지 시설 관련 사회복지법인 설립·변경 문의가 있습니다. 인가·허가와 등기를 분리해 이해하는 것이 중요합니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "부산 사회복지법인은 부산광역시장 인가 후 부산 관할 등기소에 설립·변경등기를 합니다. 법무사는 등기 단계를 지원합니다.",
    primaryKeyword: "부산 사회복지법인 등기",
    secondaryKeywords: [
      "부산 사회복지법인 설립",
      "부산 복지법인 등기",
      "부산 사회복지법인 인가",
    ],
    questionKeywords: ["부산 사회복지법인 설립", "부산 복지법인 등기"],
    searchIntent: "부산에서 사회복지법인 등기를 의뢰하려는 검색",
    whoNeedsThis: [
      "부산 소재 사회복지시설 설립",
      "부산 복지법인 임원·주소 변경",
    ],
    whenAndDeadline: ["인가 후 1월 이내 설립등기"],
    decisionBodies: ["이사회·총회", "시장 변경인가(해당 항목)"],
    documents: ["인가서", "정관", "의사록", "임원 서류"],
    procedures: ["인가", "등기", "운영 중 변경등기"],
    costFactors: ["기본재산", "변경 항목"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["구청 vs 시장 관할 혼동"],
    diyErrors: ["변경인가 전 등기"],
    faqs: [
      {
        question: "전국 단위 복지법인도 부산에서 등기하나요?",
        answer: "주사무소 소재지 관할 등기소에 접수합니다.",
      },
    ],
    relatedLinks: [
      { href: "/사회복지법인설립등기", label: "사회복지법인 설립등기" },
      { href: "/사회복지법인임원변경등기", label: "임원변경등기" },
      ...specialLawRelated,
    ],
    ctaTitle: "부산 사회복지법인 등기 상담",
    ctaText: "인가서·등기사항증명서를 기준으로 필요한 등기를 확인할 수 있습니다.",
    legalProfile: {
      entityName: "사회복지법인(부산)",
      legalBasis: ["사회복지법"],
      establishmentMethod: "부산광역시장 설립인가 후 설립등기",
      competentAuthority: ["부산광역시장", "부산지방법원 등기국 등"],
      preRegistrationSteps: ["인가 신청", "임원·시설·기본재산"],
      registrationDeadline: "인가일부터 1월 이내",
      registrableMatters: ["설립·변경·해산 등기사항"],
      lawyerScope: ["등기 서류·접수"],
      excludedScope: ["인가 신청", "시설 인허가"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["부산 복지시설·지역단체 수요"],
    },
  },
  {
    slug: "사회복지법인임원변경등기",
    kind: "intent",
    title: "사회복지법인 임원변경등기",
    metaTitle: "사회복지법인 임원변경등기｜취임·사임·이사회 결의 후 등기",
    metaDescription:
      "사회복지법인 이사·이사장·감사 변경등기. 변경인가·결의 후 등기 순서 — 다옴법무사.",
    h1: "사회복지법인 임원변경등기 — 변경인가와 등기 순서를 확인하세요",
    eyebrow: "사회복지법인 · 변경",
    heroIntro: "사회복지법인 임원 변경도 취임·사임 등기가 필요하며, 일부는 시·도지사 변경인가가 선행됩니다.",
    heroParagraphs: [
      "이사장·이사·감사 교체 시 의사록·취임승낙서·사임서를 준비하고, 정관·법률에 따른 변경인가 후 등기합니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "사회복지법인 임원변경은 결의·변경인가(해당 시) 후 등기 기한 내 접수해야 합니다.",
    primaryKeyword: "사회복지법인 임원변경등기",
    secondaryKeywords: ["사회복지법인 이사 변경", "복지법인 대표 변경"],
    questionKeywords: ["사회복지법인 임원 바뀌면"],
    searchIntent: "사회복지법인 임원 변경 등기를 확인하려는 검색",
    whoNeedsThis: ["이사·이사장이 교체된 사회복지법인"],
    whenAndDeadline: ["결의·인가 후 등기 기한 적용"],
    decisionBodies: ["이사회·총회", "시·도지사 변경인가"],
    documents: ["등기부", "정관", "의사록", "인가서", "취임·사임 서류"],
    procedures: ["결의·인가", "등기"],
    costFactors: ["사임·취임 동시 여부"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["비영리법인 임원변경과 동일 가정"],
    diyErrors: ["인가 전 등기"],
    faqs: [],
    relatedLinks: [
      { href: "/비영리법인임원변경등기", label: "비영리법인 임원변경" },
      { href: "/사회복지법인설립등기", label: "사회복지법인 설립" },
      ...specialLawRelated,
    ],
    ctaTitle: "사회복지법인 임원변경 상담",
    ctaText: "등기사항증명서를 보내주시면 필요한 등기를 확인할 수 있습니다.",
  },
  {
    slug: "사회복지법인해산청산등기",
    kind: "intent",
    title: "사회복지법인 해산·청산등기",
    metaTitle: "사회복지법인 해산·청산등기｜결의·인가·청산인 등기",
    metaDescription:
      "사회복지법인 해산·청산 절차와 등기. 시·도지사 보고·인가, 청산인 선임등기 — 다옴법무사.",
    h1: "사회복지법인 해산·청산 — 행정 보고와 등기를 순서대로",
    eyebrow: "사회복지법인 · 해산",
    heroIntro: "사회복지법인 해산은 총회 결의·시·도지사 보고·인가 후 해산등기·청산 절차가 이어집니다.",
    heroParagraphs: [
      "시설 폐지·사업 종료 시 잔여재산 처리·사회복지사업 승계 등을 인가 단계에서 함께 검토해야 합니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "해산·청산은 결의·인가·해산등기·청산인 등기·청산종결등기 순으로 진행됩니다. 법무사는 등기 단계를 지원합니다.",
    primaryKeyword: "사회복지법인 해산 청산등기",
    secondaryKeywords: ["복지법인 해산", "사회복지법인 청산"],
    questionKeywords: ["사회복지법인 폐지 절차"],
    searchIntent: "사회복지법인 해산·청산 등기 절차를 확인하려는 검색",
    whoNeedsThis: ["사업 종료·합병을 검토하는 사회복지법인"],
    whenAndDeadline: ["결의·인가 후 해산등기"],
    decisionBodies: ["총회", "시·도지사"],
    documents: ["해산 결의록", "인가·보고 서류", "청산인 서류"],
    procedures: ["해산 결의", "인가·보고", "해산등기", "청산", "청산종결"],
    costFactors: ["잔여재산", "채권·채무 정리"],
    penaltyRisks: ["청산 절차 누락"],
    commonConfusions: ["시설 폐업=해산 완료로 오인"],
    diyErrors: ["해산등기 없이 운영 중단"],
    faqs: [],
    relatedLinks: [
      { href: "/비영리법인해산청산등기", label: "비영리법인 해산·청산" },
      ...specialLawRelated,
    ],
    ctaTitle: "사회복지법인 해산·청산 상담",
    ctaText: "해산 결의·인가 단계를 알려주시면 등기 순서를 확인할 수 있습니다.",
  },
  {
    slug: "학교법인설립등기",
    kind: "intent",
    title: "학교법인 설립등기",
    metaTitle: "학교법인 설립등기｜교육감 인가·정관·기본재산 후 등기",
    metaDescription:
      "학교법인 설립인가·기본재산·이사회, 인가 후 설립등기. 사립학교·유치원 법인화 — 다옴법무사.",
    h1: "학교법인 설립등기 — 교육감 인가가 먼저입니다",
    eyebrow: "학교법인 · 설립",
    heroIntro:
      "학교법인은 사립학교를 설립·경영하기 위한 법인으로, 학교법·민법에 따라 교육감 인가 후 설립등기합니다.",
    heroParagraphs: [
      "기본재산·정관·이사·감사 구성, 학교 설립 계획이 인가 심사의 핵심입니다. 인가 후 정해진 기한 내 설립등기를 해야 합니다.",
      "학교 운영 인허가·교육과정·시설 기준은 교육 행정 영역이며, 법무사는 등기와 관련 서류를 지원합니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "학교법인 설립은 관할 교육감 설립인가 후 설립등기가 필요합니다. 부산 소재 학교법인은 부산광역시교육감 관할이 원칙입니다.",
    primaryKeyword: "학교법인 설립등기",
    secondaryKeywords: [
      "학교법인 설립인가",
      "사립학교 법인",
      "학교법인 정관",
      "학교법인 기본재산",
    ],
    questionKeywords: ["학교법인 설립 절차", "학교법인 등기"],
    searchIntent: "학교법인 설립·등기 절차를 확인하려는 검색",
    whoNeedsThis: [
      "사립학교·유치원·대안학교 설립",
      "학교 설립인가 후 등기 준비",
    ],
    whenAndDeadline: ["설립인가 후 법정 기한 내 설립등기(학교법·시행령 확인)"],
    decisionBodies: ["설립위원회·이사회", "교육감"],
    documents: ["설립인가서", "정관", "기본재산 증빙", "임원 서류", "학교 설립 계획"],
    procedures: ["설립인가 신청", "인가 후 설립등기", "학교 설립(별도 행정)"],
    costFactors: ["기본재산", "학교 유형"],
    penaltyRisks: ["등기 기한 경과"],
    commonConfusions: ["학교 설립 인가=학교법인 완료로 오인"],
    diyErrors: ["인가 전 등기", "기본재산 미확보"],
    faqs: [
      {
        question: "학원도 학교법인으로 설립하나요?",
        answer:
          "학원은 학원법상 별도 제도입니다. 학교법인은 학교법상 학교 설립과 연계됩니다.",
      },
    ],
    relatedLinks: [
      { href: "/부산학교법인등기", label: "부산 학교법인 등기" },
      { href: "/학교법인임원변경등기", label: "학교법인 임원변경" },
      ...specialLawRelated,
    ],
    ctaTitle: "학교법인 설립등기 상담",
    ctaText: "설립인가서가 있다면 등기 서류 검토가 가능합니다.",
    legalProfile: {
      entityName: "학교법인",
      legalBasis: ["학교법", "민법(비영리법인)"],
      establishmentMethod: "교육감 설립인가 후 설립등기",
      competentAuthority: [
        "설립인가: 관할 교육감(부산: 부산광역시교육감)",
        "등기: 주사무소 관할 등기소",
      ],
      preRegistrationSteps: ["기본재산·정관", "설립인가", "임원 구성"],
      registrationDeadline: "설립인가 후 법정 기한(학교법·시행령)",
      registrableMatters: ["목적·기본재산·임원·주사무소"],
      lawyerScope: ["인가 후 설립·변경 등기"],
      excludedScope: ["학교 설립 인허가", "교육과정"],
      lastLegalReview: "2026-07-29",
    },
  },
  {
    slug: "부산학교법인등기",
    kind: "intent",
    title: "부산 학교법인 등기",
    metaTitle: "부산 학교법인 등기｜교육감 인가 후 설립·변경등기",
    metaDescription:
      "부산 소재 학교법인 설립등기·임원변경·기본재산 변경. 부산교육청 관할 — 다옴법무사.",
    h1: "부산 학교법인 등기 — 부산교육청 인가와 등기소 관할",
    eyebrow: "부산 · 학교법인",
    heroIntro: "부산에 주사무소·학교를 두는 학교법인은 부산광역시교육감 인가 후 부산 관할 등기소에 등기합니다.",
    heroParagraphs: [
      "사립유치원·초·중·고·대안학교 설립 관련 학교법인 등기 문의가 있습니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "부산 학교법인은 부산광역시교육감 설립·변경인가 후 등기합니다.",
    primaryKeyword: "부산 학교법인 등기",
    secondaryKeywords: ["부산 학교법인 설립", "부산 사립학교 법인"],
    questionKeywords: ["부산 학교법인 설립"],
    searchIntent: "부산 학교법인 등기를 확인하려는 검색",
    whoNeedsThis: ["부산 소재 학교 설립·운영 단체"],
    whenAndDeadline: ["인가 후 설립등기 기한"],
    decisionBodies: ["이사회", "부산광역시교육감"],
    documents: ["인가서", "정관", "임원 서류"],
    procedures: ["인가", "등기"],
    costFactors: ["기본재산", "변경 범위"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["교육청 vs 등기소 역할 혼동"],
    diyErrors: ["인가 없이 등기"],
    faqs: [],
    relatedLinks: [
      { href: "/학교법인설립등기", label: "학교법인 설립등기" },
      ...specialLawRelated,
    ],
    ctaTitle: "부산 학교법인 등기 상담",
    ctaText: "인가·등기 단계를 알려주시면 필요한 서류를 확인할 수 있습니다.",
    legalProfile: {
      entityName: "학교법인(부산)",
      legalBasis: ["학교법"],
      establishmentMethod: "부산광역시교육감 인가 후 설립등기",
      competentAuthority: ["부산광역시교육감", "부산 관할 등기소"],
      preRegistrationSteps: ["설립인가"],
      registrationDeadline: "인가 후 법정 기한",
      registrableMatters: ["설립·변경 등기사항"],
      lawyerScope: ["등기"],
      excludedScope: ["학교 설립 행정"],
      lastLegalReview: "2026-07-29",
    },
  },
  {
    slug: "학교법인임원변경등기",
    kind: "intent",
    title: "학교법인 임원변경등기",
    metaTitle: "학교법인 임원변경등기｜이사·이사장·감사 변경과 교육감 승인",
    metaDescription:
      "학교법인 이사·이사장·감사 취임·사임 등기. 교육감 승인·결의 후 등기 — 다옴법무사.",
    h1: "학교법인 임원변경등기 — 교육감 승인과 등기",
    eyebrow: "학교법인 · 변경",
    heroIntro: "학교법인 임원 변경은 이사회·총회 결의와 교육감 승인·변경인가 후 등기가 필요할 수 있습니다.",
    heroParagraphs: ["이사장·이사·감사 교체 시 정관·학교법상 요건을 함께 확인합니다."],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion: "학교법인 임원변경은 승인·결의 후 등기 기한 내 접수해야 합니다.",
    primaryKeyword: "학교법인 임원변경등기",
    secondaryKeywords: ["학교법인 이사 변경", "학교 이사장 변경등기"],
    questionKeywords: ["학교법인 임원 바뀌면"],
    searchIntent: "학교법인 임원 변경 등기를 확인하려는 검색",
    whoNeedsThis: ["이사·이사장이 교체된 학교법인"],
    whenAndDeadline: ["승인·결의 후 등기"],
    decisionBodies: ["이사회·총회", "교육감"],
    documents: ["등기부", "의사록", "승인서", "취임·사임 서류"],
    procedures: ["결의·승인", "등기"],
    costFactors: ["변경 임원 수"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["학교장=이사장 혼동"],
    diyErrors: ["승인 전 등기"],
    faqs: [],
    relatedLinks: [
      { href: "/학교법인설립등기", label: "학교법인 설립" },
      { href: "/비영리법인임원변경등기", label: "비영리법인 임원변경" },
      ...specialLawRelated,
    ],
    ctaTitle: "학교법인 임원변경 상담",
    ctaText: "결의·승인 서류를 기준으로 등기 항목을 확인할 수 있습니다.",
  },
  {
    slug: "의료법인설립등기",
    kind: "intent",
    title: "의료법인 설립등기",
    metaTitle: "의료법인 설립등기｜허가 후 1월 이내 등기·정관·출자",
    metaDescription:
      "의료법인 설립허가·정관·출자·의료기관 개설, 허가 후 1월 이내 설립등기 — 다옴법무사.",
    h1: "의료법인 설립등기 — 의료기관 허가와 법인 등기는 별개입니다",
    eyebrow: "의료법인 · 설립",
    heroIntro:
      "의료법인은 의료법에 따라 의료기관을 개설·운영하기 위한 법인으로, 설립허가 후 설립등기를 합니다.",
    heroParagraphs: [
      "보건복지부장관 또는 시·도지사의 설립허가를 받은 후 1월 이내 설립등기(의료법 제34조). 의료기관 개설 허가·의료인 자격·시설 기준은 별도 행정입니다.",
      "법무사는 허가 이후 등기 서류 작성·접수를 지원합니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "의료법인 설립은 설립허가 후 1월 이내 설립등기가 필요합니다. 부산 소재 의료법인은 부산광역시장(또는 관할 규정) 허가·부산 등기소 접수가 일반적입니다.",
    primaryKeyword: "의료법인 설립등기",
    secondaryKeywords: [
      "의료법인 설립허가",
      "병원 법인 설립",
      "의료기관 법인화",
      "의료법인 정관",
    ],
    questionKeywords: ["의료법인 설립 절차", "병원 법인 설립 등기"],
    searchIntent: "의료법인 설립·등기 절차를 확인하려는 검색",
    whoNeedsThis: [
      "병원·의원·한방·치과 등 의료기관 법인 설립",
      "설립허가 후 등기 준비",
    ],
    whenAndDeadline: ["설립허가일부터 1월 이내(의료법 제34조)"],
    decisionBodies: ["발기인·이사회", "설립허가권자"],
    documents: [
      "설립허가서",
      "정관",
      "출자·납입 증빙",
      "임원(의료인) 자격 증빙",
      "의료기관 개설 관련(별도)",
    ],
    procedures: ["설립허가", "설립등기", "의료기관 개설(별도)"],
    costFactors: ["출자금", "의료기관 규모"],
    penaltyRisks: ["등기 기한 경과"],
    commonConfusions: [
      "의료기관 개설 허가=법인 설립 완료",
      "개인 의료인과 법인 구조 혼동",
    ],
    diyErrors: ["허가 전 등기", "의료인 자격 서류 누락"],
    faqs: [
      {
        question: "의료법인과 사단법인 차이는?",
        answer:
          "의료기관 운영 목적이면 의료법인이 해당됩니다. 일반 의료 단체·협회는 사단법인일 수 있습니다.",
      },
    ],
    relatedLinks: [
      { href: "/부산의료법인등기", label: "부산 의료법인 등기" },
      { href: "/의료법인임원변경등기", label: "의료법인 임원변경" },
      { href: "/의료법인주사무소이전등기", label: "의료법인 주사무소 이전" },
      ...specialLawRelated,
    ],
    ctaTitle: "의료법인 설립등기 상담",
    ctaText: "설립허가서가 준비되었다면 등기 서류부터 검토할 수 있습니다.",
    legalProfile: {
      entityName: "의료법인",
      legalBasis: ["의료법"],
      establishmentMethod: "보건복지부장관 또는 시·도지사 설립허가 후 설립등기",
      competentAuthority: [
        "설립허가: 보건복지부장관 또는 시·도지사",
        "등기: 주사무소 관할 등기소",
      ],
      preRegistrationSteps: ["설립허가 신청", "정관·출자", "임원 구성"],
      registrationDeadline: "설립허가일부터 1월 이내(제34조)",
      registrableMatters: ["명칭·주사무소·임원·출자"],
      lawyerScope: ["허가 후 설립·변경 등기"],
      excludedScope: ["의료기관 개설 허가", "의료광고·세무"],
      lastLegalReview: "2026-07-29",
    },
  },
  {
    slug: "부산의료법인등기",
    kind: "intent",
    title: "부산 의료법인 등기",
    metaTitle: "부산 의료법인 등기｜설립·임원·주사무소 이전등기",
    metaDescription:
      "부산 소재 의료법인 설립등기·임원변경·주사무소 이전. 부산광역시장 허가와 등기 — 다옴법무사.",
    h1: "부산 의료법인 등기 — 병원·의원 법인 설립과 변경",
    eyebrow: "부산 · 의료법인",
    heroIntro:
      "부산에 의료기관·주사무소를 두는 의료법인은 관할 시장 허가 후 부산 등기소에 등기합니다.",
    heroParagraphs: [
      "부산은 종합병원·전문병원·의원·한방·치과 등 의료법인 설립·임원변경·주소 변경 수요가 있습니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "부산 의료법인은 설립허가 후 등기하고, 변경 시 허가·승인과 등기 순서를 확인해야 합니다.",
    primaryKeyword: "부산 의료법인 등기",
    secondaryKeywords: [
      "부산 병원 법인 설립",
      "부산 의료법인 설립",
      "부산 의원 법인화",
    ],
    questionKeywords: ["부산 의료법인 설립", "부산 병원 법인 등기"],
    searchIntent: "부산에서 의료법인 등기를 의뢰하려는 검색",
    whoNeedsThis: ["부산 의료기관 설립·변경"],
    whenAndDeadline: ["허가 후 1월 이내 설립등기"],
    decisionBodies: ["이사회", "시장·보건복지부(허가 권한)"],
    documents: ["허가서", "정관", "임원 서류"],
    procedures: ["허가", "등기", "변경 시 승인·등기"],
    costFactors: ["의료기관 규모", "변경 항목"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["개설 허가와 법인 등기 혼동"],
    diyErrors: ["허가 없이 등기"],
    faqs: [],
    relatedLinks: [
      { href: "/의료법인설립등기", label: "의료법인 설립등기" },
      { href: "/의료법인임원변경등기", label: "임원변경등기" },
      ...specialLawRelated,
    ],
    ctaTitle: "부산 의료법인 등기 상담",
    ctaText: "허가·등기 단계를 알려주시면 필요한 서류를 확인할 수 있습니다.",
    legalProfile: {
      entityName: "의료법인(부산)",
      legalBasis: ["의료법"],
      establishmentMethod: "설립허가 후 설립등기",
      competentAuthority: ["부산광역시장 등", "부산 관할 등기소"],
      preRegistrationSteps: ["설립허가"],
      registrationDeadline: "허가 후 1월 이내",
      registrableMatters: ["설립·변경 등기사항"],
      lawyerScope: ["등기"],
      excludedScope: ["의료기관 개설 허가"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["부산 의료기관 밀집 지역"],
    },
  },
  {
    slug: "의료법인임원변경등기",
    kind: "intent",
    title: "의료법인 임원변경등기",
    metaTitle: "의료법인 임원변경등기｜대표·이사·의료인 자격 확인",
    metaDescription:
      "의료법인 대표·이사 변경등기. 승인·결의 후 등기, 의료인 자격 — 다옴법무사.",
    h1: "의료법인 임원변경등기 — 의료인 자격과 등기를 함께 확인",
    eyebrow: "의료법인 · 변경",
    heroIntro: "의료법인 임원·대표 변경은 의료인 자격 요건과 허가·승인 후 등기가 필요합니다.",
    heroParagraphs: ["병원장·대표이사 교체 시 의사록·취임승낙서·면허 증빙을 함께 준비합니다."],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion: "의료법인 임원변경은 결의·승인 후 등기해야 하며, 의료인 자격을 갖춘 임원 요건을 확인해야 합니다.",
    primaryKeyword: "의료법인 임원변경등기",
    secondaryKeywords: ["의료법인 대표 변경", "병원장 변경등기"],
    questionKeywords: ["의료법인 대표 바뀌면"],
    searchIntent: "의료법인 임원·대표 변경 등기를 확인하려는 검색",
    whoNeedsThis: ["대표·이사가 교체된 의료법인"],
    whenAndDeadline: ["승인·결의 후 등기"],
    decisionBodies: ["이사회", "허가권자 승인"],
    documents: ["등기부", "의사록", "면허·자격 증빙", "취임·사임 서류"],
    procedures: ["결의·승인", "등기"],
    costFactors: ["대표·이사 동시 변경"],
    penaltyRisks: ["등기 지연", "자격 미충족"],
    commonConfusions: ["면허만 있고 등기 안 함"],
    diyErrors: ["승인 전 등기"],
    faqs: [],
    relatedLinks: [
      { href: "/의료법인설립등기", label: "의료법인 설립" },
      { href: "/부산의료법인등기", label: "부산 의료법인" },
      ...specialLawRelated,
    ],
    ctaTitle: "의료법인 임원변경 상담",
    ctaText: "등기부와 결의 서류를 기준으로 확인할 수 있습니다.",
  },
  {
    slug: "의료법인주사무소이전등기",
    kind: "intent",
    title: "의료법인 주사무소 이전등기",
    metaTitle: "의료법인 주사무소 이전등기｜허가·관할 변경과 등기",
    metaDescription:
      "의료법인 본점·주사무소 이전. 변경허가 후 등기, 관할 등기소 변경 — 다옴법무사.",
    h1: "의료법인 주사무소 이전 — 허가 변경과 등기소 관할이 바뀝니다",
    eyebrow: "의료법인 · 이전",
    heroIntro: "의료법인 주사무소를 옮기면 변경허가·의료기관 신고와 함께 주사무소 이전등기가 필요합니다.",
    heroParagraphs: [
      "부산 내 이전과 타 시·도 이전은 허가 권한·관할 등기소가 달라질 수 있습니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "주사무소 이전은 변경허가·결의 후 이전등기를 하며, 관할 등기소가 바뀔 수 있습니다.",
    primaryKeyword: "의료법인 주사무소 이전등기",
    secondaryKeywords: ["의료법인 본점 이전", "병원 이전 등기"],
    questionKeywords: ["의료법인 주소 바꾸면"],
    searchIntent: "의료법인 주사무소 이전 등기를 확인하려는 검색",
    whoNeedsThis: ["병원·의원 이전을 준비하는 의료법인"],
    whenAndDeadline: ["변경허가 후 등기 기한"],
    decisionBodies: ["이사회", "허가권자"],
    documents: ["변경허가서", "의사록", "새 주소 증빙"],
    procedures: ["변경허가", "이전등기", "의료기관 신고"],
    costFactors: ["관할 변경", "시설 이전"],
    penaltyRisks: ["등기·신고 불일치"],
    commonConfusions: ["임대차만 변경하고 등기 안 함"],
    diyErrors: ["허가 전 이전등기"],
    faqs: [],
    relatedLinks: [
      { href: "/부산본점이전등기", label: "주식회사 본점이전(비교)" },
      { href: "/의료법인설립등기", label: "의료법인 설립" },
      ...specialLawRelated,
    ],
    ctaTitle: "의료법인 주사무소 이전 상담",
    ctaText: "이전 예정 주소와 허가 여부를 알려주시면 등기 순서를 확인할 수 있습니다.",
  },
  {
    slug: "공익법인설립등기",
    kind: "intent",
    title: "공익법인 설립등기",
    metaTitle: "공익법인 설립등기｜공익법인 등에 관한 법률 체계 안내",
    metaDescription:
      "공익법인 설립·인가·등기. 공익법인 등에 관한 법률, 기존 제도와의 관계 — 다옴법무사.",
    h1: "공익법인 설립등기 — 새로운 공익법인 제도를 확인하세요",
    eyebrow: "공익법인 · 설립",
    heroIntro:
      "공익법인은 공익법인 등에 관한 법률에 따른 법인으로, 공익 목적 사업을 수행합니다.",
    heroParagraphs: [
      "2024년 시행된 공익법인 등에 관한 법률에 따라 공익법인 제도가 정비되었습니다. 기존 공익법인 지정·민법상 재단법인과는 제도가 다를 수 있으므로 설립 시점의 법령을 확인해야 합니다.",
      "설립 인가·등기 절차는 해당 법률·시행령·주무관청 안내에 따릅니다. 세제·기부금은 별도 확인이 필요합니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "공익법인 설립은 법률상 설립 인가·허가 후 설립등기가 필요합니다. 법무사는 등기 단계를 지원하며, 공익 목적·기본재산 요건은 행정 절차에서 확인합니다.",
    primaryKeyword: "공익법인 설립등기",
    secondaryKeywords: [
      "공익법인 설립",
      "공익법인 인가",
      "공익 목적 법인",
    ],
    questionKeywords: ["공익법인 설립 절차", "공익법인과 재단법인"],
    searchIntent: "공익법인 설립·등기 절차를 확인하려는 검색",
    whoNeedsThis: [
      "공익 목적 사업을 법인으로 설립하려는 경우",
      "기존 재단·비영리에서 공익법인 전환 검토",
    ],
    whenAndDeadline: ["설립 인가·허가 후 법정 기한 내 등기(해당 법률·시행령)"],
    decisionBodies: ["설립발기인·이사회", "주무관청"],
    documents: ["인가·허가서", "정관", "기본재산 증빙", "임원 서류"],
    procedures: ["설립 인가·허가", "설립등기"],
    costFactors: ["기본재산", "사업 범위"],
    penaltyRisks: ["등기 기한 경과"],
    commonConfusions: [
      "재단법인·공익법인 지정과 혼동",
      "기부금 세제와 설립등기 혼동",
    ],
    diyErrors: ["구 제도 기준으로 정관 작성"],
    faqs: [
      {
        question: "재단법인과 공익법인 차이는?",
        answer:
          "민법상 재단법인과 공익법인 등에 관한 법률상 공익법인은 근거법·인가·운영 규율이 다릅니다. 설립 시점 법령과 목적을 기준으로 선택하세요.",
      },
    ],
    relatedLinks: [
      { href: "/공익법인임원변경등기", label: "공익법인 임원변경" },
      { href: "/사단법인과재단법인차이", label: "사단·재단 비교" },
      { href: "/부산재단법인설립", label: "재단법인 설립" },
      ...specialLawRelated,
    ],
    ctaTitle: "공익법인 설립등기 상담",
    ctaText: "설립 목적과 인가 진행 상황을 알려주시면 등기 단계를 확인할 수 있습니다.",
    legalProfile: {
      entityName: "공익법인",
      legalBasis: ["공익법인 등에 관한 법률"],
      establishmentMethod: "주무관청 설립 인가·허가 후 설립등기",
      competentAuthority: ["주무관청(법률·시행령)", "관할 등기소"],
      preRegistrationSteps: ["정관·기본재산", "설립 인가·허가"],
      registrationDeadline: "인가·허가 후 법정 기한(시행령 확인)",
      registrableMatters: ["목적·기본재산·임원·주사무소"],
      lawyerScope: ["인가 후 설립·변경 등기"],
      excludedScope: ["기부금·세제", "인가 대리 보장"],
      lastLegalReview: "2026-07-29",
    },
  },
  {
    slug: "공익법인임원변경등기",
    kind: "intent",
    title: "공익법인 임원변경등기",
    metaTitle: "공익법인 임원변경등기｜승인·결의 후 등기",
    metaDescription:
      "공익법인 이사·감사 변경등기. 주무관청 승인과 등기 순서 — 다옴법무사.",
    h1: "공익법인 임원변경등기 — 승인과 등기",
    eyebrow: "공익법인 · 변경",
    heroIntro: "공익법인 임원 변경도 결의·승인 후 등기가 필요합니다.",
    heroParagraphs: ["이사·감사 취임·사임 시 정관·공익법인법상 요건을 확인합니다."],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion: "공익법인 임원변경은 결의·승인 후 등기 기한 내 접수해야 합니다.",
    primaryKeyword: "공익법인 임원변경등기",
    secondaryKeywords: ["공익법인 이사 변경"],
    questionKeywords: ["공익법인 임원 변경"],
    searchIntent: "공익법인 임원 변경 등기를 확인하려는 검색",
    whoNeedsThis: ["임원이 교체된 공익법인"],
    whenAndDeadline: ["승인·결의 후 등기"],
    decisionBodies: ["이사회·총회", "주무관청"],
    documents: ["등기부", "의사록", "승인서", "취임·사임 서류"],
    procedures: ["결의·승인", "등기"],
    costFactors: ["변경 범위"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["비영리법인과 동일 가정"],
    diyErrors: ["승인 전 등기"],
    faqs: [],
    relatedLinks: [
      { href: "/공익법인설립등기", label: "공익법인 설립" },
      { href: "/비영리법인임원변경등기", label: "비영리법인 임원변경" },
      ...specialLawRelated,
    ],
    ctaTitle: "공익법인 임원변경 상담",
    ctaText: "등기사항증명서를 기준으로 확인할 수 있습니다.",
  },
];
