import type { SpecialEntityPageContent } from "../types";
import {
  SPECIAL_ENTITY_OFFICE_LINE,
  SPECIAL_ENTITY_SCOPE_NOTICE,
  baseSpecialRelated,
} from "./shared";

const agriRelated = [
  { href: "/농어업법인설립등기", label: "농·어업 법인 허브" },
  ...baseSpecialRelated,
];

export const phase2AgriculturePages: SpecialEntityPageContent[] = [
  {
    slug: "영농조합법인설립",
    kind: "intent",
    title: "영농조합법인 설립",
    metaTitle: "영농조합법인 설립｜영농조합 전환·설립과 등기",
    metaDescription:
      "영농조합법인 설립·전환·등기. 농업협동조합법, 조합원·출자·정관 — 다옴법무사.",
    h1: "영농조합법인 설립 — 조합 체계와 등기 절차",
    eyebrow: "영농조합법인 · 설립",
    heroIntro:
      "영농조합법인은 농업협동조합법에 따른 법인으로, 영농조합이 법인화하거나 신설 설립됩니다.",
    heroParagraphs: [
      "농업회사법인과 달리 조합원·조합 체계가 전제입니다. 설립·전환 인가·총회 결의 후 설립등기를 합니다.",
      "농지·세제·정책자금은 등기와 별도 영역입니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "영농조합법인 설립은 농업협동조합법상 절차(전환·설립) 완료 후 관할 등기소에 설립등기합니다.",
    primaryKeyword: "영농조합법인 설립",
    secondaryKeywords: ["영농조합 법인화", "영농조합 전환", "농협 영농조합법인"],
    questionKeywords: ["영농조합법인 절차", "영농조합 법인 설립"],
    searchIntent: "영농조합법인 설립·등기를 확인하려는 검색",
    whoNeedsThis: ["영농조합의 법인 전환", "농업 조합 기반 사업 확대"],
    whenAndDeadline: ["총회·인가 후 법정 기한 내 등기(해당 법률)"],
    decisionBodies: ["조합원총회", "중앙회·관할 조합"],
    documents: ["인가·승인서", "정관", "조합원·출자 증빙", "의사록"],
    procedures: ["전환·설립 결의", "인가", "설립등기"],
    costFactors: ["조합원 수", "출자금"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["농업회사법인과 혼동"],
    diyErrors: ["조합원 자격 미확인"],
    faqs: [
      {
        question: "농업회사법인과 차이는?",
        answer: "`/농업회사법인과영농조합법인차이`를 참고하세요.",
      },
    ],
    relatedLinks: [
      { href: "/부산농업회사법인설립", label: "농업회사법인" },
      { href: "/농업회사법인과영농조합법인차이", label: "유형 비교" },
      ...agriRelated,
    ],
    ctaTitle: "영농조합법인 설립 상담",
    ctaText: "전환·설립 단계를 알려주시면 등기 준비를 확인할 수 있습니다.",
    legalProfile: {
      entityName: "영농조합법인",
      legalBasis: ["농업협동조합법"],
      establishmentMethod: "조합원총회 결의·인가 후 설립등기(전환·설립)",
      competentAuthority: ["농협·중앙회 체계", "관할 등기소"],
      preRegistrationSteps: ["총회 결의", "인가·승인"],
      registrationDeadline: "법률·시행규정에 따른 기한",
      registrableMatters: ["명칭·주사무소·조합원·출자"],
      lawyerScope: ["설립·변경 등기"],
      excludedScope: ["농지·세무", "조합 인가 대리"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["부산·경남 농촌·귀농 지역"],
    },
  },
  {
    slug: "영어조합법인설립",
    kind: "intent",
    title: "영어조합법인 설립",
    metaTitle: "영어조합법인 설립｜수산업협동조합법 체계와 등기",
    metaDescription:
      "영어조합법인 설립·전환·등기. 어촌계열·수협 체계, 조합원·출자 — 다옴법무사.",
    h1: "영어조합법인 설립 — 어업 조합의 법인화",
    eyebrow: "영어조합법인 · 설립",
    heroIntro:
      "영어조합법인은 수산업협동조합법에 따른 법인으로, 영어조합이 법인화하거나 설립됩니다.",
    heroParagraphs: [
      "부산·경남 연안·어촌 지역에서 어업 생산·가공·유통 사업의 법인화 문의가 있습니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "영어조합법인은 수산업협동조합법상 절차 후 설립등기합니다. 어업권·어장 관련 사항은 별도 법령 확인이 필요합니다.",
    primaryKeyword: "영어조합법인 설립",
    secondaryKeywords: ["영어조합 법인화", "어촌계열 법인", "수협 영어조합법인"],
    questionKeywords: ["영어조합법인 절차"],
    searchIntent: "영어조합법인 설립을 확인하려는 검색",
    whoNeedsThis: ["영어조합·어촌계열의 법인 전환"],
    whenAndDeadline: ["총회·인가 후 등기"],
    decisionBodies: ["조합원총회", "수협 체계"],
    documents: ["인가서", "정관", "조합원 명부", "의사록"],
    procedures: ["결의·인가", "설립등기"],
    costFactors: ["조합원·출자"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["어업회사법인과 혼동"],
    diyErrors: ["어업 자격 미확인"],
    faqs: [],
    relatedLinks: [
      { href: "/어업회사법인설립", label: "어업회사법인" },
      ...agriRelated,
    ],
    ctaTitle: "영어조합법인 설립 상담",
    ctaText: "조합 전환·설립 단계를 알려주세요.",
    legalProfile: {
      entityName: "영어조합법인",
      legalBasis: ["수산업협동조합법"],
      establishmentMethod: "조합원총회·인가 후 설립등기",
      competentAuthority: ["수협·관할 기관", "등기소"],
      preRegistrationSteps: ["총회", "인가"],
      registrationDeadline: "법률·규정 기한",
      registrableMatters: ["명칭·주사무소·출자"],
      lawyerScope: ["등기"],
      excludedScope: ["어업권·어장", "세무"],
      lastLegalReview: "2026-07-29",
      regionalNotes: ["부산·기장·남해 연안"],
    },
  },
  {
    slug: "어업회사법인설립",
    kind: "intent",
    title: "어업회사법인 설립",
    metaTitle: "어업회사법인 설립｜수산 가공·유통 법인 인증과 등기",
    metaDescription:
      "어업회사법인 설립·인증·등기. 수산 가공·유통·양식 사업 법인화 — 다옴법무사.",
    h1: "어업회사법인 설립 — 수산 사업 구조에 맞는 법인",
    eyebrow: "어업회사법인 · 설립",
    heroIntro:
      "어업회사법인은 수산업 관련 법률에 따라 어업·수산 가공·유통 사업을 법인화하는 형태입니다.",
    heroParagraphs: [
      "영어조합법인·농업회사법인과 사업 구조·인증 요건이 다릅니다. 인증·인가 후 설립등기합니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "어업회사법인 설립은 해당 법률상 인증·인가 후 설립등기가 필요합니다. 어업권·입어 관련은 별도 확인이 필요합니다.",
    primaryKeyword: "어업회사법인 설립",
    secondaryKeywords: ["수산업 법인", "어업 법인 설립", "귀어 법인"],
    questionKeywords: ["어업회사법인 절차"],
    searchIntent: "어업·수산 사업 법인 설립을 확인하려는 검색",
    whoNeedsThis: ["수산 가공·유통·양식 사업자", "귀어·귀촌 사업 법인화"],
    whenAndDeadline: ["인증·인가 후 등기 기한"],
    decisionBodies: ["발기인·총회"],
    documents: ["인증서", "정관", "출자 증빙"],
    procedures: ["인증·인가", "설립등기"],
    costFactors: ["출자·사업 규모"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["영어조합법인과 혼동"],
    diyErrors: ["인증 전 등기"],
    faqs: [],
    relatedLinks: [
      { href: "/영어조합법인설립", label: "영어조합법인" },
      ...agriRelated,
    ],
    ctaTitle: "어업회사법인 설립 상담",
    ctaText: "인증·사업 구조를 알려주시면 등기 단계를 확인할 수 있습니다.",
    legalProfile: {
      entityName: "어업회사법인",
      legalBasis: ["수산업협동조합법 등 수산 관련 법률"],
      establishmentMethod: "인증·인가 후 설립등기",
      competentAuthority: ["해양수산부·유관기관", "등기소"],
      preRegistrationSteps: ["사업계획", "인증·인가"],
      registrationDeadline: "인증·인가 후 법정 기한",
      registrableMatters: ["명칭·본점·임원·출자"],
      lawyerScope: ["설립등기"],
      excludedScope: ["어업권·입어", "세무"],
      lastLegalReview: "2026-07-29",
    },
  },
];
