import type { SpecialEntityPageContent } from "../types";
import {
  SPECIAL_ENTITY_OFFICE_LINE,
  SPECIAL_ENTITY_SCOPE_NOTICE,
  baseSpecialRelated,
} from "./shared";

const profRelated = [
  { href: "/전문직법인등기", label: "전문직 법인 허브" },
  ...baseSpecialRelated,
];

export const phase2ProfessionalPages: SpecialEntityPageContent[] = [
  {
    slug: "법무사법인설립등기",
    kind: "intent",
    title: "법무사법인 설립등기",
    metaTitle: "법무사법인 설립등기｜법무사법상 법인 설립 요건과 등기",
    metaDescription:
      "법무사법인 설립·구성원·정관·사무소, 법인 설립 인가 후 등기 — 다옴법무사.",
    h1: "법무사법인 설립등기 — 법무사법상 요건을 먼저 확인하세요",
    eyebrow: "법무사법인 · 설립",
    heroIntro:
      "법무사법인은 법무사법에 따라 둘 이상의 법무사가 법인으로 사무소를 운영하는 형태입니다.",
    heroParagraphs: [
      "법무사법·시행령·규칙에 따른 구성원 자격·출자·정관·사무소 요건을 충족한 뒤 법인 설립 인가·등기를 합니다.",
      "개인 법무사 등록과 법인 설립은 별개이며, 법무사 업무 범위는 법무사법에 따릅니다.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "법무사법인 설립은 법무사법상 법인 설립 요건·인가 후 설립등기가 필요합니다. 구성원 변경 시에도 등기가 필요할 수 있습니다.",
    primaryKeyword: "법무사법인 설립등기",
    secondaryKeywords: [
      "법무사법인 설립",
      "법무사 합동",
      "법무사 사무소 법인화",
    ],
    questionKeywords: ["법무사법인 만들기", "법무사법인 절차"],
    searchIntent: "법무사법인 설립·등기 절차를 확인하려는 검색",
    whoNeedsThis: [
      "법무사 2인 이상의 법인 설립",
      "구성원 변경·합병 검토",
    ],
    whenAndDeadline: ["법인 설립 인가 후 등기 기한(법무사법·규칙)"],
    decisionBodies: ["구성원 총회", "대한법무사협회 등(해당 절차)"],
    documents: ["인가·등록 서류", "정관", "구성원 명부", "출자 증빙"],
    procedures: ["요건 확인", "인가·등록", "설립등기"],
    costFactors: ["구성원 수", "사무소"],
    penaltyRisks: ["인가 후 등기 지연"],
    commonConfusions: ["주식회사와 동일 구조 가정"],
    diyErrors: ["자격 미충족 구성원 포함"],
    faqs: [],
    relatedLinks: profRelated,
    ctaTitle: "법무사법인 설립등기 상담",
    ctaText: "법인 설립 인가 단계를 알려주시면 등기 준비를 확인할 수 있습니다.",
    legalProfile: {
      entityName: "법무사법인",
      legalBasis: ["법무사법", "법무사법 시행령·규칙"],
      establishmentMethod: "법무사법상 법인 설립 인가·등록 후 설립등기",
      competentAuthority: ["법무부·대한법무사협회(해당 절차)", "등기소"],
      preRegistrationSteps: ["구성원·정관", "법인 설립 인가"],
      registrationDeadline: "인가 후 법정 기한",
      registrableMatters: ["명칭·주사무소·구성원·대표"],
      lawyerScope: ["설립·변경 등기(동업 법무사 범위 내)"],
      excludedScope: ["법인 설립 인가 자체"],
      lastLegalReview: "2026-07-29",
    },
  },
  {
    slug: "세무법인설립등기",
    kind: "intent",
    title: "세무법인 설립등기",
    metaTitle: "세무법인 설립등기｜세무사법인 설립 인가와 등기",
    metaDescription:
      "세무법인(세무사법인) 설립등기 안내. 세무신고·세무자문이 아닌 등기·서류만 — 다옴법무사.",
    h1: "세무법인 설립등기 — 세무사법인 설립과 등기",
    eyebrow: "세무법인 · 설립",
    heroIntro:
      "세무법인은 세무사법에 따른 세무사법인으로, 구성원 세무사의 자격·출자 요건을 충족해야 합니다.",
    heroParagraphs: [
      "세무사 개인 등록과 법인 설립은 별개입니다. 설립 등록·인가 후 관할 등기소에 설립등기합니다.",
      "이 페이지는 설립등기·변경등기 안내입니다. 세무신고·장부·세무조사 대응 등 세무사 고유 업무는 해당 세무사·세무법인에 문의하세요.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "세무법인 설립등기는 세무사법상 법인 설립 요건·등록 후 등기가 필요합니다.",
    primaryKeyword: "세무법인 설립등기",
    secondaryKeywords: ["세무사법인 설립", "세무법인 등기"],
    questionKeywords: ["세무법인 설립 절차"],
    searchIntent: "세무법인 설립등기를 확인하려는 검색",
    whoNeedsThis: ["세무사 사무소의 법인화"],
    whenAndDeadline: ["설립 등록 후 등기 기한"],
    decisionBodies: ["구성원 총회"],
    documents: ["등록·인가 서류", "정관", "구성원 서류"],
    procedures: ["등록·인가", "설립등기"],
    costFactors: ["구성원·사무소"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["세무 대리와 법인 설립 혼동"],
    diyErrors: ["등록 전 등기"],
    faqs: [],
    relatedLinks: profRelated,
    ctaTitle: "세무법인 설립등기 상담",
    ctaText: "설립 등록이 완료되었다면 등기 서류를 확인할 수 있습니다.",
    legalProfile: {
      entityName: "세무사법인(세무법인)",
      legalBasis: ["세무사법"],
      establishmentMethod: "세무사법상 법인 설립 등록 후 설립등기",
      competentAuthority: ["한국세무사회·관할 기관", "등기소"],
      preRegistrationSteps: ["구성원·정관", "설립 등록"],
      registrationDeadline: "등록 후 법정 기한",
      registrableMatters: ["명칭·주사무소·구성원"],
      lawyerScope: ["설립·변경 등기"],
      excludedScope: ["세무사법인 설립 등록", "세무 업무"],
      lastLegalReview: "2026-07-29",
    },
  },
  {
    slug: "노무법인설립등기",
    kind: "intent",
    title: "노무법인 설립등기",
    metaTitle: "노무법인 설립등기｜공인노무사 법인 설립과 등기",
    metaDescription:
      "노무법인(공인노무사법인) 설립·구성원·정관, 설립 인가 후 등기 — 다옴법무사.",
    h1: "노무법인 설립등기 — 공인노무사법인 설립",
    eyebrow: "노무법인 · 설립",
    heroIntro:
      "노무법인은 공인노무사법에 따른 공인노무사법인으로, 구성원 자격·출자 요건이 있습니다.",
    heroParagraphs: [
      "법인 설립 인가·등록 후 설립등기를 합니다. 노무 업무와 법인 설립은 별개입니다.",
      "이 페이지는 등기 안내입니다. 근로계약·4대보험·노동 쟁송 등 노무사 고유 업무는 공인노무사·노무법인에 문의하세요.",
    ],
    officeLine: SPECIAL_ENTITY_OFFICE_LINE,
    scopeNotice: SPECIAL_ENTITY_SCOPE_NOTICE,
    conclusion:
      "노무법인 설립은 공인노무사법상 요건·인가 후 설립등기가 필요합니다.",
    primaryKeyword: "노무법인 설립등기",
    secondaryKeywords: ["공인노무사법인", "노무법인 설립"],
    questionKeywords: ["노무법인 설립"],
    searchIntent: "노무법인 설립등기를 확인하려는 검색",
    whoNeedsThis: ["노무사 사무소 법인화"],
    whenAndDeadline: ["인가 후 등기"],
    decisionBodies: ["구성원 총회"],
    documents: ["인가서", "정관", "구성원 서류"],
    procedures: ["인가", "설립등기"],
    costFactors: ["구성원 수"],
    penaltyRisks: ["등기 지연"],
    commonConfusions: ["노무 업무=법인 설립"],
    diyErrors: ["인가 전 등기"],
    faqs: [],
    relatedLinks: profRelated,
    ctaTitle: "노무법인 설립등기 상담",
    ctaText: "인가 단계를 알려주시면 등기 준비를 확인할 수 있습니다.",
    legalProfile: {
      entityName: "공인노무사법인(노무법인)",
      legalBasis: ["공인노무사법"],
      establishmentMethod: "법인 설립 인가·등록 후 설립등기",
      competentAuthority: ["고용노동부·한국공인노무사회", "등기소"],
      preRegistrationSteps: ["구성원·정관", "설립 인가"],
      registrationDeadline: "인가 후 법정 기한",
      registrableMatters: ["명칭·주사무소·구성원"],
      lawyerScope: ["설립·변경 등기"],
      excludedScope: ["노무 업무", "인가 대리"],
      lastLegalReview: "2026-07-29",
    },
  },
];
