import type { GlossaryIndexAction } from "./types";

export type GlossaryPolicyRow = {
  slug: string;
  intentLevel: 0 | 1 | 2 | 3 | 4;
  businessIntent: number;
  serviceFit: number;
  ownerUniqueness: number;
  seoOpportunity: number;
  conversionPotential: number;
  action: GlossaryIndexAction;
  serviceOwner: string;
  serviceOwnerLabel: string;
  primaryQuery: string;
  allowedSecondary: string[];
  forbiddenQueries: string[];
  discoverable: boolean;
  inquiryField?: string;
};

/**
 * 내부 QA 점수. 네이버 알고리즘 점수가 아님.
 * Search Advisor 실측 없음 → impressions/clicks는 UNKNOWN.
 *
 * GATE: KEEP/UPGRADE 는 BI≥60, SF≥60, cannibalization CRITICAL 없음.
 * 고전환 용어는 이미 서비스 URL이 있어 glossary는 SUPPORT_NOINDEX.
 */
export const GLOSSARY_POLICY: Record<string, GlossaryPolicyRow> = {
  "inheritance-registration": {
    slug: "inheritance-registration",
    intentLevel: 4,
    businessIntent: 88,
    serviceFit: 95,
    ownerUniqueness: 12,
    seoOpportunity: 20,
    conversionPotential: 90,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산상속등기",
    serviceOwnerLabel: "부산 상속등기",
    primaryQuery: "상속등기 다음 절차",
    allowedSecondary: ["상속등기 준비서류", "상속등기 확인사항"],
    forbiddenQueries: ["부산 상속등기", "부산 상속등기 법무사", "부산 법무사"],
    discoverable: true,
    inquiryField: "inheritance-registration",
  },
  "inheritance-renunciation": {
    slug: "inheritance-renunciation",
    intentLevel: 4,
    businessIntent: 92,
    serviceFit: 95,
    ownerUniqueness: 12,
    seoOpportunity: 18,
    conversionPotential: 92,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산상속포기",
    serviceOwnerLabel: "부산 상속포기",
    primaryQuery: "상속포기 신청 전 확인",
    allowedSecondary: ["상속포기 3개월", "상속포기 준비서류"],
    forbiddenQueries: ["부산 상속포기", "부산 상속포기 법무사"],
    discoverable: true,
    inquiryField: "inheritance-registration",
  },
  "qualified-acceptance": {
    slug: "qualified-acceptance",
    intentLevel: 4,
    businessIntent: 92,
    serviceFit: 95,
    ownerUniqueness: 12,
    seoOpportunity: 18,
    conversionPotential: 92,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산한정승인",
    serviceOwnerLabel: "부산 한정승인",
    primaryQuery: "한정승인 신청 전 확인",
    allowedSecondary: ["한정승인 3개월", "한정승인 재산목록"],
    forbiddenQueries: ["부산 한정승인", "부산 한정승인 법무사"],
    discoverable: true,
    inquiryField: "inheritance-registration",
  },
  "special-qualified-acceptance": {
    slug: "special-qualified-acceptance",
    intentLevel: 3,
    businessIntent: 86,
    serviceFit: 90,
    ownerUniqueness: 28,
    seoOpportunity: 35,
    conversionPotential: 85,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/특별한정승인",
    serviceOwnerLabel: "특별한정승인 안내",
    primaryQuery: "상속포기 기한 지난 뒤",
    allowedSecondary: ["특별한정승인 사유", "3개월 지난 상속"],
    forbiddenQueries: ["부산 한정승인", "부산 상속포기"],
    discoverable: true,
    inquiryField: "inheritance-registration",
  },
  "inheritance-division-agreement": {
    slug: "inheritance-division-agreement",
    intentLevel: 3,
    businessIntent: 84,
    serviceFit: 92,
    ownerUniqueness: 30,
    seoOpportunity: 40,
    conversionPotential: 86,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/상속재산분할협의서준비",
    serviceOwnerLabel: "상속재산분할협의서 준비",
    primaryQuery: "부동산을 한 명 앞으로 상속",
    allowedSecondary: ["상속재산분할협의서 인감", "공동상속 등기서류"],
    forbiddenQueries: ["부산 상속등기", "부산 상속 법무사"],
    discoverable: true,
    inquiryField: "inheritance-registration",
  },
  "statutory-reserve-share": {
    slug: "statutory-reserve-share",
    intentLevel: 2,
    businessIntent: 58,
    serviceFit: 32,
    ownerUniqueness: 40,
    seoOpportunity: 25,
    conversionPotential: 28,
    action: "REMOVE_FROM_DISCOVERY",
    serviceOwner: "/유류분과상속등기",
    serviceOwnerLabel: "유류분과 상속등기",
    primaryQuery: "유류분과 상속등기 관계",
    allowedSecondary: ["분할협의 전 유류분"],
    forbiddenQueries: ["유류분 반환청구", "유류분 소송", "부산 상속등기"],
    discoverable: false,
    inquiryField: "inheritance-registration",
  },
  "legal-inheritance-order": {
    slug: "legal-inheritance-order",
    intentLevel: 1,
    businessIntent: 48,
    serviceFit: 72,
    ownerUniqueness: 22,
    seoOpportunity: 20,
    conversionPotential: 55,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산상속등기",
    serviceOwnerLabel: "부산 상속등기",
    primaryQuery: "상속인이 누구인지 확인",
    allowedSecondary: ["법정상속순위 가족관계"],
    forbiddenQueries: ["부산 상속등기", "부산 상속 법무사"],
    discoverable: true,
    inquiryField: "inheritance-registration",
  },
  "subrogation-inheritance": {
    slug: "subrogation-inheritance",
    intentLevel: 3,
    businessIntent: 78,
    serviceFit: 90,
    ownerUniqueness: 32,
    seoOpportunity: 42,
    conversionPotential: 80,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/대습상속등기",
    serviceOwnerLabel: "대습상속등기",
    primaryQuery: "자녀가 먼저 사망한 상속등기",
    allowedSecondary: ["대습상속인 서류", "손자녀 상속등기"],
    forbiddenQueries: ["부산 상속등기"],
    discoverable: true,
    inquiryField: "inheritance-registration",
  },
  mortgage: {
    slug: "mortgage",
    intentLevel: 3,
    businessIntent: 86,
    serviceFit: 95,
    ownerUniqueness: 14,
    seoOpportunity: 18,
    conversionPotential: 88,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산근저당말소등기",
    serviceOwnerLabel: "부산 근저당말소등기",
    primaryQuery: "대출 갚은 뒤 근저당 말소",
    allowedSecondary: ["잔금 전 근저당 말소", "근저당 설정 확인"],
    forbiddenQueries: ["부산 근저당말소", "부산 근저당말소등기", "부산 법무사"],
    discoverable: true,
    inquiryField: "mortgage",
  },
  "provisional-attachment": {
    slug: "provisional-attachment",
    intentLevel: 3,
    businessIntent: 68,
    serviceFit: 78,
    ownerUniqueness: 28,
    seoOpportunity: 30,
    conversionPotential: 70,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산가압류말소등기",
    serviceOwnerLabel: "부산 가압류말소등기",
    primaryQuery: "등기부 가압류 말소",
    allowedSecondary: ["가압류 있는 매매", "가압류 신청 서류"],
    forbiddenQueries: ["가압류 소송대리", "부산 법무사"],
    discoverable: true,
    inquiryField: "civil-debt",
  },
  attachment: {
    slug: "attachment",
    intentLevel: 2,
    businessIntent: 42,
    serviceFit: 52,
    ownerUniqueness: 30,
    seoOpportunity: 18,
    conversionPotential: 40,
    action: "REMOVE_FROM_DISCOVERY",
    serviceOwner: "/부산압류말소등기",
    serviceOwnerLabel: "부산 압류말소등기",
    primaryQuery: "등기부 압류 말소",
    allowedSecondary: ["압류 있는 부동산"],
    forbiddenQueries: ["압류 소송대리"],
    discoverable: false,
    inquiryField: "civil-debt",
  },
  pledge: {
    slug: "pledge",
    intentLevel: 0,
    businessIntent: 18,
    serviceFit: 28,
    ownerUniqueness: 70,
    seoOpportunity: 8,
    conversionPotential: 15,
    action: "REMOVE_FROM_DISCOVERY",
    serviceOwner: "/법인등기",
    serviceOwnerLabel: "법인등기 안내",
    primaryQuery: "질권과 등기 실무 구분",
    allowedSecondary: [],
    forbiddenQueries: ["부산 법무사", "질권 소송"],
    discoverable: false,
  },
  "jeonse-right": {
    slug: "jeonse-right",
    intentLevel: 3,
    businessIntent: 74,
    serviceFit: 90,
    ownerUniqueness: 16,
    seoOpportunity: 22,
    conversionPotential: 75,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산전세권설정등기",
    serviceOwnerLabel: "부산 전세권설정등기",
    primaryQuery: "전세권 설정·말소 확인",
    allowedSecondary: ["전세권 말소등기"],
    forbiddenQueries: ["부산 전세권설정등기", "부산 전세권말소등기"],
    discoverable: true,
    inquiryField: "real-estate-registration",
  },
  "lease-registration-order": {
    slug: "lease-registration-order",
    intentLevel: 4,
    businessIntent: 94,
    serviceFit: 95,
    ownerUniqueness: 10,
    seoOpportunity: 15,
    conversionPotential: 94,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산임차권등기명령",
    serviceOwnerLabel: "부산 임차권등기명령",
    primaryQuery: "보증금 못 받고 이사할 때",
    allowedSecondary: ["임차권등기명령 신청 서류"],
    forbiddenQueries: ["부산 임차권등기명령", "부산 임차권등기명령 법무사"],
    discoverable: true,
    inquiryField: "civil-debt",
  },
  "ownership-transfer-registration": {
    slug: "ownership-transfer-registration",
    intentLevel: 4,
    businessIntent: 90,
    serviceFit: 95,
    ownerUniqueness: 12,
    seoOpportunity: 16,
    conversionPotential: 90,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산소유권이전등기",
    serviceOwnerLabel: "부산 소유권이전등기",
    primaryQuery: "잔금일 소유권이전등기 서류",
    allowedSecondary: ["매매 이전등기 준비서류"],
    forbiddenQueries: ["부산 소유권이전등기", "부산 부동산등기"],
    discoverable: true,
    inquiryField: "real-estate-registration",
  },
  "ownership-preservation-registration": {
    slug: "ownership-preservation-registration",
    intentLevel: 3,
    businessIntent: 80,
    serviceFit: 92,
    ownerUniqueness: 34,
    seoOpportunity: 40,
    conversionPotential: 78,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/미등기건물소유권보존등기",
    serviceOwnerLabel: "미등기건물 소유권보존등기",
    primaryQuery: "신축 소유권보존등기",
    allowedSecondary: ["보존등기 준비서류", "미등기 건물 등기"],
    forbiddenQueries: ["부산 부동산등기", "부산 소유권이전등기"],
    discoverable: true,
    inquiryField: "preservation-registration",
  },
  "registration-license-tax": {
    slug: "registration-license-tax",
    intentLevel: 0,
    businessIntent: 28,
    serviceFit: 48,
    ownerUniqueness: 25,
    seoOpportunity: 10,
    conversionPotential: 22,
    action: "REMOVE_FROM_DISCOVERY",
    serviceOwner: "/등록면허세",
    serviceOwnerLabel: "등록면허세 안내",
    primaryQuery: "등기 전 등록면허세",
    allowedSecondary: [],
    forbiddenQueries: ["등록면허세 뜻", "부산 법무사"],
    discoverable: false,
  },
  "acquisition-tax": {
    slug: "acquisition-tax",
    intentLevel: 1,
    businessIntent: 36,
    serviceFit: 52,
    ownerUniqueness: 22,
    seoOpportunity: 12,
    conversionPotential: 30,
    action: "REMOVE_FROM_DISCOVERY",
    serviceOwner: "/취득세",
    serviceOwnerLabel: "취득세 안내",
    primaryQuery: "상속·매매 취득세와 등기 순서",
    allowedSecondary: ["상속취득세 기한"],
    forbiddenQueries: ["취득세 뜻", "부산 상속등기"],
    discoverable: false,
  },
  "stamp-duty": {
    slug: "stamp-duty",
    intentLevel: 0,
    businessIntent: 12,
    serviceFit: 38,
    ownerUniqueness: 55,
    seoOpportunity: 6,
    conversionPotential: 12,
    action: "REMOVE_FROM_DISCOVERY",
    serviceOwner: "/부산지방법원지급명령",
    serviceOwnerLabel: "지급명령 안내",
    primaryQuery: "법원 신청 인지대",
    allowedSecondary: [],
    forbiddenQueries: ["인지대 뜻"],
    discoverable: false,
  },
  "service-fee": {
    slug: "service-fee",
    intentLevel: 0,
    businessIntent: 12,
    serviceFit: 40,
    ownerUniqueness: 55,
    seoOpportunity: 6,
    conversionPotential: 12,
    action: "REMOVE_FROM_DISCOVERY",
    serviceOwner: "/부산개인회생",
    serviceOwnerLabel: "부산 개인회생",
    primaryQuery: "법원 송달료",
    allowedSecondary: [],
    forbiddenQueries: ["송달료 뜻"],
    discoverable: false,
  },
  "payment-order": {
    slug: "payment-order",
    intentLevel: 3,
    businessIntent: 82,
    serviceFit: 86,
    ownerUniqueness: 38,
    seoOpportunity: 45,
    conversionPotential: 84,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산지방법원지급명령",
    serviceOwnerLabel: "지급명령 안내",
    primaryQuery: "돈을 못 받았을 때 지급명령",
    allowedSecondary: ["지급명령 신청 서류", "지급명령 이의"],
    forbiddenQueries: ["지급명령 소송대리", "부산 법무사"],
    discoverable: true,
    inquiryField: "civil-debt",
  },
  "certified-mail": {
    slug: "certified-mail",
    intentLevel: 3,
    businessIntent: 76,
    serviceFit: 82,
    ownerUniqueness: 40,
    seoOpportunity: 42,
    conversionPotential: 78,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/내용증명작성준비",
    serviceOwnerLabel: "내용증명 작성 준비",
    primaryQuery: "보증금·대금 내용증명",
    allowedSecondary: ["내용증명 언제 보내나"],
    forbiddenQueries: ["부산 법무사"],
    discoverable: true,
    inquiryField: "civil-debt",
  },
  complaint: {
    slug: "complaint",
    intentLevel: 1,
    businessIntent: 38,
    serviceFit: 30,
    ownerUniqueness: 48,
    seoOpportunity: 12,
    conversionPotential: 22,
    action: "REMOVE_FROM_DISCOVERY",
    serviceOwner: "/민사소송",
    serviceOwnerLabel: "민사·채권 안내",
    primaryQuery: "소장과 지급명령 구분",
    allowedSecondary: [],
    forbiddenQueries: ["소장 작성 소송대리", "민사소송 변호사"],
    discoverable: false,
  },
  "answer-brief": {
    slug: "answer-brief",
    intentLevel: 1,
    businessIntent: 38,
    serviceFit: 30,
    ownerUniqueness: 48,
    seoOpportunity: 12,
    conversionPotential: 22,
    action: "REMOVE_FROM_DISCOVERY",
    serviceOwner: "/민사소송",
    serviceOwnerLabel: "민사·채권 안내",
    primaryQuery: "답변서 제출 기한",
    allowedSecondary: [],
    forbiddenQueries: ["답변서 소송대리"],
    discoverable: false,
  },
  "personal-rehabilitation": {
    slug: "personal-rehabilitation",
    intentLevel: 4,
    businessIntent: 90,
    serviceFit: 95,
    ownerUniqueness: 12,
    seoOpportunity: 16,
    conversionPotential: 90,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산개인회생",
    serviceOwnerLabel: "부산 개인회생",
    primaryQuery: "개인회생 신청 전 확인",
    allowedSecondary: ["개인회생 변제계획", "개인회생 서류"],
    forbiddenQueries: ["부산 개인회생", "부산 개인회생 법무사"],
    discoverable: true,
    inquiryField: "personal-rehabilitation",
  },
  "personal-bankruptcy": {
    slug: "personal-bankruptcy",
    intentLevel: 4,
    businessIntent: 90,
    serviceFit: 95,
    ownerUniqueness: 12,
    seoOpportunity: 16,
    conversionPotential: 90,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산개인파산",
    serviceOwnerLabel: "부산 개인파산",
    primaryQuery: "개인파산 신청 전 확인",
    allowedSecondary: ["개인파산 면책", "회생과 파산 비교"],
    forbiddenQueries: ["부산 개인파산", "부산 개인파산 법무사"],
    discoverable: true,
    inquiryField: "personal-rehabilitation",
  },
  discharge: {
    slug: "discharge",
    intentLevel: 2,
    businessIntent: 52,
    serviceFit: 82,
    ownerUniqueness: 28,
    seoOpportunity: 22,
    conversionPotential: 55,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산면책신청",
    serviceOwnerLabel: "면책 신청 안내",
    primaryQuery: "파산·회생 후 면책",
    allowedSecondary: ["면책 불허 사유"],
    forbiddenQueries: ["부산 개인파산"],
    discoverable: true,
    inquiryField: "personal-rehabilitation",
  },
  "company-establishment-registration": {
    slug: "company-establishment-registration",
    intentLevel: 4,
    businessIntent: 88,
    serviceFit: 95,
    ownerUniqueness: 12,
    seoOpportunity: 16,
    conversionPotential: 88,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산법인설립등기",
    serviceOwnerLabel: "부산 법인설립등기",
    primaryQuery: "법인설립등기 준비서류",
    allowedSecondary: ["설립등기 순서", "정관·자본금"],
    forbiddenQueries: ["부산 법인설립등기", "부산 법인 법무사"],
    discoverable: true,
    inquiryField: "corporate-registration",
  },
  "director-change-registration": {
    slug: "director-change-registration",
    intentLevel: 4,
    businessIntent: 94,
    serviceFit: 100,
    ownerUniqueness: 8,
    seoOpportunity: 12,
    conversionPotential: 94,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산임원변경등기",
    serviceOwnerLabel: "부산 임원변경등기",
    primaryQuery: "임원변경등기 2주 기한",
    allowedSecondary: ["대표이사 변경 과태료", "임원변경 서류"],
    forbiddenQueries: ["부산 임원변경등기", "부산 법인등기"],
    discoverable: true,
    inquiryField: "corporate-registration",
  },
  "head-office-move-registration": {
    slug: "head-office-move-registration",
    intentLevel: 3,
    businessIntent: 86,
    serviceFit: 95,
    ownerUniqueness: 18,
    seoOpportunity: 22,
    conversionPotential: 86,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산본점이전등기",
    serviceOwnerLabel: "부산 본점이전등기",
    primaryQuery: "법인 사무실 이전 등기",
    allowedSecondary: ["관할 내외 본점이전"],
    forbiddenQueries: ["부산 본점이전등기", "부산 법인등기"],
    discoverable: true,
    inquiryField: "corporate-registration",
  },
  "purpose-change-registration": {
    slug: "purpose-change-registration",
    intentLevel: 3,
    businessIntent: 80,
    serviceFit: 95,
    ownerUniqueness: 24,
    seoOpportunity: 30,
    conversionPotential: 80,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산사업목적변경등기",
    serviceOwnerLabel: "부산 사업목적변경등기",
    primaryQuery: "법인 사업목적 추가 등기",
    allowedSecondary: ["목적변경 주주총회"],
    forbiddenQueries: ["부산 법인등기"],
    discoverable: true,
    inquiryField: "corporate-registration",
  },
  "dissolution-registration": {
    slug: "dissolution-registration",
    intentLevel: 3,
    businessIntent: 76,
    serviceFit: 90,
    ownerUniqueness: 22,
    seoOpportunity: 28,
    conversionPotential: 74,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산법인해산청산등기",
    serviceOwnerLabel: "부산 법인해산·청산등기",
    primaryQuery: "법인 폐업과 해산등기",
    allowedSecondary: ["해산등기 주주총회"],
    forbiddenQueries: ["부산 법인등기"],
    discoverable: true,
    inquiryField: "corporate-registration",
  },
  "liquidation-registration": {
    slug: "liquidation-registration",
    intentLevel: 3,
    businessIntent: 74,
    serviceFit: 90,
    ownerUniqueness: 22,
    seoOpportunity: 28,
    conversionPotential: 72,
    action: "SUPPORT_NOINDEX",
    serviceOwner: "/부산법인해산청산등기",
    serviceOwnerLabel: "부산 법인해산·청산등기",
    primaryQuery: "청산종결등기 순서",
    allowedSecondary: ["해산 후 청산등기"],
    forbiddenQueries: ["부산 법인등기"],
    discoverable: true,
    inquiryField: "corporate-registration",
  },
};

export const GLOSSARY_HUB_POLICY = {
  action: "KEEP_INDEX" as const,
  forbiddenQueries: [
    "부산 법무사",
    "부산 상속 법무사",
    "부산 등기 법무사",
    "부산 법인 법무사",
    "부산 법률 강의",
  ],
};

export function finalBusinessSeoScore(row: GlossaryPolicyRow): number {
  return Math.round(
    row.businessIntent * 0.3 +
      row.serviceFit * 0.3 +
      row.ownerUniqueness * 0.15 +
      row.seoOpportunity * 0.15 +
      row.conversionPotential * 0.1,
  );
}

export function getGlossaryPolicy(slug: string): GlossaryPolicyRow | undefined {
  return GLOSSARY_POLICY[slug];
}

/** owner가 둘로 나뉘거나 연결이 약한 용어는 canonical을 붙이지 않는다. */
const SKIP_OWNER_CANONICAL = new Set([
  "pledge",
  "stamp-duty",
  "service-fee",
  "complaint",
  "answer-brief",
  "legal-inheritance-order",
  "mortgage",
  "jeonse-right",
]);

export function glossaryCanonicalToOwner(slug: string): boolean {
  if (SKIP_OWNER_CANONICAL.has(slug)) return false;
  return Boolean(GLOSSARY_POLICY[slug]?.serviceOwner);
}

/** `/glossary/{slug}` → 동일 의도 서비스 URL. 없으면 undefined. */
export function getGlossaryCanonicalOverride(path: string): string | undefined {
  const match = path.match(/^\/glossary\/([^/]+)$/);
  if (!match) return undefined;
  const slug = match[1];
  if (!slug || !glossaryCanonicalToOwner(slug)) return undefined;
  return GLOSSARY_POLICY[slug]?.serviceOwner;
}

export function glossaryNoIndexPaths(): string[] {
  return Object.values(GLOSSARY_POLICY)
    .filter(
      (row) =>
        row.action === "SUPPORT_NOINDEX" ||
        row.action === "REMOVE_FROM_DISCOVERY" ||
        row.action === "MERGE_REDIRECT_CANDIDATE",
    )
    .map((row) => `/glossary/${row.slug}`);
}

export function isGlossaryDiscoverable(slug: string): boolean {
  return GLOSSARY_POLICY[slug]?.discoverable !== false;
}

/** 허브 상황 바로가기 — 서비스 owner로 연결. glossary가 PRIMARY가 되지 않음. */
export const GLOSSARY_SITUATION_SHORTCUTS = [
  {
    label: "부모님 부동산을 상속해야 해요",
    href: "/부산상속등기",
    termSlug: "inheritance-registration",
  },
  {
    label: "빚이 있는 상속인지 걱정돼요",
    href: "/부산한정승인",
    termSlug: "qualified-acceptance",
  },
  {
    label: "보증금을 못 받고 이사해야 해요",
    href: "/부산임차권등기명령",
    termSlug: "lease-registration-order",
  },
  {
    label: "대출을 갚았는데 근저당이 남아 있어요",
    href: "/부산근저당말소등기",
    termSlug: "mortgage",
  },
  {
    label: "돈을 못 받고 있어요",
    href: "/부산지방법원지급명령",
    termSlug: "payment-order",
  },
  {
    label: "대표이사 임기가 끝났어요",
    href: "/부산임원변경등기",
    termSlug: "director-change-registration",
  },
  {
    label: "법인 주소를 옮겼어요",
    href: "/부산본점이전등기",
    termSlug: "head-office-move-registration",
  },
  {
    label: "채무를 감당하기 어려워요",
    href: "/부산개인회생",
    termSlug: "personal-rehabilitation",
  },
] as const;
