import type { GlossaryTerm } from "./types";
import { C, D, F, S } from "./link-maps";

function term(
  slug: string,
  data: Omit<GlossaryTerm, "slug" | "path">,
): GlossaryTerm {
  return { slug, path: `/glossary/${slug}`, ...data };
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  term("inheritance-registration", {
    term: "상속등기",
    category: "inheritance",
    cardDescription: "피상속인 명의 부동산을 상속인 명의로 바꾸는 등기 절차입니다.",
    oneLineDefinition: "피상속인이 남긴 부동산 등기부상 권리를 상속인 명의로 옮기는 절차입니다.",
    plainExplanation:
      "상속이 시작되면 등기부상 소유자는 여전히 돌아가신 분으로 남아 있습니다. 매매·담보·처분을 하려면 상속인 명의로 등기를 마쳐야 합니다. 관할 등기소에 상속개시사실증명, 인감·위임 등을 제출해 소유권이전등기를 신청합니다.",
    whenItMatters: [
      "상속 부동산을 팔거나 담보로 잡을 때",
      "등기부상 소유자가 피상속인으로 남아 있을 때",
      "세금·대출·임대차와 맞물려 명의 정리가 필요할 때",
    ],
    checks: ["등기부등본·가족관계·상속인 확인", "근저당·가압류 등 권리관계", "취득세·등록면허세 납부 여부"],
    diagnosisLinks: [D.inheritanceReg, D.realEstate],
    serviceLinks: [S.inheritanceReg, S.inheritanceHub],
    faqLinks: [F.inheritanceWhen, F.inheritanceCost, F.mortgage],
    caseLinks: [C.haeundaeInheritance, C.gijang],
  }),
  term("inheritance-renunciation", {
    term: "상속포기",
    category: "inheritance",
    cardDescription: "상속을 받지 않겠다고 법원에 신고하는 절차입니다.",
    oneLineDefinition: "상속인이 상속재산과 채무를 모두 포기하고 상속인 지위를 버리는 신고입니다.",
    plainExplanation:
      "상속은 재산뿐 아니라 빚까지 함께 이어질 수 있습니다. 채무가 많거나 상속을 원하지 않으면 가정법원에 상속포기를 신고합니다. 기한을 넘기면 단순승인으로 보일 수 있어 일정 확인이 중요합니다.",
    whenItMatters: ["피상속인 채무가 재산보다 클 때", "형제·배우자와 상속 방향을 정할 때", "한정승인 대신 포기를 검토할 때"],
    checks: ["상속포기 기한(상속개시 후 3개월)", "공동상속인 협의", "가족관계증명·인감"],
    diagnosisLinks: [D.renunciation, D.qualified],
    serviceLinks: [S.renunciation, S.inheritanceHub],
    faqLinks: [F.renunciationDeadline],
    caseLinks: [C.renunciation],
  }),
  term("qualified-acceptance", {
    term: "한정승인",
    category: "inheritance",
    cardDescription: "상속재산 범위 안에서만 채무를 부담하는 상속 방식입니다.",
    oneLineDefinition: "상속인이 상속재산 한도 내에서만 피상속인의 채무를 변제하는 승인 방식입니다.",
    plainExplanation:
      "채무 규모가 불분명할 때 단순승인은 위험할 수 있습니다. 한정승인은 상속으로 들어온 재산만큼만 채무를 갚으면 되므로, 빚이 재산을 넘는 상황에서 자주 검토됩니다. 가정법원 신고와 재산·채무 정리가 필요합니다.",
    whenItMatters: ["채무가 있을 수 있으나 규모를 모를 때", "상속포기보다 재산 일부는 받고 싶을 때", "단순승인 전에 선택을 비교할 때"],
    checks: ["상속개시일·신고 기한", "재산·채무 목록", "공동상속인 의견"],
    diagnosisLinks: [D.qualified, D.renunciation],
    serviceLinks: [S.qualified, S.inheritanceHub],
    faqLinks: [F.qualifiedVs, F.qualifiedProc],
    caseLinks: [C.qualified],
  }),
  term("special-qualified-acceptance", {
    term: "특별한정승인",
    category: "inheritance",
    cardDescription: "상속포기·한정승인 기한이 지난 뒤 제한적으로 인정되는 제도입니다.",
    oneLineDefinition: "정해진 기한을 넘겼을 때 법원 허가 하에 한정승인과 유사하게 처리하는 예외 제도입니다.",
    plainExplanation:
      "원칙적으로 상속포기·한정승인은 3개월 안에 해야 합니다. 기한을 놓쳤다면 단순승인으로 보일 수 있어, 정당한 사유가 있을 때 특별한정승인을 검토합니다. 사유·증빙·절차가 까다로워 조기 상담이 필요합니다.",
    whenItMatters: ["3개월 기한을 이미 넘겼을 때", "채무 사실을 뒤늦게 알았을 때", "단순승인으로 인한 불이익을 막고 싶을 때"],
    checks: ["기한 경과 시점·사유", "이미 한 행위(재산 처분 등)", "가정법원 허가 요건"],
    diagnosisLinks: [D.qualified, D.renunciation],
    serviceLinks: [S.qualified, S.inheritanceHub],
    faqLinks: [F.qualifiedProc, F.qualifiedVs],
    caseLinks: [C.qualified],
  }),
  term("inheritance-division-agreement", {
    term: "상속재산분할협의서",
    category: "inheritance",
    cardDescription: "공동상속인이 유산을 나누는 방법을 문서로 정리한 협의서입니다.",
    oneLineDefinition: "여러 상속인이 상속재산을 누가 어떻게 가져갈지 합의해 적는 문서입니다.",
    plainExplanation:
      "공동상속인은 원칙적으로 전원이 함께 등기·처분에 서명해야 합니다. 특정인에게 부동산을 몰아주거나 현금으로 정산하려면 분할협의서가 필요합니다. 유류분·세금·대출과 맞물리므로 문구를 신중히 작성합니다.",
    whenItMatters: ["형제·배우자 간 부동산 한 명 명의로 넘길 때", "현금 보상과 부동산 배분을 병행할 때", "상속등기 전에 분쟁을 예방하고 싶을 때"],
    checks: ["상속인 전원 동의", "유류분·특별수익 반영", "등기소 제출용 인감·위임"],
    diagnosisLinks: [D.inheritanceReg],
    serviceLinks: [S.inheritanceReg, S.inheritanceHub],
    faqLinks: [F.inheritanceWhen, F.inheritanceCost],
    caseLinks: [C.haeundaeInheritance, C.gijang],
  }),
  term("statutory-reserve-share", {
    term: "유류분",
    category: "inheritance",
    cardDescription: "일정 범위에서 상속인·유족이 반드시 받을 수 있는 최소 지분입니다.",
    oneLineDefinition: "법이 정한 최소 상속분으로, 유언·증여로 침해되면 반환을 청구할 수 있습니다.",
    plainExplanation:
      "유언으로 재산을 전부 다른 사람에게 주더라도 배우자·직계비속 등은 유류분만큼은 보호받습니다. 분할협의·증여·유언이 유류분을 넘으면 나중에 분쟁이 날 수 있어 사전 계산이 중요합니다.",
    whenItMatters: ["유언·증여가 있는 상속", "특정 자녀에게만 부동산을 주려 할 때", "분할협의서 작성 전"],
    checks: ["상속인·유류분 대상자", "특별수익·증여액", "현재 재산가액"],
    diagnosisLinks: [D.inheritanceReg],
    serviceLinks: [S.inheritanceHub, S.inheritanceReg],
    faqLinks: [F.inheritanceWhen],
    caseLinks: [C.gijang],
  }),
  term("legal-inheritance-order", {
    term: "법정상속순위",
    category: "inheritance",
    cardDescription: "유언이 없을 때 누가 어떤 순서로 상속하는지 정한 법률 규정입니다.",
    oneLineDefinition: "유언이 없으면 배우자·직계비속·직계존속 등 법이 정한 순위와 지분으로 상속합니다.",
    plainExplanation:
      "상속인이 누구인지에 따라 등기·세금·분쟁 구조가 달라집니다. 배우자와 자녀가 함께 상속하는 경우 지분 계산이 달라지고, 전원의 협의 없이는 등기가 어려울 수 있습니다.",
    whenItMatters: ["유언이 없는 상속", "배우자·자녀·부모 중 누가 상속인인지 확인할 때", "상속등기 서류를 준비할 때"],
    checks: ["가족관계증명", "전 배우자·인지 자녀 여부", "대습상속 해당 여부"],
    diagnosisLinks: [D.inheritanceReg],
    serviceLinks: [S.inheritanceHub, S.inheritanceReg],
    faqLinks: [F.inheritanceWhen],
    caseLinks: [C.haeundaeInheritance],
  }),
  term("subrogation-inheritance", {
    term: "대습상속",
    category: "inheritance",
    cardDescription: "상속인이 되려던 사람이 먼저 사망했을 때 그의 직계비속이 대신 상속하는 제도입니다.",
    oneLineDefinition: "자녀 등 상속인이 피상속인보다 먼저 사망한 경우, 그 자녀가 대신 상속인이 됩니다.",
    plainExplanation:
      "예를 들어 아버지 사망 전에 아들이 먼저 사망했다면 손자가 대습상속인이 될 수 있습니다. 상속인 수와 지분이 달라지므로 등기·분할협의·세금 계산을 다시 봐야 합니다.",
    whenItMatters: ["상속인 중 일부가 피상속인보다 먼저 사망한 경우", "손자·손녀가 상속에 참여할 때", "가족관계가 복잡한 상속"],
    checks: ["사망 순서·가족관계증명", "대습상속인 범위", "공동상속인 최종 목록"],
    diagnosisLinks: [D.inheritanceReg],
    serviceLinks: [S.inheritanceReg, S.inheritanceHub],
    faqLinks: [F.inheritanceWhen],
    caseLinks: [C.gijang],
  }),
  term("mortgage", {
    term: "근저당",
    category: "real-estate",
    cardDescription: "채무 담보를 위해 부동산 등기부에 설정하는 담보권입니다.",
    oneLineDefinition: "대출 등 채무를 담보하기 위해 부동산에 설정하는 저당권의 일종입니다.",
    plainExplanation:
      "근저당이 설정된 부동산은 채무가 남아 있는 한 권리가 제한됩니다. 상속·매매·이전등기 때 말소 여부와 채무 인수를 확인해야 하며, 채권자 동의 없이 임의로 말소할 수 없습니다.",
    whenItMatters: ["상속 부동산에 대출이 남아 있을 때", "매수인이 깨끗한 소유권을 원할 때", "담보 실행·경매 우려가 있을 때"],
    checks: ["등기부등본상 근저당 내역", "채무 잔액·말소 비용", "채권자 연락처"],
    diagnosisLinks: [D.inheritanceReg, D.realEstate],
    serviceLinks: [S.realEstate, S.inheritanceReg],
    faqLinks: [F.mortgage, F.inheritanceCost],
    caseLinks: [C.haeundaeInheritance],
  }),
  term("provisional-attachment", {
    term: "가압류",
    category: "rights",
    cardDescription: "소송 전에 채무자 재산 처분을 막기 위해 거는 임시 조치입니다.",
    oneLineDefinition: "채권 보전을 위해 법원이 재산 처분·양도를 제한하도록 하는 임시 강제조치입니다.",
    plainExplanation:
      "가압류가 걸리면 등기·매매·담보 설정이 제한됩니다. 부동산 등기부에 기재되므로 거래 전 등기부 확인이 필수입니다. 본안 소송·채권압류·강제집행과 이어지는 경우가 많습니다.",
    whenItMatters: ["등기부에 가압류가 보일 때", "부동산 매매·상속등기가 막힐 때", "채권 회수·방어를 준비할 때"],
    checks: ["가압류 채권자·채무액", "본안 소송 진행 여부", "해제·담보 제공 가능성"],
    diagnosisLinks: [D.paymentOrder],
    serviceLinks: [S.civilHub, S.realEstate],
    faqLinks: [F.mortgage],
    caseLinks: [C.ownership],
  }),
  term("attachment", {
    term: "압류",
    category: "rights",
    cardDescription: "강제집행 과정에서 채무자 재산을 특정해 처분을 막는 조치입니다.",
    oneLineDefinition: "채권자가 강제집행으로 채무자의 재산을 특정해 처분을 금지하는 절차입니다.",
    plainExplanation:
      "가압류 이후 본안 판결이 확정되면 압류·경매로 이어질 수 있습니다. 부동산·예금·채권 등 대상이 다양하며, 등기부상 압류는 매매와 등기에 직접 영향을 줍니다.",
    whenItMatters: ["등기부에 압류가 기재됐을 때", "경매 통지를 받았을 때", "채무 변제·이의를 검토할 때"],
    checks: ["압류 채권자·사건번호", "채무액·이의 기한", "배당·우선순위"],
    diagnosisLinks: [D.paymentOrder],
    serviceLinks: [S.civilHub],
    faqLinks: [F.mortgage],
    caseLinks: [C.ownership],
  }),
  term("pledge", {
    term: "질권",
    category: "rights",
    cardDescription: "채권·유가증권 등을 담보로 넘기는 권리입니다.",
    oneLineDefinition: "채무 담보를 위해 채권 등을 일정 범위에서 처분하지 못하게 하는 담보권입니다.",
    plainExplanation:
      "부동산 근저당과 달리 채권·주식·예금 등에 설정됩니다. 회사 지분·보험금·임대보증금 반환채권 등에도 걸릴 수 있어, 상속·회사 거래 시 숨은 부담이 될 수 있습니다.",
    whenItMatters: ["회사 지분·채권 거래 시", "담보 설정 여부를 확인할 때", "상속재산에 금융채권이 포함될 때"],
    checks: ["질권 설정 계약·등록", "담보 채권 범위", "변제·말소 조건"],
    diagnosisLinks: [D.corporate],
    serviceLinks: [S.corpHub, S.civilHub],
    faqLinks: [F.companyDocs],
    caseLinks: [C.company],
  }),
  term("jeonse-right", {
    term: "전세권",
    category: "real-estate",
    cardDescription: "전세금을 지급하고 부동산을 사용·수익하는 등기상 권리입니다.",
    oneLineDefinition: "전세금을 내고 건물 사용·수익권을 등기로 확보하는 물권입니다.",
    plainExplanation:
      "요즘은 전세권 설정보다 임차권등기명령·보증금 반환채권이 더 흔하지만, 등기부에 전세권이 남아 있으면 매매·상속 시 말소·인수 문제가 생깁니다. 전세금액·존속기간을 등기부에서 확인해야 합니다.",
    whenItMatters: ["등기부에 전세권이 설정돼 있을 때", "전세 만료·말소를 앞둘 때", "매수·상속 전 권리관계 확인"],
    checks: ["전세권 설정일·금액·기간", "말소 등기 여부", "전세금 반환과의 관계"],
    diagnosisLinks: [D.jeonse, D.leaseOrder],
    serviceLinks: [S.leaseHub, S.realEstate],
    faqLinks: [F.jeonse],
    caseLinks: [C.ownership],
  }),
  term("lease-registration-order", {
    term: "임차권등기명령",
    category: "real-estate",
    cardDescription: "전세·월세 보증금 보호를 위해 법원이 내리는 등기 명령입니다.",
    oneLineDefinition: "임차인이 보증금 반환을 보호받기 위해 등기소에 임차권을 등기하도록 하는 법원 명령입니다.",
    plainExplanation:
      "집주인이 바뀌거나 경매가 진행돼도 보증금 우선변제를 받기 쉽게 하려는 제도입니다. 대항력·확정일자와 함께 검토하며, 명령 신청 요건과 기한이 있습니다.",
    whenItMatters: ["전세 만료·보증금 미반환 우려", "집주인 경매·상속이 예정될 때", "임차인 권리를 강화하고 싶을 때"],
    checks: ["확정일자·전입신고", "임대차계약 기간·보증금", "배당요구·우선변제 기한"],
    diagnosisLinks: [D.leaseOrder, D.jeonse],
    serviceLinks: [S.leaseHub, S.realEstate],
    faqLinks: [F.jeonse],
    caseLinks: [C.ownership],
  }),
  term("ownership-transfer-registration", {
    term: "소유권이전등기",
    category: "real-estate",
    cardDescription: "부동산 소유자를 매수인·상속인 등 새 명의로 바꾸는 등기입니다.",
    oneLineDefinition: "매매·상속·증여 등 원인에 따라 부동산 소유자를 변경하는 등기 절차입니다.",
    plainExplanation:
      "계약만으로는 소유권이 바뀌지 않습니다. 등기소에 신청서·원인서류·세금 납부증명 등을 제출해야 합니다. 상속·매매·증여마다 필요한 서류와 세금이 다릅니다.",
    whenItMatters: ["부동산 매매·상속·증여 후", "명의가 실제와 다를 때", "대출·담보 설정 전"],
    checks: ["등기부등본·권리관계", "취득세·등록면허세", "인감·위임·원인서류"],
    diagnosisLinks: [D.ownership, D.realEstate, D.inheritanceReg],
    serviceLinks: [S.ownership, S.realEstate, S.inheritanceReg],
    faqLinks: [F.ownershipDocs, F.inheritanceCost],
    caseLinks: [C.ownership, C.haeundaeInheritance],
  }),
  term("ownership-preservation-registration", {
    term: "소유권보존등기",
    category: "real-estate",
    cardDescription: "처음으로 등기부에 소유자를 적는 최초 소유권 등기입니다.",
    oneLineDefinition: "신축·분양 등으로 등기가 없던 부동산에 최초로 소유자를 등기하는 절차입니다.",
    plainExplanation:
      "이전등기와 달리 ‘처음 등기’에 해당합니다. 건축물대장·토지대장과 맞춰 신청하며, 이후 매매·담보는 이전등기로 이어집니다. 미등기 상태로 거래하면 위험이 큽니다.",
    whenItMatters: ["신축·신규 분양 후", "등기부가 비어 있을 때", "보존등기 없이 거래하려 할 때"],
    checks: ["건축물대장·토지대장", "분양계약·사용승인", "세금·부담금"],
    diagnosisLinks: [D.realEstate, D.ownership],
    serviceLinks: [S.realEstate, S.ownership],
    faqLinks: [F.ownershipDocs],
    caseLinks: [C.ownership],
  }),
  term("registration-license-tax", {
    term: "등록면허세",
    category: "tax-fee",
    cardDescription: "부동산·법인 등 각종 등기·등록 시 납부하는 지방세입니다.",
    oneLineDefinition: "등기·등록 행위에 대해 부과되는 지방세로, 등기 신청 전 납부가 필요합니다.",
    plainExplanation:
      "상속·매매·담보·법인 변경마다 세율과 과세표준이 다릅니다. 납부 후 영수증을 등기 신청에 첨부해야 하며, 감면·비과세 여부를 미리 보면 비용을 줄일 수 있습니다.",
    whenItMatters: ["상속등기·이전등기·담보설정 전", "법인 등기 변경 시", "비용 견적을 낼 때"],
    checks: ["과세표준·세율", "감면 대상 여부", "관할 구청 납부"],
    diagnosisLinks: [D.inheritanceReg, D.ownership],
    serviceLinks: [S.inheritanceReg, S.realEstate],
    faqLinks: [F.inheritanceCost, F.ownershipDocs],
    caseLinks: [C.haeundaeInheritance],
  }),
  term("acquisition-tax", {
    term: "취득세",
    category: "tax-fee",
    cardDescription: "부동산·차량 등을 취득할 때 내는 지방세입니다.",
    oneLineDefinition: "부동산 등 재산을 취득할 때 납부하는 세금으로, 상속·매매·증여마다 세율이 다릅니다.",
    plainExplanation:
      "상속 취득은 신고 기한이 있고, 주택 수·가액에 따라 부담이 달라집니다. 취득세를 내야 등록면허세·등기 신청으로 넘어갈 수 있는 경우가 많습니다.",
    whenItMatters: ["상속·매매·증여 직후", "등기 전 세금 신고", "1세대 1주택 감면 검토"],
    checks: ["취득 원인·시기", "주택 보유 현황", "신고·납부 기한"],
    diagnosisLinks: [D.inheritanceReg, D.ownership],
    serviceLinks: [S.inheritanceReg, S.ownership],
    faqLinks: [F.inheritanceCost],
    caseLinks: [C.haeundaeInheritance, C.gijang],
  }),
  term("stamp-duty", {
    term: "인지대",
    category: "tax-fee",
    cardDescription: "계약서·신청서 등에 붙이는 수입인지 비용입니다.",
    oneLineDefinition: "법률행위나 신청서류에 부착하는 인지세로, 금액은 문서 종류·계약금액에 따라 정해집니다.",
    plainExplanation:
      "상속·매매·소송·회생 등 여러 절차에서 인지를 붙입니다. 금액 산정이 틀리면 접수가 반려될 수 있어, 최신 인지 규정을 확인하는 것이 좋습니다.",
    whenItMatters: ["법원·등기소 접수 직전", "계약서 작성 시", "여러 부본이 필요할 때"],
    checks: ["문서 종류·매수", "계약금액 구간", "전자수입인지 가능 여부"],
    diagnosisLinks: [D.inheritanceReg, D.paymentOrder],
    serviceLinks: [S.inheritanceHub, S.civilHub],
    faqLinks: [F.inheritanceCost],
    caseLinks: [C.renunciation],
  }),
  term("service-fee", {
    term: "송달료",
    category: "tax-fee",
    cardDescription: "법원이 문서를 당사자에게 보낼 때 부과하는 비용입니다.",
    oneLineDefinition: "소송·가사·회생 등 법원 절차에서 서류 송달에 필요한 실비 성격의 비용입니다.",
    plainExplanation:
      "소장·답변서·결정문 등을 보낼 때마다 송달료가 더해집니다. 예납·추납이 필요할 수 있어 사건마다 예상 비용을 잡아 두는 것이 좋습니다.",
    whenItMatters: ["소송·가사신청·회생 신청 시", "법원 접수 비용을 계산할 때", "추가 송달이 반복될 때"],
    checks: ["사건 종류·당사자 수", "예납 송달료", "추가 송달 발생 여부"],
    diagnosisLinks: [D.paymentOrder, D.rehab],
    serviceLinks: [S.civilHub, S.rehabHub],
    faqLinks: [F.rehabDocs],
    caseLinks: [C.rehab],
  }),
  term("payment-order", {
    term: "지급명령",
    category: "civil",
    cardDescription: "간단한 채권에 대해 법원이 빠르게 지급을 명하는 절차입니다.",
    oneLineDefinition: "인지 없는 채무 등에 대해 채권자가 신청하면 법원이 지급을 명하는 민사 절차입니다.",
    plainExplanation:
      "소장보다 빠르고 비용이 적은 편이지만, 채무자가 이의를 제기하면 본안 소송으로 넘어갑니다. 내용증명·계약서 등 증빙이 중요합니다.",
    whenItMatters: ["대여금·임대료 등 분쟁", "빠른 채권 회수가 필요할 때", "소송 전 단계를 검토할 때"],
    checks: ["채권 원인·금액", "이의신청 기한", "송달료·인지대"],
    diagnosisLinks: [D.paymentOrder, D.certified],
    serviceLinks: [S.civilHub],
    faqLinks: [F.jeonse],
    caseLinks: [C.ownership],
  }),
  term("certified-mail", {
    term: "내용증명",
    category: "civil",
    cardDescription: "우체국을 통해 내용을 공식적으로 전달·증명하는 우편 서비스입니다.",
    oneLineDefinition: "발송 내용과 일자를 증명하는 우편으로, 계약 해지·최고·협의 촉구에 자주 씁니다.",
    plainExplanation:
      "분쟁 예방과 증거 확보에 유용합니다. 문구가 부정확하면 오히려 불리해질 수 있어, 해지·최고·협의 요청 목적에 맞게 작성하는 것이 좋습니다.",
    whenItMatters: ["임대차 해지·갱신 거절", "대여금 변제 최고", "분쟁 전 사실관계 정리"],
    checks: ["수신인 주소·성명", "발송 목적에 맞는 문구", "보관용 부본"],
    diagnosisLinks: [D.certified, D.leaseOrder],
    serviceLinks: [S.leaseHub, S.civilHub],
    faqLinks: [F.jeonse],
    caseLinks: [C.ownership],
  }),
  term("complaint", {
    term: "소장",
    category: "civil",
    cardDescription: "법원에 민사 분쟁의 재판을 청구하는 서면입니다.",
    oneLineDefinition: "원고가 피고를 상대로 청구취지·원인을 적어 법원에 제출하는 소송 개시 서류입니다.",
    plainExplanation:
      "소장이 접수되면 소송이 시작됩니다. 청구취지·청구원인·증거 목록을 정확히 적어야 하며, 인지대·송달료를 함께 준비합니다. 지급명령과 비교해 절차·비용이 달라집니다.",
    whenItMatters: ["협의가 결렬됐을 때", "본안 판결을 받고 싶을 때", "지급명령에 이의가 제기됐을 때"],
    checks: ["관할 법원", "청구금액·원인", "증거자료·인지·송달료"],
    diagnosisLinks: [D.paymentOrder],
    serviceLinks: [S.civilHub],
    faqLinks: [F.jeonse],
    caseLinks: [C.ownership],
  }),
  term("answer-brief", {
    term: "답변서",
    category: "civil",
    cardDescription: "피고가 원고 청구에 대해 법원에 제출하는 반박 서면입니다.",
    oneLineDefinition: "소송에서 피고가 원고 주장에 대한 인부·반박을 적어 제출하는 서류입니다.",
    plainExplanation:
      "답변 기한을 놓치면 불리한 판단을 받을 수 있습니다. 사실관계 부인·항변·반소를 함께 검토하며, 증거를 체계적으로 제출하는 것이 중요합니다.",
    whenItMatters: ["소장을 받았을 때", "지급명령에 이의할 때", "반소·항변을 검토할 때"],
    checks: ["답변 제출 기한", "원고 청구취지 분석", "증거·인감"],
    diagnosisLinks: [D.paymentOrder],
    serviceLinks: [S.civilHub],
    faqLinks: [F.jeonse],
    caseLinks: [C.ownership],
  }),
  term("personal-rehabilitation", {
    term: "개인회생",
    category: "rehab",
    cardDescription: "일정 소득이 있는 채무자가 법원 인가 하에 변제 계획을 이행하는 제도입니다.",
    oneLineDefinition: "채무를 일정 기간 나눠 갚고 남은 채무를 면제받는 법원 절차입니다.",
    plainExplanation:
      "소득·재산·채무 규모에 따라 가능 여부가 갈립니다. 신청서·채권자 목록·변제계획안을 제출하고, 인가 후 3~5년 변제가 일반적입니다. 금지명령으로 추심을 멈출 수 있습니다.",
    whenItMatters: ["채무가 소득으로 갚을 만할 때", "압류·추심을 멈추고 싶을 때", "파산 대신 재기를 검토할 때"],
    checks: ["총 채무·소득·재산", "최근 5년 면책 이력", "가족 부양·주거"],
    diagnosisLinks: [D.rehab, D.bankruptcy],
    serviceLinks: [S.rehab, S.rehabHub],
    faqLinks: [F.rehabElig, F.rehabDocs, F.bankruptcyVs],
    caseLinks: [C.rehab],
  }),
  term("personal-bankruptcy", {
    term: "개인파산",
    category: "rehab",
    cardDescription: "재산을 정리하고 면책으로 채무를 해소하는 절차입니다.",
    oneLineDefinition: "지급 불능 상태의 채무자가 법원에 파산을 신청하고 면책을 받는 제도입니다.",
    plainExplanation:
      "회생과 달리 재산 매각·배당 후 남은 채무를 면책받는 구조입니다. 신청 요건·불가채권·면책 불허 사유를 확인해야 하며, 이후 신용·재취업에 영향이 있을 수 있습니다.",
    whenItMatters: ["소득으로 갚기 어려울 때", "회생 요건을 충족하지 못할 때", "채무를 일괄 정리하고 싶을 때"],
    checks: ["채무·재산·소득", "면책 불허 사유", "가족에게 미치는 영향"],
    diagnosisLinks: [D.bankruptcy, D.rehab],
    serviceLinks: [S.bankruptcy, S.rehabHub],
    faqLinks: [F.bankruptcyVs, F.rehabElig],
    caseLinks: [C.rehab],
  }),
  term("discharge", {
    term: "면책",
    category: "rehab",
    cardDescription: "파산·회생 절차 후 남은 채무를 법적으로 면제받는 결정입니다.",
    oneLineDefinition: "파산 또는 회생 절차를 마친 뒤 채무자가 더 이상 갚지 않아도 되게 하는 법원 결정입니다.",
    plainExplanation:
      "면책이 확정되면 원칙적으로 채권자는 더 이상 추심할 수 없습니다. 다만 세금·가족양육비 등 면책되지 않는 채무가 있고, 면책 불허 사유도 제한됩니다.",
    whenItMatters: ["파산·회생 종료 후", "추심이 계속될 때", "재기 시점을 정할 때"],
    checks: ["면책 확정 여부", "불가채권 목록", "신용회복 일정"],
    diagnosisLinks: [D.bankruptcy, D.rehab],
    serviceLinks: [S.bankruptcy, S.rehab],
    faqLinks: [F.bankruptcyVs, F.rehabElig],
    caseLinks: [C.rehab],
  }),
  term("company-establishment-registration", {
    term: "법인설립등기",
    category: "corporate",
    cardDescription: "주식회사 등 법인을 등기부에 처음 등록하는 절차입니다.",
    oneLineDefinition: "정관·발기인 결의 등을 바탕으로 새 법인을 등기소에 등록하는 최초 등기입니다.",
    plainExplanation:
      "설립등기가 끝나야 은행 계좌·사업자등록·계약 체결이 수월해집니다. 자본금·임원·본점 소재지를 정관과 일치시키고, 등록세·등기 수수료를 납부합니다.",
    whenItMatters: ["창업·법인 전환 시", "투자·대출 전 법인격 확보", "지분·임원 구조를 문서화할 때"],
    checks: ["정관·발기인 서류", "자본금 납입", "본점 주소·임원"],
    diagnosisLinks: [D.company, D.corporate],
    serviceLinks: [S.company, S.corpHub],
    faqLinks: [F.companyDocs],
    caseLinks: [C.company],
  }),
  term("director-change-registration", {
    term: "임원변경등기",
    category: "corporate",
    cardDescription: "대표이사·이사 등 법인 임원 변경을 등기하는 절차입니다.",
    oneLineDefinition: "법인 임원의 취임·퇴임·주소 변경 등을 등기부에 반영하는 등기입니다.",
    plainExplanation:
      "주주총회·이사회 결의 후 일정 기한 안에 신청해야 합니다. 대표권·은행 거래·계약 서명 권한과 직결되므로 지연 시 거래에 차질이 생길 수 있습니다.",
    whenItMatters: ["대표이사 교체", "이사·감사 변경", "임원 주소 변경"],
    checks: ["주주총회·이사회 의사록", "취임 승낙·인감", "신청 기한"],
    diagnosisLinks: [D.director, D.corporate],
    serviceLinks: [S.director, S.corpHub],
    faqLinks: [F.directorDeadline],
    caseLinks: [C.director],
  }),
  term("head-office-move-registration", {
    term: "본점이전등기",
    category: "corporate",
    cardDescription: "법인 본점 소재지를 등기부상 다른 주소로 옮기는 등기입니다.",
    oneLineDefinition: "회사 본점을 다른 시·군·구로 이전할 때 등기소에 신청하는 주소 변경 등기입니다.",
    plainExplanation:
      "관할 등기소가 바뀔 수 있어 세무서·사업장 신고도 함께 봐야 합니다. 임대차·등기 가능 여부를 먼저 확인하고, 이사회·주총 결의 후 신청합니다.",
    whenItMatters: ["사무실 이전·지역 이동", "관할·세무 변경", "등기부 주소와 실제 불일치"],
    checks: ["새 본점 임대차·사용승인", "이사회·주총 결의", "세무·4대보험 이전"],
    diagnosisLinks: [D.corporate],
    serviceLinks: [S.corporate, S.corpHub],
    faqLinks: [F.corpAddress],
    caseLinks: [C.company, C.director],
  }),
  term("purpose-change-registration", {
    term: "목적변경등기",
    category: "corporate",
    cardDescription: "정관상 회사 사업 목적을 바꿔 등기부에 반영하는 절차입니다.",
    oneLineDefinition: "법인이 할 수 있는 사업 범위(정관 목적)를 변경하고 등기하는 절차입니다.",
    plainExplanation:
      "신사업·업종 추가 시 목적 조항을 먼저 바꿔야 하는 경우가 많습니다. 주주총회 특별결의가 필요할 수 있으며, 인허가·세무 분류와도 연결됩니다.",
    whenItMatters: ["신규 사업·업종 추가", "투자 심사·계약 전", "정관과 실제 사업 불일치"],
    checks: ["변경할 목적 문구", "주주총회 결의", "인허가 영향"],
    diagnosisLinks: [D.corporate, D.company],
    serviceLinks: [S.corporate, S.corpHub],
    faqLinks: [F.companyDocs],
    caseLinks: [C.company],
  }),
  term("dissolution-registration", {
    term: "해산등기",
    category: "corporate",
    cardDescription: "법인 존속을 종료하기로 결의한 사실을 등기하는 절차입니다.",
    oneLineDefinition: "주주총회 등으로 법인 해산을 결의한 뒤 등기소에 해산 사실을 등록하는 등기입니다.",
    plainExplanation:
      "해산은 회사 생명의 종료를 선언하는 단계입니다. 이후 청산인이 자산을 정리하고 채무를 변제한 뒤 청산등기로 마무리합니다. 해산 사유·결의 절차를 지켜야 합니다.",
    whenItMatters: ["회사 폐업·합병 전", "사업 종료 결의 후", "청산 절차 시작"],
    checks: ["해산 사유·주총 결의", "청산인 선임", "채권자 공고"],
    diagnosisLinks: [D.corporate],
    serviceLinks: [S.corporate, S.corpHub],
    faqLinks: [F.companyDocs, F.corpAddress],
    caseLinks: [C.company],
  }),
  term("liquidation-registration", {
    term: "청산등기",
    category: "corporate",
    cardDescription: "청산을 마치고 법인을 최종적으로 말소하는 등기입니다.",
    oneLineDefinition: "해산 후 재산·채무 정리를 끝내고 법인 존재를 소멸시키는 마지막 등기입니다.",
    plainExplanation:
      "청산인이 잔여재산 배분·채무 변제·국세·지방세 정리를 마친 뒤 신청합니다. 중간에 청산종결보고와 채권자 보호 절차가 필요하며, 미완료 세무가 있으면 지연됩니다.",
    whenItMatters: ["해산 후 최종 폐업", "법인 말소 완료", "잔여재산 배분 종료"],
    checks: ["청산 종결 보고", "세무·채무 정리", "잔여재산 처분"],
    diagnosisLinks: [D.corporate],
    serviceLinks: [S.corporate, S.corpHub],
    faqLinks: [F.companyDocs],
    caseLinks: [C.company],
  }),
];

export function getAllGlossaryTerms(): GlossaryTerm[] {
  return GLOSSARY_TERMS;
}

export function getGlossaryTermBySlug(slug: string): GlossaryTerm | undefined {
  return GLOSSARY_TERMS.find((t) => t.slug === slug);
}

export function getGlossaryTermSlugs(): string[] {
  return GLOSSARY_TERMS.map((t) => t.slug);
}
