/**
 * 비상속 seed. 상속|포기|한정승인|대습|유류분|유언 포함 query는 넣지 않는다.
 */
export type NonInheritanceSeed = {
  keyword: string;
  cluster: string;
  owner: string;
  note?: string;
};

export const NON_INHERITANCE_SEEDS: NonInheritanceSeed[] = [
  { keyword: "부산 법무사", cluster: "상담/비용", owner: "/" },
  { keyword: "부산법무사", cluster: "상담/비용", owner: "/" },
  { keyword: "부산 법무사 상담", cluster: "상담/비용", owner: "/부산법무사상담" },
  { keyword: "부산 법무사 추천", cluster: "상담/비용", owner: "/부산법무사추천" },
  { keyword: "부산 법무사 비용", cluster: "상담/비용", owner: "/부산법무사비용" },
  { keyword: "부산 법무사 수수료", cluster: "상담/비용", owner: "/부산법무사비용" },
  { keyword: "부산 법무사 보수", cluster: "상담/비용", owner: "/부산법무사비용" },
  { keyword: "부산 법무사 사무실", cluster: "상담/비용", owner: "/부산법무사무소" },
  { keyword: "부산 여성 법무사", cluster: "상담/비용", owner: "/부산여성법무사" },
  { keyword: "부산 법무사 직접상담", cluster: "상담/비용", owner: "/부산법무사상담" },

  { keyword: "해운대 법무사", cluster: "해운대권", owner: "/해운대법무사" },
  { keyword: "해운대구 법무사", cluster: "해운대권", owner: "/해운대법무사" },
  { keyword: "센텀 법무사", cluster: "해운대권", owner: "/센텀법무사" },
  { keyword: "센텀시티 법무사", cluster: "해운대권", owner: "/센텀법무사" },
  { keyword: "재송동 법무사", cluster: "해운대권", owner: "/재송동법무사" },
  { keyword: "재송역 법무사", cluster: "해운대권", owner: "/재송동법무사" },
  { keyword: "반여동 법무사", cluster: "해운대권", owner: "/반여동법무사" },
  { keyword: "우동 법무사", cluster: "해운대권", owner: "/우동법무사" },
  { keyword: "좌동 법무사", cluster: "해운대권", owner: "/좌동법무사" },
  { keyword: "장산 법무사", cluster: "해운대권", owner: "/좌동법무사", note: "NEW_PAGE_CANDIDATE 아님. 좌동 허브." },

  { keyword: "수영구 법무사", cluster: "수영권", owner: "/수영구법무사" },
  { keyword: "수영 법무사", cluster: "수영권", owner: "/수영구법무사" },
  { keyword: "광안동 법무사", cluster: "수영권", owner: "/광안동법무사" },
  { keyword: "광안리 법무사", cluster: "수영권", owner: "/광안리법무사" },
  { keyword: "민락동 법무사", cluster: "수영권", owner: "/민락동법무사" },
  { keyword: "망미동 법무사", cluster: "수영권", owner: "/망미동법무사" },
  { keyword: "남천동 법무사", cluster: "수영권", owner: "/남천동법무사" },

  { keyword: "연제구 법무사", cluster: "연제권", owner: "/연제구법무사" },
  { keyword: "연산동 법무사", cluster: "연제권", owner: "/연산동법무사" },
  { keyword: "거제동 법무사", cluster: "연제권", owner: "/거제동법무사" },
  { keyword: "시청 법무사", cluster: "연제권", owner: "/연제구법무사" },
  { keyword: "부산지방법원 법무사", cluster: "연제권", owner: "/부산지방법원법무사" },
  { keyword: "부산법원 법무사", cluster: "연제권", owner: "/부산지방법원법무사" },

  { keyword: "동래구 법무사", cluster: "동래권", owner: "/동래구법무사" },
  { keyword: "동래 법무사", cluster: "동래권", owner: "/동래구법무사" },
  { keyword: "사직동 법무사", cluster: "동래권", owner: "/사직동법무사" },
  { keyword: "온천동 법무사", cluster: "동래권", owner: "/온천동법무사" },
  { keyword: "명륜동 법무사", cluster: "동래권", owner: "/동래구법무사" },
  { keyword: "동래역 법무사", cluster: "동래권", owner: "/동래역법무사" },

  { keyword: "부산진구 법무사", cluster: "부산진/서면", owner: "/부산진구법무사" },
  { keyword: "서면 법무사", cluster: "부산진/서면", owner: "/서면법무사" },
  { keyword: "부전동 법무사", cluster: "부산진/서면", owner: "/부전동법무사" },
  { keyword: "전포동 법무사", cluster: "부산진/서면", owner: "/전포동법무사" },
  { keyword: "양정동 법무사", cluster: "부산진/서면", owner: "/양정동법무사" },
  { keyword: "범천동 법무사", cluster: "부산진/서면", owner: "/부산진구법무사", note: "별도 URL 미생성" },

  { keyword: "남구 법무사", cluster: "남구", owner: "/남구법무사" },
  { keyword: "부산 남구 법무사", cluster: "남구", owner: "/남구법무사" },
  { keyword: "대연동 법무사", cluster: "남구", owner: "/대연동법무사" },
  { keyword: "용호동 법무사", cluster: "남구", owner: "/용호동법무사" },
  { keyword: "문현동 법무사", cluster: "남구", owner: "/문현동법무사" },
  { keyword: "문현금융단지 법무사", cluster: "남구", owner: "/문현동법무사" },

  { keyword: "북구 법무사", cluster: "북구", owner: "/북구법무사" },
  { keyword: "부산 북구 법무사", cluster: "북구", owner: "/북구법무사" },
  { keyword: "화명동 법무사", cluster: "북구", owner: "/화명동법무사" },
  { keyword: "덕천동 법무사", cluster: "북구", owner: "/덕천동법무사" },
  { keyword: "만덕동 법무사", cluster: "북구", owner: "/북구법무사" },

  { keyword: "강서구 법무사", cluster: "서부산", owner: "/강서구법무사" },
  { keyword: "부산 강서구 법무사", cluster: "서부산", owner: "/강서구법무사" },
  { keyword: "명지 법무사", cluster: "서부산", owner: "/명지법무사" },
  { keyword: "명지국제신도시 법무사", cluster: "서부산", owner: "/명지법무사" },
  { keyword: "에코델타시티 법무사", cluster: "서부산", owner: "/강서구법무사" },

  { keyword: "기장 법무사", cluster: "동부산", owner: "/기장군법무사" },
  { keyword: "기장군 법무사", cluster: "동부산", owner: "/기장군법무사" },
  { keyword: "정관 법무사", cluster: "동부산", owner: "/정관법무사" },
  { keyword: "일광 법무사", cluster: "동부산", owner: "/일광읍법무사" },

  { keyword: "사상구 법무사", cluster: "서부산", owner: "/사상구법무사" },
  { keyword: "사상 법무사", cluster: "서부산", owner: "/사상법무사" },
  { keyword: "주례동 법무사", cluster: "서부산", owner: "/주례동법무사" },
  { keyword: "엄궁동 법무사", cluster: "서부산", owner: "/사상구법무사", note: "별도 URL 미생성" },

  { keyword: "사하구 법무사", cluster: "서부산", owner: "/사하구법무사" },
  { keyword: "하단 법무사", cluster: "서부산", owner: "/하단법무사" },
  { keyword: "하단동 법무사", cluster: "서부산", owner: "/하단법무사" },
  { keyword: "괴정동 법무사", cluster: "서부산", owner: "/괴정동법무사" },

  { keyword: "금정구 법무사", cluster: "동부산", owner: "/금정구법무사" },
  { keyword: "부곡동 법무사", cluster: "동부산", owner: "/부곡동법무사" },
  { keyword: "구서동 법무사", cluster: "동부산", owner: "/구서동법무사" },
  { keyword: "부산대 법무사", cluster: "동부산", owner: "/금정구법무사" },

  { keyword: "중구 법무사", cluster: "원도심", owner: "/중구법무사" },
  { keyword: "남포동 법무사", cluster: "원도심", owner: "/남포동법무사" },
  { keyword: "부산 서구 법무사", cluster: "원도심", owner: "/서구법무사" },
  { keyword: "서대신동 법무사", cluster: "원도심", owner: "/서구법무사" },
  { keyword: "동대신동 법무사", cluster: "원도심", owner: "/서구법무사" },
  { keyword: "영도구 법무사", cluster: "원도심", owner: "/영도구법무사" },
  { keyword: "영도 법무사", cluster: "원도심", owner: "/영도구법무사" },
  { keyword: "동삼동 법무사", cluster: "원도심", owner: "/동삼동법무사" },
  { keyword: "부산 동구 법무사", cluster: "원도심", owner: "/동구법무사" },
  { keyword: "초량동 법무사", cluster: "원도심", owner: "/초량동법무사" },

  { keyword: "부산 부동산 법무사", cluster: "부동산", owner: "/부산부동산등기" },
  { keyword: "부산 부동산등기 법무사", cluster: "부동산", owner: "/부산부동산등기" },
  { keyword: "부산 등기 법무사", cluster: "부동산", owner: "/부산등기법무사" },
  { keyword: "부산 등기전문 법무사", cluster: "부동산", owner: "/부산등기법무사" },
  { keyword: "부산 소유권이전등기 법무사", cluster: "부동산", owner: "/부산소유권이전등기" },
  { keyword: "부산 아파트 등기 법무사", cluster: "부동산", owner: "/부산부동산등기" },
  { keyword: "부산 매매등기 법무사", cluster: "부동산", owner: "/부산소유권이전등기" },
  { keyword: "부산 증여등기 법무사", cluster: "부동산", owner: "/부산증여등기" },
  { keyword: "부산 부담부증여 법무사", cluster: "부동산", owner: "/부산증여등기" },
  { keyword: "부산 근저당 설정 법무사", cluster: "부동산", owner: "/부산근저당설정등기" },
  { keyword: "부산 근저당 말소 법무사", cluster: "부동산", owner: "/부산근저당말소등기" },
  { keyword: "부산 전세권 설정 법무사", cluster: "부동산", owner: "/부산전세권설정등기" },
  { keyword: "부산 전세권 말소 법무사", cluster: "부동산", owner: "/부산전세권말소등기" },
  { keyword: "부산 보존등기 법무사", cluster: "부동산", owner: "/부산신축건물보존등기" },
  { keyword: "부산 멸실등기 법무사", cluster: "부동산", owner: "/부산부동산등기" },
  { keyword: "부산 가등기 법무사", cluster: "부동산", owner: "/부산가등기" },

  { keyword: "부산 임차권등기명령 법무사", cluster: "임대차", owner: "/부산임차권등기명령" },
  { keyword: "부산 임차권등기 법무사", cluster: "임대차", owner: "/부산임차권등기명령" },
  { keyword: "부산 전세보증금 반환 법무사", cluster: "임대차", owner: "/부산전세보증금반환법무사" },
  { keyword: "부산 전세사기 법무사", cluster: "임대차", owner: "/전세사기예방교육" },
  { keyword: "부산 전세권 법무사", cluster: "임대차", owner: "/부산전세권설정등기" },

  { keyword: "부산 법인 법무사", cluster: "법인", owner: "/부산법인법무사" },
  { keyword: "부산 법인등기 법무사", cluster: "법인", owner: "/부산법인등기" },
  { keyword: "부산 법인등기", cluster: "법인", owner: "/부산법인등기" },
  { keyword: "부산 법인설립 법무사", cluster: "법인", owner: "/부산법인설립등기" },
  { keyword: "부산 회사설립 법무사", cluster: "법인", owner: "/부산법인설립등기" },
  { keyword: "부산 임원변경등기 법무사", cluster: "법인", owner: "/부산임원변경등기" },
  { keyword: "부산 대표이사 변경등기", cluster: "법인", owner: "/부산임원변경등기" },
  { keyword: "부산 임원중임 법무사", cluster: "법인", owner: "/부산임원변경등기" },
  { keyword: "부산 본점이전등기", cluster: "법인", owner: "/부산본점이전등기" },
  { keyword: "부산 목적변경등기", cluster: "법인", owner: "/부산사업목적변경등기" },
  { keyword: "부산 증자등기", cluster: "법인", owner: "/부산유상증자등기" },
  { keyword: "부산 감자등기", cluster: "법인", owner: "/부산법인등기" },
  { keyword: "부산 지점설치등기", cluster: "법인", owner: "/부산법인등기" },
  { keyword: "부산 해산등기", cluster: "법인", owner: "/부산법인해산청산등기" },
  { keyword: "부산 청산등기", cluster: "법인", owner: "/부산법인해산청산등기" },

  { keyword: "부산 개인회생 법무사", cluster: "회생/파산", owner: "/부산개인회생법무사" },
  { keyword: "부산 개인회생", cluster: "회생/파산", owner: "/부산개인회생" },
  { keyword: "부산 회생 법무사", cluster: "회생/파산", owner: "/부산개인회생법무사" },
  { keyword: "부산 회생파산 법무사", cluster: "회생/파산", owner: "/개인회생파산" },
  { keyword: "부산 개인파산 법무사", cluster: "회생/파산", owner: "/부산개인파산법무사" },
  { keyword: "부산 개인파산", cluster: "회생/파산", owner: "/부산개인파산" },
  { keyword: "부산 파산면책 법무사", cluster: "회생/파산", owner: "/부산개인파산" },
  { keyword: "부산 개인회생 비용", cluster: "회생/파산", owner: "/개인회생비용" },
  { keyword: "부산 개인파산 비용", cluster: "회생/파산", owner: "/개인파산비용" },

  { keyword: "부산 지급명령 법무사", cluster: "민사", owner: "/부산지방법원지급명령" },
  { keyword: "부산 내용증명 법무사", cluster: "민사", owner: "/내용증명작성준비" },
  { keyword: "부산 미수금 법무사", cluster: "민사", owner: "/민사소송" },
  { keyword: "부산 가압류 법무사", cluster: "민사", owner: "/부산가압류말소등기" },
  { keyword: "부산 가압류 말소 법무사", cluster: "민사", owner: "/부산가압류말소등기" },
  { keyword: "부산 개명 법무사", cluster: "민사", owner: "/부산개명허가" },

  { keyword: "부산 선박등기 법무사", cluster: "기타", owner: "/부산선박등기" },
  { keyword: "부산 선박 법무사", cluster: "기타", owner: "/부산선박등기" },
  { keyword: "부산 촉탁등기 법무사", cluster: "기타", owner: "/부산부동산등기" },
  { keyword: "부산 신탁등기 법무사", cluster: "기타", owner: "/부산부동산등기" },
];

export const INHERITANCE_QUERY_RE = /상속|포기|한정승인|대습|유류분|유언/;
