import type { ArticleImageAsset } from "./types";

/**
 * 본문 배치용 이미지 카탈로그.
 * 원본은 public/image 유지, 표시는 derivedSrc 우선.
 * 전 페이지 자동 배치를 위해 maxBodyUses는 소프트 가이드(강제 중단 없음).
 */
export const articleImageCatalog: Record<string, ArticleImageAsset> = {
  docReviewDesk: {
    id: "docReviewDesk",
    originalSrc: "/image/썸네일-서류확인.jpg",
    derivedSrc: "/image/derived/doc-review-desk.webp",
    width: 1280,
    height: 1710,
    category: "document-review",
    isLawyerPhoto: true,
    usable: true,
    fields: ["inheritance", "qualified-acceptance", "real-estate", "general"],
    overlaySafe: ["left", "right"],
    mobileFocus: "face",
    maxBodyUses: 500,
    notes: "안윤정 법무사 실제 사진 · 서류 검토",
  },
  contractOfficerReview: {
    id: "contractOfficerReview",
    originalSrc: "/image/썸네일-계약임원.jpg",
    derivedSrc: "/image/derived/contract-officer-review.webp",
    width: 1280,
    height: 960,
    category: "document-review",
    isLawyerPhoto: true,
    usable: true,
    fields: ["corporate", "director-change", "establishment", "building"],
    overlaySafe: ["right"],
    mobileFocus: "face",
    maxBodyUses: 500,
  },
  inheritanceRegCert: {
    id: "inheritanceRegCert",
    originalSrc: "/image/썸네일-등기필증_상속.jpg",
    derivedSrc: "/image/derived/inheritance-reg-cert.webp",
    width: 1280,
    height: 960,
    category: "registration-document",
    isLawyerPhoto: false,
    usable: true,
    fields: ["inheritance", "real-estate"],
    overlaySafe: ["center"],
    mobileFocus: "center",
    maxBodyUses: 400,
  },
  saleGiftRegCert: {
    id: "saleGiftRegCert",
    originalSrc: "/image/썸네일-등기필증_매매증여.jpg",
    derivedSrc: "/image/derived/sale-gift-reg-cert.webp",
    width: 1280,
    height: 960,
    category: "registration-document",
    isLawyerPhoto: false,
    usable: true,
    fields: ["real-estate", "ownership-transfer", "building"],
    overlaySafe: ["center"],
    mobileFocus: "center",
    maxBodyUses: 400,
  },
  mortgageRegCert: {
    id: "mortgageRegCert",
    originalSrc: "/image/썸네일-등기필증_근저당.jpg",
    derivedSrc: "/image/derived/mortgage-reg-cert.webp",
    width: 1280,
    height: 960,
    category: "registration-document",
    isLawyerPhoto: false,
    usable: true,
    fields: ["real-estate", "inheritance"],
    overlaySafe: ["center"],
    mobileFocus: "center",
    maxBodyUses: 400,
  },
  registryOfficeVisit: {
    id: "registryOfficeVisit",
    originalSrc: "/image/썸네일-등기소.jpg",
    derivedSrc: "/image/derived/registry-office-visit.webp",
    width: 1280,
    height: 1710,
    category: "registry-court",
    isLawyerPhoto: true,
    usable: true,
    fields: ["real-estate", "corporate", "building", "general"],
    overlaySafe: ["left"],
    mobileFocus: "face",
    maxBodyUses: 400,
  },
  consultMain: {
    id: "consultMain",
    originalSrc: "/image/상담-메인.jpg",
    derivedSrc: "/image/derived/consult-main.webp",
    width: 1280,
    height: 960,
    category: "consultation",
    isLawyerPhoto: true,
    usable: true,
    fields: ["consultation", "general", "rehab", "situations"],
    overlaySafe: ["left"],
    mobileFocus: "face",
    maxBodyUses: 500,
  },
  portraitFront: {
    id: "portraitFront",
    originalSrc: "/image/썸네일-정면.jpg",
    derivedSrc: "/image/derived/portrait-front.webp",
    width: 1280,
    height: 960,
    category: "lawyer-portrait",
    isLawyerPhoto: true,
    usable: true,
    fields: ["general", "consultation", "rehab"],
    overlaySafe: ["left", "right"],
    mobileFocus: "face",
    maxBodyUses: 500,
  },
  deskComputer: {
    id: "deskComputer",
    originalSrc: "/image/썸네일-서류등기.jpg",
    derivedSrc: "/image/derived/desk-computer.webp",
    width: 1280,
    height: 960,
    category: "document-review",
    isLawyerPhoto: true,
    usable: true,
    fields: ["corporate", "rehab", "general"],
    overlaySafe: ["right"],
    mobileFocus: "face",
    maxBodyUses: 400,
  },
  consultTalk: {
    id: "consultTalk",
    originalSrc: "/image/썸네일-상담협의.jpg",
    derivedSrc: "/image/derived/consult-talk.webp",
    width: 1280,
    height: 960,
    category: "consultation",
    isLawyerPhoto: true,
    usable: true,
    fields: ["consultation", "situations", "rehab", "inheritance"],
    overlaySafe: ["left", "center"],
    mobileFocus: "face",
    maxBodyUses: 400,
  },
  courtProcedureBook: {
    id: "courtProcedureBook",
    originalSrc: "/image/썸네일-법원절차.jpg",
    derivedSrc: "/image/derived/court-procedure.webp",
    width: 1280,
    height: 960,
    category: "other",
    isLawyerPhoto: false,
    usable: true,
    fields: ["rehab", "payment-order", "court"],
    overlaySafe: ["center"],
    mobileFocus: "center",
    maxBodyUses: 400,
  },
  busanRegistryBureau: {
    id: "busanRegistryBureau",
    originalSrc: "/image/썸네일-부산지방법원등기국.jpg",
    derivedSrc: "/image/derived/busan-registry-bureau.webp",
    width: 1280,
    height: 960,
    category: "registry-court",
    isLawyerPhoto: false,
    usable: true,
    fields: ["building", "real-estate", "corporate", "court"],
    overlaySafe: ["center", "left"],
    mobileFocus: "center",
    maxBodyUses: 400,
  },
  officeDocs: {
    id: "officeDocs",
    originalSrc: "/image/사무소-서류.jpg",
    derivedSrc: "/image/derived/office-docs.webp",
    width: 1280,
    height: 960,
    category: "office",
    isLawyerPhoto: false,
    usable: true,
    fields: ["general", "consultation", "inheritance", "corporate"],
    overlaySafe: ["center"],
    mobileFocus: "center",
    maxBodyUses: 400,
  },
  officeExteriorSeason: {
    id: "officeExteriorSeason",
    originalSrc: "/image/썸네일-사무실_가을 (1).jpg",
    derivedSrc: "/image/derived/office-exterior-fall.webp",
    width: 1280,
    height: 960,
    category: "office",
    isLawyerPhoto: false,
    usable: true,
    fields: ["general", "building", "consultation"],
    overlaySafe: ["center", "left"],
    mobileFocus: "center",
    maxBodyUses: 400,
    notes: "사무소·지역 분위기 (인물 크롭 주의)",
  },
  officeNameplate: {
    id: "officeNameplate",
    originalSrc: "/image/사무소-명판가로.jpg",
    derivedSrc: "/image/derived/office-nameplate.webp",
    width: 1280,
    height: 720,
    category: "office",
    isLawyerPhoto: false,
    usable: true,
    fields: ["corporate", "general", "consultation"],
    overlaySafe: ["center"],
    mobileFocus: "center",
    maxBodyUses: 300,
  },
  lectureYouthJeonse: {
    id: "lectureYouthJeonse",
    originalSrc: "/image/강의-청년전세사기예방접종.jpg",
    derivedSrc: "/image/derived/lecture-youth-jeonse.webp",
    width: 1280,
    height: 960,
    category: "lecture",
    isLawyerPhoto: true,
    usable: true,
    fields: ["lecture"],
    overlaySafe: ["left", "center"],
    mobileFocus: "center",
    maxBodyUses: 200,
  },
  lectureCitizenLib: {
    id: "lectureCitizenLib",
    originalSrc: "/image/강의-시민도서관1주차.jpg",
    derivedSrc: "/image/derived/lecture-citizen-lib.webp",
    width: 1280,
    height: 960,
    category: "lecture",
    isLawyerPhoto: true,
    usable: true,
    fields: ["lecture"],
    overlaySafe: ["center"],
    mobileFocus: "center",
    maxBodyUses: 200,
  },
  logo: {
    id: "logo",
    originalSrc: "/image/로고.png",
    width: 512,
    height: 512,
    category: "brand",
    isLawyerPhoto: false,
    usable: false,
    excludeReason: "브랜드 로고 · 본문 호흡용으로 부적합",
    fields: [],
    overlaySafe: [],
    mobileFocus: "center",
    maxBodyUses: 0,
  },
  directionsHugePng: {
    id: "directionsHugePng",
    originalSrc: "/image/사무소-찾아오는길1.png",
    width: 2623,
    height: 1717,
    category: "map-directions",
    isLawyerPhoto: false,
    usable: false,
    excludeReason: "8~10MB PNG · 오시는길 전용",
    fields: ["location"],
    overlaySafe: [],
    mobileFocus: "center",
    maxBodyUses: 0,
  },
};

export function getArticleImageAsset(id: string): ArticleImageAsset | undefined {
  return articleImageCatalog[id];
}

export function resolveArticleImageSrc(asset: ArticleImageAsset): string {
  return asset.derivedSrc ?? asset.originalSrc;
}
