import type { SearchIntentSeed } from "./types";

const inheritanceCase = {
  caseHref: "/services/cases/haeundae-inheritance-registration-case",
  caseLabel: "해운대 상속등기 사례",
  diagnosisHref: "/상속등기자가진단",
  diagnosisLabel: "상속등기 자가진단",
} as const;

const realEstateCase = {
  caseHref: "/services/cases/centum-ownership-transfer-case",
  caseLabel: "센텀 소유권이전 사례",
  diagnosisHref: "/부동산등기자가진단",
  diagnosisLabel: "부동산등기 자가진단",
} as const;

const corporateCase = {
  caseHref: "/services/cases/suyeong-company-establishment-case",
  caseLabel: "법인설립 사례",
  diagnosisHref: "/법인등기자가진단",
  diagnosisLabel: "법인등기 자가진단",
} as const;

const rehabCase = {
  caseHref: "/services/cases/busan-personal-rehabilitation-consultation",
  caseLabel: "부산 개인회생 상담 사례",
  diagnosisHref: "/개인회생자가진단",
  diagnosisLabel: "개인회생 자가진단",
} as const;

const bankruptcyCase = {
  diagnosisHref: "/개인파산자가진단",
  diagnosisLabel: "개인파산 자가진단",
} as const;

/** NEW search-intent pages only (existing URLs are not duplicated) */
export const searchIntentSeeds: SearchIntentSeed[] = [
  // ① 추천/선택 (new only)
  {
    slug: "부산상속법무사추천",
    label: "부산 상속 법무사 추천",
    category: "recommend",
    serviceSlug: "inheritance-registration",
    keywords: [
      "부산 상속 법무사 추천",
      "부산 상속전문 법무사 추천",
      "부산 상속등기 법무사 추천",
      "부산 상속 상담",
      "부산 상속 법무사 비용",
    ],
    focus: "상속등기·포기·한정승인 상담",
    includeLawyerScopeFaq: true,
    ...inheritanceCase,
  },
  {
    slug: "부산개인회생법무사추천",
    label: "부산 개인회생 법무사 추천",
    category: "recommend",
    serviceSlug: "personal-rehabilitation",
    keywords: [
      "부산 개인회생 법무사 추천",
      "부산 회생 법무사 추천",
      "부산 개인회생 상담",
    ],
    focus: "개인회생 신청·서류·비용 상담",
    ...rehabCase,
  },
  {
    slug: "부산개인파산법무사추천",
    label: "부산 개인파산 법무사 추천",
    category: "recommend",
    serviceSlug: "bankruptcy",
    keywords: [
      "부산 개인파산 법무사 추천",
      "부산 파산 법무사 추천",
      "부산 개인파산 상담",
    ],
    focus: "개인파산·면책 상담",
    ...bankruptcyCase,
  },
  {
    slug: "부산법무사수임료",
    label: "부산 법무사 수임료",
    category: "recommend",
    serviceSlug: "inheritance-registration",
    keywords: ["부산 법무사 수임료", "법무사 수임료", "부산 법무사 비용"],
    focus: "수임료·공과금 구분",
  },
  {
    slug: "부산법무사보수",
    label: "부산 법무사 보수",
    category: "recommend",
    serviceSlug: "inheritance-registration",
    keywords: ["부산 법무사 보수", "법무사 보수", "부산 법무사 보수표"],
    focus: "보수·비용 산정 기준",
  },
  {
    slug: "부산법무사잘하는곳",
    label: "부산 법무사 잘하는 곳",
    category: "recommend",
    serviceSlug: "inheritance-registration",
    keywords: [
      "부산 법무사 잘하는 곳",
      "부산 법무사 추천",
      "해운대 법무사 잘하는 곳",
    ],
    focus: "업무 경험·설명력·기한 안내 기준",
    includeLawyerScopeFaq: true,
  },

  // ② 등기·상속 실무 키워드 (URL 유지, 화면 카피는 ‘실무’ 표현)
  {
    slug: "부산등기전문법무사",
    label: "부산 등기 법무사 실무 안내",
    category: "expertise",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 등기 법무사",
      "부산 부동산등기 법무사",
      "부산 등기법무사",
    ],
    focus: "부동산·법인 등기 실무",
    ...realEstateCase,
  },
  {
    slug: "부산상속전문법무사",
    label: "부산 상속 법무사 실무 안내",
    category: "expertise",
    serviceSlug: "inheritance-registration",
    keywords: [
      "부산 상속 법무사",
      "부산 상속등기 법무사",
      "부산 상속등기",
    ],
    focus: "상속등기 실무",
    ...inheritanceCase,
  },
  {
    slug: "부산개인회생법무사",
    label: "부산 개인회생 법무사",
    category: "expertise",
    serviceSlug: "personal-rehabilitation",
    keywords: [
      "부산 개인회생 법무사",
      "부산 회생 법무사",
      "부산 개인회생",
    ],
    focus: "개인회생 서류·신청 실무",
    ...rehabCase,
  },
  {
    slug: "부산개인파산법무사",
    label: "부산 개인파산 법무사",
    category: "expertise",
    serviceSlug: "bankruptcy",
    keywords: ["부산 개인파산 법무사", "부산 파산 법무사", "부산 개인파산"],
    focus: "개인파산·면책 실무",
    ...bankruptcyCase,
  },
  {
    slug: "부산회생법무사",
    label: "부산 회생 법무사",
    category: "expertise",
    serviceSlug: "personal-rehabilitation",
    keywords: ["부산 회생 법무사", "부산 개인회생 법무사", "부산 회생 상담"],
    focus: "회생 상담·신청 실무",
    ...rehabCase,
  },
  {
    slug: "부산파산법무사",
    label: "부산 파산 법무사",
    category: "expertise",
    serviceSlug: "bankruptcy",
    keywords: ["부산 파산 법무사", "부산 개인파산 법무사", "부산 파산신청"],
    focus: "파산 신청 실무",
    ...bankruptcyCase,
  },

  // ③ 실제 검색 키워드
  {
    slug: "부산등기복대리",
    label: "부산 등기 복대리",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["부산 등기 복대리", "등기 복대리", "복대리 등기"],
    focus: "등기 복대리 협의·접수",
  },
  {
    slug: "복대리등기",
    label: "복대리 등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["복대리 등기", "등기 복대리", "부산 복대리"],
    focus: "복대리 등기 절차",
  },
  {
    slug: "등기복대리",
    label: "등기 복대리",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 복대리", "복대리 등기", "부산 등기 복대리"],
    focus: "등기 복대리 실무",
  },
  {
    slug: "부산집단등기",
    label: "부산 집단등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["부산 집단등기", "집단등기", "신축 집단등기"],
    focus: "집단등기·일괄 접수",
  },
  {
    slug: "집단등기",
    label: "집단등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["집단등기", "아파트 집단등기", "오피스텔 집단등기"],
    focus: "집단등기 준비·일정",
  },
  {
    slug: "아파트집단등기",
    label: "아파트 집단등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["아파트 집단등기", "신축 아파트 등기", "부산 집단등기"],
    focus: "아파트 집단등기",
    ...realEstateCase,
  },
  {
    slug: "오피스텔집단등기",
    label: "오피스텔 집단등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["오피스텔 집단등기", "오피스텔 보존등기", "집단등기"],
    focus: "오피스텔 집단등기",
  },
  {
    slug: "신축집단등기",
    label: "신축 집단등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["신축 집단등기", "신축 보존등기", "부산 집단등기"],
    focus: "신축 집단등기",
  },
  {
    slug: "법무사수임료",
    label: "법무사 수임료",
    category: "keyword",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 수임료", "법무사 비용", "등기 수임료"],
    focus: "수임료 구성",
  },
  {
    slug: "법무사비용",
    label: "법무사 비용",
    category: "keyword",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 비용", "법무사 수임료", "등기 비용"],
    focus: "법무사 비용 항목",
  },
  {
    slug: "법무사보수",
    label: "법무사 보수",
    category: "keyword",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 보수", "법무사 보수표", "수임료"],
    focus: "보수 산정",
  },
  {
    slug: "등기비용",
    label: "등기 비용",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 비용", "등록면허세", "법무사 비용"],
    focus: "등기 비용·공과금",
    glossaryHref: "/glossary/registration-license-tax",
    glossaryLabel: "등록면허세 용어",
  },
  {
    slug: "등록면허세",
    label: "등록면허세",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등록면허세", "등기 비용", "취득세"],
    focus: "등록면허세 납부",
    glossaryHref: "/glossary/registration-license-tax",
    glossaryLabel: "등록면허세",
  },
  {
    slug: "국민주택채권",
    label: "국민주택채권",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["국민주택채권", "등기 비용", "매입 의무"],
    focus: "국민주택채권 매입",
  },
  {
    slug: "취득세",
    label: "취득세",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["취득세", "부동산 취득세", "등기 비용"],
    focus: "취득세 신고·납부",
    glossaryHref: "/glossary/acquisition-tax",
    glossaryLabel: "취득세 용어",
  },
  {
    slug: "등기신청대행",
    label: "등기신청 대행",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기신청 대행", "전자등기", "법무사 등기"],
    focus: "등기신청 대행",
  },
  {
    slug: "전자등기",
    label: "전자등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["전자등기", "전자신청", "등기 접수"],
    focus: "전자등기·전자신청",
  },
  {
    slug: "전자신청",
    label: "전자신청",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["전자신청", "전자등기", "등기소 제출"],
    focus: "등기 전자신청",
  },
  {
    slug: "등기소제출",
    label: "등기소 제출",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기소 제출", "등기 접수", "창구 제출"],
    focus: "등기소 제출·접수",
  },
  {
    slug: "등기보정",
    label: "등기 보정",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 보정", "보정 명령", "등기 반려"],
    focus: "등기 보정 대응",
  },
  {
    slug: "등기완료기간",
    label: "등기 완료기간",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 완료기간", "등기 처리기간", "등기 얼마나 걸리나요"],
    focus: "등기 완료·처리 기간",
  },
  {
    slug: "등기접수",
    label: "등기 접수",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 접수", "등기신청", "전자신청"],
    focus: "등기 접수 절차",
  },
  {
    slug: "등기처리기간",
    label: "등기 처리기간",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 처리기간", "등기 완료기간", "등기 언제 끝나나요"],
    focus: "등기 처리기간",
  },

  // ④ 개인회생/파산 (new)
  {
    slug: "부산개인회생상담",
    label: "부산 개인회생 상담",
    category: "rehab",
    serviceSlug: "personal-rehabilitation",
    keywords: ["부산 개인회생 상담", "부산 회생 상담", "개인회생 상담"],
    focus: "개인회생 상담",
    ...rehabCase,
  },
  {
    slug: "부산개인회생신청",
    label: "부산 개인회생 신청",
    category: "rehab",
    serviceSlug: "personal-rehabilitation",
    keywords: ["부산 개인회생 신청", "개인회생 신청", "부산 회생"],
    focus: "개인회생 신청",
    ...rehabCase,
  },
  {
    slug: "부산파산신청",
    label: "부산 파산신청",
    category: "rehab",
    serviceSlug: "bankruptcy",
    keywords: ["부산 파산신청", "부산 개인파산", "파산 신청"],
    focus: "파산 신청",
    ...bankruptcyCase,
  },
  {
    slug: "부산개인파산상담",
    label: "부산 개인파산 상담",
    category: "rehab",
    serviceSlug: "bankruptcy",
    keywords: ["부산 개인파산 상담", "부산 파산 상담", "면책"],
    focus: "개인파산 상담",
    ...bankruptcyCase,
  },
  {
    slug: "부산면책신청",
    label: "부산 면책신청",
    category: "rehab",
    serviceSlug: "bankruptcy",
    keywords: ["부산 면책신청", "면책", "개인파산 면책"],
    focus: "면책 신청",
    ...bankruptcyCase,
    glossaryHref: "/glossary/discharge",
    glossaryLabel: "면책 용어",
  },
  {
    slug: "부산회생상담",
    label: "부산 회생 상담",
    category: "rehab",
    serviceSlug: "personal-rehabilitation",
    keywords: ["부산 회생 상담", "부산 개인회생 상담", "회생 준비"],
    focus: "회생 상담",
    ...rehabCase,
  },

  // ⑤ 고객 고민
  {
    slug: "법무사상담전준비",
    label: "법무사 상담 전 준비",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 상담 전 준비", "법무사 방문 전 준비", "상담 준비서류"],
    focus: "상담 전 준비",
  },
  {
    slug: "법무사방문전준비",
    label: "법무사 방문 전 준비",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 방문 전 준비", "법무사 상담 전 준비", "방문 상담"],
    focus: "방문 상담 준비",
  },
  {
    slug: "등기준비서류",
    label: "등기 준비서류",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 준비서류", "등기 필요서류", "등기 체크리스트"],
    focus: "등기 준비서류",
    toolHref: "/tools/real-estate-documents-check",
    toolLabel: "부동산 서류 체크",
  },
  {
    slug: "등기얼마나걸리나요",
    label: "등기 얼마나 걸리나요",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 얼마나 걸리나요", "등기 처리기간", "등기 언제 끝나나요"],
    focus: "등기 소요 기간",
  },
  {
    slug: "등기언제끝나나요",
    label: "등기 언제 끝나나요",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 언제 끝나나요", "등기 완료기간", "등기 처리기간"],
    focus: "등기 완료 시점",
  },
  {
    slug: "등기어디서하나요",
    label: "등기 어디서 하나요",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 어디서 하나요", "등기소 어디인가요", "관할 등기소"],
    focus: "등기 관할·장소",
  },
  {
    slug: "등기소어디인가요",
    label: "등기소 어디인가요",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["등기소 어디인가요", "부산 등기소", "관할 등기소"],
    focus: "관할 등기소 확인",
  },
  {
    slug: "법무사맡기면달라지는점",
    label: "법무사에게 맡기면 뭐가 달라지나요",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "법무사에게 맡기면 뭐가 달라지나요",
      "등기 대행",
      "법무사 상담",
    ],
    focus: "직접 진행 vs 대행",
    includeLawyerScopeFaq: true,
  },

  // ⑥ 공공기관
  {
    slug: "공공기관법인등기",
    label: "공공기관 법인등기",
    category: "public",
    serviceSlug: "corporate-registration",
    keywords: ["공공기관 법인등기", "공기업 등기", "촉탁등기"],
    focus: "공공기관 법인등기 실무",
    ...corporateCase,
  },
  {
    slug: "공공기관부동산등기",
    label: "공공기관 부동산등기",
    category: "public",
    serviceSlug: "real-estate-registration",
    keywords: ["공공기관 부동산등기", "촉탁등기", "공공기관 이전등기"],
    focus: "공공기관 부동산등기 실무",
  },
  {
    slug: "공기업등기",
    label: "공기업 등기",
    category: "public",
    serviceSlug: "corporate-registration",
    keywords: ["공기업 등기", "지방공기업 등기", "공공기관 등기업무"],
    focus: "공기업 등기",
  },
  {
    slug: "촉탁등기",
    label: "촉탁등기",
    category: "public",
    serviceSlug: "real-estate-registration",
    keywords: ["촉탁등기", "공공기관 촉탁등기", "공공기관 등기업무"],
    focus: "촉탁등기 절차",
  },
  {
    slug: "공공기관촉탁등기",
    label: "공공기관 촉탁등기",
    category: "public",
    serviceSlug: "real-estate-registration",
    keywords: ["공공기관 촉탁등기", "촉탁등기", "공기업 등기"],
    focus: "공공기관 촉탁등기",
  },
  {
    slug: "지방공기업등기",
    label: "지방공기업 등기",
    category: "public",
    serviceSlug: "corporate-registration",
    keywords: ["지방공기업 등기", "공기업 등기", "공공기관 법인등기"],
    focus: "지방공기업 등기",
  },
  {
    slug: "공공기관이전등기",
    label: "공공기관 이전등기",
    category: "public",
    serviceSlug: "ownership-transfer",
    keywords: ["공공기관 이전등기", "공공기관 부동산등기", "촉탁등기"],
    focus: "공공기관 이전등기",
  },

  // ⑦ 건축주
  {
    slug: "신축보존등기",
    label: "신축 보존등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["신축 보존등기", "건물 보존등기", "사용승인 후 등기"],
    focus: "신축 보존등기",
  },
  {
    slug: "건물보존등기",
    label: "건물 보존등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["건물 보존등기", "신축 보존등기", "집합건물 보존등기"],
    focus: "건물 보존등기",
    glossaryHref: "/glossary/ownership-preservation-registration",
    glossaryLabel: "소유권보존등기",
  },
  {
    slug: "집합건물보존등기",
    label: "집합건물 보존등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["집합건물 보존등기", "아파트 보존등기", "오피스텔 보존등기"],
    focus: "집합건물 보존등기",
  },
  {
    slug: "오피스텔보존등기",
    label: "오피스텔 보존등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["오피스텔 보존등기", "집합건물 보존등기", "신축 보존등기"],
    focus: "오피스텔 보존등기",
  },
  {
    slug: "상가보존등기",
    label: "상가 보존등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["상가 보존등기", "건물 보존등기", "집합건물 보존등기"],
    focus: "상가 보존등기",
  },
  {
    slug: "건축주준비서류",
    label: "건축주 준비서류",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["건축주 준비서류", "보존등기 서류", "사용승인 후 등기"],
    focus: "건축주 서류 준비",
  },
  {
    slug: "사용승인후등기",
    label: "사용승인 후 등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["사용승인 후 등기", "신축 보존등기", "건축물 등기"],
    focus: "사용승인 후 보존등기",
  },

  // 실수 모음
  {
    slug: "상속등기실수모음",
    label: "상속등기에서 많이 하는 실수",
    category: "mistakes",
    serviceSlug: "inheritance-registration",
    keywords: ["상속등기 실수", "상속등기 주의사항", "부산 상속등기"],
    focus: "상속등기 실수 예방",
    ...inheritanceCase,
  },
  {
    slug: "법인등기실수모음",
    label: "법인등기에서 많이 하는 실수",
    category: "mistakes",
    serviceSlug: "corporate-registration",
    keywords: ["법인등기 실수", "임원변경 과태료", "법인등기 주의사항"],
    focus: "법인등기 실수 예방",
    ...corporateCase,
  },
  {
    slug: "개인회생실수모음",
    label: "개인회생에서 많이 하는 실수",
    category: "mistakes",
    serviceSlug: "personal-rehabilitation",
    keywords: ["개인회생 실수", "개인회생 준비", "회생 서류"],
    focus: "개인회생 실수 예방",
    ...rehabCase,
  },
  {
    slug: "부동산등기실수모음",
    label: "부동산등기에서 많이 하는 실수",
    category: "mistakes",
    serviceSlug: "real-estate-registration",
    keywords: ["부동산등기 실수", "소유권이전 주의", "등기 보정"],
    focus: "부동산등기 실수 예방",
    ...realEstateCase,
  },
  {
    slug: "집단등기실수모음",
    label: "집단등기에서 많이 하는 실수",
    category: "mistakes",
    serviceSlug: "ownership-transfer",
    keywords: ["집단등기 실수", "신축 집단등기", "아파트 집단등기"],
    focus: "집단등기 실수 예방",
  },

  // 체크리스트
  {
    slug: "상속등기체크리스트",
    label: "상속등기 체크리스트",
    category: "checklist",
    serviceSlug: "inheritance-registration",
    keywords: ["상속등기 체크리스트", "상속등기 준비서류", "상속등기 서류"],
    focus: "상속등기 체크리스트",
    ...inheritanceCase,
  },
  {
    slug: "법인등기체크리스트",
    label: "법인등기 체크리스트",
    category: "checklist",
    serviceSlug: "corporate-registration",
    keywords: ["법인등기 체크리스트", "법인등기 준비서류", "임원변경 서류"],
    focus: "법인등기 체크리스트",
    ...corporateCase,
  },
  {
    slug: "개인회생체크리스트",
    label: "개인회생 체크리스트",
    category: "checklist",
    serviceSlug: "personal-rehabilitation",
    keywords: ["개인회생 체크리스트", "개인회생 준비서류", "회생 서류"],
    focus: "개인회생 체크리스트",
    ...rehabCase,
  },
  {
    slug: "부동산등기체크리스트",
    label: "부동산등기 체크리스트",
    category: "checklist",
    serviceSlug: "real-estate-registration",
    keywords: ["부동산등기 체크리스트", "등기 준비서류", "소유권이전 서류"],
    focus: "부동산등기 체크리스트",
    toolHref: "/tools/real-estate-documents-check",
    toolLabel: "부동산 서류 체크",
    ...realEstateCase,
  },
  {
    slug: "신축보존등기체크리스트",
    label: "신축 보존등기 체크리스트",
    category: "checklist",
    serviceSlug: "ownership-transfer",
    keywords: [
      "신축 보존등기 체크리스트",
      "건축주 준비서류",
      "보존등기 서류",
    ],
    focus: "신축 보존등기 체크리스트",
  },

  // 비용이 달라지는 이유
  {
    slug: "왜상속등기비용이다를까",
    label: "왜 상속등기 비용이 다를까",
    category: "cost-why",
    serviceSlug: "inheritance-registration",
    keywords: ["상속등기 비용", "왜 상속등기 비용이 다를까", "상속등기 수임료"],
    focus: "상속등기 비용 차이",
    ...inheritanceCase,
  },
  {
    slug: "왜법인등기비용이다를까",
    label: "왜 법인등기 비용이 다를까",
    category: "cost-why",
    serviceSlug: "corporate-registration",
    keywords: ["법인등기 비용", "왜 법인등기 비용이 다를까", "법인 수임료"],
    focus: "법인등기 비용 차이",
    ...corporateCase,
  },
  {
    slug: "왜개인회생비용이다를까",
    label: "왜 개인회생 비용이 다를까",
    category: "cost-why",
    serviceSlug: "personal-rehabilitation",
    keywords: [
      "개인회생 비용",
      "왜 개인회생 비용이 다를까",
      "회생 수임료",
    ],
    focus: "개인회생 비용 차이",
    ...rehabCase,
  },

  // Priority 1 hubs + 잔금일
  {
    slug: "등기실무",
    label: "등기 실무 안내",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 실무", "등기 접수", "부산 등기"],
    focus: "등기 실무 허브",
  },
  {
    slug: "특수등기의뢰",
    label: "특수 등기 의뢰",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["특수 등기 의뢰", "집단등기", "등기 복대리"],
    focus: "특수 등기·협업 의뢰",
  },
  {
    slug: "법무사협업",
    label: "법무사 협업",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["법무사 협업", "등기 업무제휴", "부산 법무사 제휴"],
    focus: "B2B 협업",
  },
  {
    slug: "부산잔금일법무사",
    label: "부산 잔금일 법무사",
    category: "concern",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 잔금일 법무사",
      "잔금일 등기",
      "매수인 법무사",
      "매도인 법무사",
    ],
    focus: "잔금일·말소·이전 일정",
    ...realEstateCase,
  },
];
