import type { SearchIntentSeed } from "./types";

const inheritanceCase = {
  caseHref: "/services/cases/haeundae-inheritance-registration-case",
  caseLabel: "해운대 상속등기 사례",
  diagnosisHref: "/상속등기자가진단",
  diagnosisLabel: "상속등기 자가진단",
} as const;

const realEstateCase = {
  caseHref: "/services/cases/centum-ownership-transfer-case",
  caseLabel: "센텀 소유권이전 사례",
  diagnosisHref: "/부동산등기자가진단",
  diagnosisLabel: "부동산등기 자가진단",
} as const;

const corporateCase = {
  caseHref: "/services/cases/suyeong-company-establishment-case",
  caseLabel: "법인설립 사례",
  diagnosisHref: "/법인등기자가진단",
  diagnosisLabel: "법인등기 자가진단",
} as const;

const rehabCase = {
  caseHref: "/services/cases/busan-personal-rehabilitation-consultation",
  caseLabel: "부산 개인회생 상담 사례",
  diagnosisHref: "/개인회생자가진단",
  diagnosisLabel: "개인회생 자가진단",
} as const;

const bankruptcyCase = {
  diagnosisHref: "/개인파산자가진단",
  diagnosisLabel: "개인파산 자가진단",
} as const;

/** NEW search-intent pages only (existing URLs are not duplicated) */
export const searchIntentSeeds: SearchIntentSeed[] = [
  // ① 추천/선택 (new only)
  {
    slug: "부산상속법무사추천",
    label: "부산 상속 법무사 추천",
    category: "recommend",
    serviceSlug: "inheritance-registration",
    keywords: [
      "부산 상속 법무사 추천",
      "부산 상속전문 법무사 추천",
      "부산 상속등기 법무사 추천",
      "부산 상속 상담",
      "부산 상속 법무사 비용",
    ],
    focus: "상속등기·포기·한정승인 상담",
    includeLawyerScopeFaq: true,
    ...inheritanceCase,
  },
  {
    slug: "부산개인회생법무사추천",
    label: "부산 개인회생 법무사 추천",
    category: "recommend",
    serviceSlug: "personal-rehabilitation",
    keywords: [
      "부산 개인회생 법무사 추천",
      "부산 회생 법무사 추천",
      "부산 개인회생 상담",
    ],
    focus: "개인회생 신청·서류·비용 상담",
    ...rehabCase,
  },
  {
    slug: "부산개인파산법무사추천",
    label: "부산 개인파산 법무사 추천",
    category: "recommend",
    serviceSlug: "bankruptcy",
    keywords: [
      "부산 개인파산 법무사 추천",
      "부산 파산 법무사 추천",
      "부산 개인파산 상담",
    ],
    focus: "개인파산·면책 상담",
    ...bankruptcyCase,
  },
  {
    slug: "부산법무사수임료",
    label: "부산 법무사 수임료",
    category: "recommend",
    serviceSlug: "inheritance-registration",
    keywords: ["부산 법무사 수임료", "법무사 수임료", "부산 법무사 비용"],
    focus: "수임료·공과금 구분",
  },
  {
    slug: "부산법무사보수",
    label: "부산 법무사 보수",
    category: "recommend",
    serviceSlug: "inheritance-registration",
    keywords: ["부산 법무사 보수", "법무사 보수", "부산 법무사 보수표"],
    focus: "보수·비용 산정 기준",
  },
  {
    slug: "부산법무사잘하는곳",
    label: "부산 법무사 잘하는 곳",
    category: "recommend",
    serviceSlug: "inheritance-registration",
    keywords: [
      "부산 법무사 잘하는 곳",
      "부산 법무사 추천",
      "해운대 법무사 잘하는 곳",
    ],
    focus: "업무 경험·설명력·기한 안내 기준",
    includeLawyerScopeFaq: true,
  },

  // ② 등기·상속 실무 키워드 (URL 유지, 화면 카피는 ‘실무’ 표현)
  {
    slug: "부산등기전문법무사",
    label: "부산 등기전문 법무사",
    category: "expertise",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 등기전문 법무사",
      "부산 등기 법무사",
      "부산 부동산등기 법무사",
      "부산 등기법무사",
    ],
    focus: "부동산·상속·법인 등기 상담 전 확인",
    ...realEstateCase,
  },
  {
    slug: "부산상속전문법무사",
    label: "부산 상속전문 법무사",
    category: "expertise",
    serviceSlug: "inheritance-registration",
    keywords: [
      "부산 상속전문 법무사",
      "부산 상속 법무사",
      "부산 상속등기 법무사",
      "부산 상속등기",
    ],
    focus: "상속등기·포기·한정승인 상담 전 확인",
    ...inheritanceCase,
  },
  {
    slug: "부산법인전문법무사",
    label: "부산 법인전문 법무사",
    category: "expertise",
    serviceSlug: "corporate-registration",
    keywords: [
      "부산 법인전문 법무사",
      "부산 법인 법무사",
      "부산 법인등기 법무사",
    ],
    focus: "법인등기·임원변경 실무",
    ...corporateCase,
  },
  {
    slug: "부산부동산등기전문법무사",
    label: "부산 부동산등기전문 법무사",
    category: "expertise",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 부동산등기전문 법무사",
      "부산 부동산등기 법무사",
      "부산 부동산 등기",
    ],
    focus: "부동산등기 실무",
    ...realEstateCase,
  },
  {
    slug: "부산개인회생전문법무사",
    label: "부산 개인회생전문 법무사",
    category: "expertise",
    serviceSlug: "personal-rehabilitation",
    keywords: [
      "부산 개인회생전문 법무사",
      "부산 개인회생 법무사",
      "부산 회생 법무사",
    ],
    focus: "개인회생 서류·신청 실무",
    ...rehabCase,
  },
  {
    slug: "부산개인파산전문법무사",
    label: "부산 개인파산전문 법무사",
    category: "expertise",
    serviceSlug: "bankruptcy",
    keywords: [
      "부산 개인파산전문 법무사",
      "부산 개인파산 법무사",
      "부산 파산 법무사",
    ],
    focus: "개인파산·면책 실무",
    ...bankruptcyCase,
  },
  {
    slug: "부산근저당전문법무사",
    label: "부산 근저당전문 법무사",
    category: "expertise",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 근저당전문 법무사",
      "부산 근저당등기 법무사",
      "부산 근저당 말소",
    ],
    focus: "근저당 설정·말소 등기",
    ...realEstateCase,
  },
  {
    slug: "부산전세전문법무사",
    label: "부산 전세전문 법무사",
    category: "expertise",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 전세전문 법무사",
      "부산 전세권 법무사",
      "부산 전세보증금 법무사",
    ],
    focus: "전세권·보증금 관련 등기",
    ...realEstateCase,
  },
  {
    slug: "부산임원변경전문법무사",
    label: "부산 임원변경전문 법무사",
    category: "expertise",
    serviceSlug: "director-change",
    keywords: [
      "부산 임원변경전문 법무사",
      "부산 임원변경등기 법무사",
      "부산 대표이사변경 법무사",
    ],
    focus: "임원변경등기·과태료 예방",
    ...corporateCase,
  },
  {
    slug: "부산매매등기전문법무사",
    label: "부산 매매등기전문 법무사",
    category: "expertise",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 매매등기전문 법무사",
      "부산 매매등기 법무사",
      "부산 아파트 매매등기",
    ],
    focus: "매매 소유권이전등기",
    ...realEstateCase,
  },
  {
    slug: "부산소유권이전전문법무사",
    label: "부산 소유권이전전문 법무사",
    category: "expertise",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 소유권이전전문 법무사",
      "부산소유권이전등기 법무사",
      "부산 소유권이전등기",
    ],
    focus: "소유권이전등기 원인별 실무",
    ...realEstateCase,
  },
  {
    slug: "부산한정승인전문법무사",
    label: "부산 한정승인전문 법무사",
    category: "expertise",
    serviceSlug: "qualified-acceptance",
    keywords: [
      "부산 한정승인전문 법무사",
      "부산 한정승인 법무사",
      "부산 한정승인",
    ],
    focus: "한정승인·채무 조사",
    ...inheritanceCase,
  },
  {
    slug: "부산회생전문법무사",
    label: "부산 회생전문 법무사",
    category: "expertise",
    serviceSlug: "personal-rehabilitation",
    keywords: [
      "부산 회생전문 법무사",
      "부산 회생 법무사",
      "부산 개인회생",
    ],
    focus: "회생·개인회생 상담 전 확인",
    ...rehabCase,
  },
  {
    slug: "부산파산전문법무사",
    label: "부산 파산전문 법무사",
    category: "expertise",
    serviceSlug: "bankruptcy",
    keywords: [
      "부산 파산전문 법무사",
      "부산 파산 법무사",
      "부산 개인파산",
    ],
    focus: "파산·면책 상담 전 확인",
    ...bankruptcyCase,
  },
  {
    slug: "부산면책전문법무사",
    label: "부산 면책전문 법무사",
    category: "expertise",
    serviceSlug: "bankruptcy",
    keywords: [
      "부산 면책전문 법무사",
      "부산 면책",
      "부산 면책신청",
    ],
    focus: "면책·파산 상담 전 확인",
    ...bankruptcyCase,
  },
  {
    slug: "부산상속포기전문법무사",
    label: "부산 상속포기전문 법무사",
    category: "expertise",
    serviceSlug: "inheritance-renunciation",
    keywords: [
      "부산 상속포기전문 법무사",
      "부산 상속포기",
      "상속포기 3개월",
    ],
    focus: "상속포기·3개월 기한 상담 전 확인",
    ...inheritanceCase,
  },
  {
    slug: "부산상속등기전문법무사",
    label: "부산 상속등기전문 법무사",
    category: "expertise",
    serviceSlug: "inheritance-registration",
    keywords: [
      "부산 상속등기전문 법무사",
      "부산 상속등기 법무사",
      "부산 상속등기",
    ],
    focus: "상속등기 실무 상담 전 확인",
    ...inheritanceCase,
  },
  {
    slug: "부산증여등기전문법무사",
    label: "부산 증여등기전문 법무사",
    category: "expertise",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 증여등기전문 법무사",
      "부산 증여등기",
      "부산 증여 법무사",
    ],
    focus: "증여등기 상담 전 확인",
    ...realEstateCase,
  },
  {
    slug: "부산법인설립전문법무사",
    label: "부산 법인설립전문 법무사",
    category: "expertise",
    serviceSlug: "company-establishment",
    keywords: [
      "부산 법인설립전문 법무사",
      "부산 법인설립등기",
      "부산 회사설립 법무사",
    ],
    focus: "법인설립등기 상담 전 확인",
    ...corporateCase,
  },
  {
    slug: "부산부동산전문법무사",
    label: "부산 부동산전문 법무사",
    category: "expertise",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 부동산전문 법무사",
      "부산 부동산 법무사",
      "부산 부동산등기",
    ],
    focus: "부동산등기 원인 분류·상담 전 확인",
    ...realEstateCase,
  },
  {
    slug: "부산개인회생법무사",
    label: "부산 개인회생 법무사",
    category: "expertise",
    serviceSlug: "personal-rehabilitation",
    keywords: [
      "부산 개인회생 법무사",
      "부산 회생 법무사",
      "부산 개인회생",
    ],
    focus: "개인회생 서류·신청 실무",
    ...rehabCase,
  },
  {
    slug: "부산개인파산법무사",
    label: "부산 개인파산 법무사",
    category: "expertise",
    serviceSlug: "bankruptcy",
    keywords: ["부산 개인파산 법무사", "부산 파산 법무사", "부산 개인파산"],
    focus: "개인파산·면책 실무",
    ...bankruptcyCase,
  },
  {
    slug: "부산회생법무사",
    label: "부산 회생 법무사",
    category: "expertise",
    serviceSlug: "personal-rehabilitation",
    keywords: ["부산 회생 법무사", "부산 개인회생 법무사", "부산 회생 상담"],
    focus: "회생 상담·신청 실무",
    ...rehabCase,
  },
  {
    slug: "부산파산법무사",
    label: "부산 파산 법무사",
    category: "expertise",
    serviceSlug: "bankruptcy",
    keywords: ["부산 파산 법무사", "부산 개인파산 법무사", "부산 파산신청"],
    focus: "파산 신청 실무",
    ...bankruptcyCase,
  },

  // ③ 실제 검색 키워드
  {
    slug: "부산등기복대리",
    label: "부산 등기 복대리",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["부산 등기 복대리", "등기 복대리", "복대리 등기"],
    focus: "등기 복대리 협의·접수",
  },
  {
    slug: "복대리등기",
    label: "복대리 등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["복대리 등기", "등기 복대리", "부산 복대리"],
    focus: "복대리 등기 절차",
  },
  {
    slug: "등기복대리",
    label: "등기 복대리",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 복대리", "복대리 등기", "부산 등기 복대리"],
    focus: "등기 복대리 실무",
  },
  {
    slug: "부산집단등기",
    label: "부산 집단등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["부산 집단등기", "집단등기", "신축 집단등기"],
    focus: "집단등기·일괄 접수",
  },
  {
    slug: "집단등기",
    label: "집단등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["집단등기", "아파트 집단등기", "오피스텔 집단등기"],
    focus: "집단등기 준비·일정",
  },
  {
    slug: "아파트집단등기",
    label: "아파트 집단등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["아파트 집단등기", "신축 아파트 등기", "부산 집단등기"],
    focus: "아파트 집단등기",
    ...realEstateCase,
  },
  {
    slug: "오피스텔집단등기",
    label: "오피스텔 집단등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["오피스텔 집단등기", "오피스텔 보존등기", "집단등기"],
    focus: "오피스텔 집단등기",
  },
  {
    slug: "신축집단등기",
    label: "신축 집단등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["신축 집단등기", "신축 보존등기", "부산 집단등기"],
    focus: "신축 집단등기",
  },
  {
    slug: "법무사수임료",
    label: "법무사 수임료",
    category: "keyword",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 수임료", "법무사 비용", "등기 수임료"],
    focus: "수임료 구성",
  },
  {
    slug: "법무사비용",
    label: "법무사 비용",
    category: "keyword",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 비용", "법무사 수임료", "등기 비용"],
    focus: "법무사 비용 항목",
  },
  {
    slug: "법무사보수",
    label: "법무사 보수",
    category: "keyword",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 보수", "법무사 보수표", "수임료"],
    focus: "보수 산정",
  },
  {
    slug: "등기비용",
    label: "등기 비용",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 비용", "등록면허세", "법무사 비용"],
    focus: "등기 비용·공과금",
    glossaryHref: "/glossary/registration-license-tax",
    glossaryLabel: "등록면허세 용어",
  },
  {
    slug: "등록면허세",
    label: "등록면허세",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등록면허세", "등기 비용", "취득세"],
    focus: "등록면허세 납부",
    glossaryHref: "/glossary/registration-license-tax",
    glossaryLabel: "등록면허세",
  },
  {
    slug: "국민주택채권",
    label: "국민주택채권",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["국민주택채권", "등기 비용", "매입 의무"],
    focus: "국민주택채권 매입",
  },
  {
    slug: "취득세",
    label: "취득세",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["취득세", "부동산 취득세", "등기 비용"],
    focus: "취득세 신고·납부",
    glossaryHref: "/glossary/acquisition-tax",
    glossaryLabel: "취득세 용어",
  },
  {
    slug: "등기신청대행",
    label: "등기신청 대행",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기신청 대행", "전자등기", "법무사 등기"],
    focus: "등기신청 대행",
  },
  {
    slug: "전자등기",
    label: "전자등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["전자등기", "전자신청", "등기 접수"],
    focus: "전자등기·전자신청",
  },
  {
    slug: "전자신청",
    label: "전자신청",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["전자신청", "전자등기", "등기소 제출"],
    focus: "등기 전자신청",
  },
  {
    slug: "등기소제출",
    label: "등기소 제출",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기소 제출", "등기 접수", "창구 제출"],
    focus: "등기소 제출·접수",
  },
  {
    slug: "등기보정",
    label: "등기 보정",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 보정", "보정 명령", "등기 반려"],
    focus: "등기 보정 대응",
  },
  {
    slug: "등기완료기간",
    label: "등기 완료기간",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 완료기간", "등기 처리기간", "등기 얼마나 걸리나요"],
    focus: "등기 완료·처리 기간",
  },
  {
    slug: "등기접수",
    label: "등기 접수",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 접수", "등기신청", "전자신청"],
    focus: "등기 접수 절차",
  },
  {
    slug: "등기처리기간",
    label: "등기 처리기간",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 처리기간", "등기 완료기간", "등기 언제 끝나나요"],
    focus: "등기 처리기간",
  },

  // ④ 개인회생/파산 (new)
  {
    slug: "부산개인회생상담",
    label: "부산 개인회생 상담",
    category: "rehab",
    serviceSlug: "personal-rehabilitation",
    keywords: ["부산 개인회생 상담", "부산 회생 상담", "개인회생 상담"],
    focus: "개인회생 상담",
    ...rehabCase,
  },
  {
    slug: "부산개인회생신청",
    label: "부산 개인회생 신청",
    category: "rehab",
    serviceSlug: "personal-rehabilitation",
    keywords: ["부산 개인회생 신청", "개인회생 신청", "부산 회생"],
    focus: "개인회생 신청",
    ...rehabCase,
  },
  {
    slug: "부산파산신청",
    label: "부산 파산신청",
    category: "rehab",
    serviceSlug: "bankruptcy",
    keywords: ["부산 파산신청", "부산 개인파산", "파산 신청"],
    focus: "파산 신청",
    ...bankruptcyCase,
  },
  {
    slug: "부산개인파산상담",
    label: "부산 개인파산 상담",
    category: "rehab",
    serviceSlug: "bankruptcy",
    keywords: ["부산 개인파산 상담", "부산 파산 상담", "면책"],
    focus: "개인파산 상담",
    ...bankruptcyCase,
  },
  {
    slug: "부산면책신청",
    label: "부산 면책신청",
    category: "rehab",
    serviceSlug: "bankruptcy",
    keywords: ["부산 면책신청", "면책", "개인파산 면책"],
    focus: "면책 신청",
    ...bankruptcyCase,
    glossaryHref: "/glossary/discharge",
    glossaryLabel: "면책 용어",
  },
  {
    slug: "부산회생상담",
    label: "부산 회생 상담",
    category: "rehab",
    serviceSlug: "personal-rehabilitation",
    keywords: ["부산 회생 상담", "부산 개인회생 상담", "회생 준비"],
    focus: "회생 상담",
    ...rehabCase,
  },

  // ⑤ 고객 고민
  {
    slug: "법무사상담전준비",
    label: "법무사 상담 전 준비",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 상담 전 준비", "법무사 방문 전 준비", "상담 준비서류"],
    focus: "상담 전 준비",
  },
  {
    slug: "법무사방문전준비",
    label: "법무사 방문 전 준비",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 방문 전 준비", "법무사 상담 전 준비", "방문 상담"],
    focus: "방문 상담 준비",
  },
  {
    slug: "등기준비서류",
    label: "등기 준비서류",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 준비서류", "등기 필요서류", "등기 체크리스트"],
    focus: "등기 준비서류",
    toolHref: "/tools/real-estate-documents-check",
    toolLabel: "부동산 서류 체크",
  },
  {
    slug: "등기얼마나걸리나요",
    label: "등기 얼마나 걸리나요",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 얼마나 걸리나요", "등기 처리기간", "등기 언제 끝나나요"],
    focus: "등기 소요 기간",
  },
  {
    slug: "등기언제끝나나요",
    label: "등기 언제 끝나나요",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 언제 끝나나요", "등기 완료기간", "등기 처리기간"],
    focus: "등기 완료 시점",
  },
  {
    slug: "등기어디서하나요",
    label: "등기 어디서 하나요",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 어디서 하나요", "등기소 어디인가요", "관할 등기소"],
    focus: "등기 관할·장소",
  },
  {
    slug: "등기소어디인가요",
    label: "등기소 어디인가요",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["등기소 어디인가요", "부산 등기소", "관할 등기소"],
    focus: "관할 등기소 확인",
  },
  {
    slug: "법무사맡기면달라지는점",
    label: "법무사에게 맡기면 뭐가 달라지나요",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "법무사에게 맡기면 뭐가 달라지나요",
      "등기 대행",
      "법무사 상담",
    ],
    focus: "직접 진행 vs 대행",
    includeLawyerScopeFaq: true,
  },

  // ⑥ 공공기관
  {
    slug: "공공기관법인등기",
    label: "공공기관 법인등기",
    category: "public",
    serviceSlug: "corporate-registration",
    keywords: ["공공기관 법인등기", "공기업 등기", "촉탁등기"],
    focus: "공공기관 법인등기 실무",
    ...corporateCase,
  },
  {
    slug: "공공기관부동산등기",
    label: "공공기관 부동산등기",
    category: "public",
    serviceSlug: "real-estate-registration",
    keywords: ["공공기관 부동산등기", "촉탁등기", "공공기관 이전등기"],
    focus: "공공기관 부동산등기 실무",
  },
  {
    slug: "공기업등기",
    label: "공기업 등기",
    category: "public",
    serviceSlug: "corporate-registration",
    keywords: ["공기업 등기", "지방공기업 등기", "공공기관 등기업무"],
    focus: "공기업 등기",
  },
  {
    slug: "촉탁등기",
    label: "촉탁등기",
    category: "public",
    serviceSlug: "real-estate-registration",
    keywords: ["촉탁등기", "공공기관 촉탁등기", "공공기관 등기업무"],
    focus: "촉탁등기 절차",
  },
  {
    slug: "공공기관촉탁등기",
    label: "공공기관 촉탁등기",
    category: "public",
    serviceSlug: "real-estate-registration",
    keywords: ["공공기관 촉탁등기", "촉탁등기", "공기업 등기"],
    focus: "공공기관 촉탁등기",
  },
  {
    slug: "지방공기업등기",
    label: "지방공기업 등기",
    category: "public",
    serviceSlug: "corporate-registration",
    keywords: ["지방공기업 등기", "공기업 등기", "공공기관 법인등기"],
    focus: "지방공기업 등기",
  },
  {
    slug: "공공기관이전등기",
    label: "공공기관 이전등기",
    category: "public",
    serviceSlug: "ownership-transfer",
    keywords: ["공공기관 이전등기", "공공기관 부동산등기", "촉탁등기"],
    focus: "공공기관 이전등기",
  },

  // ⑦ 건축주
  {
    slug: "신축보존등기",
    label: "신축 보존등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["신축 보존등기", "건물 보존등기", "사용승인 후 등기"],
    focus: "신축 보존등기",
  },
  {
    slug: "건물보존등기",
    label: "건물 보존등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["건물 보존등기", "신축 보존등기", "집합건물 보존등기"],
    focus: "건물 보존등기",
    glossaryHref: "/glossary/ownership-preservation-registration",
    glossaryLabel: "소유권보존등기",
  },
  {
    slug: "집합건물보존등기",
    label: "집합건물 보존등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["집합건물 보존등기", "아파트 보존등기", "오피스텔 보존등기"],
    focus: "집합건물 보존등기",
  },
  {
    slug: "오피스텔보존등기",
    label: "오피스텔 보존등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["오피스텔 보존등기", "집합건물 보존등기", "신축 보존등기"],
    focus: "오피스텔 보존등기",
  },
  {
    slug: "상가보존등기",
    label: "상가 보존등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["상가 보존등기", "건물 보존등기", "집합건물 보존등기"],
    focus: "상가 보존등기",
  },
  {
    slug: "건축주준비서류",
    label: "건축주 준비서류",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["건축주 준비서류", "보존등기 서류", "사용승인 후 등기"],
    focus: "건축주 서류 준비",
  },
  {
    slug: "사용승인후등기",
    label: "사용승인 후 등기",
    category: "builder",
    serviceSlug: "ownership-transfer",
    keywords: ["사용승인 후 등기", "신축 보존등기", "건축물 등기"],
    focus: "사용승인 후 보존등기",
  },

  // 실수 모음
  {
    slug: "상속등기실수모음",
    label: "상속등기에서 많이 하는 실수",
    category: "mistakes",
    serviceSlug: "inheritance-registration",
    keywords: ["상속등기 실수", "상속등기 주의사항", "부산 상속등기"],
    focus: "상속등기 실수 예방",
    ...inheritanceCase,
  },
  {
    slug: "법인등기실수모음",
    label: "법인등기에서 많이 하는 실수",
    category: "mistakes",
    serviceSlug: "corporate-registration",
    keywords: ["법인등기 실수", "임원변경 과태료", "법인등기 주의사항"],
    focus: "법인등기 실수 예방",
    ...corporateCase,
  },
  {
    slug: "개인회생실수모음",
    label: "개인회생에서 많이 하는 실수",
    category: "mistakes",
    serviceSlug: "personal-rehabilitation",
    keywords: ["개인회생 실수", "개인회생 준비", "회생 서류"],
    focus: "개인회생 실수 예방",
    ...rehabCase,
  },
  {
    slug: "부동산등기실수모음",
    label: "부동산등기에서 많이 하는 실수",
    category: "mistakes",
    serviceSlug: "real-estate-registration",
    keywords: ["부동산등기 실수", "소유권이전 주의", "등기 보정"],
    focus: "부동산등기 실수 예방",
    ...realEstateCase,
  },
  {
    slug: "집단등기실수모음",
    label: "집단등기에서 많이 하는 실수",
    category: "mistakes",
    serviceSlug: "ownership-transfer",
    keywords: ["집단등기 실수", "신축 집단등기", "아파트 집단등기"],
    focus: "집단등기 실수 예방",
  },

  // 체크리스트
  {
    slug: "상속등기체크리스트",
    label: "상속등기 체크리스트",
    category: "checklist",
    serviceSlug: "inheritance-registration",
    keywords: ["상속등기 체크리스트", "상속등기 준비서류", "상속등기 서류"],
    focus: "상속등기 체크리스트",
    ...inheritanceCase,
  },
  {
    slug: "법인등기체크리스트",
    label: "법인등기 체크리스트",
    category: "checklist",
    serviceSlug: "corporate-registration",
    keywords: ["법인등기 체크리스트", "법인등기 준비서류", "임원변경 서류"],
    focus: "법인등기 체크리스트",
    ...corporateCase,
  },
  {
    slug: "개인회생체크리스트",
    label: "개인회생 체크리스트",
    category: "checklist",
    serviceSlug: "personal-rehabilitation",
    keywords: ["개인회생 체크리스트", "개인회생 준비서류", "회생 서류"],
    focus: "개인회생 체크리스트",
    ...rehabCase,
  },
  {
    slug: "부동산등기체크리스트",
    label: "부동산등기 체크리스트",
    category: "checklist",
    serviceSlug: "real-estate-registration",
    keywords: ["부동산등기 체크리스트", "등기 준비서류", "소유권이전 서류"],
    focus: "부동산등기 체크리스트",
    toolHref: "/tools/real-estate-documents-check",
    toolLabel: "부동산 서류 체크",
    ...realEstateCase,
  },
  {
    slug: "신축보존등기체크리스트",
    label: "신축 보존등기 체크리스트",
    category: "checklist",
    serviceSlug: "ownership-transfer",
    keywords: [
      "신축 보존등기 체크리스트",
      "건축주 준비서류",
      "보존등기 서류",
    ],
    focus: "신축 보존등기 체크리스트",
  },

  // 비용이 달라지는 이유
  {
    slug: "왜상속등기비용이다를까",
    label: "왜 상속등기 비용이 다를까",
    category: "cost-why",
    serviceSlug: "inheritance-registration",
    keywords: ["상속등기 비용", "왜 상속등기 비용이 다를까", "상속등기 수임료"],
    focus: "상속등기 비용 차이",
    ...inheritanceCase,
  },
  {
    slug: "왜법인등기비용이다를까",
    label: "왜 법인등기 비용이 다를까",
    category: "cost-why",
    serviceSlug: "corporate-registration",
    keywords: ["법인등기 비용", "왜 법인등기 비용이 다를까", "법인 수임료"],
    focus: "법인등기 비용 차이",
    ...corporateCase,
  },
  {
    slug: "왜개인회생비용이다를까",
    label: "왜 개인회생 비용이 다를까",
    category: "cost-why",
    serviceSlug: "personal-rehabilitation",
    keywords: [
      "개인회생 비용",
      "왜 개인회생 비용이 다를까",
      "회생 수임료",
    ],
    focus: "개인회생 비용 차이",
    ...rehabCase,
  },

  // Priority 1 hubs + 잔금일
  {
    slug: "등기실무",
    label: "등기 실무 안내",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기 실무", "등기 접수", "부산 등기"],
    focus: "등기 실무 허브",
  },
  {
    slug: "특수등기의뢰",
    label: "특수 등기 의뢰",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["특수 등기 의뢰", "집단등기", "등기 복대리"],
    focus: "특수 등기·협업 의뢰",
  },
  {
    slug: "법무사협업",
    label: "법무사 협업",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["법무사 협업", "등기 업무제휴", "부산 법무사 제휴"],
    focus: "B2B 협업",
  },
  {
    slug: "부산잔금일법무사",
    label: "부산 잔금일 법무사",
    category: "concern",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 잔금일 법무사",
      "잔금일 등기",
      "잔금 당일 소유권이전",
      "아파트 잔금 등기",
    ],
    focus: "잔금일·말소·이전 일정",
    ...realEstateCase,
  },

  // ——— 부산 부동산등기 초세분화 Priority 1 ———
  {
    slug: "부산매매등기법무사",
    label: "부산 매매등기 법무사",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 매매등기 법무사",
      "부산 부동산 매매등기",
      "부산 매매 소유권이전등기",
      "부산 잔금 등기 법무사",
    ],
    focus: "매매계약 후 잔금·소유권이전등기",
    ...realEstateCase,
  },
  {
    slug: "부산증여등기",
    label: "부산 증여등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 증여등기",
      "부산 증여 법무사",
      "부산 증여등기 법무사",
      "부산 부동산 증여",
      "부산 아파트 증여등기",
      "증여 소유권이전등기",
      "증여등기 준비서류",
      "증여등기 비용",
    ],
    focus: "증여등기 서류·절차·비용 요소",
    ...realEstateCase,
  },
  {
    slug: "부산부모자녀아파트증여등기",
    label: "부산 부모자녀 아파트 증여등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 부모 자녀 아파트 증여등기",
      "부모 자녀 아파트 증여",
      "부산 아파트 증여 서류",
    ],
    focus: "부모·자녀 아파트 증여 서류·권리관계",
    ...realEstateCase,
  },
  {
    slug: "부산부부간증여등기",
    label: "부산 부부간 증여등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 부부간 증여등기",
      "부부 공동명의 증여",
      "배우자 지분 증여",
    ],
    focus: "부부 간 지분·공동명의 증여",
    ...realEstateCase,
  },
  {
    slug: "부산부담부증여등기",
    label: "부산 부담부증여등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 부담부증여 등기",
      "근저당 있는 아파트 증여",
      "전세보증금 있는 주택 증여",
    ],
    focus: "부담부증여 권리관계·서류",
    ...realEstateCase,
  },
  {
    slug: "부산공동명의지분증여등기",
    label: "부산 공동명의 지분 증여등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 지분 증여등기",
      "공동명의 지분 증여",
      "아파트 일부 지분 증여",
    ],
    focus: "일부 지분 증여등기",
    ...realEstateCase,
  },
  {
    slug: "부산명의변경등기",
    label: "부산 명의변경등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 명의변경 등기",
      "집 명의 바꾸기",
      "아파트 명의이전",
      "부동산 명의변경",
    ],
    focus: "명의변경 원인별 등기 안내",
    ...realEstateCase,
  },
  {
    slug: "부산아파트매매등기",
    label: "부산 아파트 매매등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 아파트 매매등기",
      "아파트 매매 소유권이전",
      "아파트 잔금 등기",
    ],
    focus: "아파트 매매등기 서류·대출·전세낀매매",
    ...realEstateCase,
  },
  {
    slug: "부산전세보증금반환법무사",
    label: "부산 전세보증금 반환 법무사",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "전세보증금 반환 법무사",
      "전세금 못 받을 때",
      "보증금 미반환",
    ],
    focus: "전세보증금 미반환 시 등기·서류 실무",
    diagnosisHref: "/전세보증금자가진단",
    diagnosisLabel: "전세보증금 자가진단",
    toolHref: "/tools/jeonse-deposit-timeline",
    toolLabel: "전세보증금 타임라인",
  },
  {
    slug: "부산임차권등기명령",
    label: "부산 임차권등기명령",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 임차권등기명령",
      "임차권등기명령",
      "전세금 못 받고 이사",
    ],
    focus: "임차권등기명령 신청·서류·기간",
    diagnosisHref: "/임차권등기명령자가진단",
    diagnosisLabel: "임차권등기명령 자가진단",
    glossaryHref: "/glossary/lease-registration-order",
    glossaryLabel: "임차권등기명령 용어",
  },
  {
    slug: "부산매수인법무사",
    label: "부산 매수인 법무사",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 매수인 법무사",
      "매수인이 법무사 선택",
      "매수인 소유권이전등기",
    ],
    focus: "매수인 관점 등기·서류·대출",
    ...realEstateCase,
  },
  {
    slug: "부산경매낙찰등기",
    label: "부산 경매 낙찰등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 경매 낙찰 등기",
      "경매 낙찰 소유권이전",
      "낙찰 후 등기",
    ],
    focus: "경매 낙찰 후 소유권이전·세금·담보",
    ...realEstateCase,
  },
  {
    slug: "부산공동명의등기",
    label: "부산 공동명의등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 공동명의 등기",
      "부부 공동명의",
      "아파트 공동명의",
    ],
    focus: "공동명의 전환·지분·서류",
    ...realEstateCase,
  },
  {
    slug: "부산지분이전등기",
    label: "부산 지분이전등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 지분이전등기",
      "공유지분 이전",
      "지분매매",
      "지분증여",
    ],
    focus: "지분 일부 이전등기",
    ...realEstateCase,
  },
  {
    slug: "부산이혼재산분할등기",
    label: "부산 이혼 재산분할등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "이혼 재산분할 등기",
      "이혼 후 아파트 명의변경",
      "재산분할 소유권이전",
    ],
    focus: "이혼 재산분할 후 소유권이전등기",
    ...realEstateCase,
  },
  {
    slug: "부산입주등기",
    label: "부산 입주등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부산 입주등기",
      "신축아파트 입주등기",
      "분양아파트 소유권이전",
    ],
    focus: "입주 시점 소유권이전·대출 등기",
    ...realEstateCase,
  },
  {
    slug: "부산셀프등기",
    label: "부산 셀프등기",
    category: "checklist",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 셀프등기",
      "법무사 없이 등기",
      "셀프등기 가능",
      "인터넷등기소 셀프",
    ],
    focus: "셀프등기와 법무사 검토 비교",
    toolHref: "/tools/real-estate-documents-check",
    toolLabel: "부동산 서류 체크",
  },
  {
    slug: "부산등기권리증분실",
    label: "부산 등기권리증 분실",
    category: "concern",
    serviceSlug: "ownership-transfer",
    keywords: [
      "등기권리증 분실",
      "확인서면",
      "등기권리증 잃어버림",
    ],
    focus: "등기권리증 분실 시 매도·확인서면",
    ...realEstateCase,
  },

  // ——— 부산 부동산등기 초세분화 Priority 2 ———
  {
    slug: "부산빌라매매등기",
    label: "부산 빌라 매매등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["부산 빌라 매매등기", "다세대 매매등기", "빌라 소유권이전"],
    focus: "빌라·다세대 매매 후 소유권이전",
    ...realEstateCase,
  },
  {
    slug: "부산오피스텔매매등기",
    label: "부산 오피스텔 매매등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["부산 오피스텔 매매등기", "오피스텔 소유권이전", "오피스텔 잔금 등기"],
    focus: "오피스텔 매매 후 등기·대출·임대차 확인",
    ...realEstateCase,
  },
  {
    slug: "부산상가매매등기",
    label: "부산 상가 매매등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["부산 상가 매매등기", "상가 소유권이전", "상가 잔금 등기"],
    focus: "상가 매매 후 소유권이전과 임대차 확인",
    ...realEstateCase,
  },
  {
    slug: "부산토지매매등기",
    label: "부산 토지 매매등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["부산 토지 매매등기", "토지 소유권이전", "농지 임야 매매등기"],
    focus: "토지 매매 후 지목·허가·소유권이전 확인",
    ...realEstateCase,
  },
  {
    slug: "부산가압류말소등기",
    label: "부산 가압류말소등기",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["부산 가압류말소등기", "가압류 말소", "등기부 가압류 지우기"],
    focus: "변제·판결 후 가압류 말소",
    glossaryHref: "/glossary/provisional-attachment",
    glossaryLabel: "가압류 용어",
  },
  {
    slug: "부산압류말소등기",
    label: "부산 압류말소등기",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: ["부산 압류말소등기", "압류 말소", "세금 압류 해제"],
    focus: "체납·집행 압류 말소",
    glossaryHref: "/glossary/attachment",
    glossaryLabel: "압류 용어",
  },
  {
    slug: "부산중도금대출근저당",
    label: "부산 중도금대출 근저당",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["중도금대출 근저당", "집단대출 근저당", "부산 근저당설정등기"],
    focus: "중도금대출 실행과 근저당 설정",
    ...realEstateCase,
  },
  {
    slug: "부산잔금대출근저당",
    label: "부산 잔금대출 근저당",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["잔금대출 근저당", "아파트 담보대출 등기", "부산 근저당설정등기"],
    focus: "잔금대출 실행과 근저당 설정",
    ...realEstateCase,
  },
  {
    slug: "부산상속후매매등기",
    label: "부산 상속 후 매매등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["상속 후 매매등기", "상속받은 집 바로 매매", "상속등기 후 매도"],
    focus: "상속등기와 매매 소유권이전 순서",
    ...inheritanceCase,
  },
  {
    slug: "부산확정일자전세권비교",
    label: "부산 확정일자 전세권 비교",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["확정일자 전세권 차이", "전세권 임차권 차이", "전입신고 확정일자"],
    focus: "확정일자·전세권·임차권 비교",
    diagnosisHref: "/임차권등기명령자가진단",
    diagnosisLabel: "임차권등기명령 자가진단",
  },
  {
    slug: "부산외국인부동산등기",
    label: "부산 외국인 부동산등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["외국인 부동산등기", "재외국민 부동산 매매", "아포스티유 등기서류"],
    focus: "외국인·해외거주자 부동산등기",
    ...realEstateCase,
  },
  {
    slug: "부산등기명의인표시변경",
    label: "부산 등기명의인 표시변경",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["등기명의인 표시변경", "등기부 주소변경", "개명 후 부동산등기"],
    focus: "주소·성명·법인표시 변경등기",
    ...realEstateCase,
  },
  {
    slug: "부산공매낙찰등기",
    label: "부산 공매 낙찰등기",
    category: "keyword",
    serviceSlug: "ownership-transfer",
    keywords: ["공매 낙찰등기", "온비드 낙찰등기", "캠코 공매 등기"],
    focus: "공매 낙찰 후 소유권이전",
    ...realEstateCase,
  },
  {
    slug: "부산신탁등기",
    label: "부산 신탁등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: ["부산 신탁등기", "신탁원부 확인", "신탁부동산 매매"],
    focus: "신탁부동산 등기와 이전·말소",
    ...realEstateCase,
  },
  // —— 상속 생애주기 허브 (장례 직후 → 특수 상황) ——
  {
    slug: "부모님사망후해야할일",
    label: "부모님 사망 후 해야 할 일",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["부모님 사망 후 해야 할 일", "가족 사망 후 행정절차", "장례 후 재산정리"],
    focus: "장례 직후 재산·채무·상속 순서",
    ...inheritanceCase,
  },
  {
    slug: "장례후재산채무정리",
    label: "장례 후 재산·채무 정리",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["장례 후 재산정리", "사망 후 재산 채무 정리", "부모님 사망 후 재산조회"],
    focus: "장례 후 재산·채무 확인 순서",
    ...inheritanceCase,
  },
  {
    slug: "사망신고와상속등기차이",
    label: "사망신고와 상속등기의 차이",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["사망신고와 상속등기", "사망신고 후 명의변경", "사망신고 절차"],
    focus: "사망신고와 상속등기 구분",
    ...inheritanceCase,
  },
  {
    slug: "안심상속원스톱서비스이후",
    label: "안심상속 원스톱서비스 이후",
    category: "concern",
    serviceSlug: "qualified-acceptance",
    keywords: ["안심상속 원스톱서비스 이후", "안심상속서비스 결과", "안심상속 후 할 일"],
    focus: "안심상속 신청 후 확인사항",
    ...inheritanceCase,
  },
  {
    slug: "사망자재산채무조회",
    label: "사망자 재산·채무 조회",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["사망자 재산조회", "사망자 채무조회", "부모님 빚 확인"],
    focus: "사망자 재산·채무 조회 범위",
    ...inheritanceCase,
  },
  {
    slug: "부모빚상속방법",
    label: "부모 빚이 있는 경우 상속방법",
    category: "concern",
    serviceSlug: "qualified-acceptance",
    keywords: ["부모 빚 상속", "재산보다 빚이 많을 때", "상속포기와 한정승인"],
    focus: "채무 있을 때 포기·한정 선택",
    ...inheritanceCase,
  },
  {
    slug: "방문없이준비하는상속등기",
    label: "방문 없이 준비하는 상속등기",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["방문 없는 상속등기", "비대면 상속 상담", "타지역 상속인"],
    focus: "비대면으로 상속등기 준비",
    ...inheritanceCase,
  },
  {
    slug: "상속상담전준비서류와비용",
    label: "상속 상담 전 준비서류와 비용",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["상속 상담 전 준비서류", "상속등기 비용 안내", "부산 상속 법무사 상담"],
    focus: "상담 전 서류·비용 구성",
    ...inheritanceCase,
  },
  {
    slug: "오래된상속토지정리",
    label: "오래된 상속토지 정리",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["오래된 상속등기", "할아버지 명의 토지 상속", "여러 세대 상속등기"],
    focus: "장기 미정리 상속토지",
    ...inheritanceCase,
  },
  {
    slug: "연락두절상속인",
    label: "연락두절 상속인",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["연락두절 상속인", "연락 안 되는 상속인", "상속인 소재불명"],
    focus: "연락두절 상속인 확인",
    ...inheritanceCase,
  },
  {
    slug: "미성년상속인",
    label: "미성년 상속인",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["미성년 상속인", "미성년자 상속등기", "자녀 미성년 상속"],
    focus: "미성년 상속인 서류·절차",
    ...inheritanceCase,
  },
  {
    slug: "재혼가정상속",
    label: "재혼가정 상속",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["재혼가정 상속", "전혼 자녀 상속", "재혼 배우자 상속"],
    focus: "재혼·전혼 자녀 상속인 확인",
    ...inheritanceCase,
  },
  {
    slug: "고인계좌장례비사용",
    label: "고인 계좌에서 장례비를 사용한 경우",
    category: "concern",
    serviceSlug: "qualified-acceptance",
    keywords: ["고인 계좌 장례비", "사망자 예금 인출", "장례비와 한정승인"],
    focus: "장례비 사용과 상속 선택",
    ...inheritanceCase,
  },
  {
    slug: "사망후3개월지난상속",
    label: "사망 후 3개월이 지난 경우",
    category: "concern",
    serviceSlug: "qualified-acceptance",
    keywords: ["사망 후 3개월", "상속포기 기한", "특별한정승인"],
    focus: "3개월 기한 전후 선택",
    ...inheritanceCase,
  },
  {
    slug: "해외거주상속인",
    label: "해외 거주 상속인",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["해외 거주 상속인", "해외 상속인 위임장", "외국 국적 상속인"],
    focus: "해외 상속인 서류·위임",
    ...inheritanceCase,
  },
  {
    slug: "임대인사망전세계약",
    label: "임대인이 사망한 전세계약",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["임대인 사망 전세", "임대인 사망 보증금", "상속인 전세보증금"],
    focus: "임대인 사망과 전세보증금",
    ...inheritanceCase,
  },
  {
    slug: "경상도비대면상속등기",
    label: "경상도 비대면 상속등기",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["경상도 비대면 상속등기", "경남 비대면 상속등기", "경상도 방문 없는 상속등기"],
    focus: "경남·울산·경북 비대면 준비와 한계",
    ...inheritanceCase,
  },
  {
    slug: "타지역상속인경상도부동산",
    label: "타지역 상속인과 경상도 부동산",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["타지역 상속인 경상도 부동산", "경남 부동산 부산 거주 상속인", "상속인 거주지 부동산 소재지 다를 때"],
    focus: "상속인 거주지와 부동산 소재지가 다를 때",
    ...inheritanceCase,
  },
  // 전국·원격 1단계 (지역명 비의존)
  {
    slug: "방문없이준비하는법무사업무",
    label: "방문 없이 준비하는 법무사 업무",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["방문 없는 법무사", "비대면 법무사 업무", "전국 법무사 업무"],
    focus: "방문 전 원격 확인 가능한 업무 범위",
    ...inheritanceCase,
  },
  {
    slug: "상속인이여러지역에있는경우",
    label: "상속인이 여러 지역에 있는 경우",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: [
      "상속인이 여러 지역에 있는 경우",
      "공동상속인 거주지 다른 경우",
      "가족이 전국에 흩어진 상속등기",
    ],
    focus: "공동상속인 거주지 분산과 서류 수집",
    ...inheritanceCase,
  },
  {
    slug: "부동산과거주지가다른상속등기",
    label: "부동산과 거주지가 다른 상속등기",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: [
      "부동산과 거주지 다른 상속등기",
      "타지역 부동산 상속등기",
      "거주지와 다른 지역 등기",
    ],
    focus: "거주지와 부동산 소재지 불일치",
    ...inheritanceCase,
  },
  {
    slug: "방문없이준비하는상속포기한정승인",
    label: "방문 없이 준비하는 상속포기·한정승인",
    category: "concern",
    serviceSlug: "qualified-acceptance",
    keywords: ["방문 없는 상속포기", "비대면 한정승인", "타지역 법원 상속포기"],
    focus: "포기·한정승인 원격 준비와 기한",
    ...inheritanceCase,
  },
  {
    slug: "사진전자파일우편으로서류전달",
    label: "사진·전자파일·우편으로 서류 전달",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: ["등기서류 우편", "서류 사진으로 법무사", "원본서류 필요한 등기"],
    focus: "사진·파일·우편 서류 전달 역할",
    ...inheritanceCase,
  },
  {
    slug: "법무사비용먼저확인하는방법",
    label: "법무사 비용을 먼저 확인하는 방법",
    category: "cost-why",
    serviceSlug: "inheritance-registration",
    keywords: ["법무사 비용 먼저 확인", "법무사 보수와 공과금", "서류를 보내기 전 비용"],
    focus: "업무별 비용 확인에 필요한 정보",
    ...inheritanceCase,
  },
  // 전국·원격 2단계 (법인·증여·근저당·임차권·지급명령)
  {
    slug: "방문없이준비하는법인설립",
    label: "방문 없이 준비하는 법인설립",
    category: "concern",
    serviceSlug: "company-establishment",
    keywords: [
      "방문 없는 법인설립",
      "비대면 법인설립 준비",
      "공동창업자 다른 지역 법인설립",
    ],
    focus: "법인설립 원격 준비·발기인 분산",
    ...corporateCase,
  },
  {
    slug: "방문없이준비하는임원변경",
    label: "방문 없이 준비하는 임원변경",
    category: "concern",
    serviceSlug: "director-change",
    keywords: [
      "방문 없는 임원변경등기",
      "임원변경 원격 준비",
      "정관 등기부 변경등기 확인",
    ],
    focus: "임원변경 원격 서류·결의 준비",
    ...corporateCase,
  },
  {
    slug: "해외대표이사주주법인등기",
    label: "해외 대표이사·주주 법인등기",
    category: "concern",
    serviceSlug: "director-change",
    keywords: [
      "해외 대표이사 법인등기",
      "해외 주주 법인설립",
      "외국에 있는 대표이사 변경등기",
    ],
    focus: "해외 임원·주주 서명·위임",
    ...corporateCase,
  },
  {
    slug: "부모자녀다른지역증여등기",
    label: "부모와 자녀가 다른 지역에 사는 증여등기",
    category: "concern",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부모 자녀 다른 지역 증여",
      "증여자 수증자 다른 지역",
      "타지역 증여등기 준비",
    ],
    focus: "증여 당사자·부동산 지역 분산",
    ...realEstateCase,
  },
  {
    slug: "방문없이준비하는근저당말소",
    label: "방문 없이 준비하는 근저당말소",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "근저당권 말소 비대면",
      "대출 상환 후 근저당 말소",
      "은행서류 근저당 말소",
    ],
    focus: "은행 말소서류 원격 확인",
    ...realEstateCase,
  },
  {
    slug: "이사후임차권등기명령준비",
    label: "이사 후 임차권등기명령 준비",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "이사 후 임차권등기명령",
      "타지역 임차권등기명령",
      "임차권등기명령 방문 없이 준비",
    ],
    focus: "이사 전후·타지역 임차권등기 자료",
    diagnosisHref: "/임차권등기명령자가진단",
    diagnosisLabel: "임차권등기명령 자가진단",
  },
  {
    slug: "방문없이준비하는지급명령서류",
    label: "방문 없이 준비하는 지급명령 서류",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "지급명령 방문 없이 준비",
      "지급명령 서류 비대면",
      "미수금 지급명령 자료",
    ],
    focus: "지급명령 입증자료 원격 정리",
    diagnosisHref: "/지급명령자가진단",
    diagnosisLabel: "지급명령 자가진단",
  },
  // 전국·원격 3단계 (특수 상황 — 고유성 게이트 통과분만)
  {
    slug: "사업자폐업후법인정리",
    label: "사업자 폐업 후 법인 정리",
    category: "concern",
    serviceSlug: "corporate-registration",
    keywords: [
      "사업자 폐업 후 법인 정리",
      "폐업했는데 법인등기 남음",
      "타지역에서 법인해산 준비",
    ],
    focus: "폐업 후 해산·휴면 선택과 원격 준비",
    ...corporateCase,
  },
  {
    slug: "등기권리증없이소유권이전",
    label: "등기권리증 없이 소유권이전",
    category: "concern",
    serviceSlug: "ownership-transfer",
    keywords: [
      "등기권리증 없이 소유권이전",
      "등기필증 분실 매도",
      "확인서면 소유권이전",
    ],
    focus: "권리증 분실·확인서면 매도·이전",
    ...realEstateCase,
  },
  {
    slug: "해외서류가필요한증여등기",
    label: "해외서류가 필요한 증여등기",
    category: "concern",
    serviceSlug: "ownership-transfer",
    keywords: [
      "해외 거주 자녀 증여등기",
      "해외서류 증여등기",
      "해외 위임장 부동산 증여",
    ],
    focus: "증여 원인 해외 서명·공증·번역",
    ...realEstateCase,
  },
  // 전국·원격 4단계 (업무·서류·권역 — SEO thin 금지)
  {
    slug: "방문없이준비하는부담부증여",
    label: "방문 없이 준비하는 부담부증여",
    category: "concern",
    serviceSlug: "ownership-transfer",
    keywords: [
      "부담부증여 원격 준비",
      "근저당 있는 아파트 증여",
      "전세 낀 주택 증여 서류",
    ],
    focus: "담보·전세 있는 증여 원격 점검",
    ...realEstateCase,
  },
  {
    slug: "방문없이준비하는전세권말소",
    label: "방문 없이 준비하는 전세권말소",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "전세권 말소 원격 준비",
      "전세권말소등기 서류",
      "계약 종료 후 전세권 말소",
    ],
    focus: "전세권 말소 서류 원격 확인",
    ...realEstateCase,
  },
  {
    slug: "공유물분할등기서류준비",
    label: "공유물분할등기 서류 준비",
    category: "concern",
    serviceSlug: "ownership-transfer",
    keywords: [
      "공유물분할등기 서류",
      "공유 부동산 분할 등기",
      "협의분할 등기 준비",
    ],
    focus: "공유 분할 등기원인·서류",
    ...realEstateCase,
  },
  {
    slug: "가압류신청서류준비",
    label: "가압류 신청 서류 준비",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "가압류 신청 서류",
      "가압류 신청 준비",
      "보전처분 서류 정리",
    ],
    focus: "가압류 신청 전 서류·관할",
  },
  {
    slug: "내용증명작성준비",
    label: "내용증명 작성 준비",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "내용증명 작성 준비",
      "내용증명 보내기 전",
      "독촉 내용증명 자료",
    ],
    focus: "내용증명 발송 전 사실관계",
    diagnosisHref: "/내용증명자가진단",
    diagnosisLabel: "내용증명 자가진단",
  },
  {
    slug: "방문없이준비하는유상증자",
    label: "방문 없이 준비하는 유상증자",
    category: "concern",
    serviceSlug: "corporate-registration",
    keywords: [
      "유상증자등기 원격 준비",
      "자본금 증가 등기 서류",
      "신주발행등기 준비",
    ],
    focus: "유상증자 결의·납입·등기 원격",
    ...corporateCase,
  },
  {
    slug: "휴면법인계속등기준비",
    label: "휴면법인 계속등기 준비",
    category: "concern",
    serviceSlug: "corporate-registration",
    keywords: [
      "휴면법인 계속등기 준비",
      "휴면법인 통지 후 절차",
      "휴면법인 해산과 계속",
    ],
    focus: "휴면 계속 vs 해산 선택",
    ...corporateCase,
  },
  {
    slug: "제주타지역상속인부동산",
    label: "제주 부동산과 타지역 상속인",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: [
      "제주 부동산 타지역 상속인",
      "육지 거주 제주 상속등기",
      "제주 상속 비대면 준비",
    ],
    focus: "육지 상속인×제주 부동산",
    ...inheritanceCase,
  },
  {
    slug: "가처분신청서류준비",
    label: "가처분 신청 서류 준비",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "가처분 신청 서류",
      "가처분 신청 준비",
      "점유이전금지가처분 서류",
    ],
    focus: "가처분 신청 전 서류·관할",
  },
  {
    slug: "채권압류추심서류준비",
    label: "채권압류·추심 서류 준비",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "채권압류 추심 서류",
      "채권압류명령 신청 준비",
      "판결 후 강제집행 서류",
    ],
    focus: "집행권원 후 압류·추심 서류",
  },
  {
    slug: "변제공탁서류준비",
    label: "변제공탁 서류 준비",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "변제공탁 서류",
      "변제공탁 신청 준비",
      "공탁서 작성 준비",
    ],
    focus: "변제공탁 신청 전 서류",
  },
  {
    slug: "이혼재산분할등기서류준비",
    label: "이혼 재산분할등기 서류 준비",
    category: "concern",
    serviceSlug: "ownership-transfer",
    keywords: [
      "이혼 재산분할등기 서류",
      "이혼 후 부동산 명의변경 서류",
      "재산분할 소유권이전 준비",
    ],
    focus: "재산분할 원인 등기 서류",
    ...realEstateCase,
  },
  {
    slug: "압류말소등기서류준비",
    label: "압류말소등기 서류 준비",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "압류말소등기 서류",
      "세금 압류 말소 준비",
      "체납 압류 해제 후 등기",
    ],
    focus: "기관 압류 말소 서류",
    ...realEstateCase,
  },
  {
    slug: "상속등기후매매서류준비",
    label: "상속등기 후 매매 서류 준비",
    category: "concern",
    serviceSlug: "ownership-transfer",
    keywords: [
      "상속등기 후 매매 서류",
      "상속받은 집 매도 등기",
      "상속 부동산 매매 순서",
    ],
    focus: "상속등기×매매 잔금 순서",
    ...inheritanceCase,
  },
  // Keyword-gap P1 batch (2026-08) — CREATE_NEW only, no URL collisions
  {
    slug: "특별한정승인",
    label: "특별한정승인",
    category: "concern",
    serviceSlug: "qualified-acceptance",
    keywords: [
      "특별한정승인",
      "특별한정승인 신청",
      "3개월 후 한정승인",
      "기한 지난 상속채무",
    ],
    focus: "기한 경과·뒤늦은 채무 특별한정승인",
    ...inheritanceCase,
  },
  {
    slug: "대습상속등기",
    label: "대습상속등기",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: [
      "대습상속등기",
      "대습상속",
      "손자 상속등기",
      "중간세대 사망 상속",
    ],
    focus: "대습상속인 확정·등기",
    ...inheritanceCase,
  },
  {
    slug: "유류분과상속등기",
    label: "유류분과 상속등기",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: [
      "유류분 상속등기",
      "유류분",
      "유류분과 분할협의",
    ],
    focus: "유류분 우려 시 등기 전 확인",
    ...inheritanceCase,
  },
  {
    slug: "상속취득세와등기순서",
    label: "상속 취득세와 등기 순서",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: [
      "상속 취득세",
      "상속등기 세금",
      "상속 취득세 신고",
    ],
    focus: "취득세·등기 일정 연계",
    ...inheritanceCase,
  },
  {
    slug: "신용회복과개인회생차이",
    label: "신용회복과 개인회생 차이",
    category: "rehab",
    serviceSlug: "personal-rehabilitation",
    keywords: [
      "신용회복 개인회생 차이",
      "워크아웃 개인회생",
      "신용회복위원회",
    ],
    focus: "채무조정 경로 비교",
    ...rehabCase,
  },
  {
    slug: "전세사기피해대응절차",
    label: "전세사기 피해 대응 절차",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "전세사기 피해 대응",
      "전세사기 임차권등기",
      "전세보증금 미반환",
    ],
    focus: "피해 후 임차권·서류 순서",
    ...realEstateCase,
  },
  {
    slug: "분양권명의이전등기",
    label: "분양권 명의이전등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: [
      "분양권 명의이전",
      "입주권 이전",
      "분양권 매매 등기",
      "분양권 전매",
    ],
    focus: "입주 전 분양권·입주권 승계",
    ...realEstateCase,
  },
  // Situation / problem intent batch (2026-08) — lawyer-word optional queries
  {
    slug: "지급명령이의신청준비",
    label: "지급명령 이의신청 준비",
    category: "concern",
    serviceSlug: "payment-order",
    keywords: [
      "지급명령 이의신청",
      "지급명령 이의",
      "지급명령 받은 후",
    ],
    focus: "지급명령 수령 후 이의 준비",
  },
  {
    slug: "해산간주확인절차",
    label: "해산간주 확인 절차",
    category: "concern",
    serviceSlug: "corporate-registration",
    keywords: [
      "해산간주",
      "휴면법인 해산간주",
      "폐업 후 법인등기",
    ],
    focus: "해산간주·계속·해산 갈림길",
    ...corporateCase,
  },
  {
    slug: "등기신청반려와보정",
    label: "등기신청 반려와 보정",
    category: "mistakes",
    serviceSlug: "real-estate-registration",
    keywords: [
      "등기 반려",
      "등기 보정명령",
      "등기신청 보정",
    ],
    focus: "반려·보정 후 재접수",
    ...realEstateCase,
  },
  {
    slug: "상속재산분할협의서준비",
    label: "상속재산분할협의서 준비",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: [
      "상속재산분할협의서",
      "상속 분할협의",
      "형제 상속 합의",
    ],
    focus: "분할협의서 항목·등기 전 점검",
    ...inheritanceCase,
  },
  {
    slug: "대표이사한명만남는경우",
    label: "대표이사만 남는 경우",
    category: "concern",
    serviceSlug: "corporate-registration",
    keywords: [
      "대표이사만 남는 경우",
      "이사 2명 사임",
      "이사 사임 등기",
    ],
    focus: "다수 사임 후 대표 잔류",
    ...corporateCase,
  },
  {
    slug: "경매낙찰후전세권확인",
    label: "경매 낙찰 후 전세권 확인",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "경매 낙찰 전세권",
      "낙찰 후 전세권 말소",
      "말소기준권리",
    ],
    focus: "낙찰 후 전세권·권리 확인",
    ...realEstateCase,
  },
  {
    slug: "본점이전후사업자등록순서",
    label: "본점이전 후 사업자등록 순서",
    category: "concern",
    serviceSlug: "corporate-registration",
    keywords: [
      "본점이전 후 사업자등록",
      "회사 주소 변경 사업자",
      "법인 주소 이전 순서",
    ],
    focus: "본점이전 후속 행정 연계",
    ...corporateCase,
  },
  {
    slug: "상속포기후다음순위확인",
    label: "상속포기 후 다음 순위 확인",
    category: "concern",
    serviceSlug: "inheritance-renunciation",
    keywords: [
      "상속포기 다음 순위",
      "상속포기 후 자녀",
      "손자 상속포기",
    ],
    focus: "포기 전 다음 순위 확인",
    ...inheritanceCase,
  },
  {
    slug: "부산가등기",
    label: "부산 가등기",
    category: "keyword",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 가등기",
      "가등기 설정",
      "가등기 말소",
      "소유권이전청구권 가등기",
    ],
    focus: "가등기 설정·말소·본등기",
    ...realEstateCase,
  },
  {
    slug: "부산유언검인",
    label: "부산 유언검인",
    category: "concern",
    serviceSlug: "inheritance-registration",
    keywords: [
      "부산 유언검인",
      "유언검인 신청",
      "자필유언 검인",
    ],
    focus: "유언검인 신청 서류",
    ...inheritanceCase,
  },
  {
    slug: "부동산실권리자명의등기",
    label: "부동산 실권리자명의등기",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부동산 실권리자명의등기",
      "명의신탁 해소 등기",
      "진정명의회복등기",
    ],
    focus: "명의신탁 해소·진정명의회복",
    ...realEstateCase,
  },
  {
    slug: "부산경매권리분석",
    label: "부산 경매 권리분석",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 경매 권리분석",
      "경매 말소기준권리",
      "입찰 전 등기부",
    ],
    focus: "입찰 전 등기부 권리 확인",
    ...realEstateCase,
  },
  {
    slug: "부산개명허가",
    label: "부산 개명허가",
    category: "concern",
    serviceSlug: "inheritance-renunciation",
    keywords: [
      "부산 개명허가",
      "개명허가 신청",
      "성본변경 신청",
    ],
    focus: "개명·성본변경 신청 서류",
    ...inheritanceCase,
  },
  {
    slug: "부산재산명시",
    label: "부산 재산명시",
    category: "concern",
    serviceSlug: "real-estate-registration",
    keywords: [
      "부산 재산명시",
      "재산명시신청",
      "채무자 재산목록",
    ],
    focus: "집행권원 후 재산명시 신청",
  },
  {
    slug: "부산부재자재산관리인",
    label: "부산 부재자재산관리인",
    category: "concern",
    serviceSlug: "inheritance-renunciation",
    keywords: [
      "부산 부재자재산관리인",
      "부재자재산관리인 선임",
      "부재자 재산관리",
    ],
    focus: "부재자재산관리인 선임 서류",
    ...inheritanceCase,
  },
  {
    slug: "부산상속재산관리인",
    label: "부산 상속재산관리인",
    category: "concern",
    serviceSlug: "inheritance-renunciation",
    keywords: [
      "부산 상속재산관리인",
      "상속인 없는 경우",
      "상속재산관리인 선임",
    ],
    focus: "상속재산관리인 선임 서류",
    ...inheritanceCase,
  },
];
